### ISSUE TITLE
Shadow JAR Gradle plugin version out-dated

### ISSUE THREAD

**Issue by UdoW** [eugenp/tutorials#10037]
The tutorial on how to build a FAT jar with gradle is out-dated.

Just add this on top of your build.gradle file if you want to use the Shadow JAR plugin:

```
plugins {
  id 'com.github.johnrengelman.shadow' version '6.0.0'
  id 'java'
}
```

**Comment by kwoyke** [comment]
Hi @UdoW,
Thanks for the feedback. We'll put this one on our TODO list.

**Comment by kasramp** [comment]
Hi @UdoW - We updated the code and the related tutorial. 
Thanks
