### ISSUE TITLE
Make the mail server configurable

### ISSUE THREAD

**Issue by perezdf** [eugenp/tutorials#10045]
These properties must be configurable

     `   JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
        mailSender.setHost("smtp.gmail.com");
        mailSender.setPort(587);
        mailSender.setProtocol("smtp");`

**Comment by kwoyke** [comment]
Hi @perezdf ,
Which article are you referring to?

**Comment by lor6** [comment]
I could only find an example of this in the EmailConfiguration class here: https://github.com/eugenp/tutorials/blob/master/spring-mvc-basics-2/src/main/java/com/baeldung/spring/configuration/EmailConfiguration.java and the properties are now configurable.

@perezdf  Please re-open this if you were referring to a different class.
