### ISSUE TITLE
Test Cases for java mail sender api

### ISSUE THREAD

**Issue by rubinavohra** [eugenp/tutorials#10059]
Hi,

Do you happen to have test classes written for spring-mvc-basics-2/src/main/java/com/baeldung/spring/mail/EmailServiceImpl.java  ??

**Comment by lor6** [comment]
Hi @rubinavohra No, the methods are only called from the controller: https://github.com/eugenp/tutorials/blob/master/spring-mvc-basics-2/src/main/java/com/baeldung/spring/controller/MailController.java
