### ISSUE TITLE
Do I have to download the entire repository just to get one single tutorial?

### ISSUE THREAD

**Issue by lingocoder** [eugenp/tutorials#10094]
I just want to download one single tutorial. But I could not find an obvious and straightforward way to do that. 

The only way I could think of was to copy/paste one file at a time from a given tutorial. That's even worse than downloading the entire repository, frankly.

Thanks in advance.

**Comment by lor6** [comment]
Hi @lingocoder Yes, if you want to try the code, you have to clone the repository. You can then import the project you're interested in in your IDE.
