### ISSUE TITLE
Spring Webflux and Spring Security and X509Certificate tutorial

### ISSUE THREAD

**Issue by patpatpat123** [eugenp/tutorials#10136]
Hello Baeldung,

First message in this repo, a very big thanks for the website and the tutorial series.

I would like to ask if it is possible to have a tutorial/example of Spring Webflux, combined with Spring Security, and particularly  the X509 certificate verification part.

Tutorials on Spring Webflux are very clear. 
Tutorials on Spring Security (non-Webflux) and X509 certificate auth are also very clear.

However, the combination of the both, which is not something straightforward might be a good topic for a blog/tutorial, since it is very new, and the combination of both is becoming more and more important.

If this is not the right place to start those tutorial/blog request, apologies and please forward me to the appropriate place.

Thank you

**Comment by lor6** [comment]
Hi @patpatpat123 Thanks for the suggestion, we'll add this to our to-do list, though it may take a while until it's out.

We do have an article on Spring Security for reactive applications: https://www.baeldung.com/spring-security-5-reactive though not with X509 authentication.

Please use the email: team@baeldung.com or the Contact form on the site: https://www.baeldung.com/contact for any questions or suggestions, and let's keep the github issues for problems in the repo.

Cheers.

**Comment by patpatpat123** [comment]
Understood @lor6 . Many thanks and good day!

**Comment by ashusah** [comment]
Hi @lor6 
Can you please let us know if there is any article already created for the above request
