### ISSUE TITLE
Tests MongoDbSpringIntegrationTest don't seem to work

### ISSUE THREAD

**Issue by JohnSeals** [eugenp/tutorials#10165]
Hey everyone! 

Thanks for posting all these great examples! :-)

I'm trying to run the MongoDB integration tests like MongoDbSpringIntegrationTest. However no matter what I try MongoTemplate is always null. 

Using Spring 2.3.4.RELEASE and flapdoodle 2.2.0.

Any ideas?

Thanks again!

**Comment by lor6** [comment]
Hi @JohnSeals I wasn't able to reproduce the issue on the spring-boot-persistence-mongob project here: https://github.com/eugenp/tutorials/tree/master/persistence-modules/spring-boot-persistence-mongodb The integration tests are passing successfully. 

Is this an issue you're having with our code or your custom example?

Thanks.

**Comment by lor6** [comment]
Please re-open this if it's an issue in our repository with more details, or provide a PR that reproduces the issue.
