### ISSUE TITLE
No 2 constructors in Java 11

### ISSUE THREAD

**Issue by cvielma** [eugenp/tutorials#10161]
Hey guys, just FWI in Java 11 there's no Synthetic constructor generated in this example:

https://github.com/eugenp/tutorials/blob/71b6c96a47c0104cfe47a8b8675982f28dfc39b2/core-java-modules/core-java-lang/src/main/java/com/baeldung/synthetic/SyntheticConstructorDemo.java#L9

Here's more info about it: https://product.hubspot.com/blog/java-11-dont-rely-on-generated-serialversionuid

Just in case you want to update the example :)

**Comment by lor6** [comment]
Thanks for the feedback @cvielma Looks like the same applies to the synthetic methods. 

At the moment, the code targets JDK 8, so I'll keep it, but I've added notes in the supporting article: https://www.baeldung.com/java-synthetic that mention these are no longer generated starting with JDK 11.
