### ISSUE TITLE
Examples with ClientHttpRequestInterceptor are not working.

### ISSUE THREAD

**Issue by zorner** [eugenp/tutorials#10197]
I have been trying to follow [Spring RestTemplate Request/Response Logging](https://www.baeldung.com/spring-resttemplate-logging). But the ClientHttpRequestInterceptor never gets called.

I have a stackover question, [How to get ClientHttpRequestInterceptor working?](https://stackoverflow.com/questions/64511320/how-to-get-clienthttprequestinterceptor-working), on the same issue.

Your spring-resttemplate-2 dose not have any interceptor code in it. 

[Using the Spring RestTemplate Interceptor](https://www.baeldung.com/spring-rest-template-interceptor) spring-resttemplate does have interceptor code, but it also does not call the ClientHttpRequestInterceptor. I even did a hard reset in git to the [BAEL-9710] - Standardized packages for spring-rest module amit 2103 12/8/18, 8:07 AM commit and it does not call the interceptor. (Still Spring Boot ver. 2.0.5) 

This is a pure guess, but is there a listener that is missing since Spring 5.0/Spring Boot 2.0? I am asking this for two reasons. 

One [Warning: “The type WebMvcConfigurerAdapter is deprecated”](https://www.baeldung.com/web-mvc-configurer-adapter-deprecated) talks about a change with WebMvcConfigurerAdapter being deprecated. Did they remove some default listeners at the same time with Spring 5.0/Spring Boot 2.0?

Two I was having the same issue with HandlerInterceptor and HandlerInterceptorAdapter interceptors not being called, until at the end of [Using a Custom Spring MVC’s Handler Interceptor to Manage Sessions](https://www.baeldung.com/spring-mvc-custom-handler-interceptor) it tells me to add a listener.

[Introduction to Spring MVC HandlerInterceptor](https://www.baeldung.com/spring-mvc-handlerinterceptor) is missing the listener step, and I am guessing it is broken as well.

**Comment by lor6** [comment]
Hi @zorner I was looking over the stackoverflow question, and you mention that "There is no RestTemplate code, only a controller with a @RestController annotation. That with @RequestBody in the mapping methods, should be calling the RestTemplate".

This is incorrect. The controller methods have no connection to the RestTemplate. RestTemplate is a client that can be used to make calls to other REST services - that's the only way it will be called.

The spring-resttemplate-2 module has the LoggingInterceptor class, as well as the test for it here: https://github.com/eugenp/tutorials/tree/master/spring-resttemplate-2/src/test/java/com/baeldung/resttemplate/logging. I ran the test now and it's working ok.

If you want to log all the calls to your REST endpoints, have a look at this guide: https://www.baeldung.com/spring-http-logging instead. The easiest option is using one of the pre-defined Spring filters, as shown in section 5.

I'll check the https://www.baeldung.com/spring-mvc-handlerinterceptor tutorial.

**Comment by zorner** [comment]
A person was nice enough to email me and point out, I had a misconception.

Somewhere I had picked up <strike>Spring used the `RestTemplate` for the auto decoding and encoding of POJOs in Rest controllers.</strike> That is incorrect.

Thus the Spring RestTemplate Interceptor, only works on the client side, or in test where the tests are acting as the client.

This person also, found the Spring RestTemplate Interceptor code, inside the test folder/package of spring-resttemplate-2.

To me that is not example code. The Spring RestTemplate Interceptor code should be in the main folder/package.

Both spring-resttemplate and spring-resttemplate-2 modules need to make it clear what is client side code and what is server side. At least separate folders/packages. Separate modules would make more sense. Why would you have an application both produce(server) and consume(client) a Rest service internally with all the extra overhead, unless it was for demonstration or testing?

If the intent of [Spring RestTemplate Request/Response Logging](https://www.baeldung.com/spring-resttemplate-logging) tutorial is only to be used for testing a server, it should state that.

The Primary issue, is now resolved. Improving the tutorials and code base is not.

**Comment by zorner** [comment]
Loredana,

     Thanks, that explains what is happening. Thank you, for taking the
time to look at this. I thought I had read that Spring called the
RestTemplate internally for controllers and used the RestTemplate to do
auto decoding and encoding of POJOs. I must have been wrong.

     I had read some of https://www.baeldung.com/spring-http-logging, but
had missed section 5 on the filters. Thanks for pointing it out to me.

     I have updated the issue/question accordingly. May I put your name in
those comments?

Thanks again,
William

**Comment by lor6** [comment]
Hi @zorner Yes, I replied to your issue here, that's why you received an email notification from GitHub :) 

The code is in the test folder because that's how it's used in the example. This is a common use of the RestTemplate class - to test the controllers defined in the same project. However, the approach for logging the RestTemplate requests/responses is valid whether you're using the class in a test or not. I'll update the article to clarify the example used if it helps.

**Comment by zorner** [comment]
Loredana,

     Yes, putting something in the article says this is a test example will
help. And yes the RestTemplate is often used in tests, but that is because
it is used to emulate the client. The distinction between server side and
client side is more important, then if it is used in a test. If someone is
looking for help logging Request/Response, they may not be thinking 'am I
on the server side or the client side?' As the RestTemplate, interceptors,
and filters all pop on searches for logging Request/Response, something
needs to be in the article to tell the reader which side this logging
approach is for. Otherwise with all the stuff that does not work, and so
many different approaches, the reader may get lost, if not overwhelmed, and
think they are following a sound approach when they are on the wrong one.

Thanks,
William

**Comment by zorner** [comment]
Strange 24 hrs  ago, only my initial comment was here. Now all the comments/emails are here.

**Comment by lor6** [comment]
@zorner Sure, I'll add a note in the article about the example being used in a test.

Otherwise, I think it's clear what the use case is, as it's specifically referring to logging RestTemplate requests.

I'll close this issue.

Thanks.
