### ISSUE TITLE
No search results displayed (javafx tutorial)

### ISSUE THREAD

**Issue by ellenspertus** [eugenp/tutorials#10196]
I ran the javafx tutorial in Eclipse on Windows 10 with JDK 15.0.1 and the JavaFX 15 library. The search window shows up, but no results are ever displayed, including when I search for "Monica". I was able to verify that `masterData` has one value by adding a `println` statement:

![masterdata](https://user-images.githubusercontent.com/27104250/97046682-96579a80-152c-11eb-90f5-efa46d8f0834.png)

**Comment by lor6** [comment]
Hi @ellenspertus I've added a fix for this; please update your local repository and try again.

Thanks.

**Comment by lor6** [comment]
I'm closing this issue. Please re-open it if you still have any problems.
