### ISSUE TITLE
Unknown failure: com.amazonaws.AmazonClientException: Unable to complete transfer: Can only mark at stream beginning

### ISSUE THREAD

**Issue by swetabdas** [eugenp/tutorials#10215]
I am working on the AWS Redshift. One of the client requirements was to upload the files into S3 and then to use COPY command for transferring files from S3 to Redshift. When file size is more than 16MB, it goes for S3 Multipart Upload Operation.

But the process fails giving error :

Unknown failure: com.amazonaws.AmazonClientException: Unable to complete transfer: Can only mark at stream beginning; Caused by: Unknown failure: com.amazonaws.AmazonClientException: Unable to complete transfer: Can only mark at stream beginning; Caused by: Unable to complete transfer: Can only mark at stream beginning; Caused by: Can only mark at stream beginning

Earlier I was following the below approach:

initiate the upload.
upload the object parts.
after uploaded all the parts, complete the multipart upload.
Code snippet for the same :

try {
            InitiateMultipartUploadRequest initRequest = new InitiateMultipartUploadRequest(bucketName, key);
            InitiateMultipartUploadResult initResponse = s3Client.initiateMultipartUpload(initRequest);
            uploadId = initResponse.getUploadId();
            for (int i = 1; i <= MAXIMUM_PART_NUMBERS; i++) {
                partSize = Math.min(partSize, maxPartSizeInBytes);
                UploadPartRequest uploadRequest = new UploadPartRequest().withBucketName(bucketName).withKey(key)
                        .withUploadId(uploadId).withInputStream(inputStream).withPartNumber(i).withPartSize(partSize);
                if (encryptionType.equals(SSEAlgorithm.KMS.toString())
                        || encryptionType.equals(SSEAlgorithm.AES256.toString())) {
                    ObjectMetadata objectMetadata = getObjectMetadata(encryptionType);
                    uploadRequest.withObjectMetadata(objectMetadata);
                }
                UploadPartResult uploadResult = s3Client.uploadPart(uploadRequest);
                partETags.add(uploadResult.getPartETag());
            }
            CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(bucketName, key, uploadId,
                    partETags);
            s3Client.completeMultipartUpload(compRequest);
        } catch (Exception e) {
            s3Client.abortMultipartUpload(new AbortMultipartUploadRequest(bucketName, key, uploadId));
            throw new Exception(MULTIPART_OPERATION_FAILED, e.getMessage());
        }
But it gave me the above error. So I used another approach, i.e. using TransferManager. Below is the code snippet for same:

public void uploadObject(InputStream inputStream) throws Exception {
        ObjectMetadata objectMetadata = new ObjectMetadata();
        // If not provided, the library will have to buffer the contents of the
        // inputstream in order to calculate it.which predictably will lead to
        // OutOfMemory on "sufficient large" files.
        byte[] objectBytes = IOUtils.toByteArray(inputStream);
        objectMetadata.setContentLength(objectBytes.length);
        long maxPartSizeInBytes = ByteUnit.byteSize(s3Connection.getPartSize(), ByteUnit.MB.name());
        if ((maxPartSizeInBytes * MAXIMUM_PART_NUMBERS) < input.getDataSize()) {
            throw new ConnectorException(
                    MessageFormat.format(ERROR_EXCEEDS_PART_NUMBERS, input.getDataSize(), s3Connection.getPartSize()));
        }
        String encryptionType = s3Encryption.getEncryptionType();
        String bucketName = s3Connection.getBucketName();
        long partSize = s3Connection.getPartSize();
        try {
            TransferManager tm = TransferManagerBuilder.standard().withS3Client(s3Client)
                    .withMultipartUploadThreshold(partSize).build();
            if (encryptionType.equals(SSEAlgorithm.KMS.toString()) || encryptionType.equals(AmazonS3Constants.AES)) {
                objectMetadata = getObjectMetadata(encryptionType);
            }
            PutObjectRequest request = new PutObjectRequest(bucketName, key, inputStream, objectMetadata);
            request.setGeneralProgressListener((progressEvent) -> {
                progressEvent.getBytesTransferred();
            });
            Upload upload = tm.upload(request);

            upload.waitForCompletion();
        } catch (SdkClientException e) {
            throw new Exception(MULTIPART_OPERATION_FAILED, e.getMessage());
        }
Initially, the code was working fine, but then this code is also giving the same error.

I have debugged the error, but I could not find a solution to this. Any help on this will be appreciated.

**Comment by lor6** [comment]
Hi @swetabdas It sounds like a previous upload request failed or was interrupted, and now the process is stuck on a previous part and can't continue. I suggest looking into the documentation for aborting multipart uploads: https://docs.aws.amazon.com/cli/latest/reference/s3api/abort-multipart-upload.html This mentions that the abort operation may need to be called multiple times, so you could list the parts after the abort request, to make sure there are none left.

To check if there are any parts left currently, use the CLI or the Amazon interface, and try to remove them if there are.

That should give you a starting point to look into this further. But since this is not an issue with our repository, I'll close this.
