### ISSUE TITLE
@EnableOAuth2Client deprecated

### ISSUE THREAD

**Issue by dnlnegroni** [eugenp/tutorials#10228]
Is there some news about this project?
EnableOAuth2Client was deprecated...

**Comment by lor6** [comment]
Hi @dnlnegroni 

EnableOAuth2Client is part of the legacy Spring OAuth project. This is deprecated and replaced by the OAuth support in Spring Security 5. 

Have a look at this tutorial for the new client support: https://www.baeldung.com/spring-security-5-oauth2-login

or the Spring documentation: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2
