### ISSUE TITLE
Freemarker example doesn't load templates

### ISSUE THREAD

**Issue by RadekWroblewski-VL** [eugenp/tutorials#10230]
On Freemarker example the method sendMessageUsingFreemarkerTemplate calls 
`freemarkerConfigurer.createConfiguration().getTemplate(...)`

Calling createConfiguration() means a new configuration is created with default template loader. Therefore it does not look for the templates in predefined resource directory. It should be getConfiguration().

**Comment by lor6** [comment]
Thanks @RadekWroblewski-VL  I've updated the code snippet in: https://www.baeldung.com/spring-email-templates

The github source code was correct.

Cheers.
