### ISSUE TITLE
Additional parameter

### ISSUE THREAD

**Issue by sl3w** [eugenp/tutorials#10241]
I add additional parameter in CustomOAuth2AuthorizationRequestResolver, but how and where I can get it after answer from OAuth?

**Comment by lor6** [comment]
Hi @sl3w The additional parameter is added in the authorization request sent to the Authorization Server. This server is the one that can read and handle this parameter, but it's not required to return it in the response. That depends on the Authorization Server you're using and how its requests/responses are customized.

**Comment by sl3w** [comment]
@lor6 Ok, thank you. I solved it in the following way: after the answer from OAuth I take this parameter from the request and add it to the response :) I don't see other way
