### ISSUE TITLE
spring-quartz start a job programmatically

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [eugenp/tutorials#10256]
I have noticed that the code for spring-quartz uses auto configuration. Is there a sample to start it programmatically? 
Thank you,

**Comment by kwoyke** [comment]
Hi @ahmed-adly-khalil ,

I assume what you're looking for is the way to trigger a job on demand. We do not provide such an example in the article.
Also, we'd like to keep the GitHub issues section focused only on the actual problems with our codebase.

Anyway, this kind of a question, you can ask on sites like StackOverflow. Please see this thread for example - https://stackoverflow.com/questions/48940203/spring-quartz-triggering-job-programmatically - maybe it will help you with our particular case. Good luck!
