### ISSUE TITLE
About the security-expression custom PermissionEvaluator Authentication authorities different than expected.

### ISSUE THREAD

**Issue by isfong** [eugenp/tutorials#10299]
Hi~! I follow your blog post [《A Custom Security Expression with Spring Security》](https://www.baeldung.com/spring-security-create-new-custom-security-expression), implements custom PermissionEvaluator, I only reference dependency `spring-boot-starter-oauth2-resource-server`,  but in the hasPermission method `authentication.getAuthorities( )` they are not some privilege，they are like String `SCOPE_read/SCOPE_write...`, I think are client scopes.
```java
    private boolean hasPrivilege( Authentication authentication, String targetType, String permission ) {
        for ( GrantedAuthority grantedAuthority : authentication.getAuthorities( ) ) {
            // The grantedAuthority is like String `SCOPE_read/SCOPE_write...`
            log.info( "{} Contains granted authority {}", authentication.getPrincipal( ), grantedAuthority );
            String authority = grantedAuthority.getAuthority( );
            if ( authority.startsWith( targetType ) && authority.contains( permission ) ) {
                return true;
            }
        }
        return false;
    }
```
What is going on, how can i do it? thanks~~~!

**Comment by lor6** [comment]
Hi @isfong Yes, if you're using OAuth, this is based on tokens which have one or more scopes. Then Spring Security transforms these into authorities of the form SCOPE_*. This is explained in the documentation here: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-authorization

**Comment by isfong** [comment]
> @isfong，您好：是的，如果您使用的是OAuth，则基于具有一个或多个范围的令牌。然后，Spring Security将它们转换为SCOPE_ *形式的授权。在文档中对此进行了解释：[https](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-authorization) : [//docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-authorization](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-authorization)
Thinks @lor6 ! they solved my troubles, `JwtAuthenticationConverter` and `JwtGrantedAuthoritiesConverter` very useful~
