### ISSUE TITLE
No controller method for /index endpoint

### ISSUE THREAD

**Issue by MuditJ** [eugenp/tutorials#10290]
Tried running the code and I found that after adding form input to create new user, the controller method addUser() returns "redirect:/index" instead of "redirect:/". As a result, this gives a 404 error as there is no /index endpoint. There is another method which has this mistake.

**Comment by lor6** [comment]
Hi @MuditJ  Which project exactly are you running?
Thanks.

**Comment by lor6** [comment]
If this was referring to the spring-boot-crud project, this is now fixed by the linked PR. If not, please reopen the issue and clarify the project.
