### ISSUE TITLE
Wrong documentation regarding "@EnableWebFlux" in Tutorial "Spring Webflux and CORS"

### ISSUE THREAD

**Issue by blatobi** [eugenp/tutorials#10296]
The [spring-webflux-cors](https://www.baeldung.com/spring-webflux-cors)-tutorial states in part 3:
> In addition, the implementation needs the @EnableWebFlux annotation to import the Spring WebFlux configuration

This is in my opinion wrong, because as stated by [Spring](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-webflux-auto-configuration)
> If you want to take complete control of Spring WebFlux, you can add your own `@Configuration` annotated with `@EnableWebFlux`.
By this it not enables some webflux-configuration but disables **all** auto-configuration.

[Spring](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-webflux-auto-configuration) documents:
> If you want to keep Spring Boot WebFlux features and you want to add additional WebFlux configuration, you can add your own `@Configuration` class of type WebFluxConfigurer but **without** `@EnableWebFlux`.

**Comment by lor6** [comment]
Thanks for the feedback @blatobi 
I've now updated this paragraph to:
"In addition, the implementation needs the @EnableWebFlux annotation to import the Spring WebFlux configuration in a plain Spring application. If we're using Spring Boot, then we only need this annotation if we want to override the auto-configuration"
