### ISSUE TITLE
Dangerous use of "finalize" in some unit test examples

### ISSUE THREAD

**Issue by Bluexin** [eugenp/tutorials#10309]
Some of the unit tests examples have their test cleanup in a method called finalize, which IMO is bad practise : 
https://github.com/eugenp/tutorials/blob/9572af280459b3f84f67ca74fd5d18274c5d1c20/testing-modules/junit-5-basics/src/test/java/com/baeldung/migration/junit5/BeforeEachAndAfterEachAnnotationsUnitTest.java#L30-L34
https://github.com/eugenp/tutorials/blob/65feb27817fa4986c434ec50349a3b3631ccc091/testing-modules/junit-5-basics/src/test/java/com/baeldung/migration/junit4/BeforeAndAfterAnnotationsUnitTest.java#L30-L34

In this case it doesn't matter much because they don't really have side effects, but when testing a spring boot app you tend to use these to clear db repositories after the tests are ran.
This doesn't usually cause many problems, until you run the tests on a memory constrained environment where the GC might be more aggressive, calling the `finalize` methods (emptying the db) while another test is running (which might depend on data it added to the db).

People might be using these as base for a while and then all of a sudden the tests get inconsistent...

**Comment by kwoyke** [comment]
Hi @Bluexin ,
That's an interesting finding!
We've updated the code and the article.
Thanks for the feedback.
Cheers
