### ISSUE TITLE
ClasspathXmlApplicationContextIntegrationTest no more work with spring 5.3.1

### ISSUE THREAD

**Issue by clockwiser** [eugenp/tutorials#10313]
ClassPathXmlApplicationContext's getBean method is changed drastically.

**Comment by kwoyke** [comment]
Hi @clockwiser ,
Thanks for the feedback. As for today our spring-core module is based on Spring 5.2.8.RELEASE.
We'll update the test when we'll be upgrading to Spring 5.3.x.
