### ISSUE TITLE
Wrong words in tutorial 'Spring Data MongoDB – Indexes, Annotations and Converters'

### ISSUE THREAD

**Issue by nakaldi** [eugenp/tutorials#10328]
Hello.

In the tutorial [https://www.baeldung.com/spring-data-mongodb-index-annotations-converter](https://www.baeldung.com/spring-data-mongodb-index-annotations-converter) says:

>2.1. @Indexed
(code example for @Indexed)
...
As you can see, we have two indexes – one of them is _id – which was created by default due to the @Id annotation and the second one is our name field.

But [Spring Data MongoDB - Reference Documentation](https://docs.spring.io/spring-data/data-mongo/docs/3.0.4.RELEASE/reference/html/#mapping.index-creation) says:
`Automatic index creation is turned OFF by default as of version 3.0.`

So the index will not be created. User have to turn on the following option:
`spring.data.mongodb.auto-index-creation=true`

Could you review this and update the tutorial document? It will be very helpful for readers. 
Thanks 👍

**Comment by kwoyke** [comment]
Hi @nakaldi,
Thanks for the feedback. Most probably the article hasn't been updated when we upgraded the spring-data-mongodb dependency,
We'll take a look into this and fix the article.

**Comment by kwoyke** [comment]
@nakaldi, we've updated the article. Cheers!
