### ISSUE TITLE
Query Param ignore after implementing zuul rate limiter

### ISSUE THREAD

**Issue by CasperOm** [eugenp/tutorials#10335]
Hi, I have implemented rate limiter on zuul and rate limit is working well but it ignores the query params which i have passed to restful GET service which requires query params.

Could you please help me on this why this is causing this issue. Below is properties added in zuul application.yml

 ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      testService:
        - limit: 10
          refresh-interval: 60

**Comment by kwoyke** [comment]
Hi @CasperOm,

Which article does it relates to?
Do you face an issue with our implementation or rather your own?

**Comment by CasperOm** [comment]
Hi @kwoyke 

I have implemented zuul rate limiter by taking reference of tutorials/spring-cloud/spring-cloud-zuul/spring-zuul-rate-limiting this project and implemented it.
also referred to this article : https://www.baeldung.com/spring-cloud-zuul-rate-limit

**Comment by kwoyke** [comment]
@CasperOm, it's hard to say what might be wrong with your implementation without seeing the actual code.
Anyway, we'd like to keep the GitHub issues section focused only on the problems with our codebase.
You should probably ask this kind of a question on sites like StackOverflow and I'm pretty sure the community will be happy to help.
Cheers

**Comment by CasperOm** [comment]
@kwoyke Thanks for your response. Surely will do it.
