### ISSUE TITLE
Errorn on Click Message on Spring Boot RTC

### ISSUE THREAD

**Issue by hendisantika** [eugenp/tutorials#10366]
Errorn on Click Message on Spring Boot RTC

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3713580/103322757-007f4500-4a72-11eb-889a-2c7d9b6f57bf.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/3713580/103322771-142aab80-4a72-11eb-8be4-d32659672a83.png">

Any advice?

Thank You

**Comment by lor6** [comment]
Hi @hendisantika  I've added a fix for this here: https://github.com/eugenp/tutorials/pull/10426 

Please update your local repository and try again.

Remember that you have to Create the Offer first, and then send the message.

**Comment by hendisantika** [comment]
OK. Let me check again.

**Comment by hendisantika** [comment]
Hi @lor6,

I already updated the code.

But the error still exist.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3713580/104815516-a50dcf00-5847-11eb-969c-426b0895657a.png">


Any advice?

Thank You

**Comment by lor6** [comment]
Hi @hendisantika Do you have 2 instances of the page open and have you clicked "Create offer" first to open the connection?

Thanks.

**Comment by hendisantika** [comment]
Yes, I have.

I think You can give me video or screen shot how to do your project so that I can follow your way.
