### ISSUE TITLE
Question about article about providing default values in JPA

### ISSUE THREAD

**Issue by chtseac** [eugenp/tutorials#10374]
https://www.baeldung.com/jpa-default-column-values

Sorry I'm opening an issue here but the comment section is closed there.

The article points out two ways to get default values into columns, namely the "just set it in the java class" method and the "columnDefinition" method.

The article then discusses that the drawback of first way is how explicitly setting `null` is possible, and the drawback of the second way is how explicitly setting `null` is impossible. 

Isn't the check against null better done by the `NOT NULL` constraint, i.e. `@NotNull`?

**Comment by lor6** [comment]
Hi @chtseac  Sure, checking against null can be done using the constraint. But the drawback of the second method is in case you do want to allow the null value. That won't be possible anymore using the second method.
