### ISSUE TITLE
"Reader to InputStream" should recommend Commons IO's ReaderInputStream

### ISSUE THREAD

**Issue by Marcono1234** [eugenp/tutorials#10382]
The article "[Java – Reader to InputStream](https://www.baeldung.com/java-convert-reader-to-inputstream)" should use and recommend Commons IO's [`ReaderInputStream`](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/ReaderInputStream.html) since that is currently the most efficient solution available.

See also https://github.com/google/guava/issues/5376

**Comment by kwoyke** [comment]
Hi @Marcono1234 ,
Thanks for the feedback. We've updated the code and the article.

**Comment by Marcono1234** [comment]
Thanks!
