### ISSUE TITLE
Broken tutorial link

### ISSUE THREAD

**Issue by Sam-Kruglov** [eugenp/tutorials#10380]
https://github.com/eugenp/tutorials/tree/master/spring-web-modules/spring-rest-query-language was recently moved to a different folder but the link on the website is still old: https://www.baeldung.com/rest-api-query-search-or-operation

**Comment by lor6** [comment]
Thanks @Sam-Kruglov  The link in the article is updated as well, but it's probably a caching issue; it may take a few hours to see the update.
