### ISSUE TITLE
graphql repository missing some files ? 

### ISSUE THREAD

**Issue by sourabhparsekar** [eugenp/tutorials#10394]
[graph-ql](https://github.com/eugenp/tutorials/tree/master/spring-boot-modules/spring-boot-libraries/src/main/java/com/baeldung/graphql)

It looks like spring boot starter files are missing when this got moved to graphql module.

**Comment by lor6** [comment]
Hi @sourabhparsekar The main class was in the demo package. I've now moved it to the graphql package.

Is there any other missing file you noticed?

Thanks.

**Comment by sourabhparsekar** [comment]
also this needs to be moved. graphql needs this file in resources 

https://github.com/eugenp/tutorials/tree/master/spring-boot-modules/spring-boot-libraries/src/main/resources/graphql

**Comment by lor6** [comment]
Moved where @sourabhparsekar ? This is in the resources folder of the project.
Thanks.

**Comment by sourabhparsekar** [comment]
looks good... :) Thank you so much...
