### ISSUE TITLE
agent path in `com.baeldung.instrumentation.application.AgentLoader`

### ISSUE THREAD

**Issue by nzomkxia** [eugenp/tutorials#10395]
in the java instrumentation example, there is "/home/adi/Desktop/agent-1.0.0-jar-with-dependencies.jar" in the `com.baeldung.instrumentation.application.AgentLoader`, how can I generate this jar file, thanks

**Comment by lor6** [comment]
Hi @nzomkxia You can generate the agent jar by following the instructions in the Instrumentation article: https://www.baeldung.com/java-instrumentation, or by simply building the project core-java-jvm, which already contains the code.

Of course, your resulting jar will have a different name and path than the example here, so you have to update that part in the AgentLoader class.
