### ISSUE TITLE
gRPC example does not compile

### ISSUE THREAD

**Issue by noam-bionicstork** [eugenp/tutorials#10390]
the gRPC example fails to compile. fixed by adding this to the grpc/pom.xml file:
```
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.2</version>
</dependency>```

**Comment by lor6** [comment]
Hi @noam-bionicstork  I checked the project and it does compile with JDK 8. I'm guessing you tried with a higher version and had this issue.

The repo is not yet upgraded to a higher version, so I'll close the PR for now, and we'll attempt to recompile when we upgrade.

Thanks.
