### ISSUE TITLE
I'd like to run tests in a single modules, from Eclipse, and no time to understand modularity...help?

### ISSUE THREAD

**Issue by tinynet** [eugenp/tutorials#10406]
I'd like to execute single tests classes in testing-modules/junit-5-basics (for example) from Eclipse...

I've imported the whole tutorial project as maven project (a bit overkill...)
I didn't manage to run tests from Eclipse, it seems it doesn't recognize a project for configuration.

I tried with mvn inside the module, it seems that it executes all tests in the module, but I can't execute a single class.

I've tried various combinations with mvn `mvn -Dtest=GreetingsUnitTest test` but with no success.

My understanding of modules and profiles it's still basic, not my priority now.

Is there some guide about how to run single unit tests in your project, with some IDE or command line?

thanks

**Comment by lor6** [comment]
Hi @tinynet One option is to import only the project you want in the IDE, for example the junit-5-basics project, and then run tests there.

I tried running _mvn -Dtest=GreetingsUnitTest test_ inside the junit-5-basics module and the test ran ok.  What result are you getting?

**Comment by tinynet** [comment]
Ok, importing only one project made the trick.
I also manage to run from the command line, probably I wasn't in the correct folder.
thanks!
