### ISSUE TITLE
Map custom url to wsdl

### ISSUE THREAD

**Issue by camibaez** [eugenp/tutorials#10449]
I created a SOAP endpoint with spring boot. 
My endpoint url is localhost:8080/AuthorizationServices.wsdl. 
How can I map it to AuthorizationServices?WSDL
?

**Comment by kwoyke** [comment]
Hi @camibaez,
What article does your question relate to?

**Comment by kwoyke** [comment]
@camibaez we can only help with questions that are specifically and directly related to our articles - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
