### ISSUE TITLE
Fix the Introduction to Vavr tutorial 

### ISSUE THREAD

**Issue by ozayduman** [eugenp/tutorials#10451]
The article "[Introduction to Vavr](https://www.baeldung.com/vavr)" says that "in Java 8 we would need to use a Consumer type, in Vavr Function0", but Vavr Funtion0 corresponds to **Supplier**  according to the its [javadoc](https://javadoc.io/doc/io.vavr/vavr/latest/io/vavr/Function0.html).

**Comment by kwoyke** [comment]
Hi @ozayduman,
That's a good catch - thanks! We updated the article.
