### ISSUE TITLE
Error building jjwts

### ISSUE THREAD

**Issue by h4cker39** [eugenp/tutorials#10501]
I am trying to build your project with the following tutorial

baeldung.com/java-json-web-tokens-jjwt
git clone https://github.com/eugenp/tutorials.git
cd tutorials/jjwt
mvn clean install

But every time I run this it gives me back...

no main manifest attribute, in target/jjwt-0.0.1-SNAPSHOT.jar

**Comment by kwoyke** [comment]
Hi @h4cker39,

Yeah these instructions seems not to be working as expected. We'll update the article!

Meanwhile, JJWTFunApplication is a simple Spring Boot app. This means you can either run it directly from the IDE of your choice or simply use the Spring Boot Maven plugin - just run mvn clean spring-boot:run inside the jjwt directory.

Hope that helps.

**Comment by h4cker39** [comment]
Sure thing

**Comment by kwoyke** [comment]
@h4cker39 we've updated the article.
