### ISSUE TITLE
CircularBuffer.java bugfix

### ISSUE THREAD

**Issue by kovacs-zs** [eugenp/tutorials#10503]
Hi,

A fix for the constructor in CircularBuffer.java:
instead of 
 
this.capacity = (capacity < 1) ? DEFAULT_CAPACITY : capacity;
this.data = (E[]) new Object[capacity];

should be

this.capacity = (capacity < 1) ? DEFAULT_CAPACITY : capacity;
this.data = (E[]) new Object[**this**.capacity];

Regards

**Comment by kwoyke** [comment]
Hi @kovacs-zs,
That's a really nice catch! Thanks. We updated the code and the article.
