### ISSUE TITLE
where is the code for java-list-primitive-performance

### ISSUE THREAD

**Issue by dongshen** [eugenp/tutorials#10517]
where could find the related code for https://www.baeldung.com/java-list-primitive-performance
and the code should get exception for java.lang.ArrayIndexOutOfBoundsException: Array index out of range for 10
@Benchmark
public int getArrayList() {
    return arrayList.get(getValue);
}

**Comment by kwoyke** [comment]
Hi @dongshen ,

The code is located here https://github.com/eugenp/tutorials/tree/master/core-java-modules/core-java-collections-list-3/src/main/java/com/baeldung/list/primitive

And yes, it looks like the benchmark is throwing ArrayIndexOutOfBoundsException. We'll fix the code and update the article.

**Comment by kwoyke** [comment]
We fixed the code and update the article accordingly.
