### ISSUE TITLE
Removing all duplicates from a List in Java

### ISSUE THREAD

**Issue by jferard** [eugenp/tutorials#10523]
Disclaimer : this may have been discussed in the comments of the article ["Removing all duplicates from a List in Java"](https://www.baeldung.com/java-remove-duplicates-from-list), but I can't make these comments visible in my browser.

In the article "Removing all duplicates from a List in Java", both plain Java and Guava versions may affect the order of the elements because of the `HashSet` (I believe that the `parallelStream` of the Java8 version keeps the order). I guess this is not an error of inattention but, considering the title of the article, this is not what I expected. I just expected the instance of each value be kept and the other instances to be dropped. If you consider the list `0a, 1, 2, 3, 0b, 0c` as a sequence, only `0b` and `0c` are duplicates, not `0a` because when you meet `0a`, there is no other `0`.

Something like this (see https://github.com/eugenp/tutorials/blob/master/core-java-modules/core-java-collections-list/src/test/java/com/baeldung/collections/JavaCollectionCleanupUnitTest.java):

    @Test
    public final void givenListContainsDuplicates_whenRemovingDuplicatesWithPlainJava_thenCorrect() {
        final List<Integer> listWithDuplicates = Lists.newArrayList(0, 1, 2, 3, 0, 0);
        final List<Integer> listWithoutDuplicates = ...;

        assertEquals(Lists.newArrayList(0, 1, 2, 3), listWithoutDuplicates);
    }

I think you should either specify that the order may not be preserved, or provide another implementation such as:

    public static <T> List<T> removeDuplicates(List<T> values) {
        List<T> uniqueValues = new ArrayList<T>(values.size());
        Set<T> seen = new HashSet<T>();
        for (T value : values) {
            if (!seen.contains(value)) {
                uniqueValues.add(value);
                seen.add(value);
            }
        }
        return uniqueValues;
    }

(Or provide both impementations.)
BTW, thanks for your precious site.

**Comment by nomuna** [comment]
I think the fact he is using HashSet to filter out the duplicates indicates that he doesn't care about the order. If he cared he would have gone to the trouble of using may be a LinkedHashSet which preserves the order of items added dropping duplicates as well.

**Comment by jferard** [comment]
I agree that this is probably a choice. The issue, in my mind, is that this choice was implicit while it should have been documented.

**Comment by nomuna** [comment]
HashSet is an implementation of the Set interface. Set in itself mathematically doesn't impose any order on its members. So I would say it is not necessary to write again as documentation or comment. It would be redundant in my opinion.

If you read the javadoc of HashSet it says that it makes no guarantee as to the order of iteration of the set.

**Comment by jferard** [comment]
I think there are two different levels: specification and implementation. It is not specified that the order does not matter. Using a `HashSet` (implementation) does make the intent (specification) clear because we don't know if it's a bug or a feature.

Here's a caricature that's makes the issue clearer.

Imagine this implementation:

    List<Integer> listWithoutDuplicates = new ArrayList<>();

The duplicates are indeed removed. Actually, all elements are removed. Is it a bug or a feature? Would you say that it's clear that the other elements didn't matter because they have disappeared? I would say that the result is not the expected result. Either the implementation is wrong or the specification is incomplete.

**Comment by nomuna** [comment]
Well what the test does or what he wanted to achieve is written as a test method name and he used a data structure that removes duplicates... I don't need any more information to understand what is going on. I don't really understand why this is such a bis issue for you. Code that documents itself is better than some lengthy comment or whatever that need to be kept up to date with the implementation.

**Comment by jferard** [comment]
A last try to convince you:

> Well what the test does or what he wanted to achieve is written as a test method name and he used a data structure that removes duplicates...

The various tests checks only the size of the set. I can think of a lot of functions that pass these tests. That means that the test itself is a pretty loose specification. If I look at the name of the test, I have more information but I still don't know if the order of elements be preserved or not.

> I don't need any more information to understand what is going on. 

It's not about you (or me). "This article is part of the “Java – Back to Basic” series here on Baeldung." The article targets beginners. It should be clear what the code is trying to achieve.

> I don't really understand why this is such a bis issue for you.

It is so obvious for me that something is missing the article (a warning or an alternative implementation) that I don't understand why you are convinced that this is ok.

> Code that documents itself is better than some lengthy comment or whatever that need to be kept up to date with the implementation.

That's another issue. If this code is part of a production code, we might already know if the order of elements is relevant, and why. If this is clear for everyone, then we might leave this question out.
But how do you distinguish between visitors of the site that want the order of elements preserved and the visitors that don't care about the order? Why would it be so hard to satisfy everyone?

**Comment by nomuna** [comment]
> But how do you distinguish between visitors of the site that want the order of elements preserved and the visitors that don't care about the order? Why would it be so hard to satisfy everyone?

Satisfying everyone is an impossible task... 
But in all the tests in the class he doesn't care about the order of the items in the collection. If he wanted to write a test for that case he would have done it. Why don't you extend the class write such a test and push it as a pull request.

Something like this.

```java
    @Test
    public final void givenListContainsDuplicates_whenRemovingDuplicatesWithPlainJava_thenCorrectAndInOrder() {
        final List<Integer> listWithDuplicates = Lists.newArrayList(0, 1, 2, 3, 0, 0);
        final List<Integer> listWithoutDuplicates = new ArrayList<>(new LinkedHashSet<>(listWithDuplicates));

        assertArrayEquals(Lists.newArrayList(0, 1, 2, 3).toArray(), listWithoutDuplicates.toArray());
    }
```

**Comment by jferard** [comment]
Unfortunately, this does not address the issue that the **article** is somehow misleading, or at least lacks of precision.

And you are again focusing on implementation. If I don't rely on `HashSet` to keep the insertion order of elements, it's not because it is implemented with a hash table (think of it: `LinkedHashSet` uses also a hash table), it is because of the *contract*:
>  It makes no guarantees as to the iteration order of the set; in particular, it does not guarantee that the order will remain constant over time (https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/HashSet.html)

If I knew that the `HashSet` implementation kept the insertion order, I still would not rely on it because it might change at any time.

Please have a look at this: https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6. There is an interesting discussion on the difference between an implementation and a specification.

**Comment by nomuna** [comment]
> 
> 
> Unfortunately, this does not address the issue that the **article** is somehow misleading, or at least lacks of precision.
>

I don't think so but which parts are misleading for you exactly? Please be specific. There are three points and in NONE of them he mentions that he wants to keep the order of the elements in List.

1. Remove Duplicates From a List Using Plain Java
2. Remove Duplicates From a List Using Guava
3. Remove Duplicates From a List Using Java 8 Lambdas

> And you are again focusing on implementation. If I don't rely on `HashSet` to keep the insertion order of elements, it's not because it is implemented with a hash table (think of it: `LinkedHashSet` uses also a hash table), it is because of the _contract_:
> 

The contract is set with the interface. Interface being a Set which is a mathematical model stating that the implementation must be such that no duplicates are allowed. HashSet is an implementation using hash table to implement that feature.
The second sentence in the quoted text above  makes me suspect that you are confusing HashSet with linkedHashSet.

> It makes no guarantees as to the iteration order of the set; in particular, it does not guarantee that the order will remain constant over time (https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/HashSet.html)
> 
Yes that is what Set/HashSet means. And I pointed it out to you in the previous post. You can expect every time you retrieve elements from the set the order in which they will appear is random. 
I said IF you want to keep the order of the elements AND remove the duplicates you can use LinkedHashSet.  
_HashSet_ means that it is a _Set_ (your _contract_ here ) that uses _hash table/hash function_ to remove the duplicates, _linked_ means that the underlying structure functions like a linked list and keeps the elements it contains in the order in which they were inserted.

Still think you are mixing up the two data structures.

**Comment by jferard** [comment]
> makes me suspect that you are confusing HashSet with linkedHashSet.

I think that's the core of our discussion: you assume that I have a problem (I don't know the basic data structures, I can't read the implementation of `HashSet`, I'm mixing up data structures...) and you want to help me (thank you). But I still think the article has a problem, not me.

> Please be specific. There are three points and in NONE of them he mentions that he wants to keep the order of the elements in List.

That's the issue. There is no way to know if the goal was:

- to remove duplicates and keep the order: in this case, the implementation is bugged;
- to remove duplicate but do not care about the order: in this case, there is a lack of precision.

I say that this article should not let something like the possible loss of the order of elements unspecified.

If you think the lack of precision is not an issue, then I would say: none of the points mentions what he wants to do with the elements of the list that are not duplicates.

Hence:

    return new ArrayList<>();

would be a correct implementation (the duplicates are removed, aren't they?).

The reasonable expectation is, in my mind, that the following postcondition is met:

1. all elements present in the given list are in the returned list;
2. the returned list does not contain any element more than once;
3. the order of elements of the returned list matches the order of elements of the given list (more precisely, the returned list is a subsequence of the given list).

The `return new ArrayList<>()` violates 1. Everybody will accept that 1 is a reasonable expectation and that's why nobody would accept this implementation. 

2 is the explicit subject of the article. 

We can discuss about 3: is it reasonable or not? You seem to think that it's not, I think that it is. The best way to fix this is to give a warning: if you expect 3, then look for another implementation (and maybe: this is the implementation you are looking for: ...).

**Comment by kwoyke** [comment]
@jferard @nomuna thanks for your input :)
We'll update the article so that it's clear for everybody.
Thanks for the feedback!

**Comment by jferard** [comment]
@kwoyke Thank you.
@nomuna Thanks for trying to help.

**Comment by jferard** [comment]
@kwoyke Thanks to you.
