### ISSUE TITLE
Spring boot admin redirects to /login when clicking on an application

### ISSUE THREAD

**Issue by uklance** [eugenp/tutorials#10530]
spring-boot-admin-starter-server version 2.4.0 is broken when adding the login page and security to SBA. The app will redirect to the /login page when you try to click on any of the apps (eg from the wallboard or from the applications list)

See spring-boot-admin issue 1640 - issue https://github.com/codecentric/spring-boot-admin/issues/1640

Downgrading to version 2.3.1 fixes the issue
```
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-server</artifactId>
			<version>2.3.1</version>
		</dependency>
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-server-ui-login</artifactId>
			<version>1.5.7</version>
		</dependency>

```

**Comment by kwoyke** [comment]
Hi @uklance ,
Thanks for the heads-up. We'll update our module to use the most recent versions.

**Comment by kwoyke** [comment]
We've upgraded spring-boot-admin-* dependencies to the most current versions.
