### ISSUE TITLE
Much easier usage of testcontainers

### ISSUE THREAD

**Issue by rafis** [eugenp/tutorials#10543]
Hi,
https://www.baeldung.com/spring-boot-testcontainers-integration-test

There is much easier usage of testcontainers if you don't need fine grained control over Postgres container, just add following lines into _src/test/resources/application.properties_:
```
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.datasource.url=jdbc:tc:postgresql:12:///postgres
spring.jpa.hibernate.ddl-auto=create
```

**Comment by kwoyke** [comment]
Hi @rafis ,
Thanks for the feedback. We'll take a look into this and update the article.

**Comment by kwoyke** [comment]
We updated the article.
