### ISSUE TITLE
MIME Type detection

### ISSUE THREAD

**Issue by rafis** [eugenp/tutorials#10626]
Please can you explicitly describe for each method:
https://www.baeldung.com/java-file-mime-type

Is it either:
1) file extension based detection
2) magic bytes based detection

Just listing various methods doesn't does not carry much value.

**Comment by dkapil** [comment]
@rafis the article purely lists different ways of obtaining the Mime Type of a file. The individual details can be explored further using Java official docs and jmimemagic docs incase we want to explore the 3rd party library.
