### ISSUE TITLE
Decrypted  strings return strange characters

### ISSUE THREAD

**Issue by Blakes-Mike** [eugenp/tutorials#10625]
In my use case i'm encrypting unique Ids and storing them on a MYSQL database, encryption and decryption work initially , but as soon as i restart the application and attempt to decrypt  stored keys then i get bad values like these: Q�5�ع��N�n��͡b6e39b59e090fdd4
YԢ����w\"q�)-b287f7766b71ca22 etc.

**Comment by kwoyke** [comment]
Hi @Blakes-Mike ,

What article are you referring to?
