### ISSUE TITLE
Could not find artifact org.baeldung.pmd:custom-pmd:jar:0.0.1 in central (https://repo.maven.apache.org/maven2)

### ISSUE THREAD

**Issue by logi92** [eugenp/tutorials#10640]
I downloaded this repo and maven give me some problems 
Cannot resolve plugin org.apache.maven.plugins:maven-pmd-plugin:3.13.0
Could not find artifact org.baeldung.pmd:custom-pmd:jar:0.0.1 in central (https://repo.maven.apache.org/maven2)
Could not find artifact org.baeldung.pmd:custom-pmd:pom:0.0.1 in central (https://repo.maven.apache.org/maven2)

**Comment by kwoyke** [comment]
Hi @logi92 ,

The easiest way to explore the code for a particular module is to clone the whole repo and then import only that module into your IDE. 
Hope that helps.

Cheers
