### ISSUE TITLE
RestTemplate using Operations interfaces

### ISSUE THREAD

**Issue by rafis** [eugenp/tutorials#10662]
Hi!

https://www.baeldung.com/spring-interface-driven-controllers
https://github.com/eugenp/tutorials/tree/master/spring-web-modules/spring-5-mvc

You show only half. You show only how to use Operations interfaces in Server-side, so I can create "*-api" Maven/Gradle-module (as library) and use it in "*-service" Maven/Gradle-module (as microservice). But how to use it in Client-side (in RestTemplate)? How can I call these routes and methods defined Operations interfaces from RestTemplate/WebClient without manually specifying route and method because they are already specified in interface annotations?

**Comment by ehsansasanian** [comment]
Hi @rafis, could you explain what you mean by "How can I call these routes and methods defined  ..."?
Do you want to use it in the same application, or do you want to call the REST API from another server app?

**Comment by dkapil** [comment]
Closing this one. Feel free to re-open if there are any further questions.
