### ISSUE TITLE
cas server not picking the service registry, <Loaded [0] service(s) from [InMemoryServiceRegistry] CAS Version: 6.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by ajalbani1** [eugenp/tutorials#10671]
Hello. My cas server which I deployed with the cas-overlay-template is not picking my json service.

**Comment by kwoyke** [comment]
Hi @ajalbani1 ,
What article are you referring to? Do you face an issue with our implementation or with your custom app?

**Comment by ajalbani1** [comment]
appologies. I think I put it in the wrong repo. I am using https://github.com/apereo/cas-overlay-template.
Any ideas where to register json services?

**Comment by kwoyke** [comment]
@ajalbani1 Unfortunately, we can only help with questions that are specifically and directly related to our articles - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
