### ISSUE TITLE
Not able to generate statistics in 3.6.10 Final release

### ISSUE THREAD

**Issue by karand1985** [eugenp/tutorials#10690]
Hi, 
We are trying to generate_statistics in hibernate 3.6.10 Final jar version. but are not able to generate the same. 
switching to older hibernate version 3.6.2 version the statistics are generated. 
Do we require to do something different to generate statistics in 3.6.10 ?

Note: we have updated the property generate_statistics = true in persistence-config.xml 
 Env
 Tomcat 8.5.x
 Hibernate 3.6.10
Spring 4.3.x
 Log4j2

Let know if you require more information. 

Thank you.

Regards,
Karan Dave.

**Comment by kwoyke** [comment]
Hi @karand1985,
Which article are you referring to?

**Comment by karand1985** [comment]
We are encountering this problem of statistics not getting generated in our dev environment. 
On researching more on google we found this article 
https://github.com/eugenp/tutorials/tree/master/persistence-modules/spring-hibernate-3

In this also hibernate 3.6.10 is used. so i raised the query if any thing is changed in this version to generate the hibernate statistics since, the hibernate version 3.6.2 generates statistics. 

Regards,
Karan Dave.

**Comment by kwoyke** [comment]
Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

Please check the Hibernate change log and/or ask the Hibernate community. Also, StackOverflow is a great place to ask this kind of questions.
