### ISSUE TITLE
tutorials/spring-cucumber: "mvn clean test" doesn't run cucumber tests

### ISSUE THREAD

**Issue by N1kbaz** [eugenp/tutorials#10700]
When I run command 'mvn clean test' from directory '/tutorials/spring-cucumber' then only test from file 'SpringContextTest' runs.
Expected: cucumber tests are run too.

P.S. 'mvn clean install -Pintegration' throws warning "The requested profile "integration" could not be activated because it does not exist"

**Comment by kwoyke** [comment]
Hi @N1kbaz,
You can either run the Cucumber tests manually right from the IDE or use the following maven command:
mvn clean test -Pintegration-lite-first --fail-at-end -Dgib.enabled=false

Hope this helps :)
