### ISSUE TITLE
close the server’s response body in interceptor example

### ISSUE THREAD

**Issue by swankjesse** [eugenp/tutorials#10723]
I'm reading part 7 here:
https://www.baeldung.com/java-okhttp-interceptors#error-handling-using-interceptors

The server’s response body is replaced with a custom error response body. This is a neat example! But the server’s response must be closed because it's now unreachable.

```
response.body().close();
```

**Comment by kwoyke** [comment]
Hi @swankjesse ,
Thanks for the hint. We'll update the article and related code.

**Comment by kwoyke** [comment]
@swankjesse We updated the article.
