### ISSUE TITLE
State changes is not recorded in the event store

### ISSUE THREAD

**Issue by wjqq** [eugenp/tutorials#10755]
All the state change need to be recorded in the event store, But I don't see any code  recording the order aggregate state change for OrderShippedEvent

https://github.com/eugenp/tutorials/tree/master/axon

**Comment by kwoyke** [comment]
@wjqq we use axon-spring-boot-starter and it takes care of all the configuration necessary to properly setup the Event Store. Remember you still need to download and run the server manually.
