### ISSUE TITLE
Number 9 doesn't seem to be connected with number of related authors

### ISSUE THREAD

**Issue by jkwiatko** [eugenp/tutorials#10796]
"We've got an article class with a list of authors, and the article that can have more than one author. Furthermore, we consider an author related to the article if his related article’s id matches article id."

In [ExecutorUnitTest](https://github.com/eugenp/tutorials/blob/master/core-java-modules/core-java-8/src/test/java/com/baeldung/spliteratorAPI/ExecutorUnitTest.java) Article has 13 related authors, but test asserts code for 9.

https://github.com/eugenp/tutorials/blob/daf5a7c1893a2a3d9e14750a3d756884c8ed62d4/core-java-modules/core-java-8/src/test/java/com/baeldung/spliteratorAPI/ExecutorUnitTest.java#L36

**Comment by kwoyke** [comment]
Hi @jkwiatko ,
Yeah some parts of the article are a bit unclear. We created an internal task to improve the article and related code.
Thanks for the feedback!
