### ISSUE TITLE
Use `@KeycloakConfiguration` 

### ISSUE THREAD

**Issue by M-Razavi** [eugenp/tutorials#10895]
Instead of 3 annotations 

- @Configuration
- @EnableWebSecurity
- @ComponentScan

You can use `@KeycloakConfiguration` which includes them.

https://github.com/eugenp/tutorials/blob/3f964961dac1d38c1660c114bd7a828b765191e9/spring-boot-modules/spring-boot-keycloak/src/main/java/com/baeldung/keycloak/SecurityConfig.java#L21

**Comment by kwoyke** [comment]
Hi @M-Razavi ,
Thanks for the feedback. We've updated the code.
