### ISSUE TITLE
multicoreSupport = true not found

### ISSUE THREAD

**Issue by landoephan** [eugenp/tutorials#10918]
when I use the option "multicoreSupport = true" at @EnableSolrRepository I get the following error:

`The attribute multicoreSupport is undefined for the annotation type EnableSolrRepositories`

is there a workaround to fix this?

**Comment by kwoyke** [comment]
Hi @landoephan ,
Note that in our module we don't use the latest version of spring-data-solr.
multicoreSupport has been removed in the more recent releases.
Please see this StackOverflow thread - https://stackoverflow.com/questions/52123135/spring-data-solr-multi-core-support
Hope that helps.
