### ISSUE TITLE
RestEasy 3.0.14

### ISSUE THREAD

**Issue by enriqueism** [eugenp/tutorials#10954]
This is not an issue, just a question. Is there a reason to keep the tutorial /tutorials/resteasy in version 3.0.14?, I'm try to find -without success- a tutorial/example using RestEasy 4.5.x or 4.6.x branches. Is there an issue whith those branches or is more estable the 3.x? Or developers is changing RestEasy to another REST Framework?
Thanks in advance for your reading.

**Comment by kwoyke** [comment]
Hi @enriqueism ,
There's no particular reason we keep it on 3.x version. We simply haven't upgraded the article yet. This is something we'll done in the future though.
Cheers
