### ISSUE TITLE
Possible NPE

### ISSUE THREAD

**Issue by driversti** [eugenp/tutorials#10976]
https://github.com/eugenp/tutorials/blob/d2a505b879386558135e80c06770d552c70eef39/libraries-data-db/src/main/java/com/baeldung/libraries/debezium/service/CustomerService.java#L24
You will get NPE if the `operation` attribute is `null`

Consider the following solution:
`if (Operation.DELETE == operation)`

**Comment by kwoyke** [comment]
Hi @driversti,
Thanks for a good catch! I updated the code.
Cheers
