### ISSUE TITLE
the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by martijnhiemstra** [eugenp/tutorials#10997]
The keystore works fine however when I implement the truststore I get this error:

gateway                  | org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
gateway                  | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
gateway                  | 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
gateway                  | 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
gateway                  | 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
gateway                  | 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
gateway                  | 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
gateway                  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
gateway                  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
gateway                  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
gateway                  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
gateway                  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
gateway                  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
gateway                  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
gateway                  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
gateway                  | 	at eu.orderysystems.gateway.GatewayApplication.main(GatewayApplication.java:16)
gateway                  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gateway                  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gateway                  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gateway                  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
gateway                  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
gateway                  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
gateway                  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
gateway                  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
gateway                  | Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
gateway                  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229)
gateway                  | 	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)
gateway                  | 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
gateway                  | 	... 22 common frames omitted
gateway                  | Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
gateway                  | 	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:231)
gateway                  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)
gateway                  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
gateway                  | 	... 24 common frames omitted
gateway                  | Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
gateway                  | 	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1058)
gateway                  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
gateway                  | 	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:227)
gateway                  | 	... 26 common frames omitted
gateway                  | Caused by: java.lang.IllegalArgumentException: the trustAnchors parameter must be non-empty
gateway                  | 	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:99)
gateway                  | 	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71)
gateway                  | 	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:216)
gateway                  | 	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1141)
gateway                  | 	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1227)
gateway                  | 	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:592)
gateway                  | 	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1055)
gateway                  | 	... 28 common frames omitted
gateway                  | Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
gateway                  | 	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
gateway                  | 	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:157)
gateway                  | 	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:130)
gateway                  | 	at org.apache.tomcat.util.net.SSLUtilBase.getParameters(SSLUtilBase.java:492)
gateway                  | 	at org.apache.tomcat.util.net.SSLUtilBase.getTrustManagers(SSLUtilBase.java:423)
gateway                  | 	at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:246)
gateway                  | 	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:97)
gateway                  | 	... 34 common frames omitted

**Comment by kwoyke** [comment]
Closed due to lack of activity.
