### ISSUE TITLE
Make "reactive-systems" module runnable from within IDEA IntelliJ

### ISSUE THREAD

**Issue by lopotun** [eugenp/tutorials#11029]
There are multiple issues with this module:

1. docker-compose.yml is missing.
2. Dockerfile in each submodule (inventory-service, order-service and shipping-service) tries to copy non-existing jar file:
`COPY target/[module name]-async-0.0.1-SNAPSHOT.jar app.jar` instead of `COPY target/module name-0.0.1-SNAPSHOT.jar app.jar`
3. inventory-service, order-service and shipping-service containers fail to start in Docker due to missing mainClass in jar manifest.

**Comment by kasramp** [comment]
Hi @lopotun - we updated the code, added the `docker-compose` and fixed the copy issue. Additionally, the article is updated to reflect the changes as well as how to create the Jar file: [https://www.baeldung.com/java-reactive-systems](https://www.baeldung.com/java-reactive-systems)
