### ISSUE TITLE
Association, Aggregation, Composition example

### ISSUE THREAD

**Issue by mfsi-shubhankar** [eugenp/tutorials#11022]
I wanted to know under University example with professors and departments the following code was published:

https://github.com/eugenp/tutorials/blob/ad6d8ff7378f9c7e553e9321772d5739a244778b/core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/relationships/university/University.java

Isn't this the aggregation pattern, University was said to be in composition with the departments but it is not responsible for life cycle of the departments in this example.

I am little confused here, is this still composition relation between University and departments?

**Comment by kwoyke** [comment]
As already mentioned in the article, if the university is destroyed then the departments should also be destroyed, hence the relationship b/w university and departments is Composition.
Its not compulsorily that in implementation of Composition one class should contain another class, it depends on the requirements. Composition code can be implemented in multiple ways as per requirements.
Hope this helps.
