### ISSUE TITLE
Tutorial WAR for deploying on Tomcat not running

### ISSUE THREAD

**Issue by lbenda** [eugenp/tutorials#11032]
The war which is generated by maven from module spring-boot-modules/spring-boot-deployment not take any request on Tomcat. Only 404 is returned. The deploying is successfull but no request/response work.

Minor bug: https://www.baeldung.com/spring-boot-war-tomcat-deploy talk about project spring-boot-tomcat, not spring-boot-deployment.

This is part of access log:
0:0:0:0:0:0:0:1 - admin [14/Jul/2021:09:48:29 +0200] "GET /manager/html HTTP/1.1" 200 16556
0:0:0:0:0:0:0:1 - admin [14/Jul/2021:09:48:31 +0200] "POST /manager/html/stop?path=/spring-boot-deployment&org.apache.catalina.filters.CSRF_NONCE=757ACA1C7A50F784C9840676F5A6D9CD HTTP/1.1" 200 15998
0:0:0:0:0:0:0:1 - admin [14/Jul/2021:09:48:33 +0200] "POST /manager/html/start?path=/spring-boot-deployment&org.apache.catalina.filters.CSRF_NONCE=5AE01E597D25EB76934B1E6B5A617FAF HTTP/1.1" 200 16626
0:0:0:0:0:0:0:1 - - [14/Jul/2021:09:48:39 +0200] "GET /spring-boot-deployment/ HTTP/1.1" 404 774
0:0:0:0:0:0:0:1 - - [14/Jul/2021:09:48:42 +0200] "GET /spring-boot-deployment/hello HTTP/1.1" 404 779
0:0:0:0:0:0:0:1 - - [14/Jul/2021:09:48:46 +0200] "GET /spring-boot-deployment/hello/ HTTP/1.1" 404 784

**Comment by kwoyke** [comment]
Hi @lbenda ,
Thanks for the feedback.
Indeed, I see `<mainClass>com.baeldung.webjar.WebjarsdemoApplication</mainClass>` in our pom.xml. We'll take a look into this.

**Comment by kwoyke** [comment]
We verified the application works as expected.
We also fixed the minor bugs in the article. Thanks for catching that!
Closing.
