### ISSUE TITLE
Your XSSUtils.java approach to prevent XSS is doomed to failure

### ISSUE THREAD

**Issue by kwwall** [eugenp/tutorials#11076]
Hi. Not to be negative, but my ESAPI co-lead @xeno6696 and I became recently aware of your unintentionally misleading Baeldung tutorial, https://www.baeldung.com/spring-prevent-xss, via our (now closed) [ESAPI GitHub issue 634](https://github.com/ESAPI/esapi-java-legacy/issues/634) and you should really read through those comments and update your tutorial. (I would have commented, but the comments are now closed).

This entire approach is simply doomed to fail even though it may work fine in your simple test cases.

However, since this presents itself as a security issue, and recommends using ESAPI in a non-approved way as a defense against XSS, as ESAPI co-leaders, we feel we need to speak up about this.

**Comment by lor6** [comment]
Thanks for the feedback @kwwall We're looking into this.

**Comment by venkatsimhadri** [comment]
Could someone please help me with all the types of data this filter will strip from request??

**Comment by ashleyfrieze** [comment]
It's recommended to look at https://github.com/ESAPI/esapi-java-legacy/issues/634 for discussion on this subject. Baeldung is updating the article at https://www.baeldung.com/spring-prevent-xss to take on board the input from @kwwall

**Comment by lor6** [comment]
We've now removed the section using esapi from the article.
