### ISSUE TITLE
Include Gradle setup for Spring Native Example: https://github.com/eugenp/tutorials/tree/master/spring-native

### ISSUE THREAD

**Issue by marcellodesales** [eugenp/tutorials#11116]
The spring native example doesn't include Gradle resources, just pom.xml...

Can you add it?

Thank you much! I'm a huge fan and I read all articles!

Marcello

**Comment by kwoyke** [comment]
Hi @marcellodesales ,
Vast majority of our projects are maven modules.
Few exceptions are modules that work with gradle explicitly, like https://github.com/eugenp/tutorials/tree/master/gradle-5
So we're unable to provide the gradle configuration for this particular case. You need to care of this yourself or stick with maven.
