### ISSUE TITLE
`ExecutorService` started by `Executors.newSingleThreadExecutor()` is never shut down

### ISSUE THREAD

**Issue by kriegaex** [eugenp/tutorials#11119]
When trying to use the example code from https://www.baeldung.com/run-shell-command-in-java, I noticed that my process never terminated because the `ExecutorService` started by `Executors.newSingleThreadExecutor()` is never shut down. So, instead of simply calling

```java
Executors.newSingleThreadExecutor().submit(streamGobbler);
int exitCode = process.waitFor();
assert exitCode == 0;
executorService.shutdown();
```

it should rather be

```java
ExecutorService executorService = Executors.newSingleThreadExecutor();
executorService.submit(streamGobbler);
int exitCode = process.waitFor();
assert exitCode == 0;
executorService.shutdown();
```

I think you should both update the Baeldung article and update your tests here:

https://github.com/eugenp/tutorials/blob/950bbadc353bdca114befc98cf4a18476352220e/core-java-modules/core-java-os/src/test/java/com/baeldung/shell/JavaProcessUnitIntegrationTest.java#L32-L61

**Comment by kwoyke** [comment]
Hi @kriegaex ,
Thanks for the feedback. We updated the code.

**Comment by kriegaex** [comment]
Thank you very much. BTW, do you always close issues before a feature branch is merged back into master? That kind of workflow could result in forgetting to actually merge, because the issue was closed already.

**Comment by kwoyke** [comment]
I closed the issue after the PR had been merged to master - https://github.com/eugenp/tutorials/pull/11502

**Comment by kriegaex** [comment]
Oh, I am so sorry. I did not see the `shutdown` command in the test code where I had suggested to put it. It is in the `@After tearDown` method, which I had overlooked because I had to scroll up. I am sorry for the noise. Thanks again.
