### ISSUE TITLE
scope

### ISSUE THREAD

**Issue by xenoterracide** [eugenp/tutorials#11142]
https://www.baeldung.com/spring-bean-scopes
https://github.com/eugenp/tutorials/tree/master/spring-core-2

This should really describe how to create and register a custom scope. Useful for stuff like [`SimpleTransactionScope`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/support/SimpleTransactionScope.html) which is not registered out of the box.

**Comment by ehsansasanian** [comment]
Hi @xenoterracide, here is an article that explains how to create a custom scope https://www.baeldung.com/spring-custom-scope
Could you explain why it is necessary to be presented in this article?

**Comment by xenoterracide** [comment]
Because I'm not talking about creating a custom scope I'm talking about registering one. Simple transaction scope is part of spring, but unlike the other Scopes it's not registered by default.

**Comment by ehsansasanian** [comment]
In the same article, it's explained how to register your intended scope (https://www.baeldung.com/spring-custom-scope#registering-the-custom-scope). I guess you can use that part to register any scope out of the box.

**Comment by dkapil** [comment]
Based on comments by @ehsansasanian closing this issue.
Feel free to re-open or create a new one if needed.
