### ISSUE TITLE
Bug in Travel.java. List needs to be cloned.

### ISSUE THREAD

**Issue by mariokoehler** [eugenp/tutorials#11184]
This issue regards this class:

https://github.com/eugenp/tutorials/blob/master/algorithms-genetic/src/main/java/com/baeldung/algorithms/ga/annealing/Travel.java

that is related to this article (article contains code snippets that include the bug!):

https://www.baeldung.com/java-simulated-annealing-for-traveling-salesman

I'm pretty sure that the assignments of "previousTravel" and "travel" are not doing what you are intending them to do:

```
private ArrayList<City> travel = new ArrayList<>();
private ArrayList<City> previousTravel = new ArrayList<>();

public void swapCities() {
  int a = generateRandomIndex();
  int b = generateRandomIndex();
  previousTravel = travel;
  City x = travel.get(a);
  City y = travel.get(b);
  travel.set(a, y);
  travel.set(b, x);
}

public void revertSwap() {
  travel = previousTravel;
}

```
Since they aren't primitive types, the assignment of "previousTravel = travel" does not "save" an independent  copy of travel (to later restore in revertSwap(). All you have is two "pointers" pointing to the same list in memory. So whenever you modify travel you also modify the "saved" copy in previousTravel.

What you wanna do is something like "previousTravel = new ArrayList<>(travel)" which will make an independent clone. Then you can modify travel without affecting the "saved" copy in previousTravel.

You could also go without the previousTravel List alltogether, by saving instead the two indices "a" and "b" that you swapped and then simply reverse the swap in revertSwap() by swapping the same two indices again. This will be a lot faster than cloning potentially large lists and easier on the garbage collector.

**Comment by kwoyke** [comment]
Thanks @mariokoehler ,
We fixed the article.
