### ISSUE TITLE
a question on https://www.baeldung.com/java-spliterator

### ISSUE THREAD

**Issue by carl-don-it** [eugenp/tutorials#11181]
i don't quite understand the logic in this method `com.baeldung.spliteratorAPI.RelatedAuthorCounter#accumulate`
i don't even know what  the point is ?
``` 
    public RelatedAuthorCounter accumulate(Author author) {
        if (author.getRelatedArticleId() == 0) {
            return isRelated ? this : new RelatedAuthorCounter(counter, true);
        } else {
            return isRelated ? new RelatedAuthorCounter(counter + 1, false) : this;
        }
    }
``` 
accordin to the article : `Furthermore, we consider an author related to the article if his related article’s id matches article id.`
actual code would be 
```
    public RelatedAuthorCounter accumulate(Author author) {
        if (author.getRelatedArticleId() == 1) { // 0 or 1 is ok, though result is differ ,but logic is right
            return isRelated ? new RelatedAuthorCounter(counter+1, true) : new RelatedAuthorCounter(1, true);
        } else {
            return  this ;
        }
    }
```
and the custom trySplit method `com.baeldung.spliteratorAPI.RelatedAuthorSpliterator#trySplit` does no difference no matter  `if (list.get(splitPos).getRelatedArticleId() == 0)` or not .

**Comment by kwoyke** [comment]
Hi @carl-don-it ,
Yeah some parts of the article are a bit unclear. We created an internal task to improve the article.
Thanks for the feedback!
