### ISSUE TITLE
Logic issue in UUIDGenerator.get64MostSignificantBitsForVersion1()

### ISSUE THREAD

**Issue by kierankelleher** [eugenp/tutorials#11207]
Since time is in 100 nano increments shouldn't the nanos be divided by 100 and not multiplied by 100?

```
long timeForUuidIn100Nanos = seconds * 10000000L + nanos / 100L;
```

**Comment by kasramp** [comment]
Hi @kierankelleher - the article has been updated and the issue is addressed.
Thanks
