### ISSUE TITLE
[Springboot-mongodb-persistence] NumberFormatException for the sequence string defined in User model

### ISSUE THREAD

**Issue by avitripathy01** [eugenp/tutorials#11343]
Setting a non-integer value in the sequence name in the User model defined in [1] throws a NumberFormat exception. After changing the value to an integer, the SequenceGenerator generates the sequence from the defined number. 

I am currently using Springboot v 2.5.5

[1] https://github.com/eugenp/tutorials/blob/master/persistence-modules/spring-boot-persistence-mongodb/src/main/java/com/baeldung/mongodb/models/User.java

**Comment by kwoyke** [comment]
Closed due to lack of activity.
