### ISSUE TITLE
Order in FilterRegistrationBean is ignored

### ISSUE THREAD

**Issue by MichaelKunze** [eugenp/tutorials#11370]
If you follow the hint in `tutorials/spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/bootcustomfilters/FilterConfig.java` and set a breakpoint in ServletContextInitializerBean:92 you see that the order of the `RequestResponseLoggingFilter` is ignored. It is set to 2147483647 (which is the default value)

It works if you don't use FilterRegistrationBean and let spring do it's magic.

**Comment by kwoyke** [comment]
Hi @MichaelKunze,
Thanks for the feedback. We've update the code and the article.
