### ISSUE TITLE
spring-cucumber example not behaving as expected

### ISSUE THREAD

**Issue by salvag-ntt** [eugenp/tutorials#11384]
When running either:

```
mvn clean install
```
or
```
mvn clean install -Pintegration
```

The result is the same and only the single empty unit test is ran.

I assume the profile to run integration tests is missing in the repo

**Comment by kwoyke** [comment]
Hi @salvag-ntt ,

To run the unit tests for the spring-cucumber module you should use _default-second_ profile, and for the integration tests _integration-lite-second_. So the respective command are:
`mvn clean install -Pdefault-second` and `mvn clean install -Pintegration-lite-second`

You can check which module belongs to which profile in our main [pom.xml](https://github.com/eugenp/tutorials/blob/master/pom.xml).

Hope this helps.
