### ISSUE TITLE
Libraries-6 dependencies errors

### ISSUE THREAD

**Issue by 3rcok** [eugenp/tutorials#11402]
Could not find artifact org.renjin:renjin-script-engine:pom:3.5-beta72 in default (https://repo.maven.apache.org/maven2/)

Could not find artifact org.baeldung.pmd:custom-pmd:pom:0.0.1 in default (https://repo.maven.apache.org/maven2/)

**Comment by kwoyke** [comment]
Hi @3rcok ,

Make sure you have pulled to most up-to-date code from our repo.
We indeed used to face an issue with renjin dependency. Please note that currently we use BeDataDriven repository to pull this dependency - see the [pom.xml](https://github.com/eugenp/tutorials/blob/master/libraries-6/pom.xml).

I've just tested this setup locally and it works fine.

Please let me know if it's still wrong on your end.

**Comment by kwoyke** [comment]
Closed due to lack of activity.
