### ISSUE TITLE
Logout with IE11

### ISSUE THREAD

**Issue by mbachmann** [eugenp/tutorials#1142]
Hi there. I was trying your example at https://github.com/eugenp/tuto.... It s working fine at logout with Chrome and Firefox. The logged out successfully message apears. With IE 11, I always get a "Session Timed Out" message instead of the "You logged out successfully" message. The Network Analysis at IE 11 shows, that the URL "/logout.html?logSucc=true" is correctly called.

**Comment by eugenp** [comment]
Hey @mbachmann - sorry for the late feedback here. 
What module are you running exactly? I'm not quite able to figure that out from your message here. 

Cheers, 
Eugen.
