### ISSUE TITLE
Question regarding CachedBodyHttpServletRequest example

### ISSUE THREAD

**Issue by fkluthe** [eugenp/tutorials#11461]
Hi,

I have a question regarding the [Reading HttpServletRequest Multiple Times in Spring](https://www.baeldung.com/spring-reading-httpservletrequest-multiple-times) example:

https://github.com/eugenp/tutorials/blob/950bbadc353bdca114befc98cf4a18476352220e/spring-web-modules/spring-mvc-basics-3/src/main/java/com/baeldung/cachedrequest/CachedBodyHttpServletRequest.java#L22

Shouldn't the `requestInputStream` be closed at this point? Or is it done later anyway?

**Comment by kwoyke** [comment]
Hi @fkluthe,
Since we do not create a stream ourselves and only wrap the request's input stream, I don't think we should close it. That's a container's responsibility.
If we closed it we would manually interfere with a request's life-cycle.
Hope this makes sense.

**Comment by fkluthe** [comment]
Alright, thank you 👍
