### ISSUE TITLE
Dockerfile to build and create final docker image for CI/CD pipeline

### ISSUE THREAD

**Issue by shahamit** [eugenp/tutorials#11535]
It was great to refer to your [article](https://www.baeldung.com/spring-boot-docker-images) for creating docker images for spring boot application. 
The article shows it in pieces on how to create a docker image. Can you share how the file docker file looks like that would 
1. Create the docker image through mvn spring-boot:build command 
2. Incorporate layers as shown in [step 4.3](https://www.baeldung.com/spring-boot-docker-images#1-creating-layered-jars)
3. Publish the docker image to a docker registry 

These are the steps needed in a CI/CD jenkins pipeline for a spring boot project. Pardon me if you already have a separate article that demostrate these steps. Kindly point me to that.

Thanks

**Comment by kwoyke** [comment]
Hi @shahamit ,

Thanks for the feedback. Glad you find the articles helpful.
In the 4.3 section we already present the Dockerfile to use with layered jars. For two remaining points, the best way would be to take a look at the documentation. For example here - https://docs.spring.io/spring-boot/docs/2.5.6/maven-plugin/reference/htmlsingle/#build-image - you can see how to attach the build-image goal to the package phase.
Hope this helps.

**Comment by shahamit** [comment]
My bad - I meant the Jenkinsfile that did the 3 steps listed above (not the Dockerfile).
