### ISSUE TITLE
Springfox is dead by now

### ISSUE THREAD

**Issue by mitasov-ra** [eugenp/tutorials#11544]
Hi!

In your article [Setting Up Swagger 2 with a Spring REST API][1] you use `io.springfox:springfox-swagger2:3.0.0` library, but at the moment this library considered abandoned, and it is not compatible with Spring Boot 2.6 even.

Please, can you edit this article and put some kind of warning?
We already have [Documenting a Spring REST API Using OpenAPI 3.0][2], but the first article is still more popular and appears in search results more often.

So I'm not asking to switch library in the first article, just marking it as outdated is enough.

[1]: https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api
[2]: https://www.baeldung.com/spring-rest-openapi-documentation

**Comment by kwoyke** [comment]
Hi @mitasov-ra ,
Thanks for the heads up. We'll take care of that.

**Comment by kwoyke** [comment]
Hi @mitasov-ra ,
Just wanted to let you know that we updated the article. Cheers.
