### ISSUE TITLE
MessageDigestPasswordEncoder is no longer consired secure by Spring team

### ISSUE THREAD

**Issue by pythonmeister** [eugenp/tutorials#11557]
As you can read on https://docs.spring.io/spring-security/site/docs/5.6.0/api/org/springframework/security/crypto/password/MessageDigestPasswordEncoder.html, the use of MessageDigestPasswordEncoder is deprecated and no longer considered secure.

Please consider updating the article.

**Comment by kwoyke** [comment]
Hi @pythonmeister ,
Thanks for the heads up. We'll take care of this.
I assume you're referring to the https://www.baeldung.com/java-password-hashing article.

**Comment by pythonmeister** [comment]
Yes, that is the article I'm referring to.

**Comment by kwoyke** [comment]
We've updated the article.

**Comment by pythonmeister** [comment]
Thanks for taking care :-)
