### ISSUE TITLE
jdi no ClassPrepareEvent

### ISSUE THREAD

**Issue by Wker666** [eugenp/tutorials#11628]
The JDI project event always cannot enter the ClassPrepareEvent branch, so it cannot be disconnected after running. I have tested it in MAC and windows, and it cannot work normally.

VMStartEvent - > VMDeathEvent
no ClassPrepareEvent

**Comment by Wker666** [comment]
I have slove it.

**Comment by ArgentoAskia** [comment]
兄弟能说下解决的方法吗？
