### ISSUE TITLE
Bug in StringPerformance.java

### ISSUE THREAD

**Issue by Betalord** [eugenp/tutorials#11655]
Hi,
I noticed a bug with String.indexOf() benchmark method in StringPerformance.java. It returns all tokens but the last one, which makes it faster than the other methods (which is probably why it wins).
Anyway, on the web site "https://www.baeldung.com/java-string-performance", in chapter "3.2 split()" you have the same bug in the "String.indexOf()" approach. The code returns returns one token less than it should (it skips the last one).

Can someone verify it?

**Comment by kwoyke** [comment]
Hi @Betalord ,
Thanks for the feedback! We'll take a look into this.

**Comment by kwoyke** [comment]
We fixed the code @Betalord. Cheers!
