### ISSUE TITLE
ResultSets not closed in tutorial and article

### ISSUE THREAD

**Issue by contextmap** [eugenp/tutorials#11672]
In [Extracting Database Metadata Using JDBC](https://www.baeldung.com/jdbc-database-metadata) the ResultSets which are returned from the various queries are not closed.
This can lead to issues, for instance ORA-01000 in Oracle.

Maybe the number of ResultSets in the example is limited, but as a best practice I'd recommend to 
change the code to either use try-with-resource or manually closing the ResultSets.

also see:
https://github.com/eugenp/tutorials/blob/master/persistence-modules/core-java-persistence/src/main/java/com/baeldung/jdbcmetadata/MetadataExtractor.java

**Comment by kwoyke** [comment]
Hi @contextmap ,
Thanks for the feedback! We'll take a look into this.

**Comment by kwoyke** [comment]
We fixed the code and updated the article.
