### ISSUE TITLE
Minor adjustment to java-spi example

### ISSUE THREAD

**Issue by nickshoe** [eugenp/tutorials#11676]
I guess in the following code there is a subtle error:
https://github.com/eugenp/tutorials/blob/384b3d4aefb23a0a2e380fa4d36626131812bb22/java-spi/exchange-rate-impl/src/main/java/com/baeldung/rate/impl/YahooQuoteManagerImpl.java#L23-L30

I think line 28 should look like this:
```java
                if (!baseCurrency.equals(currency.getCurrencyCode())) { 
```

Thanks for your work!

**Comment by kwoyke** [comment]
Hi @nickshoe ,
Thanks for the feedback. Yeah, this looks like a bug at first glance. We'll handle it.

**Comment by kwoyke** [comment]
We fixed the code.
