### ISSUE TITLE
docker tutorial, cant produce a single jar file

### ISSUE THREAD

**Issue by thahgr** [eugenp/tutorials#11739]
I am trying to follow [this ](https://www.baeldung.com/spring-boot-postgresql-docker) (yours) tutorial, where it says the following 

_We now have an application JAR file in the target directory. That file has the project name and version number in its name and ends with -SNAPSHOT.jar. So its name could be docker-spring-boot-postgres-0.0.1-SNAPSHOT.jar._

However, when I run the mvn clean package i get the following multiple JARs. 

find . -name '*.jar'
./docker-internal-dto/target/docker-internal-dto-0.0.1.jar
./docker-sample-app/target/docker-sample-app-0.0.1.jar
./docker-spring-boot/target/docker-spring-boot-0.0.1.jar
./docker-spring-boot-postgres/.mvn/wrapper/maven-wrapper.jar

1. Should I use one of these JARs ? if yes, which one ?
2. Shouldnt there be created a single jar for all modules in order to dockerize? Is this possible ? (I am working on a similar project myself and I cant create a single JAR from multi-modules)

Thanks!

**Comment by kwoyke** [comment]
Hi @thahgr ,
You need to run mvn command inside docker\docker-spring-boot-postgres\ directory. Then you'll find docker-spring-boot-postgres-0.0.1-SNAPSHOT.jar under the target directory.

I fixed the GitHub link in the article.
