### ISSUE TITLE
Reading properties from JSON is not working

### ISSUE THREAD

**Issue by Omcsesz** [eugenp/tutorials#11763]
Hello, Team!

In section 4 of https://www.baeldung.com/spring-boot-json-properties#propertysource, I run into the same problem as written in the text. After finishing steps 5, 6. I still get the same error message. Is there something I should add to the project apart from these classes?

**Comment by kwoyke** [comment]
Hi @Omcsesz,

I just followed the steps (section 4 & 5) on the new sample project generated on https://start.spring.io/.
All the properties are processed correctly.
Clearly, you must be missing something in your config.
Please double check all the steps described in the article.
Hope this helps.
