### ISSUE TITLE
File has empty content after downloading from DownloadServlet

### ISSUE THREAD

**Issue by konanaw** [eugenp/tutorials#11795]
Problem: file 'sample.txt' has empty content after downloading from [DownloadServlet](https://github.com/eugenp/tutorials/blob/master/javax-servlets/src/main/java/com/baeldung/servlets/DownloadServlet.java).

Fix: file moved to webapps/WEB-INF 

I've opened [PR](https://github.com/eugenp/tutorials/pull/11758)
Please consider.

**Comment by kwoyke** [comment]
Hi @konanaw ,
Thanks, we'll take a look into this.

**Comment by kwoyke** [comment]
Thanks. We merged your PR.
