### ISSUE TITLE
Wrong redirection/forwarding of servlets

### ISSUE THREAD

**Issue by konanaw** [eugenp/tutorials#11796]
I have opened a [PR](https://github.com/eugenp/tutorials/pull/11794), which fixes redirection/forwarding of servlets at the module [javax-servlets](https://github.com/eugenp/tutorials/tree/master/javax-servlets)

Please consider.

**Comment by kwoyke** [comment]
Thanks for the heads up @konanaw.
We fixed the code and updated the articles.
