### ISSUE TITLE
secured web socket project does not contain the spring boot application class

### ISSUE THREAD

**Issue by dontweaks** [eugenp/tutorials#11800]
https://github.com/eugenp/tutorials/tree/master/spring-security-modules/spring-security-web-sockets

secured web socket project does not contain the spring boot application class

**Comment by kwoyke** [comment]
Hi @dontweaks ,
Yes, this is not a Boot module. So you need to either build and deploy the WAR file or use the cargo-maven2-plugin to run the code.
