### ISSUE TITLE
SAML Example fails to start

### ISSUE THREAD

**Issue by IncPlusPlus** [eugenp/tutorials#11853]
I pulled the latest commit, set up the keystore and IDP info in `application.properties`, and tried to start the application. It failed with an error. Description below

```
Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  samlEntryPoint
↑     ↓
|  webSecurityConfig (field private org.springframework.security.saml.SAMLEntryPoint com.baeldung.saml.config.WebSecurityConfig.samlEntryPoint)
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```

The path of the project is `spring-security-modules/spring-security-saml`

**Comment by kwoyke** [comment]
Hi @IncPlusPlus,

Thanks for the heads up.
This is an issue that occurs with Spring Boot 2.6 and SamlEntryPoint.
The issue is still open at spring-security-saml : https://github.com/spring-projects/spring-security-saml/issues/518

For now we set the `spring.main.allow-circular-references=true`
