### ISSUE TITLE
Memento article code is outdated compared to the repository code

### ISSUE THREAD

**Issue by pedroluiznogueira** [eugenp/tutorials#11862]
Hey guys, I was reading the [https://www.baeldung.com/java-memento-design-pattern](url) article and there is some code that is different than the one here on github, so I wanted to point it out for you.

In fact it isn't huge, but it impacts in if you don't come here to the repo and find the diffs.

For example, here you provide it as wholeText in the first method but previously it wasn't provided any wholeText attribute in the class

![image](https://user-images.githubusercontent.com/81788112/155644860-1da74bb2-e0a0-42d7-b94e-245c84560b54.png)

And then in the repo you have it as it was previously in the article

![image](https://user-images.githubusercontent.com/81788112/155644984-b255baf1-85f9-4558-beb6-867738439ce5.png)

As I said, it isn't a major difference, so I don't know if you care about it, but as a reader I do, and in case you do aswell, I hope it helps. :)

**Comment by kwoyke** [comment]
Hi @pedroluiznogueira ,
Sure we do care about this :) Thanks for the heads up. We'll take care of that.

**Comment by kwoyke** [comment]
We updated the article.
