### ISSUE TITLE
Request: logback setup with module-info.java

### ISSUE THREAD

**Issue by i-make-robots** [eugenp/tutorials#11938]
Love the site, very helpful, nearly always first page results in google.

I followed the logback tutorial and have a module-info.java with `requires logback.core`.  When I build in maven I get 
```
[WARNING] ***********************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [logback-core-1.2.11.jar]. Please don't publish this project to a public artifact repository! *
```
Please update the tutorial to mention what should be done and I will follow this ticket for updates.

Thank you!

**Comment by i-make-robots** [comment]
ah, intellij did it wrong and auto-filled in with 'logback.core' instead of 'ch.qos.logback.core'

**Comment by kwoyke** [comment]
Hi @i-make-robots,
Glad you like the site! And good you already found an issue :)

**Comment by i-make-robots** [comment]
If you could write something about how to diagnose serviceloader problems, that would be great.  for me they fail silently and I never know which part is wrong - the services descriptor? the module info?  the version implemented?  ugh.
