### ISSUE TITLE
Unable to log in a log file using the Lombok annotation for log ,i.e, @Slf4j

### ISSUE THREAD

**Issue by subham54321** [eugenp/tutorials#11958]
The below is the xml file....

<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="DEBUG">
    <Appenders>
        <Console name="LogToConsole" target="SYSTEM_OUT">
            <PatternLayout pattern="[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%t] %-5level %c:%L - %msg%n"/>
        </Console>
        <RollingFile name="LogToFile"
                     fileName="/Users/subhamsharma/Desktop/atm_log.log"
                     filePattern="/Users/subhamsharma/Desktop/atm_log.%d{yyyy-MM-dd}.%i.log.gz">
            <PatternLayout>
                <Pattern>[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%t] %5level [%X{guid}] [%X{luid}] [%X{customId1}]
                    [%X{customId2}] [%c{3}:%L] - %m%n
                </Pattern>
            </PatternLayout>
            <Policies>
                <TimeBasedTriggeringPolicy interval="1"/>
                <SizeBasedTriggeringPolicy size="100 MB"/>
            </Policies>
        </RollingFile>
        <Async name="AsyncLogToFile" bufferSize="10000">
            <AppenderRef ref="LogToFile"/>
            <blocking>false</blocking>
        </Async>
    </Appenders>
    <Loggers>
        <Logger name="com.apnatuitionmaster" level="debug" additivity="false">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Logger>
        <Logger name="org.springframework" level="error" additivity="false">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Logger>
        <Logger name="org.apache" level="error" additivity="false">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Logger>
        <Logger name="org.hibernate" level="error" additivity="false">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Logger>
        <Logger name="springfox.documentation" level="error" additivity="false">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Logger>
        <Logger name="com.mchange" level="error" additivity="false">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Logger>
        <Logger name="org.elasticsearch" level="error" additivity="false">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Logger>
        <Root level="error">
            <AppenderRef ref="AsyncLogToFile"/>
            <AppenderRef ref="LogToConsole"/>
        </Root>
    </Loggers>
</Configuration>

Below is the application.properties file config for log:-

############## Application Access Logs Config ##############
server.tomcat.max-threads=50
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/Users/subhamsharma/Desktop
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
server.tomcat.accesslog.prefix=atm_log
server.tomcat.accesslog.pattern=%{X-Forwarded-For}i %h %A '%{User-Agent}i'; "%{Referer}i" "%l" "%u" %t %{guid}r %{luid}r %{customId1}r %{customId2}r \u201C%r\u201C %I %s %b %F %D
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.rotate=true

**Comment by subham54321** [comment]
this question has been also posted in stackoverflow:-

https://stackoverflow.com/questions/71560638/unable-to-log-properly-in-log-file?noredirect=1#comment126477745_71560638

**Comment by kwoyke** [comment]
Hi @subham54321 ,

This seems like an issue with your custom application, and not the code maintained by us.

In this case, I suggest going through StackOverflow; this is a great place to ask more general questions.
