### ISSUE TITLE
Example without Keycloak adapters

### ISSUE THREAD

**Issue by ccaspanello** [eugenp/tutorials#11971]
Hello, this is a great project!  I was wondering if you would be so kind to do a new blog/tutorial/sample on a Spring Boot/React solution that doesn't use the Keycloak Adapter as it is now deprecated.  See https://www.keycloak.org/2022/02/adapter-deprecation.html

**Comment by kwoyke** [comment]
Hi @ccaspanello ,
Thanks for the feedback.
This isn't currently on our TODO list. But this doesn't mean of course we won't do this in the future.
Glad you like the project!
Cheers
