### ISSUE TITLE
[Apache POI Example] FileNotFoundException classpath:ExcelCellFormatterTest.xlsx 

### ISSUE THREAD

**Issue by amirensit** [eugenp/tutorials#11978]
Hello.

I am following this example: [https://www.baeldung.com/java-microsoft-excel]().

I created a main method to test:

```
public class Main {

    public static void main(String[] args) throws IOException {
        ExcelPOIHelper excelPOIHelper = new ExcelPOIHelper();
        Map<Integer, List<String>> result = excelPOIHelper
                .readExcel("classpath:ExcelCellFormatterTest.xlsx");
        System.out.println(result);
    }
}
```

I get this error:
`Exception in thread "main" java.io.FileNotFoundException: classpath:ExcelCellFormatterTest.xlsx`.

Any idea please ?

**Comment by kwoyke** [comment]
Hi @amirensit ,

So you either need to provide a valid path to your file or if you still want to load it from the classpath you need to modify the ExcelPOIHelper class. See https://www.baeldung.com/reading-file-in-java
Hope this helps.

Cheers
