### ISSUE TITLE
spring-cucumber isn't running the feature ?

### ISSUE THREAD

**Issue by Johnlon** [eugenp/tutorials#11983]
This doesn't work ...    mvn clean install -Pintegration

No such profile defined. Might need "integration-heavy" ??

`
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ spring-cucumber ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
16:10:26.957 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [com.baeldung.SpringContextTest], using SpringBootContextLoader
16:10:26.964 [main] INFO  o.s.t.c.s.AbstractContextLoader - Could not detect default resource locations for test class [com.baeldung.SpringContextTest]: no resource found for suffixes {-context.xml, Context.groovy}.
16:10:27.149 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
16:10:27.161 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@2aa6bbad, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@6b2ef50e, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@6f867b0c, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@4b5ad306, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@54be6213, org.springframework.test.context.support.DirtiesContextTestExecutionListener@48a46b0f, org.springframework.test.context.event.EventPublishingTestExecutionListener@1426370c, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@9f9146d, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@2ef041bb, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@45e7bb79, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@605c7a9e, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@21c75084, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@d16209e]
16:10:28.248 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [com.baeldung.SpringContextTest], using SpringBootContextLoader
16:10:28.259 [main] INFO  o.s.t.c.s.AbstractContextLoader - Could not detect default resource locations for test class [com.baeldung.SpringContextTest]: no resource found for suffixes {-context.xml, Context.groovy}.
16:10:28.632 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
16:10:28.681 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@428640fa, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@d9345cd, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@2d710f1a, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@29215f06, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@59505b48, org.springframework.test.context.support.DirtiesContextTestExecutionListener@4efac082, org.springframework.test.context.event.EventPublishingTestExecutionListener@6bd61f98, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@48aca48b, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@13fd2ccd, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@b9b00e0, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@506ae4d4, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@7d4f9aae, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@72e5a8e]
[INFO] Running com.baeldung.SpringContextTest

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.4)

16:10:29.423 [main] INFO  com.baeldung.SpringContextTest - Starting SpringContextTest using Java 1.8.0_312 on Zoom with PID 10191 (started by john in /home/john/work/github/baeldung-tutorial/spring-cucumber)
16:10:29.425 [main] INFO  com.baeldung.SpringContextTest - No active profile set, falling back to 1 default profile: "default"
16:10:31.906 [main] INFO  com.baeldung.SpringContextTest - Started SpringContextTest in 2.814 seconds (JVM running for 4.651)
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.159 s - in com.baeldung.SpringContextTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]

`

**Comment by kwoyke** [comment]
Hi @Johnlon ,
We'll take a look into this.
