### ISSUE TITLE
kafka stream binidings not receiving the topics sent from the actual code when running integration test

### ISSUE THREAD

**Issue by raj550k** [eugenp/tutorials#11997]
<img width="462" alt="Screenshot 2022-03-31 at 7 54 44 PM" src="https://user-images.githubusercontent.com/79000059/161078650-64f30fdc-631c-40dd-b282-31ee45ba0b89.png">

**Comment by kwoyke** [comment]
Hi @raj550k ,
Can you please clarify which article/module you're referring to?

**Comment by kwoyke** [comment]
Closing due to lack of answer.
