### ISSUE TITLE
Cant find NAMED_COLUMN_CSV in libraries-data-io

### ISSUE THREAD

**Issue by thewuffel** [eugenp/tutorials#12029]
Can't find this file in the example

**Comment by kwoyke** [comment]
Hi @thewuffel ,
You're right the file is missing. Thanks for the heads up! We'll fix this.

Internal note:
- module: libraries-data-io
- test com.baeldung.libraries.opencsv.OpenCsvIntegrationTest#namedColumnExampleTest

**Comment by kwoyke** [comment]
We added a missing file.
We'll also go through the article and code and improve the overall quality.
