### ISSUE TITLE
Spring Security Angular "request from origin ... blocked by CORS policy"

### ISSUE THREAD

**Issue by dbnex14** [eugenp/tutorials#12033]
I am looking at the Spring Security Angular module provided and from everything I read and tried, it does not make sense as it does not mentions CORS at all.

1. The HttpSecurity configuration is missing it,
2. There is no CorsConfigurationSource anywhere
3. And the default Spring provided /login is overriden by a login controller which usually is not needed

Would you be able to provide more details on CORS as all I get is error like:

**Access to XMLHttpRequest at 'http://localhost:8080/myapi/v1/auth' from origin 'http://localhost:4200'/ has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

, when trying to login.

**Comment by anastasiosioannidis** [comment]
Added CORS configuration

**Comment by dbnex14** [comment]
Is this tutorial for AngularJS or for Angular?

**Comment by dbnex14** [comment]
Also, this tutorial is using very obscured sentencing I find.  It looks like it is building spring boot AND angular as one single application.  This paragraph is not clear but it looks so:

Add an Angular App
The core of a single page application in Angular (or any modern front-end framework) these days is going to be a Node.js build. Angular has some tools for setting this up quickly, so lets use those, and also keep the option of building with Maven, like any other Spring Boot application. The details of how to set up the Angular app are covered [elsewhere](https://github.com/dsyer/spring-boot-angular), or you can just checkout the code for this tutorial from github.

And then the provided URL https://github.com/dsyer/spring-boot-angular has even more difficult steps to follow.  Very unclear from the beginning whether we are building 2 applications (Spring Boot and Angular) or single application being both Spring Boot and Angular.  

I have never heard of Angular app being added into Spring Boot project but the description seems to be doing exactly that.  Why would you tie these together?

Mind clarifying that?  Thanks

**Comment by dkapil** [comment]
@dbnex14 we are going through your comments

**Comment by anastasiosioannidis** [comment]
Hi @dbnex14 

- The CORS issue your mentioned in the original request is now fixed
- We could not find the URL mentioned ("../myapi/v2/.."), but we can ensure that the login is working
- For the new request in your  last comment, could you please open a new github issue?
