### ISSUE TITLE
Outdated article: @ConfigurationProperties in Spring Boot

### ISSUE THREAD

**Issue by ValentinBossi** [eugenp/tutorials#12064]
the paragraph of https://www.baeldung.com/configuration-properties-in-spring-boot#1-spring-boot-22 is wrong. see note in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#configurationproperties-scanning

`Configuration properties scanning was enabled by default in Spring Boot 2.2.0 but as of Spring Boot 2.2.1 you must opt-in using @ConfigurationPropertiesScan.
`

**Comment by kwoyke** [comment]
Hi @ValentinBossi ,
Thanks for the feedback. We'll update the article.

**Comment by kwoyke** [comment]
We updated the article.
