### ISSUE TITLE
Build Fail on spring-cloud-security

### ISSUE THREAD

**Issue by rajeshverma228** [eugenp/tutorials#12098]
Need to add groupId  in below pom.xml
1. tutorials\spring-cloud\spring-cloud-security\auth-client\pom.xml
2. tutorials\spring-cloud\spring-cloud-security\auth-resource\pom.xml
3. tutorials\spring-cloud\spring-cloud-security\auth-server\pom.xml

Add :
"<groupId>com.baeldung</groupId>"

**Comment by kwoyke** [comment]
Thanks for the feedback @rajeshverma228! We've already fixed that.
