### ISSUE TITLE
Test Failure in CircularBuffer/RingBuffer

### ISSUE THREAD

**Issue by thabach** [eugenp/tutorials#12134]
Heya

the ProducerConsumerLiveTest class is not included in the Surefire Plugin execution:
https://github.com/eugenp/tutorials/blob/b9026dde49c6bda4d98ae462ea88e2f903c53847/data-structures/src/test/java/com/baeldung/circularbuffer/ProducerConsumerLiveTest.java#L14

Once triggered explicitly it throws the following exception:

`[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.025 s <<< FAILURE! - in com.baeldung.circularbuffer.ProducerConsumerLiveTest`
`[ERROR] givenACircularBuffer_whenInterleavingProducerConsumer_thenElementsMatch  Time elapsed: 0.02 s  <<< ERROR!
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
	at com.baeldung.circularbuffer.ProducerConsumerLiveTest.givenACircularBuffer_whenInterleavingProducerConsumer_thenElementsMatch(ProducerConsumerLiveTest.java:27)`

Thanks for fixing it, cheers, Christian.

**Comment by kwoyke** [comment]
Hi Christian,

Thanks for the feedback. We'll take a look into this!

**Comment by kwoyke** [comment]
We fixed the test.
