### ISSUE TITLE
Incorrect results in Kadane Algorithm for Maximal Subarray

### ISSUE THREAD

**Issue by pushkar-adhikari** [eugenp/tutorials#12205]
[Maximum Subarray Problem in Java -> Dynamic Programming -> Implementation](https://www.baeldung.com/java-maximum-subarray#3-implementation) and [KadaneAlgorithm.java](https://github.com/eugenp/tutorials/blob/master/algorithms-miscellaneous-5/src/main/java/com/baeldung/algorithms/maximumsubarray/KadaneAlgorithm.java) have a small error in implementation that **fails to give correct maximum sum** for the following use case:

```
void givenArrayAlgorithmFails() {
        // given
        int[] arr = new int[] {1, 2, -3};
        // when
        KadaneAlgorithm algorithm = new KadaneAlgorithm();
        int maxSum = algorithm.maxSubArraySum(arr);
        // then
        System.out.println(3 == maxSum); // prints false, but it should be true.
}
```
The for loop should begin from `1` rather than `0` as the 0th element is already included when `maxEndingHere` is initialized to `array[0]`. Without this, the else part `maxEndingHere + array[i];` causes the 0th element to be added again.

The indices printed by the logger statement are correct, so nothing needs to be changed there.

**Comment by kwoyke** [comment]
Hi @pushkar-adhikari ,
Thanks for the feedback! We'll take a look into this.
