### ISSUE TITLE
Spring JPA Multiple database example: Calling em.setDataSource(userDataSource()) in a class not annotated with Configuration errors out with error ...

### ISSUE THREAD

**Issue by dbnex14** [eugenp/tutorials#12235]
Calling em.setDataSource(userDataSource()) in the **PersistenceUserAutoConfiguration.java** class not annotated with Configuration errors out with error 

**"Method annotated with @Bean is called directly.  Use dependency injection instead."**

Located in https://github.com/eugenp/tutorials/blob/master/persistence-modules/spring-data-jpa-enterprise-2/src/main/java/com/baeldung/multipledb/PersistenceUserAutoConfiguration.java
and in https://github.com/eugenp/tutorials/blob/master/persistence-modules/spring-data-jpa-enterprise-2/src/main/java/com/baeldung/multipledb/PersistenceProductAutoConfiguration.java

**Comment by kwoyke** [comment]
Hi @dbnex14 ,
We were unable to reproduce the issue. Can you please provide us with a step by step instruction on how to replicate this?
