### ISSUE TITLE
ErrorController

### ISSUE THREAD

**Issue by arijit2002** [eugenp/tutorials#12250]
Not able to *Override* *public String getErrorPath()* in _ErrorController_ interface. Is it deprecated in newer versions?

**Comment by kwoyke** [comment]
Can you please clarify which article you're referring to?

**Comment by arijit2002** [comment]
Sir, I was talking about this controller file.

https://github.com/eugenp/tutorials/blob/master/spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/errorhandling/controllers/MyErrorController.java

The  ErrorController interface had an abstract method of  String getErrorPath(). But in recent version of spring boot, i am not getting an option to override the method as String getErrorPath() is being treated as a separate method.

**Comment by kwoyke** [comment]
Thanks for clarification. We'll take a look into this.

**Comment by kwoyke** [comment]
Yes @arijit2002,
Spring Boot 2.3 has deprecated this method.
