### ISSUE TITLE
WebSecurityConfigurerAdapter Deprecated

### ISSUE THREAD

**Issue by fitsie007** [eugenp/tutorials#12304]
Thanks for your tutorial about restricting access to resources based on whitelisted IP addresses.
Since WebSecurityConfigurerAdapter has been deprecated, how would you recommend doing this same example to restrict access based on a set of IP addresses?
I tried upgrading to the SecurityFilterChain recommended here: https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter. I then disabled SecurityAutoConfiguration while using @EnableWebSecurity on my class that uses the SecurityFilterChain, but cannot get your example to work.

**Comment by kwoyke** [comment]
Hi @fitsie007 ,
Yeah that's an interesting topic. However for now our code is based on Spring Security 5.6.
I'd suggest asking the question on StackOverflow, simply because you'll get an answer faster.
Anyway, we'll need to take care of that when we upgrade our code base.
Hope that makes sense.
