### ISSUE TITLE
The support for Pageable of spring-data-commons is available out-of-the box since springdoc-openapi v1.6.0

### ISSUE THREAD

**Issue by elonshen** [eugenp/tutorials#12318]
[Expose paging information](https://www.baeldung.com/spring-rest-openapi-documentation#exposing-pagination-information) don't need dependence springdoc-openapi-data-rest after springdoc-openapi v1.6.0.

[Information from springdoc](https://springdoc.org/#how-can-i-map-pageable-spring-data-commons-object-to-correct-url-parameter-in-swagger-ui)

**Comment by kwoyke** [comment]
Thanks for the feedback. We'll take a look into this.

**Comment by kwoyke** [comment]
We've updated the article.
