### ISSUE TITLE
Issue with log-mdc

### ISSUE THREAD

**Issue by slotony** [eugenp/tutorials#12432]
mdc/log4j/DemoIntegrationTest output is missing the MDC values, e.g., 
`0    [pool-1-thread-1]  INFO Log4JTransferService  - Preparing to transfer 556$. - tx.id= tx.owner=`
This is on Java 17 SDK.
Thank you,
Anthony

**Comment by kwoyke** [comment]
Hi @slotony ,

Works fine on my side, on JDK17 as well. Both when running the test from IntelliJ and Maven.
`0    [pool-1-thread-1]  INFO Log4JTransferService  - Preparing to transfer 1392$. - tx.id=1 tx.owner=Susan
 0    [pool-1-thread-2]  INFO Log4JTransferService  - Preparing to transfer 677$. - tx.id=2 tx.owner=Marc
 0    [pool-1-thread-3]  INFO Log4JTransferService  - Preparing to transfer 1872$. - tx.id=3 tx.owner=Samantha
 533  [pool-1-thread-2]  INFO Log4JTransferService  - Has transfer of 677$ completed successfully ? false. - tx.id=2 tx.owner=Marc
 535  [pool-1-thread-2]  INFO Log4JTransferService  - Preparing to transfer 900$. - tx.id=4 tx.owner=Susan`

Please double check the setup on your end or provide a step-by-step instruction on how to reproduce it.

**Comment by ulisseslima** [comment]
Closed due to lack of activity.
