### ISSUE TITLE
Question about logging-module

### ISSUE THREAD

**Issue by siddjain** [eugenp/tutorials#12469]
My question is about logging-modules tutorial. In the [pom.xml](https://github.com/eugenp/tutorials/blob/master/logging-modules/log4j/pom.xml) I do not see a reference to slf4j anywhere yet the code compiles and even runs. How is it possible? E.g., how does [this](https://github.com/eugenp/tutorials/blob/master/logging-modules/log4j/src/main/java/com/baeldung/slf4j/Slf4jExample.java) code compile when we have no reference to slf4j in pom.xml?

```
package com.baeldung.slf4j;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * To switch between logging frameworks you need only to uncomment needed framework dependencies in pom.xml
 */
public class Slf4jExample {
    private static Logger logger = LoggerFactory.getLogger(Slf4jExample.class);

    public static void main(String[] args) {
        logger.debug("Debug log message");
        logger.info("Info log message");
        logger.error("Error log message");

        String variable = "Hello John";
        logger.debug("Printing variable value {} ", variable);
    }
}
```

**Comment by kwoyke** [comment]
It's defined in our top parent [pom.xml](https://github.com/eugenp/tutorials/blob/master/pom.xml).
Hope this helps.
