### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by liudaolunboluo** [eugenp/tutorials#12466]
https://github.com/eugenp/tutorials/tree/master/lombok-modules/lombok-custom

after I configure it in the POM file in my own project:

 Could not find artifact com.sun:tools:jar:11.0.12 at specified path /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/../lib/tools.jar -> [Help 1]

So how do I use this annotation?

**Comment by liudaolunboluo** [comment]
I removed it:

    <profiles>
        <profile>
            <id>default-profile</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <file>
                    <exists>${java.home}/../lib/tools.jar</exists>
                </file>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>com.sun</groupId>
                    <artifactId>tools</artifactId>
                    <version>${java.version}</version>
                    <scope>system</scope>
                    <systemPath>${java.home}/../lib/tools.jar</systemPath>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

No more error reporting when mvn install,but class file don't have Singleton code

**Comment by kwoyke** [comment]
Hi @liudaolunboluo ,
Note that vast majority of our modules are still JDK8 based. I see you use JDK11. Please try with JDK8.
Hope this helps.

**Comment by ulisseslima** [comment]
Closed due to lack of activity.
