### ISSUE TITLE
spring-webflux-cacheable #3 DefaultSerializer can't handle Mono(.cache())

### ISSUE THREAD

**Issue by ThomasAtAcerta** [eugenp/tutorials#12479]
Hello,  When attempting the suggested solution in the tutorial of spring-webflux-cacheable I get into trouble:

> DefaultSerializer requires a Serializable payload but received an object of type [reactor.core.publisher.MonoFlatMap]

or.. by using the MonoInstance.cache() method it's:

> DefaultSerializer requires a Serializable payload but received an object of type [reactor.core.publisher.MonoCacheTime]

Maybe that problem should be explained and fixed in this tutorial.  I've got no idea why this is not something the author encountered.

**Comment by kwoyke** [comment]
Hi @ThomasAtAcerta ,
That's an interesting case. Would you please raise a PR with a test case that illustrates the issue in our codebase? Then, it will be much easier to fix the article.

**Comment by ulisseslima** [comment]
Closed due to lack of activity.
