### ISSUE TITLE
The code for A* is in the src/test/java directory, not the src/main/java directory

### ISSUE THREAD

**Issue by ogregoire** [eugenp/tutorials#12491]
I expect to find the code for the A* algorithm in [`src/main/java`](https://github.com/eugenp/tutorials/tree/master/algorithms-modules/algorithms-miscellaneous-2/src/main/java/com/baeldung/algorithms), not in [`src/test/java`](https://github.com/eugenp/tutorials/tree/master/algorithms-modules/algorithms-miscellaneous-2/src/test/java/com/baeldung/algorithms/astar).

**Comment by kwoyke** [comment]
Can you elaborate which article are you referring to?
Also, note that some of our code might be actually located under the test directory, as we always try to provide ready to use test cases that illustrate a particular topic.

**Comment by ogregoire** [comment]
As shown in the links of my first comment, the source for all your algorithms are under `src/main/java` except for A*, where the source code is under `src/test/java`. I don't think I can be more clear than this.

**Comment by kwoyke** [comment]
Yeah, all clear - didn't notice the links before.

**Comment by kwoyke** [comment]
We cleaned up the code.
