### ISSUE TITLE
Code style suggestion for BiFunction article in order to make it more declarative

### ISSUE THREAD

**Issue by pedroluiznogueira** [eugenp/tutorials#12510]
Hey guys, I was reading the [https://www.baeldung.com/java-bifunction-interface](https://github.com/eugenp/tutorials/issues/url) article and there's a code snippet that I think that it is worth making a suggestion.

The following part:

`List<String> list1 = Arrays.asList("a", "b", "c");`
`List<Integer> list2 = Arrays.asList(1, 2, 3);`

`List<String> result = listCombiner(list1, list2, (a, b) -> a + b);`

`assertThat(result).containsExactly("a1", "b2", "c3");`

Unless it is a code style convention of you guys, why not make the representation of the `BiFunction` more declarative with something like `(letter, number) -> letter + number;`.

Even though it is a small detail, it ends up being great for beginners and those who are not that familiar with lambdas/functional interfaces, to see right away the goal of that piece of code...

Sometimes just by not understanding right away what's happening in an article, I end up changing to another, so I think it is worth mentioning.

**Comment by ulisseslima** [comment]
Hey @pedroluiznogueira. Thanks for your feedback.

We're going to review the article and see if it makes sense to include more descriptive names for the variables.

**Comment by dkapil** [comment]
Thanks @pedroluiznogueira we have incorporated your changes.
