### ISSUE TITLE
Reactive WebSocket App example no longer works

### ISSUE THREAD

**Issue by garytse** [eugenp/tutorials#12522]
`https://github.com/eugenp/tutorials/blob/master/spring-5-reactive-modules/spring-5-reactive/src/main/java/com/baeldung/websocket/ReactiveWebSocketApplication.java`

Server side reports http 401, client side found the same with following exception:

`[reactor-http-nio-2] WARN  r.n.http.client.HttpClientConnect - [7575dbf7-1, L:/127.0.0.1:1368 - R:localhost/127.0.0.1:8080] The connection observed an error
io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid handshake response getStatus: 401 `

**Comment by ulisseslima** [comment]
Hey @garytse, thanks for your feedback.

We're going to review this article.

**Comment by dkapil** [comment]
Now resolved.
