### ISSUE TITLE
Question: Test output with JUnit5 DisplayName and DisplayNameGeneration

### ISSUE THREAD

**Issue by brunotacca** [eugenp/tutorials#12567]
I saw the test output on [this tutorial](https://www.baeldung.com/junit-custom-display-name-generator) and it left me wondering where (or how) could I generate the same output style.

![image](https://user-images.githubusercontent.com/6067887/182998305-2394a3d8-f5e2-45b2-b8df-da5d34411c48.png) \
[Source: Baeldung](https://www.baeldung.com/junit-custom-display-name-generator)

I tried digging some stuff on VSCode and wasn't successful. \
Maybe a different IDE (IntelliJ/Eclipse/Netbeans) or a maven plugin?

Thank you.

**Comment by ulisseslima** [comment]
Hey, @brunotacca 

For VSCode you can try this extension to get similar tree-style test results: https://code.visualstudio.com/docs/java/java-testing

Hope it helps.
