### ISSUE TITLE
OGM tutorial - Why are you posting an article on a dead utility

### ISSUE THREAD

**Issue by ztayluh** [eugenp/tutorials#12614]
Hibernate ended their OGM support in 2018, why are you posting this article in 2022?

Isn't there a better way to work with MongoDB than a using a no longer maintained framework?

https://hibernate.org/ogm/
https://discourse.hibernate.org/t/is-ogm-a-dead-framework/5716

**Comment by ulisseslima** [comment]
Hey, @ztayluh.

This article was initially posted in 2018.

We'll check with the team to update the article and include that information.

**Comment by dkapil** [comment]
Added a note in the article highlighting the deprecation.
