### ISSUE TITLE
Typo in the article, but source code is correct.

### ISSUE THREAD

**Issue by Enfield-Li** [eugenp/tutorials#12672]
[Section 2 of the article "RabbitMQ Message Dispatching with Spring AMQP"](https://www.baeldung.com/rabbitmq-spring-amqp#fanout-exchange) has a typo, missing `BindingBuilder`:
```
    return new Declarables(
      fanoutQueue1,
      fanoutQueue2,
      fanoutExchange,
      bind(fanoutQueue1).to(fanoutExchange), // <- this line
      BindingBuilder.bind(fanoutQueue2).to(fanoutExchange));
```
should be:
```
    return new Declarables(
      fanoutQueue1,
      fanoutQueue2,
      fanoutExchange,
      BindingBuilder.bind(fanoutQueue1).to(fanoutExchange),
      BindingBuilder.bind(fanoutQueue2).to(fanoutExchange));
```
However, the source code seemed alright.

**Comment by ulisseslima** [comment]
Hey, @Enfield-Li.

Thanks for the feedback, we'll look into it and update the article.

**Comment by lor6** [comment]
I've updated the example in the article.
