### ISSUE TITLE
Deny Access on Missing @PreAuthorize to Spring Controller Methods uses old @EnableGlobalMethodSecurity

### ISSUE THREAD

**Issue by wojteko22** [eugenp/tutorials#12697]
Please update tutorial using new @EnableMethodSecurity

**Comment by ulisseslima** [comment]
Hey, @wojteko22.

Can you provide a link to the article so we can take a look?

**Comment by wojteko22** [comment]
https://www.baeldung.com/spring-deny-access

**Comment by lor6** [comment]
Thanks @wojteko22 It's not clear from the documentation yet if the EnableGlobalMethodSecurity annotation will be deprecated. The official docs still list both options. We'll add a new dedicated topic for the new annotation for now, but wait on updating existing articles.

**Comment by pozpierwsza** [comment]
@lor6 EnableGlobalMethodSecurity is deprecated in Spring Security 5.8.0, any news about updating article?

**Comment by wojteko22** [comment]
@lor6 EnableGlobalMethodSecurity is deprecated in Spring Security 5.8.0, any news about updating article?

**Comment by wojteko22** [comment]
@lor6
> We'll add a new dedicated topic for the new annotation for now, but wait on updating existing articles.

Where can I find this topic?
