### ISSUE TITLE
The github project is not complete !

### ISSUE THREAD

**Issue by JoseRFJuniorBigData** [eugenp/tutorials#12730]
It does not have the following classes that are presented in the tutorial: https://www.baeldung.com/spring-aws-kinesis
public AmazonKinesis
private void buildShardIterator
public class IpProcessor
public class IpProcessorFactory
public class IpConsumer
public class IpProducer

It only has:
public class KinesisApplication

**Comment by ulisseslima** [comment]
Hey, @JoseRFJuniorBigData.

Thanks for pointing that out, we'll look into it.

**Comment by dkapil** [comment]
The missing code snippets are added and consumers and producers for different libraries are now present in their respective packages
