### ISSUE TITLE
[spring-kafka] Use Spring boot autoconfiguration

### ISSUE THREAD

**Issue by OneCricketeer** [eugenp/tutorials#12755]
The tutorial suggests using properties such as `kafka.bootstrapAddress` rather than the Boot auto-config `spring.kafka.bootstrap-servers`

https://docs.spring.io/spring-boot/docs/current/reference/html/messaging.html#messaging.kafka

**Comment by ulisseslima** [comment]
Hey, @OneCricketeer.

Can you link to the article you're referring to, so we can take a look?

Cheers.

**Comment by OneCricketeer** [comment]
AFAIK, there's only one that covers Spring-kafka

https://www.baeldung.com/spring-kafka

**Comment by ulisseslima** [comment]
Thanks, we'll update the article to use official property names instead of custom ones.

Cheers.

**Comment by OneCricketeer** [comment]
Fixed by https://github.com/eugenp/tutorials/pull/13003
