### ISSUE TITLE
Code from article won't compile

### ISSUE THREAD

**Issue by peterbayerle** [eugenp/tutorials#12775]
The code in [this article](https://www.baeldung.com/spring-data-jpa-method-in-all-repositories) won't compile.
I get the error
```
Class 'ExtendedRepositoryImpl' must either be declared abstract or implement abstract method 'deleteAllById(Iterable<? Extends ID>)' in 'CrudRepository'
```

**Comment by OneCricketeer** [comment]
The `// ...` in the article implies that more code is required, such as all methods needed by the interface

**Comment by ulisseslima** [comment]
Hey, @peterbayerle.

`deleteAllById()` is already implemented by `SimpleJpaRepository`, so the snippet in section 3 should compile just fine without implementing it yourself.

Make sure you are extending `SimpleJpaRepository` and your imports are correct, like in the file you mentioned.
