### ISSUE TITLE
Best replace Map.class by TypeReference

### ISSUE THREAD

**Issue by mbilbille** [eugenp/tutorials#12814]
Hello,

It would be best to use `new TypeReference<Map<String, Object>>() {}` here instead of `Map.class` to get a typed Map and avoid warning message.

https://github.com/eugenp/tutorials/blob/513cf0d4b8eb0e02bff966c6b7b9480d4ed44cd7/persistence-modules/hibernate5/src/main/java/com/baeldung/hibernate/persistjson/HashMapConverter.java#L39

Thanks for your great tutorials

**Comment by ulisseslima** [comment]
Hey, @mbilbille.

Thanks for the feedback. We'll update the article to remove the compiler warning.

Cheers.

**Comment by dkapil** [comment]
Thanks @mbilbille, we have updated our article.
