### ISSUE TITLE
Association not on both sides in the University Example

### ISSUE THREAD

**Issue by tctfox** [eugenp/tutorials#12818]
Hei there

In your example with the University, Professor and Departments classes, the associations are only on one side. For example: the departments has only a professor field but no university field. In your other examples (car/wheel) both sides have the relationships as objects. Is this an error or is it supposed to be like this?

**Comment by ulisseslima** [comment]
Hey, @tctfox.

It's not an error. As @OneCricketeer pointed out, relationship models in databases will often depend on how you're going to use your application.

It would also be possible to include a “belongs-to” relationship in _Deparment_ pointing to a _University_. It depends on your needs.

Hope it makes sense.
