### ISSUE TITLE
Docker image microsoft/azure-cosmosdb-emulator unavailable

### ISSUE THREAD

**Issue by Skandh15** [eugenp/tutorials#12867]
Hi, 

In tutorial of spring boot with cosmosDb it's specified to pull docker image using command `docker pull microsoft/azure-cosmosdb-emulator`, I am constantly getting error 

>  Error response from daemon: repository microsoft/azure-cosmosdb-emulator not found: name unknown: repository name not known to registry

I took a look at https://hub.docker.com/r/microsoft/azure-cosmosdb-emulator and there are no tags available.

**Comment by ulisseslima** [comment]
Hey, @Skandh15.

Thanks for the feedback. We'll look into it and update the article if necessary.

Article: https://www.baeldung.com/spring-data-cosmos-db

**Comment by dkapil** [comment]
@Skandh15 thanks for raising it. We have updated our article with the latest repository name and the steps.
