### ISSUE TITLE
Code on blog does not match code in repo, code in repo works, code on blog doesn't

### ISSUE THREAD

**Issue by jasonstolaruk** [eugenp/tutorials#12897]
The code for the `sayHello` method here (in this repo)...

https://github.com/eugenp/tutorials/blob/1c8962aff3e0c97f86b58ce9d33c9a2b4585e699/spring-reactive-modules/spring-reactive/src/main/java/com/baeldung/reactive/errorhandling/Handler.java#L56

...does not match the `sayHello` method on this blog:
[Handling Errors in Spring WebFlux](https://www.baeldung.com/spring-webflux-errors)

The blog illustrates the usage of `onErrorResume`. However, given the `sayHello` method and `handleRequest` methods as stated on the blog, the `onErrorResume` block in the `handleRequest` method will never be entered. The reason is that `request.queryParam("name").get()` in `sayHello` throws an exception outside of the reactive pipeline of operations. (The exception is thrown before `Mono.just` has a chance to create a `Mono` publisher.)

The `sayHello` here on GitHub catches the exception and wraps it in a `Mono.error`, which is a different approach. (It signals the error inside the reactive pipeline.)

Are you able to update the blog? If I could make a suggestion, consider updating the blog so that `sayHello` matches the `sayHello` defined here in the GitHub repo.

**Comment by ulisseslima** [comment]
Hey @jasonstolaruk.

Thanks for the feedback, we'll look into the issue and update the article.

**Comment by lor6** [comment]
Article is updated to match the code.
