### ISSUE TITLE
java-stream-append-prepend article needs minor correction

### ISSUE THREAD

**Issue by GeoffChurch** [eugenp/tutorials#12930]
Hi @lor6, I think the article still needs a minor update.

It says

> In this case, since the stream is not consumed greedily, it is still partially lazy

The new approach is actually fully lazy, so you can e.g. insert an element at index 3 billion in constant time.

Also, the conclusion says

> Keep in mind that although prepending an element works for any Stream, adding it to the end or at a specific index only works for finite streams.

This sentence can probably be removed because inserting at a specific finite index now works for any Stream, and it does technically work to append to the end of an infinite stream, you just wouldn't reach the element after a finite number of steps.

_Originally posted by @GeoffChurch in https://github.com/eugenp/tutorials/issues/10931#issuecomment-1279115547_

**Comment by ulisseslima** [comment]
Hey @GeoffChurch.

We'll look into it.

**Comment by dkapil** [comment]
The article is updated with @GeoffChurch suggestions.
