### ISSUE TITLE
Reduce memory when upload large file to S3

### ISSUE THREAD

**Issue by Argunl** [eugenp/tutorials#12953]
I'm trying to upload large file(10GB) to S3 with multipart according this [article](https://www.baeldung.com/java-aws-s3-reactive). And receive OutOfMemoryError exception. How can I clear ByteBuffer for already uploaded parts or something else reduce memory usage?
I think can change something in this function https://github.com/eugenp/tutorials/blob/35d56f7756e4b2ad679207554fddb9adb183f4fe/aws-modules/aws-reactive/src/main/java/com/baeldung/aws/reactive/s3/UploadResource.java#L238 Somehow delete ByteBuffer from memory after upload is done. 
`AsyncRequestBody.fromPublisher(Mono.just(buffer)));` use a lot of memory too.
Requests are being created too fast. How can I limit their number and launch new ones only when the future is over?

**Comment by ulisseslima** [comment]
Hi, @Argunl.

Dealing with very large files is a complex edge case. Therefore, out of the scope of this article.

You can try limiting your client's request rate: https://www.baeldung.com/spring-webclient-limit-requests-per-second

Or, you can switch to a non-reactive file upload solution: https://www.baeldung.com/java-read-lines-large-file

Hope it helps.
