### ISSUE TITLE
"Double-Checked Locking with Singleton" article is incorrect

### ISSUE THREAD

**Issue by cowwoc** [eugenp/tutorials#13039]
The [Double-Checked Locking with Singleton](https://www.baeldung.com/java-singleton-double-checked-locking) article states that double-checked locking cannot be implemented in Java. Per http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html (which the article links to) this is only true for JDK 1.4 and earlier, which nobody uses anymore. The link buries this fact at the bottom of the page, and the original article does not mention it at all.

Please update the article to indicate that double-checked locking works fine in JDK 1.5 and newer.

**Comment by ulisseslima** [comment]
Hey @cowwoc.

Thanks for the feedback. We'll look into this and update the article.

**Comment by cowwoc** [comment]
@dkapil Where? Please quote the relevant paragraph.
