### ISSUE TITLE
Springboot 3

### ISSUE THREAD

**Issue by MarinusPretorius** [eugenp/tutorials#13034]
Does not work on springboot 3. Just getting 404 errors trying to access the swagger ui and api docs

**Comment by ulisseslima** [comment]
Hey, @MarinusPretorius.

We have an internal task to keep articles up-to-date with the latest version, but it might take a while.

Currently, we're targeting Spring Boot 2.

Can you include a link to the article so we can look into this?

**Comment by ulisseslima** [comment]
Closed due to inactivity.
