### ISSUE TITLE
CacheUtils shown in this tutorial are now Deprecated and marked for removal

### ISSUE THREAD

**Issue by danielrehmann** [eugenp/tutorials#13046]
When I was looking for some less manual approaches of caching in Reactor i had a look at your https://www.baeldung.com/spring-webflux-cacheable article linking to this tutorial:
https://github.com/eugenp/tutorials/blob/7ab48bf6f4bf10a3578c6461eaa871f7482502b7/spring-5-webflux-2/src/main/java/com/baeldung/webflux/caching/ItemService.java#L38-L39

Looking in the current documentation and [this issue](https://github.com/reactor/reactor-addons/issues/237) the mentioned extensions are deprecated and marked for removal.

It might make sense to remove these parts or annotate them that they are no longer supported in the future.

**Comment by ulisseslima** [comment]
Hey, @danielrehmann.

Thanks for the feedback. We'll look into this and update the article if necessary.

Cheers.

**Comment by dkapil** [comment]
Resolved.
