### ISSUE TITLE
Can't get HATEOAS with projections

### ISSUE THREAD

**Issue by sbayonag** [eugenp/tutorials#13127]
Hi, I am following several of your tutorials. I just tried to use projections (like "CustomBook") with EntityModel and PagedModel for HATEOAS but I can't seem to get it to work. If I change the type of the variable from CustomBook to Book, it just works.

```
Page<Book> books  = bookService.getAllByAuthor(name, pageable);
        PagedModel<EntityModel<Book>> bookEntityPagedModel = pagedResourcesAssembler.toModel( books, bookModelAssembler)
        return ResponseEntity.ok(bookEntityPagedModel);
```
The above works, but changing Book to Custom Book does not.

**Comment by ulisseslima** [comment]
Hey, @sbayonag.

Can you include a link to the tutorial you're having problems with so we can take a look?

**Comment by ulisseslima** [comment]
Closed due to inactivity.
