### ISSUE TITLE
generate certificates

### ISSUE THREAD

**Issue by rodrigodevelms** [eugenp/tutorials#13161]
In the Bouncy Castle tutorial, they use a certificate and a key:
```
    baeldung.cer
    Baeldung.p12 (password="password")
```
How do I generate these certificates on my machine? I tried by commands

Generate 2048-bit RSA private key:
`openssl genrsa -out key.pem 2048`
Generate a Certificate Signing Request:
`openssl req -new -sha256 -key key.pem -out csr.csr`
Generate a self-signed x509 certificate suitable for use on web servers.
`openssl req -x509 -sha256 -days 365 -key key.pem -in csr.csr -out certificate.pem`
Create SSL identity file in PKCS12 as mentioned here
`openssl pkcs12 -export -out key.p12 -inkey key.pem -in certificate.pem`

however the generated certificates do not work in the code. (`certificate.pem` and `key.p12`)

**Comment by ulisseslima** [comment]
Hey, @rodrigodevelms.

Thanks for the feedback.

Generating the keys is out of scope for [this article](https://www.baeldung.com/java-bouncy-castle).

But, we'll check with the team to see if it makes sense to update the article to include the command to generate the certificate files.

**Comment by dkapil** [comment]
@rodrigodevelms we have added steps in our article to generate new certificates. Hope that helps.
