### ISSUE TITLE
AtomicInteger#getAndIncrement() or AtomicInteger#incrementAndGet() already does what this increment() method does

### ISSUE THREAD

**Issue by softwarebrahma** [eugenp/tutorials#13281]
https://github.com/eugenp/tutorials/blob/fa6fc0b9c1f0e876c1844f540887788fecb9f3ca/core-java-modules/core-java-concurrency-advanced/src/main/java/com/baeldung/concurrent/atomic/SafeCounterWithoutLock.java#L12

Doesn't `AtomicInteger#getAndIncrement()` or `AtomicInteger#incrementAndGet()` already do what this `increment()` method does,(atomically increment the counter by 1)? 

Why do we need this method implementation for it to be a 'thread safe' counter?

If one looks at the source code of `AtomicInteger` for any of these two methods (since in this case the return value is not returned/used) they already retry the increment until it succeeds thereby guaranteeing _that the call to the increment method always increases the value by 1_

Below is are the source references,
https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/java/util/concurrent/atomic/AtomicInteger.java#L180
https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/jdk/internal/misc/Unsafe.java#L2334

Reproducing it here below,

```
    // AtomicInteger#getAndIncrement() snippet..
    public final int getAndIncrement() {
        return U.getAndAddInt(this, VALUE, 1);
    }

   // Unsafe#getAndAddInt() snippet..
    public final int getAndAddInt(Object o, long offset, int delta) {
        int v;
        do {
            v = getIntVolatile(o, offset);
        } while (!weakCompareAndSetInt(o, offset, v, v + delta));
        return v;
    }
```

Thanks
Muthu

**Comment by ulisseslima** [comment]
Hey, @softwarebrahma.

Thanks for the feedback. `AtomicInteger#getAndIncrement()` and `AtomicInteger#incrementAndGet()` are indeed the standard way of using atomic variables.

We'll take this to the team and update the article if necessary.

**Comment by softwarebrahma** [comment]
> Hey, @softwarebrahma.
> 
> Thanks for the feedback. `AtomicInteger#getAndIncrement()` and `AtomicInteger#incrementAndGet()` are indeed the standard way of using atomic variables.
> 
> We'll take this to the team and update the article if necessary.

Cool thanks @ulisseslima. I like & trust @eugenp & the team's stuff as are many others & its important it remains accurrate.

**Comment by kasramp** [comment]
Hi @softwarebrahma - Thanks for your feedback. We adjusted the code and also updated [the referring article](https://www.baeldung.com/java-atomic-variables).
