### ISSUE TITLE
Small change here: http://localhost:8180/auth/realms/SpringBootKeycloak/protocol/openid-connect/token

### ISSUE THREAD

**Issue by robozb** [eugenp/tutorials#13314]
https://www.baeldung.com/spring-boot-keycloak#custom-loginpage

![image](https://user-images.githubusercontent.com/8656998/213641169-c5f1304c-03ae-423e-94ab-857ed5d754cb.png)

![image](https://user-images.githubusercontent.com/8656998/213641071-1b94ff49-5bf9-4f77-aeba-b8ab073e046d.png)

![SmallChange](https://user-images.githubusercontent.com/8656998/213640756-f2a854ed-c241-41d4-9d14-cde6b5b2d84a.JPG)

**Comment by robozb** [comment]
Or the difference is caused by the docker server?

docker run -p 8180:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:19.0.1 start-dev

**Comment by ulisseslima** [comment]
Hey, @robozb.

Thanks for the feedback. We'll look into this and update the article if necessary.

**Comment by lor6** [comment]
Hi @robozb The article is now updated to use Keycloack 20. The startup instructions have changed, as well as the port - this is now 8080. We've updated the URLs in the article and code, as well as the screenshots. 

Please try an incognito window if you don't see the changes yet in the article, and let us know if you find any other issues.
Thanks.

**Comment by robozb** [comment]
Thank you so much!
