### ISSUE TITLE
Documenation/Article improvement

### ISSUE THREAD

**Issue by dbnex14** [eugenp/tutorials#13318]
This tutorial is using very obscured and confusing sentencing I find on top of very high expectations for the reader.

This paragraph is very confusing and pointing to another even more confusing URL: https://spring.io/guides/tutorials/spring-security-and-angular-js/

"Add an Angular App
The core of a single page application in Angular (or any modern front-end framework) these days is going to be a Node.js build. Angular has some tools for setting this up quickly, so lets use those, and also keep the option of building with Maven, like any other Spring Boot application. The details of how to set up the Angular app are covered [elsewhere](https://github.com/dsyer/spring-boot-angular), or you can just checkout the code for this tutorial from github."

The URL https://github.com/dsyer/spring-boot-angular has even more difficult steps to follow which did not take me anywhere. These steps require advanced knowledge of linux commands, not something I would expect as a requirement for Spring Boot applications.

I have never heard of Angular app being added into Spring Boot project but the description seems to be doing exactly that. Why would you tie these together? Isn't this what monoliths are?

It would be helpful to provide simpler steps with explanations, especially for the Angular part since and as the article mentions, Java devs may not have knowledge of Angular. Same for the linux command being used all over the article, scaffolding details are also missing lots of clear guidance.

In addition to the above, it is unclear 

- if this article explains building an Angular or AngularJS app
- and is this frontend Angular part of Spring Boot backend or are they separate.  It feels like they are one app

The instructions are more deterring than attracting those interested to learn and try out the example.

**Comment by ulisseslima** [comment]
Hey, @dbnex14.

Please include a link to the article you're referring to so we can take a look.

**Comment by dbnex14** [comment]
> Hey, @dbnex14.
> 
> Please include a link to the article you're referring to so we can take a look.

added

**Comment by ulisseslima** [comment]
Hi, @dbnex14.

The article in question is not on baeldung.com.

Unfortunately, we can only help with questions that are specifically and directly related to our articles. In this case, you should check with the spring.io support team.
