### ISSUE TITLE
Q encrypt data with pbkdf2 generated key from String

### ISSUE THREAD

**Issue by freedom1b2830** [eugenp/tutorials#13352]
How to encrypt/decrypt with keys created with pbkdf2 from String password

**Comment by freedom1b2830** [comment]
I need to create a private:public key pair password protected

**Comment by ulisseslima** [comment]
Hey, @freedom1b2830.

We can only help with questions that are specifically and directly related to the articles - not with your own, custom application.

Are you having an issue with the information in a specific article? If that's the case, please include a link to it and more information about what's not working.

Cheers,
Team

**Comment by ulisseslima** [comment]
Closed due to lack of activity.

**Comment by freedom1b2830** [comment]
@ulisseslima 
I finally found what I was looking for.
here is aes from PBKDF2WithHmacSHA256
https://www.baeldung.com/java-aes-encryption-decryption
