### ISSUE TITLE
Spring Batch - JobBuilderFactory and StepBuilderFactory are deprecated

### ISSUE THREAD

**Issue by dhait** [eugenp/tutorials#13377]
Could you please update the tutorials  for Spring Batch 5.0? JobBuilderFactory and StepBuilderFactory are now deprecated.

**Comment by ulisseslima** [comment]
Hey, @dhait 

We have an internal task to update articles to Spring 6, but it might take a while.

This issue will remain open until then.

Cheers,
Team

**Comment by anastasiosioannidis** [comment]
@dhait hi,
we have upgraded the tutorial to Spring Batch 5
