### ISSUE TITLE
Unable to compile java file containing apache camel program

### ISSUE THREAD

**Issue by Hai0612** [eugenp/tutorials#13550]
I would like to try JDI with apache-camel program. However, when i compile file : **javac Write_Pape.java**, i  get some the following errors:
Write_Paper.java:3: error: package org.apache.camel does not exist
import org.apache.camel.CamelContext;
                       ^
Write_Paper.java:4: error: package org.apache.camel.builder does not exist
import org.apache.camel.builder.RouteBuilder;
                               ^
Write_Paper.java:5: error: package org.apache.camel.impl does not exist
import org.apache.camel.impl.DefaultCamelContext;
                            ^
Write_Paper.java:9: error: cannot find symbol
        CamelContext context = new DefaultCamelContext();
        ^
  symbol:   class CamelContext
  location: class Write_Paper
Write_Paper.java:9: error: cannot find symbol
        CamelContext context = new DefaultCamelContext();
                                   ^
  symbol:   class DefaultCamelContext
  location: class Write_Paper
Write_Paper.java:10: error: cannot find symbol
        context.addRoutes(new RouteBuilder() {
                              ^
  symbol:   class RouteBuilder
  location: class Write_Paper
Write_Paper.java:12: error: cannot find symbol
                from("file:sourceFolder?noop=true")
                ^
  symbol: method from(String)
7 errors
FIle content Write_Paper here :
package test;

**import org.apache.camel.CamelContext;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.impl.DefaultCamelContext;

public class Write_Paper {
    public static void main(String[] args) throws Exception {
        CamelContext context = new DefaultCamelContext();
        context.addRoutes(new RouteBuilder() {
            public void configure() {
                from("file:sourceFolder?noop=true")
                .to("file:destinationFolder");
            }
        });
        context.start();
        Thread.sleep(10000);
        context.stop();
    }
}**
And it is my pom.xml file:
**<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>jdi</groupId>
  <artifactId>jdi</artifactId>
  <version>0.0.1-SNAPSHOT</version>
    <dependencies>
      
    <dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-core</artifactId>
    <version>3.15.0</version>
</dependency>
  
  </dependencies>
</project>**

I have tried many solutions but i can't fix these bug, How should i do to fix them?

**Comment by ulisseslima** [comment]
Hi @Hai0612,

This seems like an issue with your custom application and not the code maintained by us.

In this case, I suggest going through StackOverflow; this is a great place to ask more general questions.

**Comment by Hai0612** [comment]
Can I use JDI to monitor and debug java program containing apache camel lib?
