### ISSUE TITLE
Question regarding testing of WebService

### ISSUE THREAD

**Issue by jeserkin** [eugenp/tutorials#13563]
In this article https://www.baeldung.com/spring-webserviceservertest it is mentioned, that there is a nice way of testing with the help of `@WebServiceServerTest` and `MockWebServiceClient client`, but I noticed, that it ignores things like `EndpointInterceptor` and "exceptionResolver" of type `AbstractEndpointExceptionResolver`.

Is there any clear explanation on how to deal with them (`EndpointInterceptor`, `AbstractEndpointExceptionResolver`)? Should they be mocked and verified, that they were actually interacted with or how should one check that?

**Comment by timis1** [comment]
Based on the Java doc for @WebServiceServerTest that classes will automatically be mocked when you use that annotation.

> Using this annotation will disable full auto-configuration and instead apply only configuration relevant to Web Service server tests (i.e. Endpoint and EndpointInterceptor beans but not @Component, @Service or @Repository beans).

References: https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/webservices/server/WebServiceServerTest.html
