### ISSUE TITLE
Null parameter suggestion from `Spring Data JPA and Null Parameters` does not work with Long and UUID

### ISSUE THREAD

**Issue by agreedSkiing** [eugenp/tutorials#13644]
Been trying to reproduce the results from the article https://www.baeldung.com/spring-data-jpa-null-parameters to some extent. What i mean to some extent is that the null check works great with String values but as soon as the parameter changes to a UUID or Long (the two other values that I use in work) the query fails.

To make a more stable solution to this i tried multiple different approaches across a "pure" Hibernate ORM and Hibernate Reactive (with Mutiny) implementation that can be found here as a reproducer https://github.com/agreedSkiing/hibenate-optional-query-testing. I have even documented in a changelog the different commits and the stack-traces which can be found test-failures catalogue in the GitHub repo.

Issue is regard to the code in https://github.com/eugenp/tutorials/tree/master/persistence-modules/spring-data-jpa-filtering

**Comment by ulisseslima** [comment]
Hey, @agreedSkiing.

Using the sample project, it's possible to include `Long` and `UUID` properties to the `Customer` class and corresponding query methods on `CustomerRepository`, which will work as expected.

For the `UUID` type, we need to add a `@Type` annotation: https://stackoverflow.com/questions/18350154/findbyuuid-using-spring-datas-jpa-repository 

We've created an internal task to include examples for these types in the article, but it might take some time.

This issue will remain open until then.

**Comment by kasramp** [comment]
Hi @agreedSkiing - We updated the code as well as the referred article.
Thanks
