### ISSUE TITLE
Error in kubernetes resource in spring cloud modules 

### ISSUE THREAD

**Issue by ralvarezmar** [eugenp/tutorials#13647]
When I try to create a deployment with mongo: 

error: resource mapping not found for name: "mongo" namespaces: "" from "mongo-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by ulisseslima** [comment]
Hey, @ralvarezmar.

Please include the article you're referring to, and the steps to reproduce the error.

**Comment by ralvarezmar** [comment]
The resource api is deprecated in kubernetes v1.16: [](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16)


I just executed "helm install" and i got this error. I will attach a screenshot tomorrow with this error

**Comment by ralvarezmar** [comment]
![k8sError](https://user-images.githubusercontent.com/34791948/227456759-0d5c2ce8-4244-4063-a7dc-d8046579b0db.png)

**Comment by ulisseslima** [comment]
Hey, @ralvarezmar.

I'm assuming this is the article you're referring to: https://www.baeldung.com/spring-cloud-kubernetes

We'll look into this and update the article if necessary.

**Comment by anastasiosioannidis** [comment]
Hi @ralvarezmar 
We have fixed the mongodb issue.
Could get the latest code and try again?
Thanks
