### ISSUE TITLE
Could not find artifact org.baeldung.pmd:custom-pmd:pom:0.0.1 in central (https://repo.maven.apache.org/maven2)

### ISSUE THREAD

**Issue by ilwsm** [eugenp/tutorials#13696]
if i open this pom in jetbrain idea 
https://github.com/eugenp/tutorials/blob/master/spring-web-modules/spring-mvc-forms-thymeleaf/pom.xml

**Comment by llv8** [comment]
has the same issue

**Comment by billson-my** [comment]
Hi, came across this.

I'm still having the issue, but found this URL below is useful for me to continue.
https://github.com/eugenp/tutorials/issues/6021
