### ISSUE TITLE
spring-reactive-exceptions: config setting to increase max-in-memory-size does not exist

### ISSUE THREAD

**Issue by DennisBecker** [eugenp/tutorials#13692]
In your example spring-reactive-exceptions and article https://www.baeldung.com/spring-webflux-databufferlimitexception you mention a config property value for `max-in-memory-size`. We had the issue mentioned in this article and tried the config property but this did not work. I have checked the spring framework documentation and there is no hint on any config property - just the in code solution. See https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client-builder-maxinmemorysize

I would appreciate if you remove the config property example in your article and code example.

**Comment by ulisseslima** [comment]
Hey, @DennisBecker.

Thanks for the feedback. We'll look into this and update the article.

This issue will remain open until then.

**Comment by ehsansasanian** [comment]
Hi @DennisBecker 
Did you use the configured bean provided by Spring Boot (WebClient.Builder)? If so, I think all the properties are already set to the builder. However, if you use the create method (WebClient.Create) you'll get Spring Framework [defaults](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html#webflux-client-builder-maxinmemorysize)

**Comment by ehsansasanian** [comment]
@DennisBecker, I forgot to mention the property. It should be set in the configuration as you sent the link. We will fix it. Thanks!

**Comment by anastasiosioannidis** [comment]
@DennisBecker we have fixed the article
