### ISSUE TITLE
About "Working with Fragments in Thymeleaf"

### ISSUE THREAD

**Issue by ilwsm** [eugenp/tutorials#13705]
Here article:
[Working with Fragments in Thymeleaf](https://www.baeldung.com/spring-thymeleaf-fragments#flexible-layouts)
**4.5. Flexible Layouts**
`<thead th:replace="fragments/tables.html :: fields(~{ :: .myFields})">`
in
[other.html](https://github.com/eugenp/tutorials/blob/master/spring-web-modules/spring-thymeleaf/src/main/webapp/WEB-INF/views/other.html#L15)

How does this code work? Is there an error here? I can generally delete this `<thead th:replace="fragments/tables.html :: fields(~{ :: .myFields})">`, and nothing will change. The resulting `html` source will be same.

**Comment by ulisseslima** [comment]
Hey, @ilwsm.

It's not an error. This code will replace the `fields` fragment in tables.html with the content of the element with CSS class `myFields`.

For example, this can be useful if you want default headers in your template but easily override them.

If you include this default content in the `fields` fragment of tables.html:
```xml
        <tr th:replace="${theadFields}">
        	<th>Field 1</th>
        	<th>Field 2</th>
        </tr>
```

You can check this behavior by changing `thead` in other.html to use the default fragment content:
```xml
<thead th:replace="fragments/tables.html :: fields(_)">
```

Hope it helps.
