### ISSUE TITLE
About article "Logging in Spring Boot"

### ISSUE THREAD

**Issue by TusharGirase** [eugenp/tutorials#13709]
In this article [Topic 4](https://www.baeldung.com/spring-boot-logging#logback-configuration-logging) says we can set any of the files as below
logback-spring.xml
logback.xml
logback-spring.groovy
logback.groovy

But in the source code logback-spring.xml is missing

`@Override
	protected String[] getStandardConfigLocations() {
		return new String[] { "logback-test.groovy", "logback-test.xml", "logback.groovy", "logback.xml" };
	}`

Above method is from LogbackLoggingSystem class from Spring Boot 3.0.5 version. Need to remove this file name from article.

**Comment by ulisseslima** [comment]
Hey @TusharGirase.

Thanks for the feedback. We'll look into this and update the article if necessary.

This issue will remain open until then.

**Comment by brianmaresca** [comment]
on a separate note for this article - everything ive seen, read, and heard strongly discourages the use of `JsonLayout` in favor of the new and improved `JsonTemplateLayout`. it's even mentioned several times in the apache JsonLayout docs (https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout) that you should use JsonTemplateLayout instead (https://logging.apache.org/log4j/2.x/manual/json-template-layout.html). in my experience for some reason JsonTemplateLayout is quite confusing to implement. i think a tutorial on implementing JsonTemplateLayout would be very beneficial for all.

**Comment by ehsansasanian** [comment]
Hey @TusharGirase 
It's recommended in the [docs ](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.custom-log-configuration)to use logback-spring.xml, and it seems like it is supported.

**Comment by dbadu** [comment]
Hi @TusharGirase, to add the logback extensions, it is recommended to use the `logback-spring.xml` file.  It is not possible to add the logback extensions to the file `logback.xml` as stated in official docs [link](https://docs.spring.io/spring-boot/docs/3.0.1/reference/html/features.html#features.logging.logback-extensions).

So it is not an issue, hence closing the ticket.
Thank you @ehsansasanian for the analysis.
