### ISSUE TITLE
missing packages to match hexagonal architecture - dddhexagonalspring 

### ISSUE THREAD

**Issue by amirensit** [eugenp/tutorials#13733]
Hello.

I started following the hexagonal tutorial but I noticed that there is no **port** sub-package under the domain package.  I know there are many variation but I think It is a mandatory part.

Am I wrong ?

**Comment by ulisseslima** [comment]
Hey, @amirensit.

It's not mandatory to have a port sub-package under the domain package when implementing Hexagonal Architecture. 

Organizing the ports and adapters under the domain package is common practice to make it clear that the application layer is separate from the infrastructure layer. However, you can choose any package structure that makes sense for your application if you follow the principles of hexagonal architecture.
