### ISSUE TITLE
Nash-Carp solve algorithm

### ISSUE THREAD

**Issue by EddDoubleD** [eugenp/tutorials#13781]
It is possible to solve Sudoku as a system of differential equations, see more on article [The Chaos Within Sudoku](https://www.nature.com/articles/srep00725)
Example of my [solution](https://github.com/EddDoubleD/sudokuNinja)

**Comment by ulisseslima** [comment]
Hey, @EddDoubleD.

Unfortunately, we can only help with questions that are specifically and directly related to existing articles on Baeldung.

If you can reproduce an issue on our codebase, create a pull request with this in a new issue, and we’ll look into it. Also, remember to include the article link.

Cheers,
Team
