### ISSUE TITLE
Regarding article "Introduction to JsonPath"

### ISSUE THREAD

**Issue by pedroluiznogueira** [eugenp/tutorials#13792]
Hi, since there's not much content on different scenarios on `json-path` out there, and their maintainers seem to not be answering pretty often to issues, requests, etc.

I would like to suggest the [article](https://www.baeldung.com/guide-to-jayway-jsonpath) to include the use case of using a `Predicate` to filter a root document property.

Imagine right above `"root"` in `intro_api.json` it had a property `age`:

```json
{
	"age": 5, 
	"tool": "..."
}
```
It would be great to have an example on how to delete/read this document based on a `Predicate` based on the `age` property.

**Comment by ulisseslima** [comment]
Hey, @pedroluiznogueira.

Thanks for the feedback.

We'll look into this and update the article if necessary.

This issue will remain open until then.

**Comment by dkapil** [comment]
We have updated the article and code to include this example

**Comment by pedroluiznogueira** [comment]
awesome 😄  > We have updated the article and code to include this example
