### ISSUE TITLE
How to json-patch with real entities?

### ISSUE THREAD

**Issue by Manfred73** [eugenp/tutorials#13840]
I've been following the example of the json-patch (https://github.com/eugenp/tutorials/tree/master/spring-web-modules/spring-rest-http), but then using Quarkus and Pananche with a real database and entity.

I did the same as in the example code, but then with my entity:

Lookup the entity from the repository based on id, then apply the JsonPatch and persist it to the repository again. The persisting doesn't go as expected (because of a detached entity since the apply just returns a new entity??). How can I make this work with real entities without having to do manual mapping to the retrieved entity from the db?

```
@Transactional
public MyModel updateEntity(final Long id, final JsonPatch jsonPatch) {
    return repository.findByIdOptional(id)
            .map(e -> updateEntity(e, jsonPatch))
            .orElseThrow(() -> new ResourceNotFoundException(id));
}

private MyModel updateEntity(final MyEntity entity, final JsonPatch patch) {
    final var entityPatched = applyPatchToMyEntity(entity, patch);
    repository.persist(entityPatched);  // this is where it goes wrong, since entityPatched is not the retrieved entity but becomes a new detached entity?
    return modelMapper.map(entityPatched, MyModel.class);
}

private MyEntity applyPatchToMyEntity(MyEntity targetMyEntity, JsonPatch patch) {
    try {
        final var patched = patch.apply(objectMapper.convertValue(targetMyEntity, JsonNode.class));
        return objectMapper.treeToValue(patched, MyEntity.class);
    } catch (JsonPatchException | JsonProcessingException e) {
        throw new MyException("Error patching/updating entity", e);
    }
}
```

**Comment by ulisseslima** [comment]
Hey, @Manfred73.

Thanks for the feedback. We'll add an example using a real database, but it might take a while.

This issue will remain open until then.

**Comment by Manfred73** [comment]
Hi,

I found the solution was to do a merge instead of a persist.
Panache doesn't have a merge (like persist) on the repository itself, but you can do it via the EntityManager as follows:

```
repository.getEntityManager().merge(entityPatched)
```
