### ISSUE TITLE
Not able to load providers in Java SPI example.

### ISSUE THREAD

**Issue by vibhorgarg** [eugenp/tutorials#14013]
Hi, I am not able to load providers in Java SPI example. 
I am able to run the main class, but the provider list is zero.
Any hints for what I might have missed ? 
Attaching one image for reference.
In the terminal, we can see that no provider is loaded.

![Screenshot 2023-05-15 at 2 14 25 AM](https://github.com/eugenp/tutorials/assets/8424906/4757836d-1ce1-4c5f-9463-2b5155deb22a)

**Comment by ulisseslima** [comment]
Hey, @vibhorgarg.

Article: https://www.baeldung.com/java-spi

Try running the command exactly as described in the article:
```bash
java -Djava.ext.dirs=$JAVA_HOME/jre/lib/ext:./exchange-rate-impl/target:./exchange-rate-impl/target/depends -cp ./exchange-rate-api/target/exchange-rate-api-1.0.0-SNAPSHOT.jar:./exchange-rate-app/target/exchange-rate-app-1.0.0-SNAPSHOT.jar com.baeldung.rate.app.MainApp
```

Your command is setting `java.ext.dir` instead of `java.ext.dirs`.

Also, make sure `$JAVA_HOME` is pointing to a valid Java installation.

**Comment by vibhorgarg** [comment]
thanks, its wikring with this fix.
