### ISSUE TITLE
Consumer-Producer doesn't work

### ISSUE THREAD

**Issue by EvgeniyBokovFIT** [eugenp/tutorials#14031]
![consprod](https://github.com/eugenp/tutorials/assets/75373950/65c0d41a-953d-4b5e-a162-fa86b6e210ff)
Here we are holding the dataQueue monitor. In the while loop, we are waiting on the FULL_QUEUE object (in the dataQueue.waitOnFull() method). So other threads can't use the dataQueue monitor because we're waiting on a different object.

**Comment by ulisseslima** [comment]
Hey, @EvgeniyBokovFIT.

Thanks for the feedback. We'll look into this and update the article if necessary.

This issue will remain open until then.

**Comment by GaetanoPiazzolla** [comment]
Hello @EvgeniyBokovFIT you are right. 
Leaving the synchronized code block as it is, we will only produce messages without consuming them.
This was the fix: https://github.com/eugenp/tutorials/pull/14318

**Comment by dkapil** [comment]
Closing here
