### ISSUE TITLE
Oracle Spring Boot Starters for UCP and wallet available in Maven Central

### ISSUE THREAD

**Issue by markxnelson** [eugenp/tutorials#14035]
Hi, 
I saw your sample https://github.com/eugenp/tutorials/tree/master/persistence-modules/spring-boot-persistence-2
and this related article https://www.baeldung.com/spring-oracle-connection-pooling

I wanted to let you know that there are now Oracle Spring Boot Starters for UCP and wallet available in Maven Central 
https://central.sonatype.com/namespace/com.oracle.database.spring

If you have a chance to check them out and give any feedback, that would be great!

**Comment by ulisseslima** [comment]
Hey, @markxnelson.

Thanks for the feedback. We'll look into this and update the article if necessary.

This issue will remain open until then.

**Comment by dkapil** [comment]
We have improved our article to use oracle ucp starter
