### ISSUE TITLE
Endpoint is not appearing in the wsdl

### ISSUE THREAD

**Issue by ssiva89** [eugenp/tutorials#14111]
I've created a new endpoints in an existing webservice,  following the tutorial. I'm not able to see the endpoint in the wsdl for some reason. 
i've checked the below, 
1. endpoint is annotated with "@Endpoint"
2. "@payloadroot" is mentioned (name space and local part are good)
3. "@requestpayload" and "@responsepayload" are in place
4. xsd file has the required configs for the bean contracts
5. service config is good , as the other endpoints are visible wsdl.
let me know , if I need to check anything else.

below is the response from curl cmd

> curl --header "content-type: text/xml" -d @request.xml http://localhost:8090/ws
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
		<SOAP-ENV:Body>
			<SOAP-ENV:Fault>
				<faultcode>SOAP-ENV:Client</faultcode>
				<faultstring xml:lang="en">Validation error</faultstring>
				<detail><spring-ws:ValidationError xmlns:spring-ws="http://springframework.org/spring-ws">cvc-elt.1: Cannot find the declaration of element 'sch:activateRequest'.</spring-ws:ValidationError></detail>
			</SOAP-ENV:Fault>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
>

thank you
Siva

**Comment by ulisseslima** [comment]
Closed due to inactivity.
