### ISSUE TITLE
Correct typo in original article "Qualifier" -> "@Qualifier"

### ISSUE THREAD

**Issue by TeaTiMe08** [eugenp/tutorials#14285]
In the aricle describing multiple datasources:
[https://www.baeldung.com/spring-boot-configure-multiple-datasources](https://www.baeldung.com/spring-boot-configure-multiple-datasources)

a typo is in the block, so the code does not compile, missing an @ sign. See here:

"5. Spring Data JPA"
...
So, we need to declare EntityManager factories for each data source:
_here_

make "Qualifier" -> "@Qualifier"

**Comment by ulisseslima** [comment]
Hey, @TeaTiMe08.

Thanks for the feedback.

We'll update the article to fix this.
