### ISSUE TITLE
Correct typo in original article "todosDataSource()" -> "dataSource"

### ISSUE THREAD

**Issue by TeaTiMe08** [eugenp/tutorials#14287]
In the aricle describing multiple datasources:
[https://www.baeldung.com/spring-boot-configure-multiple-datasources](https://www.baeldung.com/spring-boot-configure-multiple-datasources)

a typo is in the block, so the code does not compile, autocorrect replaced the constructor datasource with the bean reference. See here:

"5. Spring Data JPA"
...
So, we need to declare EntityManager factories for each data source:
```
@Bean
public LocalContainerEntityManagerFactoryBean todosEntityManagerFactory(
  Qualifier("todosDataSource") DataSource dataSource,
  EntityManagerFactoryBuilder builder) {
    return builder
      .dataSource(todosDataSource()) // should be .dataSource(dataSource)
```

**Comment by ulisseslima** [comment]
Hey, @TeaTiMe08.

Thanks for the feedback.

We'll update the article to fix this.
