### ISSUE TITLE
Spring Boot autoconfiguration tutorial doesn't work in Spring Boot 3

### ISSUE THREAD

**Issue by prdoyle** [eugenp/tutorials#14371]
Spring Boot 3 has removed support for `META_INF/spring.factories` autoconfiguration [here](https://github.com/spring-projects/spring-boot/issues/29699).

**Comment by ulisseslima** [comment]
Hey, @prdoyle.

We have internal tasks to update our articles to Spring Boo 3, but it might take some time.

This article will remain open until then.

**Comment by anastasiosioannidis** [comment]
Hi @prdoyle we have updated the article.
