### ISSUE TITLE
Queue size goes beyond MAX_QUEUE_CAPACITY

### ISSUE THREAD

**Issue by ronak-dhiravani** [eugenp/tutorials#14417]
In Producer Consumer code with Multiple Producer, Queue size goes beyond MAX_QUEUE_CAPACITY. I have seen it goes till 6 for MAX_QUEUE_CAPACITY = 5.

Changing `notifyAll()` to `notify()` solves this problem, but is there a way to solve this with `notifyAll()` ?

**Comment by ulisseslima** [comment]
Hey, @ronak-dhiravani.

We'll look into this. This issue will remain open until then.

https://www.baeldung.com/java-producer-consumer-problem

**Comment by kasramp** [comment]
Hi @ronak-dhiravani - We have addressed the issue, updated the code and the referring article.
Thanks
