### ISSUE TITLE
Spring-rest-query-language project refers to missing class.

### ISSUE THREAD

**Issue by orangefunk** [eugenp/tutorials#14501]
MyUserRepository.java class imports the following class

import com.baeldung.persistence.model.QMyUser;

However this is not defined at all in the project and is referenced in a few places.  Is it a typo?

**Comment by ulisseslima** [comment]
Hey, @orangefunk.

QMyUser is generated by _querydsl_. Check this article for configuration: https://www.baeldung.com/rest-api-search-language-spring-data-querydsl#querydsl-configuration

When correctly configured, the _QmyUser.java_ class will be generated in _target/generated-sources/java_, which you must ensure is in your classpath.
