### ISSUE TITLE
Bulding spring-boot-jasypt module fails because of of Permissions Changes to repo.spring.io

### ISSUE THREAD

**Issue by yehor-trembovetskyi** [eugenp/tutorials#14505]
Error message

`Could not transfer artifact org.springframework.cloud:spring-cloud-dependencies:pom:Finchley.M8 from/to spring-milestones (https://repo.spring.io/libs-milestone): status code: 401, reason phrase:  (401) -> [Help 1]`

This error is caused by this: https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020

Tried to identify source of this error, but dependency analysis command fails because of the same error.

Could someone help to understand the root which causes the issue?

**Comment by ulisseslima** [comment]
Hey, @yehor-trembovetskyi.

Could you give more details? 

1. Is this the article you're referring to? https://www.baeldung.com/spring-boot-jasypt
2. Does this error happen when you run _mvn clean install_?
3. Are you running the article code without modifications?

**Comment by yehor-trembovetskyi** [comment]
Hi @ulisseslima !
Sure:
1. yes
2. exactly, here is a complete error message:

`[ERROR] Failed to execute goal on project spring-boot-jasypt: Could not resolve dependencies for project com.example.jasypt:spring-boot-jasypt:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:2.0.0: Failed to read artifact descriptor for com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:2.0.0: The following artifacts could not be resolved: org.springframework.cloud:spring-cloud-dependencies:pom:Finchley.M8 (absent): Could not transfer artifact org.springframework.cloud:spring-cloud-dependencies:pom:Finchley.M8 from/to nexus (https://delivery-nexus.leo-platform-infra.lvg-tech.net/repository/maven/): status code: 403, reason phrase: Forbidden (403) -> [Help 1]`

3. yes

**Comment by yehor-trembovetskyi** [comment]
Hi @ulisseslima !

Sure:

1. yes
2. yes, here is complete error message:

`Could not resolve dependencies for project com.example.jasypt:spring-boot-jasypt:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:2.0.0: Failed to read artifact descriptor for com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:2.0.0: The following artifacts could not be resolved: org.springframework.cloud:spring-cloud-dependencies:pom:Finchley.M8 (absent): Could not transfer artifact org.springframework.cloud:spring-cloud-dependencies:pom:Finchley.M8 from/to nexus ([our nexus repo](url)): status code: 403, reason phrase: Forbidden (403) -> [Help 1]`

3. yes

**Comment by ulisseslima** [comment]
Hey, @yehor-trembovetskyi.

Since our project isn't using any custom repositories, this seems to be a problem with a custom one defined in your local Maven settings.

Unfortunately, we cannot help in this case. You can try removing any custom repositories and building the project again.

Hope that helps.
