### ISSUE TITLE
Shall we not have a SpringServlet Initialization also in the main method?

### ISSUE THREAD

**Issue by Jayanta0123** [eugenp/tutorials#14515]
Hello team,

I do keep an eye on the latest developments in this space (eugenp/tutorials) - can we have a SpringServlet-Intialization too to the main method? That would ensure the spring-boot dependency would be auto-fetched to the dependency-library when the code is built.

Main class for the Spring-data-jpa-enterprise-2 module given below.

https://github.com/eugenp/tutorials/blob/master/persistence-modules/spring-data-jpa-enterprise-2/src/main/java/com/baeldung/multipledb/MultipleDbApplication.java

**Comment by ulisseslima** [comment]
Hey, @Jayanta0123.

Regarding the SpringServlet-Initialization, our project already uses Maven as a build tool, which automatically manages and fetches all the dependencies specified in the pom.xml file during the build process.
