### ISSUE TITLE
Incorrect reference?

### ISSUE THREAD

**Issue by karlkras** [eugenp/tutorials#14607]
https://github.com/eugenp/tutorials/blob/7874709740d3a33e0d87e8e78da328e29454bbad/testing-modules/testng/pom.xml#L36

Shouldn't this be `src/test/resources` ?

**Comment by ulisseslima** [comment]
Hey, @karlkras.

Thanks for pointing it out; we'll look into this.

This issue will remain open until then.

**Comment by dkapil** [comment]
This is fixed.
