### ISSUE TITLE
Overriding local Spring Cloud Config Server properties by Environment Variables or System Properties

### ISSUE THREAD

**Issue by ofyaniv** [eugenp/tutorials#14710]
Thank you for publishing the excellent article on  Overriding the Values of Remote Properties in Spring Cloud Config.

Overriding the Values of Remote Properties in Spring Cloud Config
https://www.baeldung.com/spring-cloud-config-remote-properties-override
https://github.com/christian-german

I have successfully built and executed the spring-cloud-config-overriding-properties-server sample:
https://github.com/eugenp/tutorials/tree/master/spring-cloud-modules/spring-cloud-config/spring-cloud-config-overriding-properties-server

I have added the following property to activate the native profile:

src/main/resources/application.properties
```
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config,file:/home/user/conf
```

1) Any idea how I can override the values of properties that are stored in the local file system by the values of environment variables or system properties of the spring cloud config server?

2) Was this behavior deprecated by the latest spring versions?

3) Is there any way to enable/integrate org.springframework.core.env.SystemEnvironmentPropertySource  with Spring Cloud Config?

Should I use any of the following properties for that?

src/main/resources/application.properties
```
spring.cloud.config.allow-override=false
spring.cloud.config.override-none=true
spring.cloud.config.override-system-properties=false
```

Thanks and regards
 Ofer

**Comment by ulisseslima** [comment]
Hey, @ofyaniv.

Thanks for the feedback. We'll look into this and update the article if necessary.

This issue will remain open until then.

**Comment by kasramp** [comment]
Hi @ofyaniv - to answer your questions

1. To override values on runtime (reading from env var), you can use placeholder. The Spring cloud config server is a Spring boot application and as usual with a Spring Boot application, these properties could also be set by environment variables or command line arguments: [https://www.baeldung.com/spring-boot-properties-env-variables](https://www.baeldung.com/spring-boot-properties-env-variables)
2. No it's no deprecated
3. Yes you can use the [SystemEnvironmentPropertySource](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/env/SystemEnvironmentPropertySource.html) with Spring Cloud Config server too. It's the part of the core Spring framework

Thanks
