### ISSUE TITLE
Rename package com.baeldung.scope.singletone to com.baeldung.scope.singleton

### ISSUE THREAD

**Issue by pfurbacher** [eugenp/tutorials#14743]
Package [`com.baeldung.scope.singletone`](https://github.com/eugenp/tutorials/tree/master/spring-core/src/main/java/com/baeldung/scope/singletone) should be renamed to 

`     com.baeldung.scope.singleton`

**Comment by ulisseslima** [comment]
Hey, @pfurbacher.

Thanks for the feedback. This issue will remain open until we look into this.

**Comment by kasramp** [comment]
Thanks @pfurbacher - the typo in package name is fixed now.
