### ISSUE TITLE
Missing 'file' Appender Configuration in Log4j Properties.

### ISSUE THREAD

**Issue by dimosntioudis** [eugenp/tutorials#14855]
**Description**

The **log4j.rootLogger** references the 'file' appender but the appender is not defined in the configuration file.

```
# Root logger
log4j.rootLogger=INFO, file, stdout

# Write to console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
```

**Expected Behavior:**

The Log4j properties file should either include a properly configured 'file' appender to allow logging to a file as indicated by the log4j.rootLogger configuration or the 'file' appender should be removed.

**Current Output:**

> log4j:ERROR Could not find value for key log4j.appender.file
> log4j:ERROR Could not instantiate appender named "file".

**Additional Information:**

- Log4j properties file location: [here](https://github.com/eugenp/tutorials/blob/master/patterns-modules/design-patterns-structural/src/main/resources/log4jstructuraldp.properties)

**Comment by ulisseslima** [comment]
Hey, @dimosntioudis.

Thanks for the feedback; we'll look into this. This issue will remain open until then.

**Comment by kasramp** [comment]
Hi @dimosntioudis - Thanks, the code is amended accordingly.
