### ISSUE TITLE
Missing implementation dependency on /java-logging-intro

### ISSUE THREAD

**Issue by juanpablolunardi** [eugenp/tutorials#14916]
https://www.baeldung.com/java-logging-intro

Description
Missing implementation dependency for log4j

1. Create a maven project from scratch
2. Add log4j-api & log4j-core as mentioned, and log4j2.xml 
3. Create a main method and log any line with debug, info and error level

Actual Behavior
Just error level is logged

Expected Behavior
All log levels are shown

Environment
- IntelliJ IDEA 2023.2.2 (Community Edition)
- OpenJDK Corretto-17.0.8.8.1 
- OS: Ventura 13

My solution
Worked fine after adding dependency: org.apache.logging.log4j:log4j-slf4j-impl

**Comment by ulisseslima** [comment]
Hey, @juanpablolunardi.

Thanks for the feedback. We'll look into this.

This issue will remain open until then.

**Comment by dkapil** [comment]
Working fine now.
