### ISSUE TITLE
.failureHandler(authenticationFailureHandler()) does not exist in spring-config 6.1.1

### ISSUE THREAD

**Issue by cobar79** [eugenp/tutorials#14969]
[spring-security-exceptionhandler](https://www.baeldung.com/spring-security-exceptionhandler)

HttpSecurity.failureHandler no longer exists.

HttpSecurity.exceptionHandling didn't catch InvalidBearerTokenException

**Comment by ulisseslima** [comment]
Hey, @cobar79.

We have internal tasks to keep articles updated with Spring 6, but it might take a while.

This issue will remain open until then.

**Comment by kasramp** [comment]
Hi @cobar79 - The `failureHandler` is not from `HttpSecurity`. It's from `FormLoginConifgurer<HttpSecurity>` superclass `AbstractAuthenticationFilterConfigurer`. 

The article and the code uses Spring Boot 2 that uses Spring Security 5.7.8. Nonetheless both [Spring Security 5.7.8](https://javadoc.io/doc/org.springframework.security/spring-security-config/5.7.8/org/springframework/security/config/annotation/web/configurers/FormLoginConfigurer.html) and [6.1](https://javadoc.io/doc/org.springframework.security/spring-security-config/6.1.5/org/springframework/security/config/annotation/web/configurers/FormLoginConfigurer.html) have that method.

`HttpSecurity.exceptionHandling` didn't catch any `InvalidBearerTokenException`.  The Invalid bearer token on the Client side is matched to an `AuthenticationFailureBadCredentialsEvent`. Therefore, HttpSecurity doesn't catch such an exception. The mapping for the exception, [here](https://docs.spring.io/spring-security/reference/servlet/authentication/events.html#_adding_exception_mappings)
