### ISSUE TITLE
Not able to mock URL

### ISSUE THREAD

**Issue by jw44250** [eugenp/tutorials#1512]
I have tried to mock the blow class but still failed 
https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2
@Mck...HtpConnetion mockConnection..
@before (){
MockAnntion(this);
}
@Test..
       URl url = Mock(URL.class)
      when(url.openConnection).returnThan(mockConnection);

//////////////////////////////////////////////////////////////////
public final class MyConnection {
private MyConnection(){}
public static HttpURLConnection getConnection(String targetURL ) {

URL url = null;
HttpConnection connection = null;

try {
  url = new URL(targetURL);

  connection = (HttpConnection) url.openConnection();
}
}
}

**Comment by eugenp** [comment]
Hmm - that's interesting @jw44250 - what's this related to? One of the articles on the site? 
This might be a better question to ask over on StackOverflow. Feel free to send me the link of course. 
Cheers, 
Eugen.
