### ISSUE TITLE
[ISSUE] @Disable should be @Disabled

### ISSUE THREAD

**Issue by tasosz** [eugenp/tutorials#15218]
**Article and Module Links**
[A Guide to JUnit 5](https://www.baeldung.com/junit-5)

**Describe the Issue**
In section 3.2
> `@Disable` – disables a test class or method (previously `@Ignore`)

should read:
> `@Disabled` – disables a test class or method (previously `@Ignore`)

https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Disabled.html

**Comment by ulisseslima** [comment]
Hey, @tasosz.

Thanks for the feedback. We'll update the article to fix this.

**Comment by ulisseslima** [comment]
Hey, @tasosz.

Article updated.
