### ISSUE TITLE
Escaping special characters is not null safe

### ISSUE THREAD

**Issue by samuelstein** [eugenp/tutorials#15250]
The escaping method for special characters is not null safe.
https://github.com/eugenp/tutorials/blob/f9a4409eb624cf92d961514c5046f1ac062dd04c/core-java-modules/core-java-io-conversions-2/src/main/java/com/baeldung/csv/WriteCsvFileExample.java#L15

**Comment by samuelstein** [comment]
I'm not very happy how this was fixed because it throws an exception for empty properties instead of returning empty string. This leads to unnecessary exception handling code and makes it more complicated to understand. In most cases you would anyway use an empty string when an exception was thrown.

**Comment by ulisseslima** [comment]
Hey, @samuelstein.

Thanks for the feedback.

While your comment makes sense, considering the focus of the article and the fact that there is no clear-cut answer on handling nullable parameters. One should be able to easily adapt the code to its needs.
