### ISSUE TITLE
[ISSUE] H2 Database Article has confusing mistakes

### ISSUE THREAD

**Issue by Luiggi33** [eugenp/tutorials#15558]
**Article and Module Links**
[Spring Boot With H2 Database @ baeldung.com](https://www.baeldung.com/spring-boot-h2-database)
[Spring Boot With H2 Database @ github.com](https://github.com/eugenp/tutorials/tree/master/persistence-modules/spring-boot-persistence-h2)

**Describe the Issue**
While talking about the database configuration, the example code for the application.properties and application.yaml file include `spring.datasource."https://mvnrepository.com/search?q="=jdbc:h2:mem:testdb` or `"https://mvnrepository.com/search?q=": jdbc:h2:mem:mydb`. I am fairly certain that this is some kind of typo and it should be `spring.datasource.url=jdbc:h2:mem:testdb` and `url: : jdbc:h2:mem:mydb` respectfully. This mistake is repeated for multiple code examples in the database configuration section and can be disruptive when not knowing Spring that much

**To Reproduce**
Not needed

**Expected Behavior**
The correct property should be used in the example code

**Screenshots**
![Screenshot of the example code](https://i.imgur.com/BK1Jq8I.png)

**Environment (please complete the following information):**
- OS: Windows
- Browser Firefox
- Version 121.0

**Additional Context**
N/A

**Comment by lor6** [comment]
Thanks @Luiggi33 This is now fixed.
