### ISSUE TITLE
core-java-8 under core-java-modules is failing with JDK 17 maven build.

### ISSUE THREAD

**Issue by s4ravanank** [eugenp/tutorials#15725]
core-java-8 under core-java-modules is failing with JDK 17 maven build.
If we use JDK 17 as java home and do the maven build. The build is failing for Unit tests. 

java/tutorials/core-j/core-java-8>mvn clean install 

[ERROR] Failures:
[ERROR]   DateFormatUnitTest.givenGregorianCalendar_whenDateInstanceWithDifferentFormats_givenSpecificDateFormatting:37 expected:<1[-feb-]2018> but was:<1[ feb ]2018>
[ERROR]   DateFormatUnitTest.givenGregorianCalendar_whenDateTimeInstanceWithDifferentFormats_givenSpecificDateTimeFormatting:64 expected:<...ì 1 febbraio 2018 10[.15.20 CET]> but was:<...ì 1 febbraio 2018 10[:15:20 Ora dell'Europa centrale]>
[ERROR]   DateFormatUnitTest.givenGregorianCalendar_whenLocaleSpecificDateTimeInstance_givenLocaleSpecificFormatting:78 expected:<...ì 1 febbraio 2018 10[.15.20 CET]> but was:<...ì 1 febbraio 2018 10[:15:20 Ora dell'Europa centrale]>
[ERROR]   DateFormatUnitTest.givenGregorianCalendar_whenTimeInstanceWithDifferentFormats_givenSpecificTimeFormatting:50 expected:<10[.15.20 CET]> but was:<10[:15:20 Ora dell'Europa centrale]>
[ERROR]   NumbersCurrenciesFormattingUnitTest.givenDifferentLocalesAndDoubleAmount_whenCurrencyInstance_thenDifferentOutput:43 expected:<102 300,46[ ]zł> but was:<102 300,46[ ]zł>
[ERROR]   NumbersCurrenciesFormattingUnitTest.givenLocaleAndNumber_whenSpecificDecimalFormat_thenSpecificOutput:57 expected:<102[ ]300,5> but was:<102[ ]300,5>
[INFO]
[ERROR] Tests run: 65, Failures: 6, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.774 s
[INFO] Finished at: 2024-01-25T07:43:21+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project core-java-8: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/saravanan.kandaswamy/works/sandbox/java/tutorials/core-java-modules/core-java-8/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Env:
Maven home: /usr/local/Cellar/maven/3.9.6
Java version: 17.0.9

**Comment by ulisseslima** [comment]
Hey, @s4ravanank.

Thanks for bringing this to our attention. We'll look into this.

This issue will remain open until then.

**Comment by dkapil** [comment]
core-java-8 module will not be upgraded to JDK 17, it now only contains articles that couldn't be upgraded to JDK 17
