### ISSUE TITLE
i use spring security-oauth2-6.2.1.jar and be a error

### ISSUE THREAD

**Issue by githubanhduong** [eugenp/tutorials#15762]
@Bean
  WebClient webClient(ReactiveClientRegistrationRepository clientRegistrations) {
      ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
        new ServerOAuth2AuthorizedClientExchangeFilterFunction(
          clientRegistrations,
          new UnAuthenticatedServerOAuth2AuthorizedClientRepository());
      oauth.setDefaultClientRegistrationId("bael");
      return WebClient.builder()
        .filter(oauth)
        .build();
  }

UnAuthenticatedServerOAuth2AuthorizedClientRepository cannot be resolved to a type

**Comment by ulisseslima** [comment]
Hey, @githubanhduong.

We're assuming this is the article you're referring to: UnAuthenticatedServerOAuth2AuthorizedClientRepository

This tutorial currently only works for Spring 5.

We have internal tasks to keep articles updated with Spring 6, but it might take a while.

This issue will remain open until then.

**Comment by githubanhduong** [comment]
thank you
