### ISSUE TITLE
[ISSUE] Minute to second conversion is minute to minute conversion

### ISSUE THREAD

**Issue by stetsche** [eugenp/tutorials#15786]
**Article and Module Links**
https://www.baeldung.com/java-timeunit-conversion

**Describe the Issue**
In the paragraph **3.2. Using the toXXX()** Method `long seconds = TimeUnit.MINUTES.toMinutes(1);` should be `long seconds = TimeUnit.MINUTES.toSeconds(1);`

**Comment by ulisseslima** [comment]
Hey, @stetsche.

Thanks for bringing this to our attention. We've updated the article to fix this.
