### ISSUE TITLE
[ISSUE] on the springboot using keycloak, authorization based on role is not working.

### ISSUE THREAD

**Issue by blackphantom0221** [eugenp/tutorials#16009]
**Article and Module Links**
(https://www.baeldung.com/spring-boot-keycloak).

**Describe the Issue**
I already followed the above link about keycloak.
first of all, I have got access token from keycloak server. at that time, I used credential with "user" role.
as you can see on the attached screenshot, when you call the URL using postman, I don't get any response.
Of course, I added token to header.

**To Reproduce**
1. Run keycloak server
2. Run the springboot serve
3. Using postman, I call the api

**Expected Behavior**

**Screenshots**
![code](https://github.com/eugenp/tutorials/assets/122392040/caf78ac4-6622-4a10-add9-0554d5a2dde3)
![postman](https://github.com/eugenp/tutorials/assets/122392040/6843a05d-2461-4dd7-a07c-15de6c84d414)

**Environment (please complete the following information):**
- OS: [Windows]
- Postman: 10.23.5

**Comment by apeterlic** [comment]
Hey @blackphantom0221,

Have you made any custom changes in the code?

Regards,
Team.

**Comment by apeterlic** [comment]
Closed due to lack of activity.
