### ISSUE TITLE
ordered parameters in LIKE queries 

### ISSUE THREAD

**Issue by sinhapul** [eugenp/tutorials#16041]
Issue: ordered parameters in LIKE queries in Spring-Data-Jpa 3.2.2

//@Query("SELECT m FROM Movie m WHERE m.director LIKE %?#{escape([0])} escape ?#{escapeCharacter()}")
    @Query("SELECT m FROM Movie m WHERE m.director LIKE %:#{[0]}")
    List<Movie> searchByDirectorEndsWith(String director ,String actor );

If more than two parameters  ((String director ,String actor ) with Like and other non-like , then  how the @Query will be formed..?

**Comment by apeterlic** [comment]
Hey @sinhapul,

Please include a link to the article you're referring to so we can check it.

Regards,
Team.

**Comment by apeterlic** [comment]
Closed due to lack of activity.
