### ISSUE TITLE
Incorrect value for HttpClient keep-alive timeout since JDK 20

### ISSUE THREAD

**Issue by marcus-bcl** [eugenp/tutorials#16298]
**Article and Module Links**
https://www.baeldung.com/java-httpclient-connection-management#connection-keepalive-timeouts

**Describe the Issue**
The article mentions that the default JDK HttpClient keep-alive timeout is 1200 (20 minutes).  However, from JDK 20 onwards, the default was reduced to 30 seconds.

**Additional Context**
* https://bugs.openjdk.org/browse/JDK-8297558

**Comment by apeterlic** [comment]
Hey @marcus-bcl,

You're right and there is already a note about it in the same section: _Since 20 minutes is a long time in modern architecture, JDK20, build 26 reduces the default to 30 seconds._

Cheers,
Team

**Comment by rishiraj88** [comment]
Nice catch and fix applied. Thanks, @marcus-bcl .
