### ISSUE TITLE
[ISSUE] Unable to compile maven-modules/multimodulemavenproject

### ISSUE THREAD

**Issue by RohimChou** [eugenp/tutorials#16300]
**Article and Module Links**
article: https://www.baeldung.com/maven-multi-module-project-java-jpms
module: https://github.com/eugenp/tutorials/tree/master/maven-modules/multimodulemavenproject

**Describe the Issue**
unable to build the project by `mvn clean compile`, errors raised:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project maven-userdaomodule: Compilation failure
[ERROR] /home/baeldung/maven-modules/multimodulemavenproject/maven-userdaomodule/src/main/java/module-info.java:[1,1] modules are not supported in -source 8
[ERROR]   (use -source 9 or higher to enable modules)
```

**To Reproduce**
```
git clone git@github.com:eugenp/tutorials.git
cd tutorials/maven-modules/multimodulemavenproject
mvn clean compile
```

**Environment (please complete the following information):**
openjdk-17
maven 3.6.3

**Comment by JavaSoftwareEntwickler** [comment]
I just made pull request for the fix. 
[](https://github.com/eugenp/tutorials/pull/16311)

![fix](https://github.com/eugenp/tutorials/assets/88802441/ecdd20b0-67c3-4e8d-a7e6-edb2327ded1c)
