### ISSUE TITLE
[ISSUE] Wrong testcase

### ISSUE THREAD

**Issue by mashirro** [eugenp/tutorials#16336]
**Article and Module Links**
https://www.baeldung.com/java-semaphore

**Describe the Issue**
in Section 4：Semaphore vs. Mutex。 test whenMutexAndMultipleThreads_thenBlocked and givenMutexAndMultipleThreads_ThenDelay_thenCorrectCount

assertTrue(counter.hasQueuedThreads());  occurs java.lang.AssertionError。

**Environment (please complete the following information):**
- Version 17

**Comment by apeterlic** [comment]
Hey @mashirro,

Thank you for the feedback. Have you made any custom modifications in the code?

Regards,
Team.

**Comment by apeterlic** [comment]
Closed due to lack of activity.
