### ISSUE TITLE
No plugin found for prefix "cargo:run" both on GIT CMD and Eclipse

### ISSUE THREAD

**Issue by MacDax** [eugenp/tutorials#1638]
INFO] um-client .......................................... SKIPPED
[INFO] um-webapp .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.759 s
[INFO] Finished at: 2017-04-10T14:07:15-07:00
[INFO] Final Memory: 22M/232M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'cargo' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\sonal\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]

**Comment by eugenp** [comment]
Hey @MacDax  - what exactly are you running?
Let me know and I'll try to reproduce it on my end. 
Cheers, 
Eugen.

**Comment by eugenp** [comment]
Cool - closing this one, but feel free to re-open it if you're still running into problems with it. 
Thanks, 
Eugen.
