### ISSUE TITLE
[ISSUE] Project spring-boot-jersey is not exposing any endpoint

### ISSUE THREAD

**Issue by ahmadshahwan** [eugenp/tutorials#16695]
**Article and Module Links**
[A link to the affected module.](https://github.com/eugenp/tutorials/tree/master/spring-boot-modules/spring-boot-mvc-jersey/spring-boot-jersey)

**Describe the Issue**
This module is supposed to expose an endpoint on /hello/{name}. It doesn't.

**To Reproduce**
1. Open a terminal.
2. Change directory to 'spring-boot-modules/spring-boot-mvc-jersey/spring-boot-jersey'
3. Run 'mvn spring-boot:run'
4. Browse to "http://localhost:8080/hello/test"
5. See error "HTTP Status 404 – Not Found"

**Expected Behavior**
A message saying "Hello, test"

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows
- Browser Chrome

**Comment by apeterlic** [comment]
Hi @ahmadshahwan,

Thanks for the feedback. We'll look into this. This issue will remain open until then.

Article link: https://www.baeldung.com/rest-api-jax-rs-vs-spring

Cheers,
Team

**Comment by s4ravanank** [comment]
Added the Fix for this and Raised the PR as well. 
https://github.com/eugenp/tutorials/pull/17133

**Comment by ahmadshahwan** [comment]
I had previously provided a [fix](https://github.com/eugenp/tutorials/pull/16696) that unfortunately went unnoticed!

**Comment by lor6** [comment]
@ahmadshahwan The PR is merged so I will close here.

Thanks again.

**Comment by ahmadshahwan** [comment]
> @ahmadshahwan The PR is merged so I will close here.
> 
> Thanks again.

Perfect. Thank you.
