### ISSUE TITLE
[QUERY] Volatile Example

### ISSUE THREAD

**Issue by DivyaSaravanan** [eugenp/tutorials#16722]
**Article and Module Links**
[Guide to the Volatile Keyword in Java.](https://www.baeldung.com/java-volatile)

**Describe the Issue**

The volatile example provided works fine, even without adding volatile keyword.

https://github.com/eugenp/tutorials/blob/master/core-java-modules/core-java-concurrency-simple/src/main/java/com/baeldung/concurrent/volatilekeyword/TaskRunner.java#L6

**To Reproduce**

- [Go to Task Runner](https://github.com/eugenp/tutorials/blob/master/core-java-modules/core-java-concurrency-simple/src/main/java/com/baeldung/concurrent/volatilekeyword/TaskRunner.java#L6)

- Remove the Volatile keyword next to the field ready.

- Execute the code, still, the code works fine.

**Expected Behavior**
If the volatile keyword is not present, ideally the reader thread and main thread would have local copies of the ready variable, and the while loop would not exit.

Does the above vary in cases, and not always expected?

**Screenshots**

**Environment (please complete the following information):**
- OS: [e.g. Windows]

**Additional Context**
Add any other context about the issue here.

**Comment by maibin** [comment]
The article has been updated to discuss why it sometimes works without the volatile keyword (section 6, to be published at the end of December)
