### ISSUE TITLE
Whats the use of FieldCallback class in Project spring-data-mongodb

### ISSUE THREAD

**Issue by arkaprovo** [eugenp/tutorials#1716]
I was looking into **spring-data-mongodb** Project. Everything looks great but I don't understand the usage of **`FieldCallback`** class. would someone please explain

**Comment by eugenp** [comment]
Hey @arkaprovo - FieldCallback is simply an interface that you can implement to have your implement get invoked on all fields. 
In the article, it's simply used to check if any of these fields are annotated with @Id
Hope that clears things up. 
Cheers, 
Eugen.

**Comment by arkaprovo** [comment]
Thanks a ton.its clear to me now
