### ISSUE TITLE
[ISSUE] The article Introduction to Open Liberty and it's app are outdated

### ISSUE THREAD

**Issue by gkwan-ibm** [eugenp/tutorials#17267]
**Article and Module Links**
- article: https://www.baeldung.com/java-open-liberty
- module: https://github.com/eugenp/tutorials/tree/master/microservices-modules/open-liberty

**Describe the Issue**
The article content and the app are outdated. It uses JEE 8, MP3.2, Liberty 20.0.0.1 (it was 4 years ago), and old plugins/dependencies. 

**Expected Behavior**
To let developers to learn and use the latest technologies, it should be updated to use latest versions of them, such as JEE10, MP6.1. Also, no need to specify Liberty version.

**Screenshots**
- n.a.

**Environment (please complete the following information):**
- OS: all
- Browser: all
- ~~Version [e.g. 22]~~

**Additional Context**
- n.a.

**Comment by gkwan-ibm** [comment]
hi, @SmartyAnsh and @eric-martin, fyi

**Comment by lor6** [comment]
Hi @gkwan-ibm,

Thanks for the feedback here - that's always super helpful.
We do naturally keep everything updated, but, as you can imagine, in some cases, we also have to prioritize some updates over others.
This looks to be one that won't have high priority.
We now have a note internally on it - closing this issue here.

Thanks,
Team

**Comment by lauracowen** [comment]
Hi, we're willing to help with the updates, if that makes any difference? We didn't want to just submit a PR because the article would need to be updated too.

**Comment by gkwan-ibm** [comment]
hi @SmartyAnsh and @eric-martin (cc @lor6)

If we provide the app update, would you mind to update the article? Even work if you can point us how to update the article. Thanks

**Comment by gkwan-ibm** [comment]
hi @SmartyAnsh and @eric-martin (cc @lor6)

If we provide the app update, would you mind to update the article? Even work if you can point us how to update the article. Thanks
