### ISSUE TITLE
[ISSUE] Escaping double quotes in code snippets is not working

### ISSUE THREAD

**Issue by etrandafir93** [eugenp/tutorials#17292]
**Article and Module Links**
https://www.baeldung.com/jackson-deserialize-json-unknown-properties

**Describe the Issue**
Escaping double quotes for  json String is not rendered properly in wordpress

**Screenshots**
![image](https://github.com/user-attachments/assets/f81d220a-60da-4023-8e53-e31ad7bae41a)

**Expected Behavior**

**Environment (please complete the following information):**
- OS: Windows
- Browser: Chrome Version 127.0.6533.100 (Official Build) (64-bit)

**Comment by apeterlic** [comment]
Hi @etrandafir93,

Thanks for the feedback. We've updated the article and fixed this. Closing here.

Cheers,
Ana
