### ISSUE TITLE
[ISSUE] Wrong example code in https://www.baeldung.com/java-completablefuture

### ISSUE THREAD

**Issue by lovelock** [eugenp/tutorials#17358]
**Article and Module Links**
https://www.baeldung.com/java-completablefuture

**Describe the Issue**
```java
CompletableFuture<String> completableFuture 
  = CompletableFuture.supplyAsync(() -> "Hello")
    .thenCombine(CompletableFuture.supplyAsync(
      () -> " World"), (s1, s2) -> s1 + s2));
```
There should not be the last close parentheses. 

**Expected Behavior**
```java
CompletableFuture<String> completableFuture 
  = CompletableFuture.supplyAsync(() -> "Hello")
    .thenCombine(CompletableFuture.supplyAsync(
      () -> " World"), (s1, s2) -> s1 + s2);
```

**Screenshots**

<img width="962" alt="image" src="https://github.com/user-attachments/assets/ea561c6a-e2a5-41ce-a0de-291c96744092">

**Comment by ulisseslima** [comment]
Hey, @lovelock.

Thanks for the feedback. We've updated the article to fix this.

Cheers,
Team
