### ISSUE TITLE
duplicate arttifact

### ISSUE THREAD

**Issue by clembo590** [eugenp/tutorials#17719]
in `video-tutorials/jackson-annotations` you have a module:
- `com.baeldung:jackson-annotations:1.0.0-SNAPSHOT`

in `jackson-modules/jackson-annotations` you have a module:
- `com.baeldung:jackson-annotations:0.0.1-SNAPSHOT`

it is very strange to have same groupId and artificactId in two different places...
`com.baeldung:jackson-annotations` is not used anywhere as a dependency anyway --> I suggest to rename one of the modules

**Comment by lor6** [comment]
The module video-tutorials/jackson-annotations has been renamed to jackson-annotations-video.
