### ISSUE TITLE
OpenID Connect with login of office 365

### ISSUE THREAD

**Issue by Gil9091e10** [eugenp/tutorials#1779]
I trying connect my app with loggin of Office 365, based in you project. but i catch exception **error="access_denied", error_description="Access token denied."** 

You can tell me why get exception.

**Comment by eugenp** [comment]
Are you working on any of the modules in this project? I don't remember a module with Office 365 integration?

**Comment by Gil9091e10** [comment]
I was trying implement a connection with office 365 based in your example but when trying acceded the token returned for office when connection is success, I have this error error="access_denied", error_description="Access token denied."

Which is the best mean of make this with OpenID Connect using login Office365?

**Comment by eugenp** [comment]
Sure, that's interesting, but since there's no tutorial or module that's doing that - I'm assuming you're working on your own codebase, not on the tutorials project here. 
With that in mind - since this isn't really an issue related to this project, I'm closing it. 
Cheers, 
Eugen.
