### ISSUE TITLE
maybe needed @ColumnTransformer(write = "?::jsonb")

### ISSUE THREAD

**Issue by vladbakumenko** [eugenp/tutorials#17797]
when I tried to use this example of working with hibernate 5 and jsonb, then when saving, an error was returned:

"ERROR: column "customer_attributes" is of type json but expression is of type character varying"

after that I found this example on [stackoverflow](https://stackoverflow.com/questions/65478350/error-column-is-of-type-json-but-expression-is-of-type-character-varying-in-hib) where the annotation @ColumnTransformer(write = "?::jsonb") is added to the responses and everything worked

https://github.com/eugenp/tutorials/blob/b95696df12b39d3c69689839ba3295f426adc599/persistence-modules/hibernate5/src/main/java/com/baeldung/hibernate/persistjson/Customer.java#L28

**Comment by ulisseslima** [comment]
Hey, @vladbakumenko. Thanks for the feedback.

Assuming this is the article: https://www.baeldung.com/hibernate-persist-json-object

Since `jsonb` is specific to PostgreSQL, we include a more universal approach in section 5.

**Comment by vladbakumenko** [comment]
yes, but in section 5 there is no such annotation @ColumnTransformer(write = "?::jsonb"). 
Or am I misunderstanding something?
