### ISSUE TITLE
[ISSUE] aws-rest Missing Main Method

### ISSUE THREAD

**Issue by ShadowM0nkey** [eugenp/tutorials#17888]
https://www.baeldung.com/java-aws-download-file-s3-url

Project builds okay but when you try to run it will get "no main manifest attribute"

1. Build aws-rest project
2. Run it using java -jar or from the IDE
3. See error

**Expected Behavior**
Code should run

**Environment (please complete the following information):**
- OS: Win 10
- Version: JDK 22

**Comment by ulisseslima** [comment]
Hey, @ShadowM0nkey.

This project contains no Main class. 

You can inspect the unit tests [here](https://github.com/eugenp/tutorials/tree/master/aws-modules/aws-rest/src/test/java/com/baeldung/aws/rest/s3/download) if you'd like to experiment with the code or [create](https://www.baeldung.com/spring-boot-start#application-configuration) a Main class.

**Comment by ShadowM0nkey** [comment]
Personally, I feel some changes are needed here. The code associated with the article ("Download File from S3 Given a URL") is **non-executable**. Suggestions:
1. Change title of article to "Unit Testing S3 Download App"
2. Add main method to make it executable
3. Add a comment to the article saying that this code is non-executable as-is
