### ISSUE TITLE
Spring security WebSecurityConfigurers must be unique

### ISSUE THREAD

**Issue by CoolR7** [eugenp/tutorials#1882]
Hi Eugen

Could you please look in the below error message Which I am getting while running this project

web - 2017-05-19 20:15:18,861 [localhost-startStop-1] WARN  o.s.w.c.s.AnnotationConfigWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 100 was already used on org.baeldung.spring.RedirectionSecurityConfig$$EnhancerBySpringCGLIB$$3fb84e15@7c4fdbf3, so it cannot be used on org.baeldung.spring.SecSecurityConfig$$EnhancerBySpringCGLIB$$8af3b19a@5a7cee26 too.
web - 2017-05-19 20:15:18,874 [localhost-startStop-1] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 100 was already used on org.baeldung.spring.RedirectionSecurityConfig$$EnhancerBySpringCGLIB$$3fb84e15@7c4fdbf3, so it cannot be used on org.baeldung.spring.SecSecurityConfig$$EnhancerBySpringCGLIB$$8af3b19a@5a7cee26 too.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)

**Comment by eugenp** [comment]
Hey @Doha2012 - can you please have a quick look at this issue and see if you can reproduce it? If you can, let's open a JIRA to handle it. 
Cheers, 
Eugne.

**Comment by lor6** [comment]
Only one WebSecurityConfigurerAdapter should be used at a time. If you want to use multiple ones in the same configuration, you have to add the @Order annotation on at least one of them to specify the order in which they should be considered. Spring Security adds a default order if none is specified, and these conflict. See this article: http://www.baeldung.com/spring-security-multiple-entry-points

**Comment by sagheersyed** [comment]
thanks @lor6 you solved my problem.
