### ISSUE TITLE
guide-to-uuid-in-java link

### ISSUE THREAD

**Issue by MrHanachoo** [eugenp/tutorials#1945]
The guide-to-uuid-in-java link in [core-java/README.md](https://github.com/eugenp/tutorials/tree/master/core-java/README.md) needs to be fixed, as well as the related blog is not found.
PS: IMHO, I think that this is done on purpose, so the blogger can easily identify not-yet-created-blogs for lately pushed tutos. In all cases, the goal of this opened issue is to clarify this point.
Thanks!

**Comment by pivovarit** [comment]
Generally, links to future posts appear in the repo before posts get published and for a few hours links might not work. But this case was obviously a mistake :)

Thanks, closing.
