### ISSUE TITLE
Deploying jar - gfsh 9.0.1

### ISSUE THREAD

**Issue by vignesh02** [eugenp/tutorials#2066]
Used maven clean install package and tried to deploy in gfsh was getting below error

Member  | Deployed JAR | Deployed JAR Location
------- | ------------ | -----------------------------------------------------------------------------------------
server1 |              | ERROR: java.lang.NoClassDefFoundError: org/springframework/data/repository/CrudRepository
server2 |              | ERROR: java.lang.NoClassDefFoundError: org/springframework/data/repository/CrudRepository

**Comment by eugenp** [comment]
Hey @vignesh02 - can you clear up what this is about?
What module are you trying to run exactly?

**Comment by eugenp** [comment]
Cool, I'm closing this thread, but of course, if you have any questions, just ping me here
