### ISSUE TITLE
Jackson maven module: Error "LocalDateTime cannot be resolved to a type"

### ISSUE THREAD

**Issue by pashtika** [eugenp/tutorials#216]
I think, you should select Java version 1.8 in the pom.xml instead of 1.7. I see following error are coming

Multiple markers at this line
	- The type CustomLocalDateTimeSerializer must implement the inherited abstract 
	 method JsonSerializer<LocalDateTime>.serialize(LocalDateTime, JsonGenerator, 
	 SerializerProvider)
	- LocalDateTime cannot be resolved to a type

**Comment by eugenp** [comment]
All projects have now been upgraded to Java 8 - thanks for the feedback. Cheers, 
Eugen.
