### ISSUE TITLE
Spring OpenID Connect Example

### ISSUE THREAD

**Issue by munilvc** [eugenp/tutorials#2279]
Hello there! First, thank you very much for the example: http://www.baeldung.com/spring-security-openid-connect

Since the comments in the page are closed now, I have a question about adding extra parameters in the Authentication Request.  For example if we need to support the JWT "request" parameter like in the sample provided in the specification:  https://tools.ietf.org/html/rfc7636  (Please see section: 6.1.1.  Request using the "request" Request Parameter)

Also if we want to add the code_challenge parameter.

Do you know if Spring implementation currently support that?  Any tip on how you would implement this?  I am thinking that maybe I need to extend OAuth2ProtectedResourceDetails but probably will need to touch other places too.

Thank you very much!

**Comment by eugenp** [comment]
I'm glad the project is helpful. 
I think a StackOverflow question would be a better way to go for two reasons. First - I'm not actively looking at OpenID implementation right now, so I'll have to do some research to see if that's supported. And second - there's a significant rewrite going on right now in Spring Security, so it's very likely that the implementation will change - and relatively soon. 
Hope that helps point you in the right direction. Cheers, 
Eugen.
