### ISSUE TITLE
Feign getting exception as Error: Could not find or load main class org.mockito.asm.util.ASMifierClassVisitor

### ISSUE THREAD

**Issue by ShilpaVKulkarni** [eugenp/tutorials#2281]
I am trying to run feign-client project, there am getting following exception:
Error: Could not find or load main class org.mockito.asm.util.ASMifierClassVisitor

Can any one provide solution in this.
Thanks & Regards
Shilpa Kulkarni

**Comment by eugenp** [comment]
Hey Shilpa - when you say "run the project" - what do you mean exactly? 
Are you seeing that error when you're building? Or running the test? Or in your local IDE?

Cheers, 
Eugen.

**Comment by eugenp** [comment]
Cool, I'm closing this thread, but of course, if you have any questions, just ping me here
