### ISSUE TITLE
Session timeout is too short on spring-security-login-and-registration

### ISSUE THREAD

**Issue by javenosa** [eugenp/tutorials#229]
When I use the login form the session timeout is too short, even if I change over de web.xml with something like this:

    <session-config>
        <session-timeout>20</session-timeout>
    </session-config>

I run the sample code over netbeans and tomcat 8.0.15.0
Do you have any idea about this issue?

Thanks

**Comment by dynamoDB** [comment]
when I modify web.xml from 
<session-config>
    <session-timeout>8</session-timeout>
</session-config>
to
<session-config>
    <session-timeout>30</session-timeout>
</session-config>
it is work for me.

If you want to use spring security in you web project, I hope this URL will help you:
     http://docs.spring.io/spring-security/site/docs/3.0.x/reference/ns-config.html
Good Luck

**Comment by dynamoDB** [comment]
when I modify web.xml session-timeout param 8 to 30 it is work for me.

If you want to use spring security in you web project, I hope this URL will help you:
     http://docs.spring.io/spring-security/site/docs/3.0.x/reference/ns-config.html
Good Luck

**Comment by javenosa** [comment]
Sorry but I cannot say the same. In any case when I change the timeout over the web.xml the timeout still are 30 seconds.

Any idea to fix this? 

Thanks

**Comment by javenosa** [comment]
Here is the problem:

On the class MySimpleUrlAuthenticationSuccessHandler.

    public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws IOException {
        handle(request, response, authentication);
        HttpSession session = request.getSession(false);
        if (session != null) {
            session.setMaxInactiveInterval(30);
        }
        clearAuthenticationAttributes(request);
    }

The session.setMaxInactiveInterval(30) is expressed in seconds, not in minutes like the web.xml.

**Comment by eugenp** [comment]
Hey @javenosa - nice catch. It's fixed. Thanks, 
Eugen.

**Comment by shrirange** [comment]
@eugenp What is fixed here. Spring Security or Tomcat. What should do to get the fix ?

**Comment by eugenp** [comment]
Well @shrirange - this was about 3 years ago, so as you can imagine - I have no idea :)
