### ISSUE TITLE
No target folders created when building the maven project(s)

### ISSUE THREAD

**Issue by mcocosila** [eugenp/tutorials#2414]
Hi,

I have built the tutorials multi-module maven project using "mvn clean install". No errors reported but no target folders are created in sub-modules. I spent quite a bit of time to figure out why to no avail. I'm not a maven newbie.

Could you please give me a hint?

Thanks,
mircea

**Comment by mcocosila** [comment]
Any update on this one? Thanks.

**Comment by eugenp** [comment]
Hey Mircea - sorry about the late reply here. 
So - /target folders should indeed be created when you do a simple `mvn clean install`. 
Can you give that a try and let me know if you see the target directories being created after the build?

Cheers, 
Eugen.

**Comment by eugenp** [comment]
Cool, I'm closing this thread, but of course, if you have any questions, just ping me here

**Comment by pushprajsingh05** [comment]
> Hey Mircea - sorry about the late reply here.
> So - /target folders should indeed be created when you do a simple `mvn clean install`.
> Can you give that a try and let me know if you see the target directories being created after the build?
> 
> Cheers,
> Eugen.

It worked for me.

**Comment by AndyGee** [comment]
Make sure <packaging> is either not defined (defaults to <packaging>jar</packaging>) or not set to pom (<packaging>pom</packaging>) in your pom.xml

**Comment by vmallik59** [comment]
Is it possible to generate target folder with *.pom ?

**Comment by eugenp** [comment]
Hey @vmallik59 - that's a great question, but unfortunately beyond the scope of this thread here. StackOverflow might be the better way to go with it. 

Cheers, 
Eugen.
