### ISSUE TITLE
org.baeldung.persistence.model.QMyUser not found

### ISSUE THREAD

**Issue by akaigoro** [eugenp/tutorials#2431]
Class org.baeldung.persistence.model.QMyUser, imported in few source texts, cannot be found.

Last commit: 12 Aug 2017 "BAEL-1035 Introduction to Eclipse Collections (#2425)"

**Comment by eugenp** [comment]
Hey @akaigoro - this one seems to not be reproducible. If you're still running into it, feel free to reopening it of course.

**Comment by SamuelDourado** [comment]
Hi @eugenp 
What is this class ?
