### ISSUE TITLE
convert List<User> users to Page<User> in spring data mongo Pagination

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#248]
I am really struggling to convert `List<User> users` to `Page<User>` in spring data mongo? Note Page is an API from `org.springframework.data.domain.Page`;

I am using `Pagination` of Spring Data Mongo, so I need to sent `Page<User>` and not the `List<User>`. Please help me.

**Comment by eugenp** [comment]
The easiest way to do that is to simply create a page out of the existing list: 
`new PageImpl<Foo>(listOfFoos, new PageRequest(page, size, sort), listOfFoos.size())`
Hope it helps. Cheers, 
Eugen.

**Comment by pashtika** [comment]
Thank you. You're just a great !!

**Comment by eugenp** [comment]
So, the pagination is driven by the client (in our case, the UI) - not by the API. In the API, both the size and the page are parameters, so whatever the client asks for, that's what the API will return. 
If you need these values, you need to make sure that's how the UI sends out the HTTP request.

**Comment by pashtika** [comment]
Right, thank you. But API also provide the way to have defaults if values don't come from UI. so, I was looking to make those default values as configurable ?

**Comment by eugenp** [comment]
If you're thinking of `findAllRedirectToPagination` - yes, these are hardcoded. The way to make open that up is to: 
- add a new properties file called `web.properties`
- import that in via a `@PropertySource` in `WebConfig`
- add the new property there: `web.pagination.size`
- inject that either via the Environment or just with `@Value` in the abstract controller
- use it to replace the hard-coded values

**Comment by pashtika** [comment]
Thanks for idea. I will try for it, but could you please provide sudo code ?

**Comment by eugenp** [comment]
Let's get these changes into a branch and I'll have a look. Let me know what that branch is.

**Comment by pashtika** [comment]
I was facing an issue in developing Pagination through UI (Angular JS). (I am doing some customization), AJ API pagination starts from Index=1 by default, so we need mechanism if we get page=1, then Pageable should start from page=0 to get data from DB and size=10 as fixed. So I research we can do it using following config, I did refere link - . I am still researching for how effectively we can unit test in junit?

<html>
<div style="border-left: #0066cc ; padding-left: 6px">
    <a href="http://stackoverflow.com/questions/19756786/spring-pageableargumentresolver-deprecated-how-to-use-pageablehandlermethodargu" target="blank"><h4 style="margin:5px">This link</h4></a>
</div>
</html>


`<mvc:argument-resolvers>
            <bean class="org.springframework.data.web.PageableHandlerMethodArgumentResolver" >
                <property name="oneIndexedParameters" value="true"></property>
                <property name="pageParameterName" value="page"></property>
                <property name="sizeParameterName" value="size"></property>
                <property name="fallbackPageable">
                    <bean class="org.springframework.data.domain.PageRequest">
                        <constructor-arg name="page" value="1" />
                        <constructor-arg name="size" value="10" />
                    </bean>
                </property>
            </bean>
        </mvc:argument-resolvers>`

**Comment by eugenp** [comment]
A couple of things here. First - why not use Java config?
Second - yes, you can configure that just fine via the defaults. Testing it can be done from outside the API, with a live test. That should enable you to quite easily test these defaults. You can of course write a simple integration test, or Spring MVC specific tests as well - to get to the same result here. 
Hope that helps. Cheers, 
Eugen.

**Comment by pashtika** [comment]
Yes, thank you...

**Comment by YogitaRana** [comment]
I want to do pagination in mybatis using the default values of pagination not by giving value for the page size. Is there any approach for it ....and also how can I convert List<T> into Page<T> using mybatis.Kindly guide me for the same

**Comment by eugenp** [comment]
So, for this kind of technical question not strictly related to any article, the best way to ask if over on StackOverflow - then email me the link and I'll have a look.

**Comment by omm7029** [comment]
Hi eugenp, Please check my code and respose. Problem is _embedded is not coming in response. Please help me how to convert content to _embedded

@RequestMapping(value = "/technicalSearch", method = RequestMethod.POST, consumes="application/json")
HttpEntity<PagedResources<SalesOrder>>  persons(Pageable pageable, 
	    PagedResourcesAssembler assembler, @RequestBody List<TechnicalSearchPojo> techSearchParam) {
		List<SalesOrder> result=repo.searchByCriteria(techSearchParam);
		Page<SalesOrder> pg=new PageImpl<SalesOrder>(result, new PageRequest(0, 50),result.size());
		ResponseEntity<PagedResources<SalesOrder>> pg1=new ResponseEntity<>(assembler.toResource(pg), HttpStatus.OK);
		return pg1;

==========
Response==

{
  "links" : [ {
    "rel" : "self",
    "href" : "http://localhost:8090/quote_ws/technicalSearch?page=0&size=50"
  } ],
  "content" : [ {
    "createdBy" : "vivek.rathor@ncs-india.com",
    "createdAt" : "2018-01-19T10:37:12.276+0000"
  
  } ],
  "page" : {
    "size" : 50,
    "totalElements" : 4,
    "totalPages" : 1,
    "number" : 0
  }
}

**Comment by eugenp** [comment]
Hey @omm7029 - this looks like an interesting question, but it's also unrelated to any of the modules here, so you'll have to go to StackOverflow with this one. 
Feel free to email me the link, in case I get to it before the community is able to. 
Cheers, 
Eugen.

**Comment by GuruprasadAN** [comment]
to convert from List to Pagination, i used the solution what you guys discussed but its not working, its returning all the data

**Comment by hendisantika** [comment]
How about to convert from Pagination to List?

from Page<User> into List<User>?

Thanks

**Comment by gssitrainee** [comment]
I tried the suggestion above but it seems that the totalElements, totalPages values are wrong.
It displays all the results... `numberOfElements` value is not changing... while `totalElements` is varying.

lets say the number of results is 7.

current page is 1 and size is 5.. 
	"first": true,
	"last": false,
	"number": 0,
	"numberOfElements": 7,
	"size": 5,
	"totalElements": 7,
	"totalPages": 2

current page is 2 and size is 5..
	"first": false,
	"last": false,
	"number": 1,
	"numberOfElements": 7,
	"size": 5,
	"totalElements": 12,
	"totalPages": 3

current page is 3 and size is 5..
	"first": false,
	"last": false,
	"number": 2,
	"numberOfElements": 7,
	"size": 5,
	"totalElements": 17,
	"totalPages": 4

current page is 4 and size is 5..
	"first": false,
	"last": false,
	"number": 3,
	"numberOfElements": 7,
	"size": 5,
	"totalElements": 22,
	"totalPages": 5

It is really acting weird. below is the code used

```
    public Page<Ticket> getOwnedTicketList(Pageable pageable) throws IOException {
        User user = getCurrentUser();
        List<Ticket> tickets = m_ticketRepository.getTicketsOwned(user);
        Page<Ticket> page = new PageImpl<>(tickets,
                new PageRequest(pageable.getPageNumber(), pageable.getPageSize(), pageable.getSort()),
                tickets.size());
        return page;
    }
```

Thanks

**Comment by SelimHorri** [comment]
This is a very fruitful discussion, Thank u all guys..
