### ISSUE TITLE
How to get Page<> count? Please refer below screen shot.

### ISSUE THREAD

**Issue by pashtika** [eugenp/tutorials#251]
How we can get value 77 of screen shot into variable?

![page](https://cloud.githubusercontent.com/assets/8208031/9921581/ab42d4b6-5cfc-11e5-9cda-14ba9fb29f06.png)

**Comment by eugenp** [comment]
If you're asking how to extract that out of this wrapper - `getTotalElements` is the API you're looking for.

**Comment by pashtika** [comment]
Perfect, Thanks worked. I did some customization in my implementation class... Like I am getting data in Page<User> from DB, but method is developed to return Page<UserDetails>, because I need to send UserDetailsResource to AJ.

**Comment by eugenp** [comment]
That sounds interesting. Have you ever thought about writing? I recently opened up the site for writers - but I've not really shared the "Write for Baeldung" page around a lot. Here's [the page](http://www.baeldung.com/contribution-guidelines) if it sounds like something you want to explore. Cheers, 
Eugen.
