### ISSUE TITLE
Eclipse artifacts

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#254]
Suggestion - I see all projects has ".classpath",".project", ".settings" and ".springBeans" etc.., files are present, but when we're importing it to STS / Eclipse it some times gives compilation error. Because since we may've different class-path setting that yours. so to fixed this
* You could remove this by doing: mvn clean and mvn eclipse:clean so that it wont appear in your commit. 
* You need to manually remove this files as these file should never get committed as a good practice.

Please let me know your suggestions on this. Thank you..

**Comment by eugenp** [comment]
Thanks for the suggestion - I've been considering doing this. I wouldn't necessarily say it's good practice - it depends on some circumstances, but overall I agree - especially if it's causing problems. What is the actual compilation error you're seeing? 
Cheers, 
Eugen.
