### ISSUE TITLE
Do you've any idea why CORS filters blocks the AuthenticationEntryPoint to execute?

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#255]
Do you've any idea why CORS filters blocking the AuthenticationEntryPoint to execute? I developed "CORSFilter.java" from link- http://stackoverflow.com/questions/32319396/cors-with-spring-boot-and-angularjs-not-working, but its not calling AuthenticationEntryPoint, though I've given it in 

`<security:http
            use-expressions="true"     auto-config="false"      create-session="stateless"
            disable-url-rewriting="true"     entry-point-ref="unauthorizedEntryPoint"
            authentication-manager-ref="authenticationManager">`

`<bean id="unauthorizedEntryPoint" class="com.test.common.checks.UnauthorizedEntryPoint" />`

Or Can you help us on http://stackoverflow.com/questions/32725249/cors-filter-issue-for-authentrypoint?

**Comment by eugenp** [comment]
I had a look at the SO question - but without a working sample project reproducing the issue, it's hard to tell. I'd start by just debugging through your CORS filter when the request is going through to see exactly what happens. 
Also - here's a very liberal implementation of that simple filter (the main method): 
```
