### ISSUE TITLE
DefaultHttpClient is deprecated, please use API HttpClient instead.

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#261]
This is regarding the project name "spring-security-rest-digest-Auth". `ClientPreemptiveDigestAuthentication` uses the `"DefaultHttpClient"` which is a deprecated method, instead this new API has come `HttpClient client = HttpClientBuilder. create (). build ();` 

Could you please correct respective code? Thank you.

**Comment by eugenp** [comment]
This is definitely on the content calendar list - I'll update this issue when it's done. 
Cheers, 
Eugen.

**Comment by eugenp** [comment]
This should be sorted out now. Cheers, 
Eugen.
