### ISSUE TITLE
How to convert Page to Pageable in Java?

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#266]
```List<Person> expected = new ArrayList<Person>();``` ==> Here I've 20 records and would like to convert into ```Pageable``` interface
```Page expectedPage = new PageImpl(expected);
Pageable p =``` ???? What is the correct way ?

I need to return with Pages (Let's say 20 records, so 2 pages, each Page should show 10 records)
return new ```PageImpl<Person>(expected ,expectedPage , expected .size());```

Could you please guide me ?

**Comment by eugenp** [comment]
Using the constructor of the `PageImpl` is perfectly OK, yes - that's how constructing the page is usually done (if you're not using auto-generated methods).
