### ISSUE TITLE
How we can run this code?

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#2673]
How we can run this code?

Could you please update README so that the beginner like can understand the issue?

**Comment by eugenp** [comment]
Run what code?

**Comment by Ssunnyy** [comment]
I have a problem, the previous project did not use Spring data couchbase, and there is no _class: property in doument. Now, how do I use the Spring data couchbase framework to query the data in the previous database?. I tried findByTitle and other property query methods to return null, but using findById to check the data, I need help, I hope you can get your advice.
I can't get through to you. This is my email address, sm812a@gmail.com. I want to keep in touch with you.
