### ISSUE TITLE
how do I use the Spring data couchbase framework to query the data in the previous database?

### ISSUE THREAD

**Issue by Ssunnyy** [eugenp/tutorials#2687]
I have a problem, the previous project did not use Spring data couchbase, and there is no _class: property in doument. Now, how do I use the Spring data couchbase framework to query the data in the previous database?. I tried findByTitle and other property query methods to return null, but using findById to check the data, I need help, I hope you can get your advice.
I can't get through to you. This is my email address, sm812a@gmail.com. I want to keep in touch with you.

**Comment by eugenp** [comment]
Hey @Ssunnyy - two notes/questions here. 
First, when you say you can't get through to me, what do you mean exactly? I don't see any email from you. 
Second, for this kind of technical question, the best way to ask if over on StackOverflow - then email me the link and I'll have a look. 
Cheers, 
Eugen.
