### ISSUE TITLE
spring-security-openid tutorial -  I don't see signature validation... possible security hole?

### ISSUE THREAD

**Issue by Mark2009** [eugenp/tutorials#2712]
This example has been pretty helpful.  So thanks, however, I think there might be a big security hole, unless there's some signature validation going on else where that I'm not seeing..

I was looking at this line in particular:

    final Jwt tokenDecoded = JwtHelper.decode(idToken);

I believe that needs to be decodeAndVerify(idToken,verifier)

The Jwt Token is passed from the authentication provider through the browser to the application, without signature validation, anyone could forge or modify a Jwt token and the application would be none the wiser...

I am using this to help with Azure and OIDC, so maybe the pattern is slightly different with google, but if it is open id connect, then the flow is the same and this is an issue...  unless I'm missing where signature validation is being done.

**Comment by lor6** [comment]
The project and article have been updated.
