### ISSUE TITLE
How to make Jackson marshal an Object that contains an interface with n implementations

### ISSUE THREAD

**Issue by syg6** [eugenp/tutorials#272]
What if you had a class, Stuff, like this:

public class Stuff<t>
Selections<t>
}
... where Selections is an Interface:

public interface Selections<t> {
List<t> getSelected();
}

with 2 implementations:

public class SimpleSelections implements Selections<string> {
private List<string> _selected;

public List<string> getSelected() {
return _selected;
}
}

public class ComplexSelections implements Selections<complexselection> {
private List<complexselection> _selected;

public List<complexselection> getSelected() {
return _selected;
}
}

public class ComplexSelection {
String field1;
String field2;
}

Can Jackson automagically detect which class to marshall, depending on the json sent to it?

**Comment by eugenp** [comment]
Hey @syg6 - a simple JUnit test going over this description would do wonders :)
