### ISSUE TITLE
mongo configuration for applicationContext in cluster mode

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#284]
My mongodb is clustered database (load balancing between two servers i.e) dev-1 and dev2)
Spring MVC application Context.xml use following 

```<mongo id="mongo" host="${mongo.db.host}" port="${mongo.db.port}"/>```

```
mongo.db.host=dev-1
mongo.db.port=27017
```

What configuration I need to use so that my application points to both databases (dev-1 and dev-2)? Please help provide pointers/answers?

**Comment by eugenp** [comment]
While I haven't explored the clustering implementation in MongoDB - you usually don't have to point to both nodes. As a client, you only point to a master node and it's on the MongoDB configuration side where you configure the semantics of the cluster. 
From the point of view of the client, you're talking to a single DB instance.
