### ISSUE TITLE
tutorials/mesos-marathon/ : Error while execution of dockerise.sh script. 

### ISSUE THREAD

**Issue by speaktoabu** [eugenp/tutorials#2849]
Issue : In tutorials/mesos-marathon/ : Error while execution of dockerise.sh script. 

Error : "flag needs an argument: 'p' in -p"

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.076 s
[INFO] Finished at: 2017-10-23T10:03:34+00:00
[INFO] Final Memory: 30M/72M
[INFO] ------------------------------------------------------------------------
+ ./dockerise.sh
flag needs an argument: 'p' in -p
See 'docker login --help'.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by eugenp** [comment]
Hey @Doha2012 - let's see if this is reproducible on our end. 
Cheers, 
Eugen.

**Comment by eugenp** [comment]
Hey @lor6 - let's see if this one is reproducible on our end. 
Cheers, 
Eugen.

**Comment by lor6** [comment]
Hey @speaktoabu Have you modified the dockerise.sh file with your own username and password?

Cheers.
