### ISSUE TITLE
Spring 5 MVC Matching Is Disabled in Spring 5.0.0.RELEASE

### ISSUE THREAD

**Issue by dgrahn** [eugenp/tutorials#2938]
https://github.com/spring-projects/spring-framework/commit/b1440b681663c4087ca19fdb755598b7c9706c11

**Comment by eugenp** [comment]
Thanks for the note @dgrahn - I'll definitely look into it, as it affects the early plans for one of the new lessons in the course. 
Cheers, 
Eugen.
