### ISSUE TITLE
Completable future article mistake?

### ISSUE THREAD

**Issue by blackduck-joe** [eugenp/tutorials#2939]
I could not figure out how to comment on the article itself for some reason. 

In any event, there is this example:

Future<String> resultFuture = 
  service.scheduleAtFixedRate(callableTask, 100, 450, TimeUnit.MILLISECONDS);

But I do not believe that "scheduleAtFixedRate" has a method to take a callable, only one that take a Runnable.

**Comment by pivovarit** [comment]
Good catch - that should've been a `runnableTask`. Thanks!
