### ISSUE TITLE
Spring security using JWT and LDAP example

### ISSUE THREAD

**Issue by wmfairuz** [eugenp/tutorials#295]
Hi,

Great work on the tutorials! 

As we can see today more and more applications use a full restful API services where API consumers is not necessarily hosted on the same machine as the API backend. I see people use JWT for this matter.

Do you plan to a tutorial on using Spring security with JWT and LDAP? 

Thanks

**Comment by eugenp** [comment]
Hey Fairuz - yes, it's on the content calendar of the site. I'm also doing a live workshop - "Advanced API Security" - that's going to focus on that - I'm going to announce it on the email list at some point. Cheers, 
Eugen.
