### ISSUE TITLE
Do you know how to implement Async in Java 7 ?

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#296]

**Comment by eugenp** [comment]
That's an interesting question. It's also a very broad question - so it doesn't have a single answer. Async in what? Web requests - Servlet 3.1, etc? in Spring - @Async. Jobs? Or something else? 
Let me know more specifically what you have in mind and I might add a writeup to the content calendar of the site. Cheers, 
Eugen.

**Comment by JavaHelper** [comment]
I am looking to developed Async concept in java 7. I've a method which is long running (takes 3-4 mins) to execute it that is developed to get a call from controller. What will happens if many clients starts executing method? Each user has to wait till the 1st user completed it's execution. So its a problematic.

So to overcome this issue, I started reading about async programming in java which is non-blocking, event-driven programming model. This programming model leverages the multiple cores in your system to provide parallelization by using multiple CPU cores to execute the tasks, thus increasing the application's throughput

so far I developed code like below. Could you please suggest if this correct?

```
Future<StudentDetails> StudentDetailsFuture = executor.submit(new Callable<StudentDetails>() {
            public StudentDetails call() {
            	return new StudentDetailsMapper().getStudentDetails(StudentId);
            }
        });
StudentDetails StudentDetails = StudentDetailsFuture.get();
```

**Comment by eugenp** [comment]
So, let me see if I understand your situation here (I'm not sure that I do). You have an API operation that's long-running. And you want to basically notify the client of its completion. 
If that's the case, yes - returning a Future and taking advantage of the Servlet 3.1 spec is a good way to go. 
Hope that helps. Cheers, 
Eugen.
