### ISSUE TITLE
graphiql always returns an error

### ISSUE THREAD

**Issue by candysmurf** [eugenp/tutorials#3073]
The tutorial is great however, on the this URL: http://127.0.0.1:8080/, I can see Graphiql is up with the `TypeError: Failed to fetch` as the default in the response panel. The clicking on the `docs`, it showed `No Schema Available`. If running any query, it showed the same error: `TypeError: Failed to fetch`. How to make it work? Thanks.

**Comment by eugenp** [comment]
Thanks for letting me know @candysmurf  - looking into it.

**Comment by eugenp** [comment]
Hey @candysmurf  - the server should run on port 5050. Someone from the team just tested it and everything works OK on her end. 

Cheers, 
Eugen.
