### ISSUE TITLE
Spring vert.x integration + spring admin

### ISSUE THREAD

**Issue by armdev** [eugenp/tutorials#3093]
Hello,

If you exclude spring-boot-starter-tomcat from dependencies Spring admin does not understand spring boot/vert.x as web application. If you keep tomcat dependency and run vert.x in different port, spring admin get information only from spring boot default port. 
So full integration impossible at the moment.
Problem only with Spring admin, integration between spring cloud nodes fine.
Any idea?

**Comment by armdev** [comment]
Simple project location is https://github.com/armdev/reactive-web , admin understand only tomcat or undertow port . Actually run two port , one vert.x http server, second spring tomcat/undertow server. If you exclude tomcat/undertow, spring boot admin does not receive any information.

**Comment by lor6** [comment]
@armdev I was going to suggest opening an issue with the spring boot admin project, but I see you already did and got an answer :)
