### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JLLeitschuh** [eugenp/tutorials#3097]
Can you include some sort of `License.txt` in the root of this project so that it is immediately obvious what this project is licensed under. Thanks!

**Comment by eugenp** [comment]
That's a good point @JLLeitschuh - it's on my TODO list.

**Comment by JLLeitschuh** [comment]
Can you say what you are planning on using here?

**Comment by eugenp** [comment]
I just set the MIT license on the repo. 
So, we're good to go here. 
Closing.

**Comment by JLLeitschuh** [comment]
Thanks!!
