### ISSUE TITLE
some sub maven modules have wrong parent.relativePath config

### ISSUE THREAD

**Issue by hitme** [eugenp/tutorials#3147]
pom.xml of sub modules like testing should have their parent.relativePath config adjusted, since been moved into separate folders.
e.g.
    <parent>
        <groupId>com.baeldung</groupId>
        <artifactId>parent-modules</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>

**Comment by lor6** [comment]
I see you pushed a commit for this, thanks. Closing.
