### ISSUE TITLE
Extend spring-rest-query-language tutorial with "in" operation

### ISSUE THREAD

**Issue by chrisinmtown** [eugenp/tutorials#3158]
Very very useful tutorial.  May I suggest extending spring-rest-query-language with operation "in" - i.e., test if a value is a member of a set?  I think it would involve extending the specification class's toPredicate() method with code along these lines:

		if (!(criteria.getValue() instanceof List))
			throw new IllegalArgumentException("Not list: " + criteria.getValue());
		List<?> list = (List<?>) criteria.getValue();
		Expression<String> exp = root.<String>get(criteria.getKey());
		return exp.in(list);

**Comment by eugenp** [comment]
Hey @chrisinmtown - I'm glad you enjoyed that article (and series). 
The thing is - there are a number of interesting options we could include in the QL (including an "in" operation), but it would be a lot of work to cover all of them. 
My thinking is that the article shows you a baseline of how to tackle a QL implementation - and then, that can be further extended as needed. 
That being said, you can always write a guest article - if you're working on that :)
Hope that makes sense. 
Cheers, 
Eugen.

**Comment by GuiRitter** [comment]
This is how I did it:

```java
public class DefaultSpecification <T> implements Specification<T> {
    // ...
    @Override
    public Predicate toPredicate(Root<T> root, CriteriaQuery<?> query, CriteriaBuilder builder) {
        switch (criteria.getOperation()) {
            // ...
            case COLLECTION_CONTAINS:
                return builder.isMember(criteria.getValue(), root.get(criteria.getKey()));
            // ...
        }
    }
}
```

And use it like this:

```java
DefaultSpecificationsBuilder<EntityType> builder = new DefaultSpecificationsBuilder<EntityType>();
builder.with(null, "collectionName", "whateverSymbolYouChoose", objectInCollection, null, null);
```

**Comment by eugenp** [comment]
Interesting, thanks for posting this @GuiRitter. 

Cheers, 
Eugen.
