### ISSUE TITLE
Resources are ignored by spring security per default

### ISSUE THREAD

**Issue by CasaSky** [eugenp/tutorials#3209]
My login page can't load resources.

I tried to comment this line  //web.ignoring().antMatchers("/resources/**");
but it still be ignored. I was trying to permit all /resources but same issue.

I don't know how to permit my resources to show my login page properly.

Thanks for your support.

**Comment by lor6** [comment]
@CasaSky  If you're using Spring Boot, any static resources in the /resources folder will be automatically added. If you have a plain Spring MVC project, you have to handle the static resources explicitly, like here: http://www.baeldung.com/spring-mvc-static-resources
