### ISSUE TITLE
Mail Authentication With Valid credentials 

### ISSUE THREAD

**Issue by ashvins1912** [eugenp/tutorials#3234]
org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials j5sm3207422pgn.82 - gsmtp

**Comment by lor6** [comment]
Are you encountering this error when running one of our projects? If so, please be more specific.
