### ISSUE TITLE
What should I do after pull your project

### ISSUE THREAD

**Issue by long241191** [eugenp/tutorials#3248]
Hi. I want to deloy your custom authentication code to existing activiti-rest and activiti-app (war).

I haved pull your code and export to .jar file, copy to activiti-rest/WEB-INF/lib and activiti-app/WEB-INF/lib but nothing happen.

What should I do if I want to deploy into  activiti-rest and  activiti-app to use my custom authentication for both activiti-rest and  activiti-app.

Many thanks.

**Comment by lor6** [comment]
You'll have to integrate the code into your own application. It's not really an auto-configuration type of project.
