### ISSUE TITLE
EnvironmentEndpoint bean could not write to JSON

### ISSUE THREAD

**Issue by yangzii0920** [eugenp/tutorials#3250]
I'm using version 1.5.9 of spring-boot. This issue starts from 1.5.3. 

I created a ListEndpoints class, which extends AbstractEndpoint class and return a list of actuator endpoints on invoke. But it seems not able to serialize environment endpoint bean. Here's the error message:

> "message": "Could not write JSON: No serializer found for class org.springframework.core.convert.support.DefaultConversionService and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.springframework.core.convert.support.DefaultConversionService and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.springframework.boot.actuate.endpoint.EnvironmentEndpoint[\"resolver\"]->org.springframework.boot.actuate.endpoint.EnvironmentEndpoint$PlaceholderSanitizingPropertyResolver[\"conversionService\"])",

Any thought?

**Comment by lor6** [comment]
Fixed using the Spring Boot suggested solution. Thanks.
