### ISSUE TITLE
Consider splitting rxjava tests to rxjava2 and rxjava.

### ISSUE THREAD

**Issue by Wosin** [eugenp/tutorials#3382]
Currently, we have all RxJava tests and code in single module `rxjava`. Having both versions of RxJava makes it quite annoying to write code. As we have to pick between classes from packages in RxJava1 and RxJava2 on most of the imports. It can easily lead to stupid mistakes and makes using quto-import harder.

**Comment by lor6** [comment]
@eugenp I actually added an improvement for this: http://jira.baeldung.com/browse/BAEL-1582
but it hasn't been picked up yet.

**Comment by eugenp** [comment]
Cool. Closing this one. @Wosin yes, this will get done, thanks for the feedback.
