### ISSUE TITLE
Dynamic table

### ISSUE THREAD

**Issue by ajdocherty** [eugenp/tutorials#3428]
Hello,

I noticed that you define your model as so:

`
@DynamoDBTable(tableName = "")
...
`

For when we want to define the tableName dynamically, I found code to save into the DynamoDBMapper with an explicit override as so:

`
dynamoDBMapper.save(model, new DynamoDBMapperConfig.TableNameOverride("tableName"));
` 

However, in your code you save into the _repository_ not the mapper directly - so I am wondering if you know how to replicate the behaviour in the repository? I am thinking to extend SimpleDynamoDBCrudRepository instead of extending the CrudRepository interface, and implement a save method that will do the same thing. Would you say that sounds like the way to go?

Thanks

**Comment by lor6** [comment]
Hey @ajdocherty 
I'm not sure I understand your question. You want to add a method that changes the table's name?

**Comment by lor6** [comment]
Closing since this doesn't seem to be an issue with our project and due to inactivity.

**Comment by quan240594** [comment]
I'm currently facing a problem with this. Trying to feed a variable into the table name (depending on environments) and haven't found a working solution yet.
