### ISSUE TITLE
Invalid derived query! No property customize found for type MyUser!

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#346]
This is regarding `spring-security-rest-full` code, when I imported this project in STS, it's compiling fine, but still I see MyUserRepository.java showing the error. Could you please fixed this issue ASAP?

```
Multiple markers at this line
    - Invalid derived query! No property customize found for type MyUser!
    - implements 
     org.springframework.data.querydsl.binding.QuerydslBinderCustomizer<org.baeldung.persistence.model.QMyUser>.customize
```

**Comment by StevenNdaye** [comment]
Maybe too late and not sure but try this please.
Add this method in your repository interface assuming your are using JpaRepository

    @Override
    default void customize(QuerydslBindings bindings, QMyUser root) {

        bindings.bind(String.class).first((SingleValueBinding<StringPath, String>) StringExpression::containsIgnoreCase);
    }

Make sure that your repository interface extends QuerydslBinderCustomizer<QMyUserr>

Alternatively have a look at this project: https://github.com/StevenNdaye/i-code-java-conf-2016/tree/master/query_dsl

**Comment by eugenp** [comment]
This one should be running fine now (it's been running OK for a while, I just missed updating this issue). 
Closing. 
Cheers, 
Eugen.
