### ISSUE TITLE
In international example broken assets paths

### ISSUE THREAD

**Issue by WHK102** [eugenp/tutorials#3463]
In internationalize example the Beans cause a conflict with default routes from assets and spring canot find the resources paths like as images, css, etc.

**Comment by lor6** [comment]
Hey @WHK102 Thanks for the bringing this up.

I'm able to reproduce the issue and it seems to be caused by the EnableWebMvc annotation. If I remove that, everything works ok. Is that what you had in mind as well?

**Comment by WHK102** [comment]
Thanks works fine :D
