### ISSUE TITLE
Crawl page with Infinite Scroll or AJAX not working (Google Album Archive)

### ISSUE THREAD

**Issue by tamaspflanzner** [eugenp/tutorials#3500]
HtmlUnit 2.29

I'm using these settings:

webClient.getOptions().setJavaScriptEnabled(true);
webClient.getOptions().setCssEnabled(false);
webClient.setCssErrorHandler(new SilentCssErrorHandler());
webClient.getOptions().setRedirectEnabled(true);
webClient.getOptions().setThrowExceptionOnScriptError(false);
webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
webClient.getOptions().setPrintContentOnFailingStatusCode(false);
webClient.getCurrentWindow().setInnerHeight(Integer.MAX_VALUE);
webClient.waitForBackgroundJavaScript(10000);
webClient.setAjaxController(new NicelyResynchronizingAjaxController());

If I try to crawl an album:

HtmlPage albumPage = webClient.getPage(PREFIX_GOOGLE_GET + albumRelLink)
// example: https://get.google.com/albumarchive/103435896752145457656/album/AF1QipM4quOBnp_cTvckNLl6u8QemRKcSITLH3FM4BVN
albumPage.getByXPath("//div[@role='list']/div/img")

It only returns the first 24 items.

**Comment by lor6** [comment]
Hey @tamaspflanzner Is this an issue with our code base, or something you wanted to customize?
