### ISSUE TITLE
Authentication is not taking Place

### ISSUE THREAD

**Issue by manojmahijpr** [eugenp/tutorials#3514]
In Multiple Login Pages Authentication is not taking Place only redirection of URL with antMatchers

**Comment by lor6** [comment]
Hey @manojmahijpr I'm not able to reproduce your issue. Can you explain why you think authentication is not taking place?

The example has two links accessible by a user and an admin. If you login as a user for example then attempt to access the admin page, you will get a page that says "You do not have permission"

Cheers.

**Comment by lor6** [comment]
Closing since the issue doesn't reproduce and due to inactivity.
