### ISSUE TITLE
How do I compile and run spring-cloud-gateway example?

### ISSUE THREAD

**Issue by tshah010** [eugenp/tutorials#3554]
I am in tutorials/spring-cloud/spring-cloud-gateway directory and I run "mvn install spring-boot:run" but the application doesn't start. I also tried "mvn install" but doesn't run the application. Please tell me which command to run and from which directory. Thanks.

**Comment by tshah010** [comment]
on running mvn install at root of tutorial folder, I keep getting following error
```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.baeldung:spring-jpa:0.1-SNAPSHOT (/Users/tshah/projects/tutorials/persistence-modules/spring-jpa/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.baeldung:spring-jpa:0.1-SNAPSHOT: Could not find artifact com.baeldung:parent-modules:pom:1.0.0-SNAPSHOT in repo (https://<MY-COMPANY-INTERNAL-REPO>/artifactory/repo) and 'parent.relativePath' points at wrong local POM @ line 12, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```

**Comment by lor6** [comment]
Hey @tshah010 There were some project setup issue in the example. Please pull from master again. You should be able to run mvn spring-boot:run in the spring-cloud-gateway directory to run the app, or run it from an IDE.

Cheers.
