### ISSUE TITLE
Get all feild of current User login

### ISSUE THREAD

**Issue by dodacvan** [eugenp/tutorials#3557]
how to all all feild in database of current user,( not only name and password) such as .. id, address, age. Thanks

**Comment by lor6** [comment]
Hey @dodacvan If you're referring to a Spring application backed by a database, then you would have to load the user details from the database based on the username. 

Here's an example of an implementation: http://www.baeldung.com/spring-security-authentication-with-a-database

Here, you can use the loadUserByUsername() method of UserDetailsService.

Hope that helps.
