### ISSUE TITLE
Performance problems at first call to DynamoDb

### ISSUE THREAD

**Issue by mikes222** [eugenp/tutorials#3603]
I have created a lambda function in Java for Cognito. When the Lambda function is started for the first time (coldstart) it takes about 100ms for startup. As soon as I try to access a dynamodb database the coldstart time increases to 6 seconds!
This also occurs if the table does not have any rows in it. The dynamoDb and the lambda-function are of course in the same region. 

The question is if you also experience such bad coldstarttimes with DynamoDB access and if you have any suggestions how to get rid of it. 

The core function I am currently using is:

    public class PostAuthentication implements RequestHandler<CognitoEvent, CognitoEvent> {

	protected DynamoDB dynamoDb;

	private DynamoDB getDynamoDbClient() {
		if (dynamoDb != null)
			return dynamoDb;
		AmazonDynamoDBClient client = (AmazonDynamoDBClient) AmazonDynamoDBClientBuilder.standard()
				.withRegion(Regions.EU_CENTRAL_1).build();
		this.dynamoDb = new DynamoDB(client);// new AmazonDynamoDB(client);
		return dynamoDb;
	}

	@Override
	public CognitoEvent handleRequest(CognitoEvent event, Context context) {
		context.getLogger().log("Input for cognito: " + event);
                // the following line makes the difference between 100ms and 6 secs coldstart-time
		Item item = getDynamoDbClient().getTable(CustomerDbo.TABLENAME).getItem("id", "test");
        }
    }

**Comment by eugenp** [comment]
Hey @mikes222  - that's very interesting, but I'm a bit confused - what is this in relation to? Is this an "issue" with any of the modules here?
Cheers, 
Eugen.

**Comment by eugenp** [comment]
I haven't heard back from you @mikes222 - closing this one.
