### ISSUE TITLE
Springboot + /tmp/tomcat-docbase.* directory is always created when starting the app.

### ISSUE THREAD

**Issue by RohitGupta31** [eugenp/tutorials#3615]
If I  run a spring boot app(jar file) I see a couple of directories being created. Work directory and a 'tomcat-docbase*' directory

tomcat.*.8080
tomcat-docbase.*.8080

 The default base directory can be overridden using the config property server.tomcat.basedir.
However, this has no effect on tomcat-docbase. It is possible to override tomcat-docbase or stop it from creating as in my jar there are no static files being served.

**Comment by lor6** [comment]
Hey @RohitGupta31  This question is more suited to stackoverflow.

Here's an answer that offers solutions for your issue: https://stackoverflow.com/questions/43089611/tmp-tomcat-docbase-is-always-created-with-a-spring-boot-jar-but-not-a-war
