### ISSUE TITLE
BAEL-86: Unclosed Input Stream

### ISSUE THREAD

**Issue by Thoughtscript** [eugenp/tutorials#3628]
I caught an unclosed input stream in the multipart file uploader that should be manually closed: https://github.com/eugenp/tutorials/blob/master/spring-dispatcher-servlet/src/main/java/com/baeldung/springdispatcherservlet/controller/MultipartController.java

This should also be updated in: http://www.baeldung.com/spring-dispatcherservlet

**Comment by Thoughtscript** [comment]
https://github.com/eugenp/tutorials/pull/3629

**Comment by lor6** [comment]
Hey @Thoughtscript  Thanks :) Merged and updated the article.

**Comment by Thoughtscript** [comment]
Hey @lor6 - thank you!
