### ISSUE TITLE
5.1. Custom Method Security Expression example not working 

### ISSUE THREAD

**Issue by melissapalmer** [eugenp/tutorials#3660]
Hi for the 5.1. Custom Method Security Expression at: 
http://www.baeldung.com/spring-security-create-new-custom-security-expression 

I am always getting the following error 
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method isMember(#id) cannot be found on org.springframework.security.access.expression.method.MethodSecurityExpressionRoot type

Is there possibly a missing step in the tutorial? 
Is using the CustomPermissionEvaluator within the MethodSecurityConfig doesn't seem correct if I just want to add a new method expression. 

Thank you in advance for the help
(I am using Spring Boot <version>1.5.4.RELEASE</version> with 
 <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>  
)

**Comment by melissapalmer** [comment]
Sorry I managed to sort out what the issue was. I had the annotation @EnableGlobalMethodSecurity(prePostEnabled = true) twice in my code on the Config class you described and on one my main config classes. 

THANK YOU I have it all working!

**Comment by lor6** [comment]
Sounds good @melissapalmer. Closing.
