### ISSUE TITLE
Could not initialize class io.restassured.RestAssured

### ISSUE THREAD

**Issue by TahaRafi** [eugenp/tutorials#3724]
java.lang.NoClassDefFoundError: io/restassured/mapper/factory/ObjectMapperFactory!!Error occured when i am running the test cases.Even, in pom.xml i have added the restAssured dependency and also in jar file the class ObjectMapperFactory  there.
Please help!!

**Comment by lor6** [comment]
Hey @TahaRafi is this an issue with one of our projects? If not, the question would be better suited for stackoverflow, with more detail.

Cheers.
