### ISSUE TITLE
spring-openid - How to get clientId and clientSecret?

### ISSUE THREAD

**Issue by JavaNeed** [eugenp/tutorials#375]
This is regarding the "spring-openid" I don't see you provided README.md or steps to execute this particular project. Also there is no details, how to obtain the google.clientId and google.clientSecret.

I see querydsl and some other project are not running properly. Did you tested these projects on Eclipse or STS?

**Comment by eugenp** [comment]
That's a good point - I'll add it to the TODO list - should be sorted out soon. 
As for QueryDSL - I see you already opened a separate issue - that's good - I'll follow up there. 
Cheers, 
Eugen.

**Comment by eugenp** [comment]
Quick update on this - there is now a readme in the module - hope that sorts things out. 
Cheers, 
Eugen.
