### ISSUE TITLE
May I request you to please remove .classpath from all your commits?

### ISSUE THREAD

**Issue by JavaNeed** [eugenp/tutorials#383]
May I request you to please remove following files from your each commit. Certainly committing following files into GIT is not a good practice. Also your .project setting and classpath will be always different to others settings. So importing any of your project always causes problem.  Hope you'll be doing that soon.

The following files should not be a part of commit.
.classpath
.settings
.project
target
.springBeans
..externalToolBuilders

**Comment by eugenp** [comment]
That's a good idea, since these files are more harmful than helpful. 
Feel free to open a PR for it; otherwise, I'll certainly get to it, but probably not very soon. 
Cheers, 
Eugen.

**Comment by pivovarit** [comment]
closed by #503
