### ISSUE TITLE
401 - Could not obtain an access token

### ISSUE THREAD

**Issue by rrgonzalez** [eugenp/tutorials#3908]
Hi, I just downloaded the project and tried the single sso.
After I enter the credentials and login, I get a 401 Status "Could not obtain an access token". I think it's a problem with the client, because I tested the server with a REST Client and it works fine. Does anybody had this issue? What do you think it could be? Thanks in advance

This is the error from the client log:
g.c.AuthorizationCodeAccessTokenProvider : Encoding and sending form: {grant_type=[authorization_code], code=[S1pj34], redirect_uri=[http://my-redirect-url]}
2018-03-30 00:39:32.579 DEBUG 15394 --- [nio-8084-exec-7] uth2ClientAuthenticationProcessingFilter : Authentication request failed: org.springframework.security.authentication.BadCredentialsException: Could not obtain access token

**Comment by lor6** [comment]
Hey @rrgonzalez I'm not able to reproduce the issue. Which client are you running? The error suggests the user credentials are incorrect. Are you using the john/123 credentials from the config?

Cheers.

**Comment by rrgonzalez** [comment]
I'm using this: https://github.com/eugenp/tutorials/tree/master/spring-security-sso/spring-security-sso-ui
Yes, I'm using john/123, but it's not on that step. It's just before to get the access token. After obtainin the authorization grant code.

**Comment by lor6** [comment]
@rrgonzalez  Are you running the client with our server application or your own? Because if you look in the security configuration of our server app, it's set to auto-approve the client, so there shouldn't be another step. 

I suggest checking that the client credentials in the client app (application.yml file) match the ones registered in the server app.

**Comment by eugenp** [comment]
Quick ping here @rrgonzalez

**Comment by rrgonzalez** [comment]
It all ended up being a CSRF issue. I just configured the CSRF permission on the service and all worked perfectly! Sorry, for not keep all of you up to date. In case someone else fall in this hole, here was my solution:

```
@Configuration
public class OauthSecurityConfig extends WebSecurityConfigurerAdapter {
	
	@Override
    protected void configure(HttpSecurity http) throws Exception {
		System.out.println("HTTP: " + http.toString());
		
		http
		.cors().and()
		.requestMatchers()
        .antMatchers("/login", "/authorize", "/token")
        .and()
        .authorizeRequests()
        .anyRequest().authenticated()
        .and()
        .formLogin().permitAll();
    }
	
	@Override
    protected void configure(AuthenticationManagerBuilder builder) throws Exception {
		builder.authenticationProvider(new MirthAuthenticationProvider());
    }
	
    // Here the origin is configurated a /** for all hosts, my advice is that you put this first to try, then write the proper hosts.
	@Bean
	CorsConfigurationSource corsConfigurationSource() {
		CorsConfiguration configuration = new CorsConfiguration();
		configuration.setAllowedOrigins(Arrays.asList("*"));
		configuration.setAllowedMethods(Arrays.asList("GET","POST"));
		UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
		source.registerCorsConfiguration("/**", configuration);
		return source;
	}
}
```

**Comment by lor6** [comment]
@rrgonzalez  Cool, thanks. I think that's an issue with Spring 5. We've added updating the SSO article to Spring 5 to our roadmap.

Cheers.
