### ISSUE TITLE
Question: How to set gridSize (Spring Batch)?

### ISSUE THREAD

**Issue by aresares** [eugenp/tutorials#3942]
HI how can I set the gridSize using the annotations. I have an example but it uses xml
```
	<!-- partitioner job -->
	<job id="partitionJob" xmlns="http://www.springframework.org/schema/batch">
		<step id="masterStep">
			<partition step="slave" partitioner="partitioner">
				<handler grid-size="3" task-executor="taskExecutor" />
			</partition>
		</step>
	</job>
```

**Comment by lor6** [comment]
Hey @aresares  The PartitionerStepBuider has a gridSize() method:
//...
 .partitioner("masterStep", partitioner())
          .step(slaveStep())
          .taskExecutor(taskExecutor())
          .gridSize(3)
//...
