### ISSUE TITLE
When I access localhost:8081/auth/oauth/token 401, "Full authentication is required to access this resource",

### ISSUE THREAD

**Issue by haoxiaoyong1014** [eugenp/tutorials#4069]
Https://github.com/eugenp/tutorials/tree/master/spring-security-sso
When I access localhost:8081/auth/oauth/token 401, "Full authentication is required to access this resource",

Request header:
  Content-Type:application/x-www-form-urlencoded
Here are the parameters to carry:
Client_id:SampleClientId
Grant_type:authorization_code
Client_secret:secret
Scope:user_info
Someone encountered this problem did not, thank you very much

**Comment by lor6** [comment]
Hey @haoxiaoyong1014  Are you calling this from one of the ui projects or from a REST client app?

**Comment by haoxiaoyong1014** [comment]
The program starts directly in the postman test localhost:8081/auth/oauth/token, carrying the above parameters, that is, there is 401, is it a problem with the parameters I carry?
The following are the parameters that need to be carried:
Client_id:SampleClientId
Grant_type:authorization_code
Client_secret:secret
Scope:user_info

**Comment by lor6** [comment]
Hey @haoxiaoyong1014 

To access that URL, you have to provide an Authorization header in Postman of type Basic with the client id and secret. However, when using the authorization_code grant type, you also need to provide a code. So first, you would have to call the oauth/authorize URL to obtain an authorization code for the client, then use that to get the token - which is a bit more difficult to do in Postman.

If you want a standard oauth server project, we have another repo: https://github.com/Baeldung/spring-security-oauth

This project is meant for an SSO scenario. If you want to see how it works, I suggest you try to run the ui projects and have a look at the network calls done there.

**Comment by haoxiaoyong1014** [comment]
Thank you for your answer, thank you very much

**Comment by lor6** [comment]
Cool, closing.
