### ISSUE TITLE
Jackson MismatchedInputException

### ISSUE THREAD

**Issue by vijaysl** [eugenp/tutorials#4111]
Hi Eugen, 
Apologize if this is not the right place for this question.
In the Spring Data Rest example, it will also be helpful to add the following example where you can associate a relationship directly.

- curl -i -X POST -H "Content-Type:application/json" -d '{"name":"My Library"}' http://localhost:8080/libraries
- curl -i -X POST -d '{"title":"Books", "library":"http://localhost:8080/libraries/1"}' -H "Content-Type:application/json" http://localhost:8080/books

This works in Java and when using a regular class for the JPA entity. However, if I change this to a kotlin data class this fails with the following error
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.baeldung.models.Library` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('http://localhost:8080/libraries/1')

I have shared the updated code under https://github.com/vijaysl/spring-data-rest.git

Appreciate any feedback.

Thanks,
Vijay

**Comment by lor6** [comment]
Hey @vijaysl 

The Kotlin question is more appropriate for StackOverflow, since it's not an issue with this repository. But most likely the jackson library for kotlin simply doesn't support deserializing objects from URIs, at least not yet.

**Comment by vijaysl** [comment]
I did post this on stackoverflow and received some valueable feedback. The issue was appeared to be caused by including com.fasterxml.jackson.module:jackson-module-kotlin in the build. It works fine after removing it. I have updated the example https://github.com/vijaysl/spring-data-rest
