### ISSUE TITLE
detectDocTypeUsingDetector method 

### ISSUE THREAD

**Issue by yuanbing1113** [eugenp/tutorials#4117]
I try to use this method, after input file inputstream.  there will be a error respond .
error: Exception in thread "main" java.io.IOException: mark/reset not supported

**Comment by lor6** [comment]
Hey @yuanbing1113  Is this an issue when running the test in our repository?

**Comment by yuanbing1113** [comment]
Hello Ior6, It was fine running the test function. The issue is I just copy the code to my local, and I also can use detectDocTypeUsingFacade method to check mediaType. Thanks

**Comment by lor6** [comment]
Ok. Since there's no issue with our code, this question is more appropriate for StackOverflow. I suggest you create a post there, with more details on what you're trying to do and some code snippets. Then feel free to email the link to team@baeldung.com and we'll try to have a look.

Cheers.
