### ISSUE TITLE
spring-activiti example requires authentication

### ISSUE THREAD

**Issue by kirenpillay** [eugenp/tutorials#4193]
The spring-activiti example without security asks for security when it shouldn't. This is caused byf the dependency of activiti-spring-boot-starter-security being on the classpath. 

Possible Solutions?

1. Add caveat in readme to remove the dependency when running ActivitiWithSpringApplication.
2. Split the project into 2
3. Add same security to ActivitiWithSpringApplication.

**Comment by lor6** [comment]
Good point, thanks. Fixed by excluding the Security Auto-configuration in the ActivitiWithSpringApplication class.
Closing.
