### ISSUE TITLE
Validation logic does not work under Webflux/netty context

### ISSUE THREAD

**Issue by petivagyok16** [eugenp/tutorials#4205]
Hi!

I implemented the Validation solution you presented [in this article](http://www.baeldung.com/spring-data-rest-validators)

But i keep getting this error.
```
Field validatingRepositoryEventListener in 
com.friendlytalks.friendlytalksapi.config.ValidatorEventRegister required a bean 
of type 'org.springframework.data.rest.core.event.ValidatingRepositoryEventListener' 
that could not be found.
```
The file looks the same in my project as the article file and i imported
`spring-boot-starter-data-rest` as well.
How can solve this problem? Is it even compatible with Webflux/netty?
If i comment out all the Validation logic Springboot starts Tomcat, which is not the expected behavior for me, this is because of the `spring-boot-starter-data-rest` package. How could i manage to start my project with Netty?
Thanks in advance

**Comment by lor6** [comment]
Hey @petivagyok16  From the docs, I see Spring Data REST supports "JPA, MongoDB, Neo4j, Solr, Cassandra, Gemfire" Which one are you using?

**Comment by petivagyok16** [comment]
I use MongoDB.
The main problem is that i import the `spring-boot-starter-data-rest` package, which contains the `ValidatingRepositoryEventListener`, but the Spring context does not see it when i start the server.

**Comment by lor6** [comment]
@petivagyok16  Ok, I'm not sure why that is, unless you want to start debugging the Spring configuration classes. All I could find was this ticket on the Spring JIRA that states Spring Data REST doesn't currently support Webflux and there are no plans to support it: https://jira.spring.io/browse/DATAREST-933

**Comment by petivagyok16** [comment]
Alirght, thanks!
