### ISSUE TITLE
Use ResourceSupport types when returning Spring HATEOAS resources

### ISSUE THREAD

**Issue by gregturn** [eugenp/tutorials#4217]
In your tutorial, http://www.baeldung.com/spring-hateoas-tutorial#link, you illustrate returning REST resources. However, the documents are not HAL.

For Spring HATEOAS to properly render HAL documents, your REST controllers must return a `ResourceSupport` or one of its subclasses. In the tutorial's example, returning a `Resource<Customer>` would be a good fit.

For more examples, please check out https://github.com/spring-projects/spring-hateoas-examples.

**Comment by lor6** [comment]
Hey @gregturn Our Customer and Order model classes extend ResourceSupport. Is that not sufficient to return HAL?

Thanks.

**Comment by eugenp** [comment]
That's a super interesting point @gregturn, thanks for the feedback. We'll get the implementation (and the article) sorted. 
Cheers, 
Eugen.

**Comment by lor6** [comment]
This is updated in the code and article. Closing.
