### ISSUE TITLE
dijkstra | can we use PriorityQueue (min Heap)

### ISSUE THREAD

**Issue by krishnaexplore** [eugenp/tutorials#4253]
can we use PriorityQueue (min heap) instead of settled and unsettled?

https://github.com/eugenp/tutorials/blob/master/algorithms/src/main/java/com/baeldung/algorithms/ga/dijkstra/Dijkstra.java#L14:L15

**Comment by lor6** [comment]
Sure, but the algorithm changes a bit. Have a look here for an example implementation: https://github.com/vaishnav/Dijkstra
