### ISSUE TITLE
sso logout

### ISSUE THREAD

**Issue by kyawzinhtun** [eugenp/tutorials#4315]
Hi

When i add logout function, It does not single sign off. Do you have any idea.
Thanks

**Comment by lor6** [comment]
Hey @kyawzinhtun  Is this an issue with one of our projects?

**Comment by lor6** [comment]
Since this isn't an issue with our project, I suggest reading more about SSO logout in the Spring official guide: https://spring.io/blog/2015/02/03/sso-with-oauth2-angular-js-and-spring-security-part-v#the-logout-experience

Closing.
