### ISSUE TITLE
A mistake in article about static keyword

### ISSUE THREAD

**Issue by LennonChin** [eugenp/tutorials#4328]
Hello,

In article - [A Guide to the Static Keyword in Java](http://www.baeldung.com/java-static), pharse 6.3 - key Points to Remember, there is a mistake about conclusion "static nested classes do not have access to any member of the enclosing outer class; it can only access them through an object’s reference" , we can access static member of the enclosing outer class in static nested classes. like this:

```java
class OuterClass {
	private static String name = "OuterClass";
	static class InnerClass {
		InnerClass() {
			System.out.println("inner class access static field of outer class " + name);
		}
	}
}
```

**Comment by lor6** [comment]
Good point, thanks. Updated the article.
