### ISSUE TITLE
Small mistake in CDI vs Spring

### ISSUE THREAD

**Issue by GedMarc** [eugenp/tutorials#4329]
cdi-interceptor-vs-spring-aspectj

9. CDI Interceptor VS Spring AspectJ

If your current project uses Spring then considering Spring AspectJ is a good choice.

If you are using a full-blown application server, or your project doesn’t use Spring and is strictly Java EE then there is nothing left than to choose the CDI interceptor.

There is Guice (Which is Highly Preferred over Spring and Weld CDI - See Guice vs Spring documentation from Google), there is also Haskel and a few others as well.
Limiting to crappy weld or spring is quite a restriction :)

**Comment by lor6** [comment]
Hey @GedMarc I think the main idea was to compare Spring with vanilla JEE. Of course, there are other frameworks and libraries that would be possible to use. I've added a small caveat in the article.

Thanks.
