### ISSUE TITLE
In XML-based configuration, we can’t use angle bracket operators ?

### ISSUE THREAD

**Issue by bollenchak** [eugenp/tutorials#4362]
In the guide part 3.2 says 'In XML-based configuration, we can’t use angle bracket operators'.

> 3.2. Using Operators in Configuration
Each operator from the first section of this article can be used in XML and annotation-based configurations. However, remember that in XML-based configuration, we can’t use angle bracket operators. Instead, we should use their alphabetic aliases, such as lt (less than) or le (less than or equals). For annotation-based configurations, there are no such restrictions.

But the example in the part 3.2,xml configuration use the ">" but "gt" , it still does work in my test.

```xml
 <bean id="spelOperators" class="com.baeldung.spring.spel.SpelOperators">
   <property name="equal" value="#{1 == 1}"/>
   <property name="notEqual" value="#{1 lt 1}"/>
   <property name="greaterThanOrEqual" value="#{someCar.engine.numberOfCylinders >= 6}"/>
   <property name="and" value="#{someCar.horsePower == 250 and someCar.engine.capacity lt 4000}"/>
   <property name="or" value="#{someCar.horsePower > 300 or someCar.engine.capacity > 3000}"/>
   <property name="addString" value="#{someCar.model + ' manufactured by ' + someCar.make}"/>
</bean>
```
I don't think it's very precise.

**Comment by lor6** [comment]
@bollenchak  True, it's mainly the "<" operator that's disallowed. If you try adding it, you'll get an exception. 

I've updated the article, thanks.
