### ISSUE TITLE
An example isnt work

### ISSUE THREAD

**Issue by qwertukg** [eugenp/tutorials#4473]
Did u try it before post?

**Comment by qwertukg** [comment]
Or i do something wring?

**Comment by lor6** [comment]
Hi @qwertukg Which example are you referring to?

**Comment by qwertukg** [comment]
Hello! 
spring cloud with ldap. I have a connection to my LDAP server, but getting a bad credentials error for correct user. If make auth in LDAP manually, by `LdapTemplate` and query builder, its ok too

**Comment by qwertukg** [comment]
Also, using  inMemoeryAuth manager its ok too

**Comment by lor6** [comment]
Thanks. Is this the article you're referring to: http://www.baeldung.com/spring-security-ldap and this project: https://github.com/eugenp/tutorials/tree/master/spring-security-mvc-ldap ? Just making sure, because it's not a Spring Cloud project.

**Comment by lor6** [comment]
Checked the spring-ldap project. Everything works ok. Closing.
