### ISSUE TITLE
Running spring-ejb example

### ISSUE THREAD

**Issue by danksch** [eugenp/tutorials#4504]
Hello,

I'm currently trying to get [the Spring-EJB example](http://www.baeldung.com/spring-ejb) to work. 
I am new to Maven and Spring and unsure about the commands needed for proper execution:

As far as I understand, two commands are needed - one to deploy the beans in the wildfly cargo container, and one to start the spring tomcat server from which RMI is performed. 

But, for instance, when I type in **mvn clean package cargo:run -Pwildfly-standalone**, it just says "Build Successful", and not starting the server or anything (i can't open the server console on port 9990). doesn't work at both parent directory level and module level. 

Similar case with booting the spring ejb client itself. To my knowledge, the command to do so is **mvn spring-boot:run** , which just builds the project when executed on parent directory level, and fails when executed from the spring-ejb-client level. The log here is 

`[WARNING] The POM for com.baeldung.spring.ejb:ejb-remote-for-spring:jar:1.0.1 is missing, no dependency information available
...
[ERROR] Failed to execute goal on project spring-ejb-client: Could not resolve dependencies for project com.baeldung:spring-ejb-client:jar:0.0.1-SNAPSHOT: Failure to find com.baeldung.spring.ejb:ejb-remote-for-spring:jar:1.0.1 in https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -`

It seems a dependency of one of the modules is missing, but when I look into the pom.xml of said module, _ejb-remote-for-spring_ is not marked as _jar_, but _ejb_. 

What am I missing ? 

Thanks for any help in advance!

**Comment by bbhavsar2018** [comment]
Looks like jar it self is not there on remote repository that you are using, check here https://repo.spring.io/snapshot/com/

you may use this instead. 
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.wildfly%22%20AND%20a%3A%22wildfly-ejb-client-bom%22

Manually you can download jar and put it under your .m2.

**Comment by lor6** [comment]
@danksch We've updated the dependency versions. Please do a pull and try to run the projects again.
