### ISSUE TITLE
intro-to-feign seems to have minor json serialize bug

### ISSUE THREAD

**Issue by gli00001** [eugenp/tutorials#4559]
curl http://localhost:8081/api/books
returns 
[
  {
    "book": {
      "isbn": "1447264533",
      "author": "Margaret Mitchell",
      "title": "Gone with the Wind",
      "synopsis": null,
      "language": null
    },
    "links": [
      {
        "rel": "self",
        "href": "http://localhost:8081/api/books/1447264533"
      }
    ]
  },
...
}

curl http://localhost:8081/api/books/1447264533
returns
{
  "book": {
    "isbn": "1447264533",
    "author": "Margaret Mitchell",
    "title": "Gone with the Wind",
    "synopsis": null,
    "language": null
  },
  "_links": {
    "self": {
      "href": "http://localhost:8081/api/books/1447264533"
    },
    "add-to-cart": {
      "href": "http://localhost:8081/api/cart"
    }
  }
}

see the difference between  "links": [     and  "_links": {  ?
the "_links": { .. }  part with an underscore coming in before "link" seems messed up, and expected an array, not an object

**Comment by gli00001** [comment]
Thanks, Loredana!
you led me to https://sookocheff.com/post/api/on-choosing-a-hypermedia-format/ and then I see

**Comment by lor6** [comment]
Cool, closing.
