### ISSUE TITLE
Missing rules file

### ISSUE THREAD

**Issue by ArthurFlanagan** [eugenp/tutorials#4762]
The file that contains the rule(s) doesn't seem to be available on Github.

Also, what is the correct directory for the rules file, when creating a Spring application?

Does the project require a kmodule.xml file?

Thanks

Art

P.S. Thanks for your work creating great tutorials.

**Comment by lor6** [comment]
Hey @ArthurFlanagan  I assume you're referring to the spring-drools and drools modules?

Both have the rules files available in the src/main/resources directory.

You can use an in-memory kie module or the xml file.

Cheers.

**Comment by rahulaga** [comment]
I think correct repo is this one: https://github.com/eugenp/tutorials/tree/master/drools

**Comment by lor6** [comment]
@rahulaga  Right, we have a simple drools module that you linked to, and a Spring with drools module: https://github.com/eugenp/tutorials/tree/master/spring-drools

Both have the rules files in the src/main/resources directory.
