### ISSUE TITLE
Producer consumer in blocking queue

### ISSUE THREAD

**Issue by sukhmeet2390** [eugenp/tutorials#4924]
[https://github.com/eugenp/tutorials/blob/master/core-java-concurrency/src/main/java/com/baeldung/concurrent/blockingqueue/BlockingQueueUsage.java](url)

`		int N_PRODUCERS = 4;
        int N_CONSUMERS = Runtime.getRuntime().availableProcessors();
        int poisonPill = Integer.MAX_VALUE;
        int poisonPillPerProducer = N_CONSUMERS / N_PRODUCERS;`

Here if `Available processor =1` , then `N_CONSUMERS = 1`
Hence `poisonPillPerProducer = 1/4` to `int = 0`. 
Should that be reverse @Doha2012 ?

**Comment by Doha2012** [comment]
Hi @sukhmeet2390,
As I understand the `poisonPill` act as a special message to end the consumer, so `poisonPillPerProducer` should indicate number of `poisonPill` generated by each producer 
`int poisonPillPerProducer = N_CONSUMERS / N_PRODUCERS;`

But in your scenario, no `poisonPill` will be generated, so the consumer will never stop.
I guess we should modify it to use ceil of `N_CONSUMERS / N_PRODUCERS` 

@pivovarit what do you think?

**Comment by lor6** [comment]
@sukhmeet2390  This was the solution chosen: https://github.com/eugenp/tutorials/pull/4992/files
