### ISSUE TITLE
web-flow tutorial: no hint on how to start a web app

### ISSUE THREAD

**Issue by colourful-land** [eugenp/tutorials#4982]
I was following this tutorial:

https://www.baeldung.com/spring-web-flow

Which says:

> To navigate through the flows, start up the web app and go to `http://localhost:8080/{context-path}/activationFlow`. 

It is not given what is the "means" to start up the web app. `mvn spring-boot:run` would give:

    Unable to find a suitable main class, please add a 'mainClass' property

I noticed that the servelet is registerred through `WebInitializer.java`, but couldn't solve the equation of filling in a `mainClass` to utilise `WebInitializer.java`.

If there is a tutorial that user should do before doing web-flow, kindly link that. Would save hours for learners.

**Comment by colourful-land** [comment]
# experiment with tomcat7

https://github.com/eugenp/tutorials/tree/master/spring-mvc-webflow

I experimented with tomcat7 by adding its plugin to the `pom.xml` (it had no plugins for running a web-app). But I just get 404 when attempting to access the said link for the beginning of the flow.

In the tomcat7 plugin I added, my context-path is `/` so the actual address I used to get the 404 is `http://localhost:8080/activationFlow` and no clue was given in the `tomcat/logs`

Here is the plugin I added.

            <plugin>
                <groupId>org.apache.tomcat.maven</groupId>
                <artifactId>tomcat7-maven-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <path>/</path>
                </configuration>
            </plugin>

I also attached the pom.xml file [pom.xml.txt](https://github.com/eugenp/tutorials/files/2295963/pom.xml.txt). Apart from pom.xml file I changed absolutely nothing from https://github.com/eugenp/tutorials/tree/master/spring-mvc-webflow

P.S. I don't have a preference to use tomcat7 - anything that can start the web app will do. It's just unclear to me what kind of `mainClass` should I provide to make sure it utilises `WebFlowConfig.java` and `WebMvcConfig.java`

**Comment by colourful-land** [comment]
Although a solution is provided, the bug remain open as a pledge to add some explanation around the line in the tutorial which says "start up the web app".

**Comment by lor6** [comment]
Hey @colourful-land This isn't a Spring Boot app, it's a standard Spring app. The way to run it is to build the war and deploy it on a server (like Tomcat). I've added a sentence on this in the article.
