### ISSUE TITLE
+ and - are useless

### ISSUE THREAD

**Issue by Tanonic** [eugenp/tutorials#5043]
https://github.com/eugenp/tutorials/blob/2639324919453df76b689b7cc2fc85fc66a4005c/algorithms/src/main/java/com/baeldung/algorithms/mcts/tree/Node.java#L68

1 is being added to noOfPossibleMoves and then instantly subtracted again.
Same problem in State.java

https://github.com/eugenp/tutorials/blob/2639324919453df76b689b7cc2fc85fc66a4005c/algorithms/src/main/java/com/baeldung/algorithms/mcts/montecarlo/State.java#L90

**Comment by lor6** [comment]
Thanks for the note; fixed.
