### ISSUE TITLE
new new org.neo4j.ogm.config.Configuration() is no longer supported

### ISSUE THREAD

**Issue by sanyalpp** [eugenp/tutorials#5048]
Hi,
In this

     @Bean
    public org.neo4j.ogm.config.Configuration getConfiguration() {
        org.neo4j.ogm.config.Configuration config = new org.neo4j.ogm.config.Configuration();
        config.driverConfiguration().setDriverClassName("org.neo4j.ogm.drivers.http.driver.HttpDriver").setURI(URL);
        return config;
    }

Can you please fix this part?

**Comment by lor6** [comment]
Hey @sanyalpp I've updated the code and articles to use the latest neo4j libraries versions.

Cheers.
