### ISSUE TITLE
this would fail if not sleep enough time

### ISSUE THREAD

**Issue by teekcode** [eugenp/tutorials#5065]
https://github.com/eugenp/tutorials/blob/1609a9a5de267c69f26dc80027424a74d3e37fe6/core-java-concurrency/src/test/java/com/baeldung/concurrent/semaphores/SemaphoresManualTest.java#L26

**Comment by eric-martin** [comment]
Thanks @teekcode. We've fixed the JUnit test. 

Here is the PR for reference:
https://github.com/eugenp/tutorials/pull/5553
