### ISSUE TITLE
Custom classloader should override findClass, not loadClass

### ISSUE THREAD

**Issue by lukehutch** [eugenp/tutorials#5075]
In this article:

https://www.baeldung.com/java-classloaders

You advocate creating a custom classloader by overriding loadClass(). 

The Javadoc for ClassLoader strongly recommends overriding findClass(), not loadClass(). The findClass() method was defined for the purpose of being overridden in custom classloaders. The loadClass() method is harder to get right than findClass(), if overridden.

Additionally, loadClass() may change in future releases, which may break a custom classloader if it is overridden, depending on how the overridden method is defined.

**Comment by eugenp** [comment]
Thanks for the feedback @lukehutch - it's not on my internal TODO list to look into and revisit the article.
