### ISSUE TITLE
Dynamic neo4j queries

### ISSUE THREAD

**Issue by sanyalpp** [eugenp/tutorials#5093]
Hi,

Is it possible to create and run dynamic queries in neo4j using EntityManager or some other combination provided by Spring data?

**Comment by eugenp** [comment]
Hey @sanyalpp 
In the case of these kinds of technical, code-focused and very specific questions, we need to go through StackOverflow. 
They have very clear (and strict) guidelines on everything from how to structure the question, how much (or little) detail to provide, how to structure code, etc. 
And these help with how easy it is for me (and anyone else) to go through that and actually help. 
Hope that makes sense. 

So, after you structure your question / code and post it there, feel free to follow up here with the link. I get a lot of these questions, so I can't promise an answer, but I do try to get to them as much as I can. 
I actually recently wrote a short piece about that here: https://www.baeldung.com/how-can-i-help

Cheers, 
Eugen.
