### ISSUE TITLE
https://stackoverflow.com/questions/52064126/powermock-emma-code-coverage-showing-0-for-private-static-methods-and-other

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#5101]
Could you please guide here https://stackoverflow.com/questions/52064126/powermock-emma-code-coverage-showing-0-for-private-static-methods-and-other ?

**Comment by eugenp** [comment]
Hey @JavaHelper - feel free to email me when it comes to StackOverflow questions you'd like me to help with - the issues here in GitHub are not the ideal place to have this. 
Hope that makes sense. 
Cheers, 
Eugen.
