### ISSUE TITLE
Client for Spring Secured Websocket

### ISSUE THREAD

**Issue by christomaliyekkal** [eugenp/tutorials#5148]
How do we connect from java client to spring secured websocket (https://www.baeldung.com/spring-security-websockets ) ?Could you please add a sample for that too?

**Comment by eric-martin** [comment]
@christomaliyekkal Does this help out?

Article:
https://www.baeldung.com/websockets-api-java-spring-client

GitHub:
https://github.com/eugenp/tutorials/tree/master/spring-boot-client/src/main/java/org/baeldung/websocket/client
