### ISSUE TITLE
Webflow project not working

### ISSUE THREAD

**Issue by jkoorts** [eugenp/tutorials#5481]
Readme file needs more info on what endpoint/url to hit after booting up the project. 

I've tried the urls in the flow config but they're not working either.

**Comment by lor6** [comment]
Hey @jkoorts Have you had a look at the accompanying article: https://www.baeldung.com/spring-web-flow?

You can access the project at http://localhost:8080/spring-mvc-webflow/activationFlow

**Comment by jkoorts** [comment]
Hi I did,

Had a another go at it, and found that I had my context-path wrong. thanks for helping
