### ISSUE TITLE
AWS S3 - Fix "SpringCloudS3IntegrationTest" by using "PathMatchingSimpleStorageResourcePatternResolver" 

### ISSUE THREAD

**Issue by gtantachuco-pivotal** [eugenp/tutorials#5533]
The `SpringCloudS3IntegrationTest` test fails at: https://github.com/eugenp/tutorials/blob/master/spring-cloud/spring-cloud-aws/src/test/java/com/baeldung/spring/cloud/aws/s3/SpringCloudS3IntegrationTest.java#L84

To solve this test failure, you need to edit the "SpringCloudS3" class and replace this:

```
@Autowired
    ResourcePatternResolver resourcePatternResolver;
```
with

```
    private ResourcePatternResolver resourcePatternResolver;

 	@Autowired
    public void setupResolver(ApplicationContext applicationContext, AmazonS3 amazonS3){
        this.resourcePatternResolver = new PathMatchingSimpleStorageResourcePatternResolver(amazonS3, applicationContext);
    }
```

**Comment by eric-martin** [comment]
@gtantachuco-pivotal - I'm not able to recreate your issue.

Here are my steps:
Checkout the latest master branch 
Go to spring-cloud-aws submodule
Change the 'cloud.aws.credentials.accessKey' and 'cloud.aws.credentials.secretKey' keys in the application.properties file to match the security credentials from my test account.
Run SpringCloudS3IntegrationTest as a JUnit test. All three test methods passed.

Is it possible that for your test you are using a different version of the spring or aws dependencies?

**Comment by gtantachuco-pivotal** [comment]
@eric-martin, thanks for taking the time to review my request. 

Currently, I am using Spring Boot 2.0.5 and Spring Cloud AWS 2.0.1

**Comment by eric-martin** [comment]
@gtantachuco-pivotal I think that is your issue. Our example uses spring-boot-* 1.5.16 and spring-cloud-aws* 1.2.1. It is definitely possible that with your dependency versions, you would also need the code change that you noted above.

**Comment by gtantachuco-pivotal** [comment]
@eric-martin gotcha. Please feel free to close this issue.
