### ISSUE TITLE
Update for current version of Spring-boot 2.0.4

### ISSUE THREAD

**Issue by Doogiemuc** [eugenp/tutorials#5539]
Current version of spring-boot 2.0.4 already has a `AutowireCapableBeanJobFactory` this automatically configured. So you can just simply do:

    @Autowired
    SchedulerFactoryBean schedulerFactoryBean;
    [...]   
    Scheduler scheduler = schedulerFactoryBean.getScheduler();

**Comment by eugenp** [comment]
Thanks for pointing that out, @Doogiemuc - what's the specific module you're referring to?
I'll have a look. 
Cheers, 
Eugen.

**Comment by eric-martin** [comment]
It looks like spring-quartz

**Comment by cibarrac** [comment]
hi all !

**Comment by Doogiemuc** [comment]
Yes I was talking  about spring-quartz  scheduler.   => closed as solved
