### ISSUE TITLE
Problem with tutorial Simple Single Sign-On with Spring Security OAuth2

### ISSUE THREAD

**Issue by rherebia** [eugenp/tutorials#5569]
I've downloaded the [code](https://github.com/eugenp/tutorials/tree/758648eb05cde1690d7095216a9160fef15d93d2/spring-security-sso) of [Simple Single Sign-On with Spring Security OAuth2 tutorial](https://www.baeldung.com/sso-spring-security-oauth2) and I cannot log in with username **john** and password **123**. Both ui applications redirect to Authorization Server log in, but after typing credentials, appears the following message: "Full authentication is required to access this resource".

It seems like [the Autorization Header is missing in request](https://stackoverflow.com/questions/26881296/spring-security-oauth2-full-authentication-is-required-to-access-this-resource), but I can't figure out how to solve.

**Comment by eric-martin** [comment]
I'm not able to reproduce your issue. I'm testing using the latest master branch. Here are my steps:

1) Run AuthorizationServerApplication (spring-security-sso-auth-server module)
2) Run UiApplication (spring-security-sso-ui module)
3) Open a browser to http://localhost:8082/ui
4) Click login
5) Enter 'john' and '123' and click login
6) You should see a page that looks like:
Secured Page
Welcome, john
