### ISSUE TITLE
Broken links on Monte Carlo Tree Search article

### ISSUE THREAD

**Issue by TerryCavanagh** [eugenp/tutorials#5570]
Hi there!

I've been following this article to learn about Monte Carlo Tree Search, and it's been very useful. Thank you! https://www.baeldung.com/java-monte-carlo-tree-search

Just thought you should know that the the links to github in that article are broken. 👍 

(if you have a working link to the complete project from that article, that would be appreciated too!)

**Comment by eric-martin** [comment]
Thanks @TerryCavanagh. The link has been fixed.

There isn't a standalone project for the article. I would start here:

Source:
https://github.com/eugenp/tutorials/tree/master/algorithms-miscellaneous-1/src/main/java/com/baeldung/algorithms/mcts

Unit Test:
https://github.com/eugenp/tutorials/blob/master/algorithms-miscellaneous-1/src/test/java/com/baeldung/algorithms/mcts/MCTSUnitTest.java
