### ISSUE TITLE
Bug in WordIndexer.java

### ISSUE THREAD

**Issue by varunu28** [eugenp/tutorials#5600]
Great article on index matching. There is a small bug where we are trying to find index of word in textString in [WordIndexer.java](https://github.com/eugenp/tutorials/blob/master/java-strings/src/main/java/com/baeldung/string/searching/WordIndexer.java)

```
theString = "hey there";
expectedResult = Arrays.asList(0, 5);
actualResult = wordIndexer.findWord(theString, "he");
```

It is missing an index if the word is starting from index 0. 

I would be raising a PR for the same.

**Comment by eric-martin** [comment]
Thanks @varunu28 . PR tested and merged. Article updated.
