### ISSUE TITLE
https://stackoverflow.com/questions/53134556/caused-by-java-lang-illegalargumentexception-containing-1-iscontaining-co/53135364?noredirect=1#comment93175062_53135364

### ISSUE THREAD

**Issue by JavaHelper** [eugenp/tutorials#5615]
https://stackoverflow.com/questions/53134556/caused-by-java-lang-illegalargumentexception-containing-1-iscontaining-co/53135364?noredirect=1#comment93175062_53135364

Could you please guide me here ?

**Comment by eric-martin** [comment]
Is this a question about a test application in this project? I can't find the code that you are referencing.

**Comment by eric-martin** [comment]
It looks like you have another ticket logged about the same issue with the Spring Data Redis team.
https://jira.spring.io/browse/DATAREDIS-887
and it looks like they are providing guidance.
