### ISSUE TITLE
Deprecated method IOUtils.copy

### ISSUE THREAD

**Issue by juancho0506** [eugenp/tutorials#5639]
https://github.com/eugenp/tutorials/blob/91ec114e9afeb6e33112f67ff618a6a232932fd0/spring-cucumber/src/test/java/com/baeldung/ResponseResults.java#L18

This method is deprecated so would be better to find another alternative to this one, for example: 
IOUtils.copy(bodyInputStream, stringWriter, Charset.defaultCharset());

**Comment by eric-martin** [comment]
@juancho0506 This module is using apache commons-io 1.3.2. In that version, the IOUtils.copy(InputStream, Writer) method is not deprecated.
