### ISSUE TITLE
https://github.com/eugenp/tutorials/tree/master/spring-mvc-java

### ISSUE THREAD

**Issue by altuga** [eugenp/tutorials#5679]
Hello I'm trying to execute spring-mvc-java with Spring Boot. I did everything as the blog wrote but I couldn't run the app as Spring boot

I just added a new class in order to execute the project 

```
@ServletComponentScan
@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
```

I got error : Caused by: java.lang.ClassNotFoundException: javax.persistence.EntityManagerFactory

Any suggestion ?

**Comment by altuga** [comment]
I can add javax .persistence.EntityManagerFactory to maven dependency but  this kind of adding dependencies one by one will not solve my problem so I want to ask if I'm missing something bigger

**Comment by altuga** [comment]
As far as I can see your code repos are totally messed up

**Comment by eric-martin** [comment]
@altuga Can you post a link to the article you are referring to?

What pom changes have you made?

**Comment by altuga** [comment]
Hello

I tried to work on https://github.com/eugenp/tutorials/tree/master/spring-mvc-java
I

Thanks
