### ISSUE TITLE
sso and quick question 

### ISSUE THREAD

**Issue by huntw999** [eugenp/tutorials#5691]
spring security sso:

i used maven from the command line as suggested and ran the server and 2 clients.
then i looked in the files for some kind of  username and password to use in the clients

i found john and 123 and they did not get authorized - i also found SampleClientId and secret
this did not authorize trying both

i had the server and the clients running - i typed the two tries above and did not get authorized

my next step was to start debugging the server response to request - i quickly realized i would have to figure out how to run the modules in debug mode with your build and i did not want to do that without seeing if i could get some clues about password and debugging in intellij or any ide with maven - i am not a newbee just wanted to save time 

any thoughts?

**Comment by eric-martin** [comment]
@huntw999 I'm testing using the latest master branch. Here are my steps:

1. Run AuthorizationServerApplication (spring-security-sso-auth-server module)
2. Run UiApplication (spring-security-sso-ui module)
3. Open a browser to http://localhost:8082/ui
4. Click login
5. Enter 'john' and '123' and click login
6. You should see a page that looks like:
Secured Page
Welcome, john

**Comment by huntw999** [comment]
that is exactly what i did and why i submitted the report - following the same steps i got:

<oauth>
<error_description>
Full authentication is required to access this resource
</error_description>
<error>unauthorized</error>
</oauth>

this will cause me to look for some other reason for the error

bh

**Comment by huntw999** [comment]
as it turns out my problem is tied to cookies - i just tried the above implementation on edge browser from Microsoft - it worked - somehow chrome is having problems with cookies - this problem causes facebook to complain about cookie permissions even though i have it enabled to use cookies - i am assuming the error i am experiencing is caused by cookies not allowing the sso to work properly - i will uninstall chrome and report back
