### ISSUE TITLE
Inaccessible user endpoint

### ISSUE THREAD

**Issue by dosindi** [eugenp/tutorials#5738]
On Simple Single Sign-On with Spring Security OAuth2 when trying to access User Endpoint 

[http://localhost:8081/auth/user/me](http://localhost:8081/auth/user/me)

It displays the below output instead of the user data in JSON representation
```
<oauth>
<error_description>
Full authentication is required to access this resource
</error_description>
<error>unauthorized</error>
</oauth>
```

**Comment by eric-martin** [comment]
Thanks @dosindi 
I'm able to reproduce the issue. I'll keep this ticket updated with my findings.

**Comment by dosindi** [comment]
On the same note, is it possible to bundle the UI with the Single Sign-On with Spring Security OAuth2 AuthorizationServerApplication?

**Comment by eric-martin** [comment]
@dosindi  We have an internal ticket logged about this issue. I will keep this ticket updated with our progress.

**Comment by eric-martin** [comment]
@dosindi It looks like things are working fine. The auth/user/me endpoint is secured and requires authorization.

We've added a test to help out:
https://github.com/eugenp/tutorials/blob/master/spring-security-sso/spring-security-sso-auth-server/src/test/java/org/baeldung/UserInfoEndpointLiveTest.java
