### ISSUE TITLE
In jenkins-pipeline Running all integration tests fails

### ISSUE THREAD

**Issue by emmanuelhar** [eugenp/tutorials#5765]
When i followed the tutorial about jenkins pipeline https://www.baeldung.com/jenkins-pipelines
 I got the jenkins pipeline failing with the following stacktrace while executing all integration tests : 
~~~stacktrace
[org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed;   
nested exception is java.io.IOException: Could not start process: failed errno:48 Address already in use for socket: 127.0.0.1:27017
2018-11-23T16:38:00.808+0100 E NETWORK  [initandlisten]   addr already in use
~~~
The error was first raised by testReport/junit/org.baeldung/SpringContextIntegrationTest/whenSpringContextIsBootstrapped_thenNoExceptions/

It looks similar to this problem : 
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/176
Anyone can reproduce ?
If so the solution would be to add to   
spring-jenkins-pipeline/src/test/java/org/baeldung/SpringContextIntegrationTest.java a @DirtiesContext annotation ...

**Comment by eric-martin** [comment]
Thanks @emmanuelhar. I was able to reproduce the issue. This has been fixed in master.
