### ISSUE TITLE
can i use oidc in authserver

### ISSUE THREAD

**Issue by YINZHU2016** [eugenp/tutorials#5859]
Hello, I want to integrate the spring security EnableAuthorizationServer server app with a third-party login. How to do it?

The scenario is like this, I have a self-defined sso server, use EnableAuthorizationServer, and define my own loginpage, I want to add google, facebook and other login signs in my loginpage.

When the user accesses the interface that my client app needs to authorize, I use the spring security oauth2, so it will jump to my sso server login interface, then he can log in directly using our system account password, or log in. The interface contains external logins such as google.

**Comment by eric-martin** [comment]
Hey @YINZHU2016

Here are a few articles that might help you out:
https://www.baeldung.com/facebook-authentication-with-spring-security-and-social
https://www.baeldung.com/spring_social_twitter_setup

If that doesn't help out enough, then StackOverflow might be a better place for this question.
