### ISSUE TITLE
Maven/update project/core-java-8 leads to failure

### ISSUE THREAD

**Issue by rolfschumacher** [eugenp/tutorials#6021]
Failure message is:
"Failed to access classpath of mojo org.apache.maven.plugins:maven-pmd-plugin:3.8:pmd
Plugin org.apache.maven.plugins:maven-pmd-plugin:3.8 or one of its dependencies could not be resolved: Failure to find org.baeldung.pmd:custom-pmd:jar:0.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced"

Context: Debian/Stretch, Eclipse Photon, jdk-11

**Comment by eric-martin** [comment]
@rolfschumacher Try installing (mvn install) the custom-pmd module:
https://github.com/eugenp/tutorials/tree/master/custom-pmd
