### ISSUE TITLE
How BookRepository injected in BookController without showing as bean? 

### ISSUE THREAD

**Issue by zubaidullo** [eugenp/tutorials#6149]
I'm new in Spring boot and trying to understand how you injected BookRepository in BookController? 
When I run your sample project, it's throwing an exception. 
Actually, it's not a problem to solve, but if this tutorial is used in **baeldung.com** then, many beginners should have the same problem.

```
Field bookRepository in .....web.BookController required a bean of type '.....persistence.repo.BookRepository' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
```

**Comment by maibin** [comment]
@zubaidullo Could you please let us know which article is this?
