### ISSUE TITLE
An exception when building libraries-data

### ISSUE THREAD

**Issue by alonsoir** [eugenp/tutorials#6185]
~/b/t/libraries-data> pwd
/Users/aironman/baeldung/tutorials/libraries-data
~/b/t/libraries-data> mvn clean install -Dgib.enabled=false
...
`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.975 s
[INFO] Finished at: 2019-01-21T14:59:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.datanucleus:datanucleus-maven-plugin:5.0.2:enhance (default) on project libraries-data: Error executing DataNucleus tool org.datanucleus.enhancer.DataNucleusEnhancer: InvocationTargetException: java/sql/SQLException: java.sql.SQLException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by maibin** [comment]
Hi @alonsoir,

Did you try to update your project first with Maven Update?

**Comment by alonsoir** [comment]
Hi @maibin, i tried to compile the project with clean install maven phases, as you mention in README file.
I have pulled again the full repo and i got new compiling [problems](https://pastebin.com/hgeY39kb).
It looks like there are problems with jdk10. Tomorrow i will try to change to jdk8 and compile again.

**Comment by maibin** [comment]
@alonsoir any updates in here?

**Comment by alonsoir** [comment]
Sorry, i forgot it. It Will probably work using jdk 8.

**Comment by alonsoir** [comment]
Not working doing clean install -U.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] parent-modules 1.0.0-SNAPSHOT ...................... SUCCESS [  0.956 s]
[INFO] lombok-custom 0.1-SNAPSHOT ......................... FAILURE [  2.351 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.019 s
[INFO] Finished at: 2019-02-08T17:43:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project lombok-custom: Could not resolve dependencies for project com.baeldung:lombok-custom:jar:0.1-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.8 at specified path /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :lombok-custom
aironman@MacBook-Pro-Retina-de-Alonso ~/b/tutorials> java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
