### ISSUE TITLE
"Java 9 logging" tutorial has a minor latent bug

### ISSUE THREAD

**Issue by Farmbuyer** [eugenp/tutorials#6244]
This is in reference to https://www.baeldung.com/java-9-logging-api section 3.1, in which a `Slf4jLogger` class is demonstrated.

In particular, the `log` method taking a format string and params array; in the online post it's simply summarized as "*same as the previous switch*" which is certainly sufficient for the points the tutorial is trying to make.  However, the code shown in the previous switch -- and the actual implementation in blob/master/core-java-9/src/modules/com.baeldung.logging.slf4j/com/baeldung/logging/slf4j/Slf4jLogger.java -- simply forwards to calling `logger.<whatever>(format, params);`

You might wish to point out that Java's native logger and SLF4J use different formatting for parameterization.  The `log` method taking an Object varargs array is specified to take a `MessageFormat` string.  Simply passing the `(format,params)` arguments along will not work for any client code expecting to work with Java's `System.Logger`.  As an example,

    System.Logger logger = ...calls that eventually resolve to a Slf4jLogger instance...;
    ....
    logger.info("The foo is {0} and the bar is {1} now.",  foo, bar);

But the parameterization used by SLF4J won't do those replacements, and instead the {0} and {1} will show up in the log unchanged.

Because the curly-brace format specifiers can take their own oddball parameters (like "{42,time}" and similar), the easiest way to ensure correctness is to run the formatter before passing on to SLF4J:

    public void log (Level level, ResourceBundle bundle, String format, Object... params) {
        ... existing isLoggable check ...

        // Real code would do a static import or something, instead of this:
        String message = java.text.MessageFormat.format (format, params);

        switch (level) {
            .... logger.<whatever>(message);  ....

Once the `params` have been expanded, they no longer need to be passed to SLF4J.

All of this might be orthogonal or otherwise irrelevant to the tutorial, but as currently published, it gives the mistaken impression that the arguments can be simply passed through unchanged.

**Comment by lor6** [comment]
@Farmbuyer  That's a good point, thanks. I've updated the code.
