### ISSUE TITLE
spring-boot-keycloak not working  

### ISSUE THREAD

**Issue by samyzm** [eugenp/tutorials#6255]
Hi this example  is  not working  as it  should 👍 
the application is  loaded correctly  but  when you clikc  on customers  its not  redirected  to keycloack instead  its redirected  to  : 

xx.xx.xx.xx:YYYY/sso/login

**Comment by maibin** [comment]
Hey @samyzm,
Could you please let us know to which article you are referring to?

**Comment by samyzm** [comment]
@maibin i followd this article :
https://www.baeldung.com/spring-boot-keycloak

**Comment by maibin** [comment]
@samyzm we are working on it. Thanks!

**Comment by maibin** [comment]
@samyzm the issue has been fixed. Thanks!
