### ISSUE TITLE
Question about callback and ArgumentCapture example

### ISSUE THREAD

**Issue by weijia-yu** [eugenp/tutorials#6293]
I am reading https://www.baeldung.com/mockito-callbacks

Just to make sure I understand correctly. By capturing the callback and invoke the callback. It is violating this warning in the documentation correct?

Warning: it is recommended to use ArgumentCaptor with verification but not with stubbing. Using ArgumentCaptor with stubbing may decrease test readability because captor is created outside of assert (aka verify or 'then') block. Also it may reduce defect localization because if stubbed method was not called then no argument is captured. 

http://static.javadoc.io/org.mockito/mockito-core/2.24.0/org/mockito/Mockito.html#captors

**Comment by maibin** [comment]
@weijia-yu could you please follow up with a comment to the article or sent us an email instead? I believe it's not an issue with the code.

**Comment by weijia-yu** [comment]
All right, I couldn't find a way to comment. I will send an email
