### ISSUE TITLE
tutorials/spring-security-x509/keystore/Makefile potential typo?

### ISSUE THREAD

**Issue by glenlivet** [eugenp/tutorials#6373]
In tutorials/spring-security-x509/keystore/Makefile, # Generate signed certificate with the certificate authority, should the key-store be truststore?

**Comment by glenlivet** [comment]
I guess the script is correct. it is saving the signed certificate into keystore first. However, I do still have a question in this tutorial. Both keystore and trustedstore have ca and signed client certificates, what do we understand the difference between these two key stores then?

**Comment by maibin** [comment]
Hey @glenlivet,
For this specific question, please contact us over team@baeldung.com. I believe it's more as an additional explanation question then the issue with code.
Thanks!
