### ISSUE TITLE
spring-boot-bootstrap module - build fails

### ISSUE THREAD

**Issue by naXa777** [eugenp/tutorials#6427]
The [project](https://github.com/eugenp/tutorials/tree/master/spring-boot-bootstrap) referenced in the article about [Spring Boot](https://www.baeldung.com/spring-boot-start) fails to build.

* OS: Ubuntu
* JDK: OpenJDK 11.0.1
* Active Maven profiles: `cloudfoundry`, `spring-context`
* Exception message:

        BeanDefinitionOverrideException: Invalid bean definition with name 'dataSource'  defined in BeanDefinition defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]

* Reason: incompatible dependencies; Spring Boot 2.1.x in [parent pom.xml](https://github.com/eugenp/tutorials/blob/master/parent-boot-2/pom.xml) and `spring-cloud-config Finchley.XX` in [project pom.xml](https://github.com/eugenp/tutorials/blob/master/spring-boot-bootstrap/pom.xml).
* This Github issue is related: https://github.com/spring-cloud/spring-cloud-config/issues/1142#issue-360571753 
* Solution: update `spring-cloud-config` to `Greenwich.RELEASE`.

Let me fix this.

**Comment by maibin** [comment]
Thanks!
