### ISSUE TITLE
BULL mapper integration

### ISSUE THREAD

**Issue by fborriello** [eugenp/tutorials#6444]
It would be good to add the java bean mapping framework: **BULL** - Bean Utils Light Library in the performance comparison module.
**BULL** is a Java Bean to Java Bean transformer that recursively copies data from one object to another, it is generic, flexible, reusable, configurable and incredibly fast. It's the only library able to transform Mutable, Immutable and Mixed bean without any custom configuration.
More information about this new library are available [here](https://github.com/HotelsDotCom/bull).

**Comment by eric-martin** [comment]
@fborriello This repo supports our articles and tutorials here:
https://www.baeldung.com/

The test is specifically from this article:
https://www.baeldung.com/java-performance-mapping-frameworks

Let me see if there is interest in including this library.

**Comment by fborriello** [comment]
Great! Please, let me know. By the way, I already did the job and opened a pull request so, in case they are interested in, we just need to review and merge the PR.
Have a nice day

**Comment by eric-martin** [comment]
It looks like BULL was first released in January and has had quite a few versions since. I think we would like to hold off a bit and see if this library gets a little more traction in the community and stabalizes.

**Comment by fborriello** [comment]
Ok, let’s follow up in the next future then
