### ISSUE TITLE
Not compiling with JDK10 or above

### ISSUE THREAD

**Issue by alonsoir** [eugenp/tutorials#6456]
After doing git pull, lombok project is failing.

[INFO] parent-modules 1.0.0-SNAPSHOT ...................... SUCCESS [  0.732 s]
[INFO] lombok-custom 0.1-SNAPSHOT ......................... FAILURE [  0.092 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.455 s
[INFO] Finished at: 2019-03-03T15:28:53+01:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "default" could not be activated because it does not exist.
[ERROR] Failed to execute goal on project lombok-custom: Could not resolve dependencies for project com.baeldung:lombok-custom:jar:0.1-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.8 at specified path /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :lombok-custom

JDK 8 is deprecated, isnt?

**Comment by eric-martin** [comment]
The lombok-custom module builds with JDK 8.

JDK 8 is still supported.
