### ISSUE TITLE
HOW CAN I START THE APPLICATION SPRING-MVC-JAVA?

### ISSUE THREAD

**Issue by DeAngelisLuca** [eugenp/tutorials#6469]
https://github.com/eugenp/tutorials/tree/master/spring-mvc-java
This is the link of the project, i want to know how to run it for practicing with xlsx file.
Thank

**Comment by eric-martin** [comment]
@DeAngelisLuca Does this help out?
https://www.baeldung.com/spring-mvc-tutorial

**Comment by DeAngelisLuca** [comment]
Adding this code on a Application.class i solve my problem?

@SpringBootApplicationpublic class Application { 
   public static void main(String[] args) {   
     SpringApplication.run(Application.class, args);   
 }
}

**Comment by eric-martin** [comment]
@DeAngelisLuca Are you trying to run it from an IDE? If so, which one? Command line?

**Comment by DeAngelisLuca** [comment]
Eclipse

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by DeAngelisLuca** [comment]
How do you will run it on application server?
________________________________

**Comment by eric-martin** [comment]
It will probably be less effort to get it running in eclipse as a dynamic web project (instead of converting it to a spring boot app).

See if this helps out:
https://crunchify.com/convert-java-project-to-dynamic-web-project-in-eclipse-environment/
