### ISSUE TITLE
Custom serialisation

### ISSUE THREAD

**Issue by h3dud5** [eugenp/tutorials#6471]
Hi,

Referring to the unit test for Custom serialisation in https://www.baeldung.com/java-serialization

Should the code be 
e.writeObject(objectOutputStream)

instead of 
objectOutputStream.writeObject(e)

Otherwise, the 'override' methods don't make sense.

**Comment by maibin** [comment]
@h3dud5 could you please open a PR for this one?

**Comment by saravanan-kandaswamy** [comment]
I have verified the code,  is the issue still valid?
