### ISSUE TITLE
Spring cloud security break migrating to Spring boot 2

### ISSUE THREAD

**Issue by eyuel4** [eugenp/tutorials#6534]
Hi team,

   I used the Spring cloud security example of yours and migrate to
Spring boot: 2.1.3.RELEASE
Spring Cloud : Greenwich.SR1
 When I try to access a protected resource through zuul gateway I get the login view. Once I put user credential and click login it redirect me to zuul gateway with the original url lost [redirected url](http://localhost:2020/?code=NakkF8&state=LwnJsL) with 401 unauthorized access.
![Initial Request to gateway](https://user-images.githubusercontent.com/18273109/54386189-cc554d00-466e-11e9-80c6-810a0980e8ad.JPG)
![Redirected url after login](https://user-images.githubusercontent.com/18273109/54386190-cc554d00-466e-11e9-831e-6b51b25bd582.JPG)
could you please help me on this? 
Thanks for your time.

**Comment by eyuel4** [comment]
I am referring to this article https://www.baeldung.com/spring-cloud-security

**Comment by getwordsdone** [comment]
Hey @eyuel4 , could you create a PR with your specific changes for us to take a look?

**Comment by zimou13** [comment]
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
(...)

@Bean
LettuceConnectionFactory lettuceConnectionFactory() {
   LettuceConnectionFactory redisConnectionFactory = new LettuceConnectionFactory();
   redisConnectionFactory.setHostName(hostName);
   redisConnectionFactory.setPort(port);
   return redisConnectionFactory;

**Comment by Doha2012** [comment]
Hi @eyuel4,
I have upgraded the module to the same versions you mentioned, related [commit](https://github.com/eugenp/tutorials/commit/cf68c5c771fdc3a8d7ec057857ab83749e61f3ee) 
Everything is working properly, I think the main issue was that _zuul.sensitiveHeaders_ property need to be set in [auth-client](https://github.com/eugenp/tutorials/blob/master/spring-cloud/spring-cloud-security/auth-client/src/main/resources/application.yml#L25)
