### ISSUE TITLE
spring-security-openid filter ordering

### ISSUE THREAD

**Issue by patrick-m-m** [eugenp/tutorials#6541]
I was hoping you could comment on why you chose the filter ordering for the Spring Security and OpenId Connect tutorial.

```
        .addFilterAfter(new OAuth2ClientContextFilter(), AbstractPreAuthenticatedProcessingFilter.class)
        .addFilterAfter(myFilter(), OAuth2ClientContextFilter.class)
```

From what I can tell from the source, there is no reliance upon or interaction with this particular filter, which is "for processing filters that handle pre-authenticated authentication requests, where it is assumed that the principal has already been authenticated by an external system." Is that correct?

If so, is this just a convenient point in the filter chain to insert the OpenIdConnectFilter? What makes it preferable to another point in the chain?

Thank you for the excellent tutorial. It is very helpful, I'm just hoping to learn a little more.

**Comment by patrick-m-m** [comment]
I've been wrestling with this quite a bit more and discovered a potential problem. There is a hidden pitfall in the [`@Bean` annotation on the `OpenIdConnectFilter` on in the `SecurityConfig` class](https://github.com/eugenp/tutorials/blob/master/spring-security-openid/src/main/java/org/baeldung/config/SecurityConfig.java#L27). Since the OpenIdConnectFilter extends the GenericFilterBean (via Abstract ), declaring it as a bean risks Spring Boot from automatically adding it to the filter chain. [Add a Servlet, Filter, or Listener by Using a Spring Bean](https://docs.spring.io/spring-boot/docs/2.1.x/reference/htmlsingle/#howto-add-a-servlet-filter-or-listener-as-spring-bean)

This doesn't seem to be happening in the tutorial and I'm not sure why. Possibly because the bean is declared in the same file as the config that consumes it, possibly because of the annotations. However, I definitely ran into the filter being added twice when I adapted this to my project and declared the bean in a separate file and imported it to the SecurityConfig via a `@Resource` annotation.

I wind up with one instance of the filter in the chain before all the spring security stuff kicks in and another added to the `FilterChainProxy` by the `addFilterAfter` call.

Does the `@Bean` annotation on the `OpenIdConnectFilter` serve any purpose? Why isn't the OpenIdConnectFilter added to the chain twice in the tutorial? In my experiments with the stock tutorial code, removing it breaks things terribly, resulting in an infinite redirect loop to the callback endpoint due to a null pointer exception from the values (e.g. jwkUrl) not being wired in.

**Comment by Doha2012** [comment]
Hi @patrick-m-m 
**1. About filter ordering:**
In this scenario we are using Spring Security for authorization only and the authentication is done by external system "Google". And as you can see in _OpenIdConnectFilter_ implementation, we extended _AbstractAuthenticationProcessingFilter_ to extract our Authentication object from OAuth response.
Authentication filters come directly after _AbstractPreAuthenticatedProcessingFilter_, you can check Security Filters ordering [here](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/builders/HttpSecurity.html#addFilter-javax.servlet.Filter-).

**2. About using @Bean annotation:**
We don't usually need to use _@Bean_ to inject our filters, but in this case our filter needs autowired bean _OAuth2RestTemplate_ [here](https://github.com/eugenp/tutorials/blob/master/spring-security-openid/src/main/java/org/baeldung/config/SecurityConfig.java#L20) to extract information from access token.
To learn more about Spring Bean, check [this](https://www.baeldung.com/spring-bean)
To learn more about @Resource, check [this](https://www.baeldung.com/spring-annotations-resource-inject-autowire)
