### ISSUE TITLE
Spring boot with cvc-complex-type.3.2.2 error. 

### ISSUE THREAD

**Issue by Lisa09Liu** [eugenp/tutorials#6556]
Multiple annotations found at this line:
	- cvc-complex-type.3.2.2: Attribute 'cache-level' is not allowed to appear in element 'int-jms:message-driven-channel-adapter'.
	- cvc-complex-type.3.2.2: Attribute 'subscription-durable' is not allowed to appear in element 'int-jms:message-driven-channel-
	 adapter'.
	- cvc-complex-type.3.2.2: Attribute 'durable-subscription-name' is not allowed to appear in element 'int-jms:message-driven-channel-
	 adapter'.

Hi , in the xml file I have some problems as belows , anyone can help this ?

**Comment by maibin** [comment]
Hey @Lisa09Liu,
Could you let us know which article you are referring to?
Thanks!

**Comment by Lisa09Liu** [comment]
Hi @maibin,

This problem occurred in my project with eclipse , I guess that this maybe some eclipse issues, but I have no idea for fixing it. Could you give some suggestions ? 

Thanks!
