### ISSUE TITLE
[ERROR] No plugin found for prefix 'spring-boot'

### ISSUE THREAD

**Issue by marrhub** [eugenp/tutorials#6587]
I want to run tutorials\metrics example on Windows 7 with Maven:
C:\usr\src\java\baeldung\eugenp\tutorials\metrics>mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: c:\usr\bin\java\apache-maven\bin\..
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: c:\usr\bin\java\Java\jdk1.8.0_121\jre
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
As per README I enter tutorials\metrics module and run:
C:\usr\src\java\baeldung\eugenp\tutorials\metrics>mvn clean install -Dgib.enabled=false
[INFO] BUILD SUCCESS
and later I try:
C:\usr\src\java\baeldung\eugenp\tutorials\metrics>mvn spring-boot:run -Dgib.enabled=false
which fails:

[INFO] Scanning for projects...
[INFO] gitflow-incremental-builder is disabled.
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
3/14 KB   3/20 KB   
3/20 KB   
3/14 KB   5/20 KB   
5/14 KB   5/20 KB   
5/14 KB   8/20 KB   
8/14 KB   8/20 KB   
11/14 KB   8/20 KB   
13/14 KB   8/20 KB   
14/14 KB   8/20 KB   
14/14 KB   11/20 KB   
14/14 KB   13/20 KB   
14/14 KB   16/20 KB   
14/14 KB   19/20 KB   
14/14 KB   20/20 KB   
                      
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 12.5 KB/sec)
                      
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 KB at 8.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.999 s
[INFO] Finished at: 2019-03-25T12:03:33+01:00
[INFO] Final Memory: 14M/379M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\user\\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by maibin** [comment]
Hey @marrhub,
Could you let us know the article you are referring to?
Thanks!

**Comment by marrhub** [comment]
Well as per:
[https://github.com/eugenp/tutorials/tree/master/metrics](url)

it says:

> ## Relevant articles:
> - [Intro to Dropwizard Metrics](http://www.baeldung.com/dropwizard-metrics)
> - [Introduction to Netflix Servo](http://www.baeldung.com/netflix-servo)
> - [Quick Guide to Micrometer](http://www.baeldung.com/micrometer)

Anyway I'm just trying to run metrics example according to tutorials README instructions
[https://github.com/eugenp/tutorials](url)
regarding single module:

> Building a single module
> To build a specific module run the command: mvn clean install -Dgib.enabled=false in the module directory
> Running a Spring Boot module
> To run a Spring Boot module run the command: mvn spring-boot:run -Dgib.enabled=false in the > module directory

**Comment by tgreiser** [comment]
Same issue - windows 10, java 9+181

```
$ cd tutorials/spring-security-rest-basic-auth
$ mvn spring-boot:run -Dgib.enabled=false
...
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\user\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

**Comment by tgreiser** [comment]
On further investigation, that error just shows up because neither of these are spring-boot modules (they all have spring-boot name prefix). I can compile successfully using: mvn clean install -Dgib.enabled=false

**Comment by eric-martin** [comment]
@marrhub The metrics module isn't a spring boot application.

**Comment by harugerv** [comment]
i am also facing same issue

**Comment by lewisMachilika** [comment]
same problem

**Comment by RafaellaMZ** [comment]
Same problem

**Comment by khanhbq2k** [comment]
Same problem

**Comment by skillz4real** [comment]
Make sure you are in the right folder

**Comment by dhruvdornal** [comment]
> On further investigation, that error just shows up because neither of these are spring-boot modules (they all have spring-boot name prefix). I can compile successfully using: mvn clean install -Dgib.enabled=false

thank you so much man, was struggling with this for more than an hour.
