### ISSUE TITLE
The command npm run build fails to copy resources in spring-boot-angular-ecommerce

### ISSUE THREAD

**Issue by ghjansen** [eugenp/tutorials#6594]
By following [this great tutorial](https://www.baeldung.com/spring-angular-ecommerce) it was noticed that the step `4. Merging Spring Boot and Angular Applications` does not perform as expected at the script `deploy`, leaving the directory `../resources/static` empty, thus compromising the application's frontend. Bellow is the line referred:

https://github.com/eugenp/tutorials/blob/ccc39861fe55965ed7096bb5f00a423c7abc96b6/spring-boot-angular-ecommerce/src/main/frontend/package.json#L10

It seems that the source folder `dist/` doesnt contain any files apart from the directory `frontend/`, and this is actually the directory that contains all resources, so it needs to be considered in this command.

**Comment by maibin** [comment]
Thanks!
