### ISSUE TITLE
Update Gradle tutorials to no longer use deprecated configurations

### ISSUE THREAD

**Issue by ljacomet** [eugenp/tutorials#6644]
Some Gradle tutorials, at least the fat jar one, still use `compile` configuration.
That configuration has been soft deprecated for a while and really should not longer be used. [Documentation](https://docs.gradle.org/5.3.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) indicates what are the recommended replacement, with the [`java-library` plugin](https://docs.gradle.org/5.3.1/userguide/java_library_plugin.html#sec:java_library_separation) giving more context.

Filing the issue as the fat jar tutorial still gets referenced in Stackoverflow answers like [this one](https://stackoverflow.com/questions/55446815/include-the-bytecode-of-a-jar-file-in-a-gradle-library-vs-just-adding-it-as-a-d).

**Comment by eugenp** [comment]
Hey @ljacomet - thanks for the ping here, adding an internal issue to deal with that. 
Cheers, 
Eugen.
