### ISSUE TITLE
[Spring batch demo ] Weird method in configuration

### ISSUE THREAD

**Issue by zak905** [eugenp/tutorials#6740]
Hello, 

This method is not annotated with `@Bean`,  I was wondering what is it used for ?

https://github.com/eugenp/tutorials/blob/master/spring-batch/src/main/java/org/baeldung/batch/SpringConfig.java#L69

```
public JobLauncher getJobLauncher() throws Exception {
        SimpleJobLauncher jobLauncher = new SimpleJobLauncher();
        // SimpleJobLauncher's methods Throws Generic Exception,
        // it would have been better to have a specific one
        jobLauncher.setJobRepository(getJobRepository());
        jobLauncher.afterPropertiesSet();
        return jobLauncher;
    }
```

**Comment by eric-martin** [comment]
This should help out:
https://docs.spring.io/spring-batch/4.0.x/reference/html/job.html#javaConfig

Notice that the SpringConfig class is annotated with @EnableBatchProcessing
