### ISSUE TITLE
Kotlin Random Number should discuss Secure Random

### ISSUE THREAD

**Issue by JLLeitschuh** [eugenp/tutorials#6762]
https://www.baeldung.com/kotlin-random-number

This writeup doesn't discuss Secure Random or the impacts of not using a Secure Random number generator when non-predictable randomness is needed.

Related:
https://github.com/Kotlin/KEEP/issues/184

**Comment by eric-martin** [comment]
@JLLeitschuh We have logged an internal ticket to update the article. I'll keep this ticket updated with our progress.

**Comment by JLLeitschuh** [comment]
Thanks! Given the risks of using an insecure RNG in a security critical location, I recommend highlighting it first.

**Comment by zimou13** [comment]
Before 1.3, on the JVM we use Random or even ThreadLocalRandom if we're on JDK > 1.6.

fun IntRange.random() = 
       Random().nextInt((endInclusive + 1) - start) + start
Used like this:

// will return an `Int` between 0 and 10 (incl.)
(0..10).random()

**Comment by eric-martin** [comment]
@JLLeitschuh We added a new 'Pseudo vs Secure Random Number Generators' section to the article. Thanks for bringing this to our attention.

**Comment by kasautizindagikihd** [comment]
<a href="https://kasautizindagikihd.net/">Molkki</a> Drama Serial All Episodes, Colors Tv Voot Drama Molkki Watch Online at Mx Player Latest Episodes, Molkki Apne Tv Desi Serial indian Drama HD ...
