### ISSUE TITLE
Almost not possible to load the parent project in IDEA

### ISSUE THREAD

**Issue by baibinghere** [eugenp/tutorials#6813]
There are too many sub-modules, almost impossible to load parent project (Even though the sub-modules are grouped by profile).
Not sure if I'm loading it correctly with IDEA. 
Is there anyone facing the same issue with me?

**Comment by eric-martin** [comment]
This repository isn't really meant to be loaded all at once. 

Our articles typically just span a single module, Just load the module that you need at the time.
