### ISSUE TITLE
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalArgumentException: Error looking up JNDI datasource

### ISSUE THREAD

**Issue by JavaNeed** [eugenp/tutorials#682]
I am facing the exact issue mentioned in the link http://stackoverflow.com/questions/39465272/caused-by-javax-naming-namenotfoundexception-name-jdbc-baeldungdatabase-is-n . Could you please guide ?

**Comment by pivovarit** [comment]
But where exactly?

**Comment by eugenp** [comment]
Alright, the original question seems to be gone, and there's also no answer here, so I'm closing it. 
@JavaNeed if you need any help, of course, feel free to reopen it. 
Cheers, 
Eugen.

**Comment by thilinaucsc** [comment]
any update

**Comment by eugenp** [comment]
Update to what? :)
