### ISSUE TITLE
2nd micro service has no UI

### ISSUE THREAD

**Issue by jnsunkersett** [eugenp/tutorials#6846]
Great tutorial baeldung.
I have the following query, for which I found no straight forward answer -

In section 4.4, we create the Dealer APP () and then "We shouldn’t forget to navigate to gateway-app and tell it to generate the front-end code for the dealer"
1. cd ../gateway-app
2. yo jhipster:entity dealer

I do not require that. In my design the second microservice, will be consumed by the first, so no UI required for 2nd micro.
So can I skip that step?

So what should be skipped or done besides what is documented

thanks
Jeevan

**Comment by eric-martin** [comment]
@jnsunkersett Since this isn't a bug in our tutorials repository, I would suggest you post this question to stackoverflow.
