### ISSUE TITLE
Graph / Vertex.equals() method should use String.equals() instead of ==

### ISSUE THREAD

**Issue by mytechstackrocks** [eugenp/tutorials#6879]
https://github.com/eugenp/tutorials/blob/3ca1646e75c488fd5c9aa65ae1ff2f463384c5a5/core-java/src/main/java/com/baeldung/graph/Graph.java#L65

 == is for reference comparison (address comparison) <==not what we need
.equals() method for content comparison <==what we need!

Thanks for sharing this code!

**Comment by mytechstackrocks** [comment]
Suggested update:
        return vertex.label.equals(this.label);

**Comment by eric-martin** [comment]
Thanks @mytechstackrocks - I've updated the Vertex class with a generated hashCode and equals method. Thanks!
