### ISSUE TITLE
Tests in `testing-modules/test-containers` don't actually run

### ISSUE THREAD

**Issue by nhooey** [eugenp/tutorials#6996]
When running `mvn test verify integration-test` in the `testing-modules/test-containers` directory, the test don't actually run.

This can be verified by adding the following code to this file:
`src/test/java/com/baeldung/testconainers/DockerComposeContainerLiveTest.java`:

In the test class:
```java
private static int number = 5;
```

And then add this in the `@Test` function:
```java
if (number == 5) throw new RuntimeException("Test is actually getting executed");
```

And notice that no exception is thrown when running tests.

I came across this because it doesn't seem like this example can work, because the container isn't started and has no `WaitStrategy`.

**Comment by eric-martin** [comment]
@nhooey Our *LiveTest classes are not part of our unit test or integration test builds - they typically require extra dependencies that aren't available at build time.
