### ISSUE TITLE
cf-uaa-oauth2-resource-server deployed but cannot get data

### ISSUE THREAD

**Issue by spencerhuang** [eugenp/tutorials#7079]
After setting up resource-client successfully, I am able to get the access_token using password grant_type.

However, when I try to use that token to access a resource server, I'm getting 401 Unauthorized 
![Screen Shot 2019-06-03 at 8 05 38 PM](https://user-images.githubusercontent.com/20566499/58848353-19780800-863b-11e9-99b8-235c94e39e2d.png)
with the following issue:
Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"

**Comment by eric-martin** [comment]
@spencerhuang Can you tell me which article you are referring to please?
