### ISSUE TITLE
H2 settings

### ISSUE THREAD

**Issue by june555** [eugenp/tutorials#7118]
Hi,
I have DB issue.
My project use Maria DB and spring-cloud-zuul makes some errors.
-- error message : no database selected --
I guess H2 doesn't work because of Maria db settings. ( maybe default conflict? )
( I used @primary  and bean name for Maria DB )
Is there any property options to use H2 in zuul ?

Thank you.

**Comment by eric-martin** [comment]
@june555 Is this a question about one of our articles? If so, please share the link,

**Comment by june555** [comment]
https://github.com/eugenp/tutorials/tree/master/spring-cloud/spring-cloud-zuul

I just added DB info in application.properties and made DataSourceConfig.java for maria DB
I cannot upload those tested source because of company security policy.
I will upload codes more if making same errors at home.

Thank you.

**Comment by june555** [comment]
https://github.com/eugenp/tutorials/tree/master/spring-cloud/spring-cloud-zuul

I just added DB info in application.properties and made DataSourceConfig.java for maria DB
I cannot upload those tested source because of company security policy.
I will upload codes more if making same errors at home.

Thank you.

**Comment by maibin** [comment]
@june555 first of all, the question is, why are you using mappers from mybatis in DataSourceConfig?

**Comment by june555** [comment]
Mappers ( maria db ) are used for the other business.

**Comment by maibin** [comment]
@june555 this sounds more like a consulting new code issue rather than an issue with our code. For such cases, please send an email to team@baeldung.com with the description of your case.
Cheers!
