### ISSUE TITLE
at org.kie.internal.io.ResourceFactory.newClassPathResource(ResourceFactory.java:95) for drools

### ISSUE THREAD

**Issue by Prithal** [eugenp/tutorials#7126]
at org.kie.internal.io.ResourceFactory.newClassPathResource(ResourceFactory.java:95) for drools

**Comment by Prithal** [comment]
ERROR!
java.lang.NullPointerException: null

**Comment by maibin** [comment]
Hi @Prithal,
Could you please let us know to which article are you referring to?
Thanks!
