### ISSUE TITLE
Server sent event with spring security

### ISSUE THREAD

**Issue by haider-ali** [eugenp/tutorials#7143]
I was looking to use server sent event with spring security in order to push notification to specific user , is it possible to do this if yes is there any sample available in this repo

**Comment by maibin** [comment]
@haider-ali please refer to:
https://www.baeldung.com/spring-server-sent-events
https://www.baeldung.com/java-ee-jax-rs-sse
https://www.baeldung.com/spring-mvc-sse-streams

**Comment by haider-ali** [comment]
Thanks for sharing the links  they are all example of broadcasting to all users i was looking for an example of integrating the spring-security with SSE to broadcast to single user but couldn't find one
