### ISSUE TITLE
Secure Websocket

### ISSUE THREAD

**Issue by rameelrahman** [eugenp/tutorials#7144]
Reactive Websocket is working fine. I would like to make a Secure Websocket connection(wss://) to an existing Wwebsocket Server. Is it possible with the code provided.

**Comment by maibin** [comment]
@rameelrahman could you please let us know to which article you are referring to?

**Comment by rameelrahman** [comment]
@maibin Sorry, I forgot to mention that. I was referring to the samples code given in this path: tutorials/spring-5-reactive/src/main/java/com/baeldung/websocket/

**Comment by maibin** [comment]
You'll need to modify the code in order to make Secure Websockets. Spring Security might help in this case. @rameelrahman hope this helps:
https://www.baeldung.com/spring-security-websockets

**Comment by rameelrahman** [comment]
Yes, I understood, but I guess that's on the server side. I'm looking to make a secure call from the client using "wss://..." with all the credentials needed. My query is, how can we make a secure websocket call to the server.

**Comment by maibin** [comment]
@rameelrahman depends on which language your client is written. Usually, the easiest way is to use js. We do have a post about creating a client in JS:
https://www.baeldung.com/rest-vs-websockets (5.1.)
but also this might help:
https://stackoverflow.com/questions/54063255/simple-secure-websocket-wss-chat-using-node-js-server-and-jquery-client

**Comment by rameelrahman** [comment]
@maibin thanks for sharing the link.
I'm using Java at the Client side. Server side is a third party wss service written in Spring.
So I'm looking to make a secure wss connection to the server from the Java client. By Java client I meant, the client to the third party wss service, but it actually resides in my server. So it will be a server-to-server communication, both in Java.

**Comment by kcacademic** [comment]
@rameelrahman, Secure WebSocket works on top of TLS similar to HTTPS. From a client, in any language like Java or JS if you happen to use secure URL (starting with wss) it should automatically work given the WS Server is set-up for TLS. It may require client authentication as well but that is a non-typical case. Can you please let us know the error you are getting? Also, since I assume you have not developed the server here, are you sure it is set-uo for TLS.
