### ISSUE TITLE
[query]idea can't run example - drools，but eclipse dose

### ISSUE THREAD

**Issue by huahuayu** [eugenp/tutorials#7149]
hi, I git clone the project, and open drools example in `idea`, I used below command
```
mvn clean install
```

but I got `Cannot resolve symbol 'kie'` error, can you please tell me how to deal with it? I have done google search and try the [stackoverflow solution](https://stackoverflow.com/questions/5905896/intellij-inspection-gives-cannot-resolve-symbol-but-still-compiles-code) but without lucky  

![](https://raw.githubusercontent.com/huahuayu/img/master/20190621100444.png)

but I can run the project in eclipse(sts4) I don't know why.

**Comment by maibin** [comment]
@huahuayu please try this:
1) Right click on the code editor
2) Hover on Maven and expand
3) Click on Reimport
That should help

**Comment by huahuayu** [comment]
@maibin thank you, I tried just now, there is no effect.

**Comment by huahuayu** [comment]
@eugenp please check `tutorials/drools` can't be run in intellij(but do ok in STS), my colleague and I tried and failed.

**Comment by GongFuBoy** [comment]
> @eugenp please check `tutorials/drools` can't be run in intellij(but do ok in STS), my colleague and I tried and failed.

there is same appearance in my IDEA, 
my settings:
IDEA version: 2018.3
JDK version: 1.8
maven version: 3.3.9
system: window 10

**Comment by maibin** [comment]
@huahuayu @GongFuBoy we run some tests, and this is IDEA related bug. To fix it, please upgrade to the latest version 2019.2, and everything should work perfectly fine.
