### ISSUE TITLE
null -> Optional conversion with Jackson and Jdk8Module

### ISSUE THREAD

**Issue by kamilgregorczyk** [eugenp/tutorials#7184]
Hi everyone, I wanted to comment under the article but it seems to be impossible. I'm trying to find a way how a not provided value could be converted to empty Optional with Jackson.

The article: `https://www.baeldung.com/jackson-ignore-null-fields`

There is a test case which verifies if null is properly converted to Optional.empty which is great:
https://github.com/eugenp/tutorials/blob/ca560514a0b7c55093f2a17fe2709c76a6a89ab8/jackson/src/test/java/com/baeldung/jackson/miscellaneous/mixin/OptionalTypeUnitTest.java#L55
But I'm trying to find a solution which also sets not provided fields to empty optional  so this test would pass:

```
  @Test
    public void givenNullField_whenDeserializingIntoOptional_thenIsEmpty() throws IOException {

        String book = "{ \"title\": \"Oliver Twist\"}";

        Book result = mapper.readValue(book, Book.class);

        assertThat(result.getSubTitle()).isEmpty();
    }
```
It will fail as `getSubTitle` will return null, do you guys have any idea how it could be done ? It would be great to update the article if it's a straightforward thing

**Comment by eric-martin** [comment]
@kamilgregorczyk 
https://www.baeldung.com/jackson-optional

**Comment by kamilgregorczyk** [comment]
I found a way how it can be done:
```
public class Book {
   String title;
   Optional<String> subTitle = Optional.empty()
    
   // getters and setters omitted
}
```

Jackson does not fill fields that were not provided hence the default value in class, with it when it's not provided or when it's null it will be empty optional. It would be good to update the art.

**Comment by ShenghuiXue** [comment]
Thanks. This is very helpful.
