### ISSUE TITLE
[CommandPattern] Lambda Expression will not work

### ISSUE THREAD

**Issue by mzhKU** [eugenp/tutorials#7231]
The part here would not work:

```
TextFileOperationExecutor textFileOperationExecutor = new TextFileOperationExecutor();
textFileOperationExecutor.executeOperation(() -> "Opening file file1.txt");
textFileOperationExecutor.executeOperation(() -> "Saving file file1.txt");
```
I can issue a PR if that would help..

**Comment by lor6** [comment]
Hi @mzhKU  We added that code in a unit test here and it's working ok: https://github.com/eugenp/tutorials/blob/master/patterns/design-patterns/src/test/java/com/baeldung/command/test/TextFileOperationExecutorUnitTest.java#L72

Can you clarify what you meant?
Thanks.
