### ISSUE TITLE
Fails to start the application: jobLauncher could not be registered

### ISSUE THREAD

**Issue by belgoros** [eugenp/tutorials#7272]
The provided implementation raises the error:
```
The bean 'jobLauncher', defined in class path resource [hello/BatchConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.class] and overriding is disabled.
```

**Comment by lor6** [comment]
Hi @belgoros Which application are you running? Does this refer to the spring-batch project?

**Comment by belgoros** [comment]
@lor6 It is [spring-batch](https://github.com/eugenp/tutorials/tree/master/spring-batch). Maybe, in the meanwhile, spring-batch updated the version you used. If youdeclare `jobLauncher` bean as you did:
```java
 @Bean
    public JobLauncher jobLauncher() throws Exception {
        SimpleJobLauncher jobLauncher = new SimpleJobLauncher();
        jobLauncher.setJobRepository(jobRepository());
        jobLauncher.afterPropertiesSet();
        return jobLauncher;
    }
```
it raises the error:
```
The bean 'jobLauncher', defined in class path resource [hello/BatchConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.class] and overriding is disabled.
```
To make it work, I had to use  `name` option when declaring `jobLauncher` bean as follows:
```java
@Bean(name = "launcher")
    public JobLauncher jobLauncher() throws Exception {
        SimpleJobLauncher jobLauncher = new SimpleJobLauncher();
        jobLauncher.setJobRepository(jobRepository());
        jobLauncher.afterPropertiesSet();
        return jobLauncher;
    }
```
The same is to aply to `jobRepository()`  bean as well.

I'm using:
```
spring-boot-starter-parent: 2.1.6
java 8
```

**Comment by lor6** [comment]
Thanks @belgoros Will look into it.

**Comment by lor6** [comment]
Hi @belgoros The spring-batch project in the repository is working ok, as it's not using Spring Boot.
The issue you're seeing is because in Spring Boot 2.1. bean overriding has been disabled by default: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes

If you want to change this, you can set the property:
_spring.main.allow-bean-definition-overriding=true_
in application.properties

I'll add an internal issue to update our project also.
Thanks.
