### ISSUE TITLE
Hystrix Dashboard ?

### ISSUE THREAD

**Issue by areddy7021** [eugenp/tutorials#733]
Hi Eugene , 

This is an awesome example for the people who do not wnat to upgrade their spring version to get the hystrix features. I have a requirement where i have to integrate the UI to the existing spring application which is enabled with the hystrix through AOP. Can you suggest any way that how can we integrate the metrics  dashboard to the existing spring application ?

Thanks,
Akhil.

**Comment by eugenp** [comment]
Hey @areddy7021 - quick note here - this looks more like a question for StackOverflow (feel free to email me the link if it's still relevant). 
Closing the issue here. 
Cheers, 
Eugen.
