### ISSUE TITLE
Unzip.java is missing empty folders contained in zipfile

### ISSUE THREAD

**Issue by hudeany** [eugenp/tutorials#7361]
I found your unzip example very useful, especially with your path traversal/breakout check.
But all empty folders included in a zipfile are skiped by your unzipping method.
Maybe you could use something like this:
while (zipEntry != null) {
				if (zipEntry.getName().endsWith("/")) {
					final File newDirectory = new File(destinationDirectory, zipEntry.getName());
					final String newDirectoryPath = newDirectory.getCanonicalPath();
					if (!newDirectoryPath.startsWith(destinationDirectoryPath + File.separator)) {
						throw new IOException("ZipEntry is outside of the destination directory: " + zipEntry.getName());
					}

					if (!newDirectory.exists()) {
						newDirectory.mkdirs();
					} else if (!newDirectory.isDirectory()) {
						throw new IOException("Destination directory exists but is not a directory: " + newDirectory.getAbsolutePath());
					}
				} else {
					final File destFile = new File(destinationDirectory, zipEntry.getName());
					final String destFilePath = destFile.getCanonicalPath();
					if (!destFilePath.startsWith(destinationDirectoryPath + File.separator)) {
						throw new IOException("ZipEntry is outside of the destination directory: " + zipEntry.getName());
					}

					final File parentDirectory = destFile.getParentFile();
					if (!parentDirectory.exists()) {
						parentDirectory.mkdirs();
					} else if (!parentDirectory.isDirectory()) {
						throw new IOException("Destination directory exists but is not a directory: " + parentDirectory.getAbsolutePath());
					}

					try (final FileOutputStream fos = new FileOutputStream(destFile)) {
						int len;
						while ((len = zis.read(buffer)) > 0) {
							fos.write(buffer, 0, len);
						}
					}
				}
				zipEntry = zis.getNextEntry();
			}

**Comment by maibin** [comment]
Hey @hudeany,
With these kinds of code-heavy questions, let's talk about them over email - just to keep the comments here readable.
So, feel free to reach out with your feedback over email.
