### ISSUE TITLE
NullPointerException from createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42) Java

### ISSUE THREAD

**Issue by ShanChathusanda93** [eugenp/tutorials#7407]
Hi,
I am using java-jira maven dependencies as this example to get some details from the jira tickets. But when creating a JiraRestClient from createWithBasicHttpAuthentication() method, it prompts a NullPointerException. But at the end the details are displayed. My problem is the beginning NullPointerException. Is there anyone who can help with this issue?

**Comment by eric-martin** [comment]
@ShanChathusanda93 Can you let me know what article and module you are looking at?

**Comment by ShanChathusanda93** [comment]
@eric-martin This is the article that I have referred.
https://www.baeldung.com/jira-rest-api

**Comment by eric-martin** [comment]
Can you give me some more details about the exception? 
Is your URI, username and password all non-null?

**Comment by ShanChathusanda93** [comment]
Yes, they are all not-null.

**Comment by eric-martin** [comment]
Can you post the exception message and full stack trace?
