### ISSUE TITLE
Class PostRoutingApi.kt does not compile

### ISSUE THREAD

**Issue by carlolf** [eugenp/tutorials#7420]
I am just a Kotlin beginner and try to learn with your examples. I have started with project core-kotlin, and after fixing missing gradle dependencies(see issues/7245), I get these compile errors in class PostRoutingAPI:

`e: /home/carlo/develop/baeldung/tutorials/core-kotlin/src/main/kotlin/com/baeldung/fuel/PostRoutingAPI.kt: (10, 5): Class 'posts' is not abstract and does not implement abstract base class member public abstract val bytes: ByteArray? defined in com.baeldung.fuel.PostRoutingAPI
e: /home/carlo/develop/baeldung/tutorials/core-kotlin/src/main/kotlin/com/baeldung/fuel/PostRoutingAPI.kt: (12, 5): Class 'comments' is not abstract and does not implement abstract base class member public abstract val bytes: ByteArray? defined in com.baeldung.fuel.PostRoutingAPI
e: /home/carlo/develop/baeldung/tutorials/core-kotlin/src/main/kotlin/com/baeldung/fuel/PostRoutingAPI.kt: (38, 27): Type of 'headers' is not a subtype of the overridden property 'public abstract val headers: Map<String, HeaderValues /* = Collection<String> */>? defined in com.github.kittinunf.fuel.util.FuelRouting'`

I'm using Kotlin version 1.3.40; Idea 2.19.1; Gradle 5.4.1

**Comment by maibin** [comment]
@carlolf could you please let us know to which article you are referring to?

**Comment by carlolf** [comment]
Sorry, I do not refer to an article at Baeldung's website. Of course, I read some of them on Kotlin themes. And then wanted to try some code. So I pulled the whole huge tutorial code from and tried to test module "core-kotlin". First things I discovered were missing dependencies in build.gradle. I could resolve them. But class 'PostRoutingAPI' gave compile errors as reported.

**Comment by maibin** [comment]
@carlolf our modules uses Maven as a primary dependency management framework. Gradle dependencies are added as optional in some article. Could you please check if it will work for you when built with Maven?
Thanks!

**Comment by carlolf** [comment]
Well, this is not a matter of using Gradle or using Maven. The error is an error reported by Kotlin compiler. It says, class PostRoutingAPI is not abstract but has undefined methods from the inherited interface. PostRoutingAPI, as it is on Github, has these inner classes: 
`class posts(val id: String, override val body: String?): PostRoutingAPI()
 class comments(val postId: String, override val body: String?): PostRoutingAPI()`
If I implement the classes like this:
`    class Posts(val id: String, override val body: String?): PostRoutingAPI() {
        override val bytes: ByteArray?
            get() = TODO("not implemented") //To change initializer of created properties use File | Settings | File Templates.
    }

    class Comments(val postId: String, override val body: String?): PostRoutingAPI() {
        override val bytes: ByteArray?
            get() = TODO("not implemented") //To change initializer of created properties use File | Settings | File Templates.
    }
` 
the compiler is quite satisfied.

**Comment by carlolf** [comment]
Please note also: your inner classes are named 'posts' and 'comments'. This should be by convention: 'Posts' and 'Comments'.

**Comment by carlolf** [comment]
Your module is provided with a Gradle build file. So I used this; and of course my IDE IntelliJ also uses it. 
To make it useable for Gradle, I declared these dependencies:
`dependencies {
	compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
	compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
	compile 'com.github.kittinunf.fuel:fuel:2.1.0'
	compile 'com.google.code.gson:gson:2.8.5'
	compile 'uy.kohesive.injekt:injekt-core:1.16.1'

    compile "ch.qos.logback:logback-classic:1.2.1"
    testCompile group: 'junit', name: 'junit', version: '4.12'
}`

**Comment by maibin** [comment]
Thanks for letting us know - we'll update the configuration. Do you need any additional help in here?
