### ISSUE TITLE
Getting NullPointerException using CassandraAdminOperations

### ISSUE THREAD

**Issue by harvi9s** [eugenp/tutorials#745]
Can anyone help me resolve why CassandraAdminOperations is returning NullPointerException?

import org.springframework.data.cassandra.core.CassandraAdminOperations;

@Autowired
    private static CassandraAdminOperations adminTemplate;

@Before
    public void createTable() {
        adminTemplate.createTable(true, CqlIdentifier.cqlId(Test.TABLE_NAME),Test.class, new HashMap<String, Object>());
       }

**Comment by eugenp** [comment]
Hey @harvi9s - sorry for the late reply here. I'm not able to reproduce the problem here, so I assume it's been fixed in the meantime. 
Closing (but feel free to reopen it if you need to). 
Cheers, 
Eugen.
