### ISSUE TITLE
UnzipFile cannot unzip files created by Windows

### ISSUE THREAD

**Issue by thomasturrell** [eugenp/tutorials#7511]
**Steps to reproduce** 
1. Create a folder 'a'
2. Create a subfolder within 'a' called 'b'
3. Create a file called 'readme.txt' in subfolder 'b'
4. Right click on folder 'a' and [send to a compressed folder](https://support.microsoft.com/en-us/help/14200/windows-compress-uncompress-zip-files)
5. Attempt to unzip the zip file you have just created using unzip.java

**Expected behaviour**
The file a/b/readme.txt is created.

**Actual behaviour**
There is the following exception:

```
Exception in thread "main" java.io.FileNotFoundException: src/test/resources/unzipTest/a/b (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.baeldung.unzip.UnzipFile.main(UnzipFile.java:20)
```

**Cause**
Not all software creates archives with all of the original folders and subfolders. 

Linux zip command would create the following entires:
* a
* b (path a)
* readme.txt (path a/b)

Windows send to compressed folders would create the following entries:
* b (path a)
* readme.txt (path a/b)

From what I understand both are valid zip files, its just that the native zipping utility in Windows omits zip entries for folders in the root of the archive (I don't know why).

Apache commons have a [useful example](https://commons.apache.org/proper/commons-compress/examples.html) which avoids this issue by checking for and, if necessary, creating the parent directories for each zip entry.

**Comment by maibin** [comment]
@thomasturrell thanks for detailed information. Could you also please let us know to which article you are referring to?

**Comment by thomasturrell** [comment]
I am referring to the the [UnzipFile](https://github.com/eugenp/tutorials/blob/master/core-java-modules/core-java-io/src/main/java/com/baeldung/unzip/UnzipFile.java) class in the [Zipping and Unzipping in Java tutorial](https://www.baeldung.com/java-compress-and-uncompress).

**Comment by hudeany** [comment]
I have a  solution to this Problem: see attached ZipUtilities.java
It creates the not-in-zip-file-included empty path directories as well as it keeps an eye on the zip-decrompress path-traversal problem in the unzip-destination path, which would allow to decompress files from tampered zip files into your local system directories etc.. (e.g. using ../../../../file.name in zip entries path)
[ZipUtilities.txt](https://github.com/eugenp/tutorials/files/3489217/ZipUtilities.txt)

**Comment by maibin** [comment]
@thomasturrell we logged an internal ticket to investigate. I'll follow up in here once we'll get this resolved.

**Comment by lor6** [comment]
This is a valid issue; I've added a fix in the linked PR.
