### ISSUE TITLE
[Security] Spring Maven Repository Guide Suggests HTTP instead of HTTPS

### ISSUE THREAD

**Issue by JLLeitschuh** [eugenp/tutorials#7517]
Your guides recommend that users resolve dependencies over HTTP instead of HTTPS. This is a security vulnerability that exposes users to a MITM attack.

For more information, see my public disclosure of this industry wide vulnerability:

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
[Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)

Here is the vulnerable guide:
https://www.baeldung.com/spring-maven-repository

**Comment by maibin** [comment]
@JLLeitschuh thanks for the information and your post. We logged in an internal ticket and we'll deal with it soon.
