### ISSUE TITLE
@Bean dissallowed on ToDoList

### ISSUE THREAD

**Issue by jessewriter** [eugenp/tutorials#7577]
Please update your document in https://www.baeldung.com/spring-mvc-session-attributes @Bean is dissallowed in spring boot 2 at the ToDoList location

**Comment by eric-martin** [comment]
@jessewriter Are you referring to this configuration class snippet?

@Bean
@Scope(
  value = WebApplicationContext.SCOPE_SESSION, 
  proxyMode = ScopedProxyMode.TARGET_CLASS)
public TodoList todos() {
    return new TodoList();
}

**Comment by jessewriter** [comment]
Sorry I don't remember now, maybe I was confused between the controller and the config file where it was supposed to go...
