### ISSUE TITLE
Import in DockerComposeContainer is not up-to-date

### ISSUE THREAD

**Issue by pgleska** [eugenp/tutorials#7613]
When runnig DockerComposeContainerLiveTest.java there occurs an error: java.lang.NoClassDefFoundError: com/github/dockerjava/api/DockerException caused by: java.lang.ClassNotFoundException: com.github.dockerjava.api.DockerException because current source is: com.github.dockerjava.api.**exception**.DockerException

**Comment by maibin** [comment]
@pgleska could you please let us know to which article are you referring to?
Thanks!
