### ISSUE TITLE
Dependencies contain several vulnerabilities

### ISSUE THREAD

**Issue by brampat** [eugenp/tutorials#7623]
This concerns at least the JSF tutorial:

Dependencies contain several vulnerabilities
spring-aop-4.3.4.RELEASE.jar: CRITICAL
jstl-1.2.jar: HIGH
primefaces-6.2.jar: MEDIUM
spring-core-4.3.4.RELEASE.jar: CRITICAL
logback-core-1.1.7.jar: CRITICAL
jsf-impl-2.2.14.jar: HIGH
primefaces-6.2.jar: jquery.js: MEDIUM

**Comment by brampat** [comment]
I can fix some, but not all. Please see these remarks:

- Primefaces has upgraded jquery to 3.4.1 but this hasnt been released. The latest available release-version for Primefaces is 7.0, while 7.0.6 is available via the Primefaces store. Also, Primefaces Mobile was deprecated in 6.2 and removed from 7.0.
- JSF Faces impl up to 2.2.20 is available via Maven Central. That version doesn't fix the issue and I can't get any of the JBoss or RedHat alternatives to work with the application, though they do seem to solve the issue.
- jstl has not been maintained since 2011, but Apache's taglibs-standard is a replacement and fixes the issue in 1.2.5 (latest)

**Comment by brampat** [comment]
[dependency-check-report_fix.txt](https://github.com/eugenp/tutorials/files/3533118/dependency-check-report_fix.txt)
[dependency-check-report_org.txt](https://github.com/eugenp/tutorials/files/3533119/dependency-check-report_org.txt)

**Comment by maibin** [comment]
@brampat sorry for a delay response - could you please let us know to which article you are referring to?
