### ISSUE TITLE
volatile example is incorrect

### ISSUE THREAD

**Issue by ryannedolan** [eugenp/tutorials#7635]
In Guide to Volatile Keyword, it is implied that SharedObject is racy if volatile keyword is not used, but that adding volatile fixes the race condition. In fact, the volatile keyword does not prevent any race conditions related to incrementing the counter.

Volatile in the example _does_ prevent two threads from disagreeing about what the current count is, if they simply getCount() at the same time.

Volatile in the example does _not_ prevent race conditions, where the value of count can be incorrect.

Removing volatile does _not_ introduce any race conditions in the code. Only, two threads may disagree about the current count, which is _not_ a race condition.

Volatile is _not_ interchangeable with AtomicInteger here, as seems to be implied.

Moreover, volatile does _not_ prevent any race conditions in code that may be calling incrementCount() or getCount().

**Comment by veontomo** [comment]
Hey Ryanne,
you're right, volatile does not prevent any race conditions. 
The article mentions that in multithread applications, two issues should be taken into considerations: mutual exclusion and visibility. Volatile deals with visibility, while synchronized - with mutual exclusion. 
Namely, synchronized (and not volatile) is useful for resolving race conditions as you've correctly pointed out.
