### ISSUE TITLE
Optimistic Locking - Column "version" is reserved keyword.

### ISSUE THREAD

**Issue by enexusde** [eugenp/tutorials#7690]
The column Version is a reserved keyword in PostgreSQL.
A different name should be used.

Fortunately the name is not reserved in SQL2003 in general.

Test this by open a JDBC connection and call:

> connection.getMetaData().getSQLKeywords()

**Comment by eric-martin** [comment]
@enexusde Can you tell me what article you are referring to?

**Comment by enexusde** [comment]
https://github.com/eugenp/tutorials/search?q=%22long+version%3B%22&unscoped_q=%22long+version%3B%22

**Comment by eric-martin** [comment]
@enexusde Out article and code example are using H2, so there isn't an issue.

I can't find any references to 'version' being a reserved word in PostgreSQL though. 

This lists it as 'non-reserved':
https://www.postgresql.org/docs/9.6/sql-keywords-appendix.html

Same with this:
https://www.petefreitag.com/tools/sql_reserved_words_checker/?word=version

**Comment by enexusde** [comment]
https://github.com/pgjdbc/pgjdbc/issues/1564

**Comment by enexusde** [comment]
Thank you for your attention.

**Comment by enexusde** [comment]
By the way, postgres sais it is a keyword but it is not reserved.
