### ISSUE TITLE
BULL Mapper integration

### ISSUE THREAD

**Issue by fborriello** [eugenp/tutorials#7735]
With reference to the issue [#6444](https://github.com/eugenp/tutorials/issues/6444).

As BULL library is growing and articles on that library have been published on:
 - [DZone](https://dzone.com/articles/how-to-transform-any-type-of-java-bean-with-one-li)
 - [InfoQ EN](https://www.infoq.com/articles/expedia-rid-of-bean-transformers/) 
 - [InfoQ PT-BR](https://www.infoq.com/br/articles/expedia-rid-of-bean-transformers/)
 - [Medium](https://medium.com/expedia-group-tech/how-expedia-is-getting-rid-of-java-bean-transformers-6ea5ce3a511f)

It would be good to add the java bean mapping framework: **BULL** - Bean Utils Light Library in the performance comparison module.
More information about this library are available [here](https://github.com/HotelsDotCom/bull).

**Comment by maibin** [comment]
Hi @fborriello,
Thanks for your work and the references. We do write on various libraries, but our threshold is 500 stars/forks on GitHub. While BULL is definitely growing, it's not yet at our popularity target.
Let's see the numbers in 6 months or so.

Hope that it helps.

**Comment by sorin-costea** [comment]
JMapper has even less stars and was included...
