### ISSUE TITLE
source does not compile JDK8 for spring-mvc-forms

### ISSUE THREAD

**Issue by cscumming-dwss** [eugenp/tutorials#7811]
pom is missing version numbers for the following
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${javax.servlet-api.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet.jsp</groupId>
            <artifactId>javax.servlet.jsp-api</artifactId>
            <version>${javax.servlet.jsp-api.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>jstl</artifactId>
            <version>${jstl.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

**Comment by eric-martin** [comment]
These versions are defined in the parent pom:
https://github.com/eugenp/tutorials/tree/master/parent-spring-5
