### ISSUE TITLE
Small bug in WordCount sample app

### ISSUE THREAD

**Issue by arnabguptadev** [eugenp/tutorials#7845]
https://github.com/eugenp/tutorials/blob/master/apache-spark/src/main/java/com/baeldung/WordCount.java#L31 has:

SPACE.split(s)

Should be:

s.split(SPACE)

**Comment by eric-martin** [comment]
@arnabguptadev This is using java.util.regex.Pattern.split() which is correct.

**Comment by arnabguptadev** [comment]
Yep. Sorry about that. I copied that page from the webpage and the SPACE ended up importing from Apache StringUtils class where it was declared as a string.
