### ISSUE TITLE
Dijkstra algo : what if distance between C -> E is <8

### ISSUE THREAD

**Issue by grib0** [eugenp/tutorials#7888]
The page https://www.baeldung.com/java-dijkstra is a great intro to dijkstra algo, but that would be great if it explains that this simple algo don't always find the shortest path.
If the distance between C and E in the graph is lower or equal to 8, the shortest path, passing by A to C will never be evaluated.
Is it a simplification or the dijkstra algo limitation ?
Why not evaluating all paths from A to E ?

**Comment by maibin** [comment]
@grib0 Dijkstra's always gives shortest path when the edge costs are all positive - in the example we evaluate only one option from node A, which yes, is a simplification of an algorithm - it should check all options from A. We'll add a sentence to article about it.
