### ISSUE TITLE
Mockito Strict Stubbing: Remove default stubbing

### ISSUE THREAD

**Issue by DJViking** [eugenp/tutorials#7921]
Good article about the "Mockito Strict Stubbing".
Forgive me if this is not the right place to discuss the article, as commenting on the article is closed.

What if we want to keep having stubbing strict and not use the lenient() ?
Is there a way to remove stubbing for one single test case with JUnit 5 and Mockito 2?

If 9 out of 10 tests needs the default stubbing, and we want to keep it strict, then we would need a addDefaulStubbing() to be called in all 9 tests.

It would be better if that one single test could somewhat remove the default stubbing. Is that possible?

**Comment by JonCook** [comment]
Hello @DJViking, I'm glad you liked the article and thanks for your questions. I'm not sure I follow them exactly I'm afraid.

As explained in the article strict stubbing is enabled by default in Mockito 2. There is no obligation to use the lenient() method. In fact Mockito explicitly recommends against this if possible. 

When you say remove stubbing, what do you mean? Do you mean remove strict stubbing for a test case, if so the answer is of course yes using the lenient() method.

To comment on your next point, the default stubbing mode is strict. So again I don't follow.

If you explain your doubts more clearly or provide some examples perhaps we can help.

Thanks
