### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by PARK-JONGSEOK** [eugenp/tutorials#7979]
- Problem : [tutorials/java-streams/README.md](https://github.com/eugenp/tutorials/blob/master/java-streams/README.md)'s last line `More articles : [next -->]` link

- Solution : I think it's a simple link error.
  - https://github.com/eugenp/tutorials/blob/java-streams-2 → https://github.com/eugenp/tutorials/blob/master/java-streams-2
  
- Thank you for making me a good tutorial.

**Comment by fanatixan** [comment]
Hello @PARK-JONGSEOK,

We are happy you liked the tutorial.
Thank you for letting us now this issue, we fixed it.

Cheers,
Attila
