### ISSUE TITLE
tryAcquire() already acquires a permit, if one is available (no need to call acquire() after it)

### ISSUE THREAD

**Issue by IgorNB** [eugenp/tutorials#7984]
I was going through your tutorial on https://www.baeldung.com/java-util-concurrent `section 2.7. Semaphore`. 
1) Is the acquire() call after [tryAcquire() wich already acquires a permit, if one is available](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Semaphore.html#tryAcquire--) necessary? 
2) Is release() call outside finally block safe?

May be you'd like following fixes https://github.com/eugenp/tutorials/pull/7927/files

**Comment by fanatixan** [comment]
Hello @IgorNB,

Thank you for your comment, you're right. Also, big thanks for the PR, it fixes the issue perfectly.

Cheers.
