### ISSUE TITLE
Spring Security Context Propagation with @Async Issue

### ISSUE THREAD

**Issue by compfantasy** [eugenp/tutorials#8003]
After read the tutorial, there is no problem if the new thread will be created every time, but we usually use a thread pool to provide thread for async request, that is a problem for isolation the identity object, for example, if we have 2 threads in thread pool, we may propagate authentication object to the first thread, and return this thread to thread pool at the end of the process, so thread already been authenticated in the pool, meanwhile the second user send request via async, then choose thread from thread pool, now we assume the first thread was chosen here, the thread was authenticated but with credentials of the first user, identity object got mix up, thus I think I will forward the user credentials or token as parameters in the async method, so that thread will not persist the identity information

**Comment by alessiostalla** [comment]
Hi @compfantasy, what article or tutorial are you referring to? It's hard to answer properly without context and a code example. Anyway, your question is on point. Look at https://stackoverflow.com/questions/5246428/spring-security-and-async-authenticated-users-mixed-up and specifically the `DelegatingSecurityContextAsyncTaskExecutor` (https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/task/DelegatingSecurityContextAsyncTaskExecutor.html). Hope this helps.
