### ISSUE TITLE
Embedded DynamoDB integration test issue.

### ISSUE THREAD

**Issue by cpandya231** [eugenp/tutorials#8056]
Need to change test rule to include -sharedDb parameter to successfully run DynamoDB integration test.

https://github.com/eugenp/tutorials/blob/621d4629e86b0ba4f10d9393f8c9430bcb30ab5a/aws/src/test/java/com/baeldung/dynamodb/rule/LocalDbCreationRule.java#L18

**Comment by maibin** [comment]
@dkapil could you please verify that?
