### ISSUE TITLE
Spring Security and Jersey tutorial

### ISSUE THREAD

**Issue by carljmosca** [eugenp/tutorials#8069]
I am having difficulty adding Spring Security to this example.  Is there another non-Spring Boot Jersey REST example I missed which includes Spring Security?

TIA,
Carl

**Comment by maibin** [comment]
@carljmosca to which article are you referring to?

**Comment by carljmosca** [comment]
https://www.baeldung.com/jersey-rest-api-with-spring

**Comment by maibin** [comment]
@carljmosca currently we don't have an article with Spring Security, but please reach out to team@baeldung.com with your question and we'll help you from there.
Thanks!

**Comment by carljmosca** [comment]
Thank you. I have reached out.  In the meantime, I created this.

https://github.com/carljmosca/jersey-spring-security
