### ISSUE TITLE
httpclient-multipart-upload - wrong endpoint !?

### ISSUE THREAD

**Issue by IcingInk** [eugenp/tutorials#8178]
Hello,

Following the examples in this tutorial : https://www.baeldung.com/httpclient-multipart-upload 
There you declare a number of clients.
The endpoint though is a site on internet "http://echo.200please.com" , that site is no-longer and I am redirected to some yahoo-account.
Would it not be better if you had a 'server'-project as well written in Java, I am seeing myself (when trying out different client-server)  some mismatch here between tech-stacks&versions here - so it is really hard to know how to implement a server for a specific client.
If you do have some server-code, for instance linking to example 3, it would be good if there is a link in your code - that makes it possible for us following you to test the example fully.

-i (2019-11-11)

**Comment by maibin** [comment]
@IcingInk thanks for noticing - we created an internal ticket to work on it. I'll follow up in here with resolution.

**Comment by eric-martin** [comment]
This has been fixed
