### ISSUE TITLE
org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval

### ISSUE THREAD

**Issue by tejagaridepally** [eugenp/tutorials#8208]
I have added the redirectURI in the properties file and passing the value to the OAuth client as mentioned in the code, but still it says  "A redirect is required to get the users approval". I am trying integrate OpenId to my application

**Comment by maibin** [comment]
@tejagaridepally could you please let us know to which article you are referring to?

**Comment by tejagaridepally** [comment]
https://www.baeldung.com/spring-security-openid-connect I am referring to Open ID connect integration to a springboot web application, Do you have any references?

**Comment by tejagaridepally** [comment]
https://github.com/eugenp/tutorials/tree/master/spring-security-openid This is the article

**Comment by tejagaridepally** [comment]
@maibin any luck?

**Comment by lor6** [comment]
@tejagaridepally  Note the code has been moved to https://github.com/eugenp/tutorials/tree/master/spring-security-modules/spring-security-legacy-oidc as it's using the legacy OAuth stack.

I wasn't able to reproduce the issue in our code, so this is likely an issue in your configuration, either in the application or at the OIDC provider side. If you can create a PR that will reproduce the issue, we'll have a look.

Thanks.
