### ISSUE TITLE
spring-data-rest can't start

### ISSUE THREAD

**Issue by eborgbjerg** [eugenp/tutorials#8244]
It seems the spring-data-rest project is broken somehow.
When running

$ mvn spring-boot:run

I get this:

[WARNING] 
java.lang.ClassNotFoundException: com.baeldung.SpringDataRestApplication
    at java.net.URLClassLoader.findClass (URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run (AbstractRunMojo.java:538)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.939 s
[INFO] Finished at: 2019-11-24T23:44:37+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.9.RELEASE:run (default-cli) on project spring-data-rest: An exception occurred while running. com.baeldung.SpringDataRestApplication

**Comment by maibin** [comment]
@dkapil could you look into it?

**Comment by dkapil** [comment]
@maibin this occurred due to internal improvements related to restructuring. This should fix it https://github.com/eugenp/tutorials/pull/8314
