### ISSUE TITLE
spring 5 mvc url matching

### ISSUE THREAD

**Issue by mehran-mehrafarin** [eugenp/tutorials#8312]
I'm looking for a way to use multiple path parameters as one string.Something like [this](https://www.baeldung.com/spring-5-mvc-url-matching#1-uri-variable-syntax-foo-using-a-handler-method) I want to create something like file manager.But it doesn't work!!!

**Comment by maibin** [comment]
@mehran-mehrafarin could you please provide more details? Is there something not working in our code, or do you want to achieve something similar but it doesn't work in your scenario? If the latter, we suggest reaching out to team@baeldung.com, they will be happy to help, as here we usually deal with issues directly related to our articles and codebase.
Hope that his helps
