### ISSUE TITLE
Typos in the Guide to sun.misc.Unsafe

### ISSUE THREAD

**Issue by pbodnar** [eugenp/tutorials#8322]
The tutorial is located at https://www.baeldung.com/java-unsafe.

There are the following small issues. To quote the otherwise great article:

> In this article, we'll have a look at a fascinating class provided by the JDK – Unsafe from the sun.misc package

To be exact, the class is actually from JRE, not from JDK. I know the terms are often used interchangeably, but I think using JDK may cause confusion in this context.

> In this article, we were looking at the Unsafe class and its most useful construct.

One "s" is missing in the last word... ;)

**Comment by maibin** [comment]
@pbodnar thanks - we'll deal with that ASAP :)
