### ISSUE TITLE
Intellij Idea Class Resolving Issue

### ISSUE THREAD

**Issue by Artemsetko** [eugenp/tutorials#8338]
Actually I have an issue in the idea. I tried to test the example from https://www.baeldung.com/java-mongodb and I've got this annoying "cannot find symbol" error
What should I do in this case?
<img width="1054" alt="Screen Shot 2019-12-09 at 4 47 34 PM" src="https://user-images.githubusercontent.com/8721460/70445163-cb3d3900-1aa3-11ea-882b-036856bbc0af.png">

**Comment by maibin** [comment]
@Artemsetko did you import your project as a Maven one? Also, we can suggest using Maven update to re-download the dependencies. If the problem still persists please let us know.
