### ISSUE TITLE
Shared primary key (one-to-one)

### ISSUE THREAD

**Issue by yshinkarev** [eugenp/tutorials#8397]
Hello.
Seems you have issue in a [jpa-one-to-one](https://www.baeldung.com/jpa-one-to-one#spk-strategy) page.
You can read more [here](https://stackoverflow.com/a/6839336/238089).
Thanks.

**Comment by kwoyke** [comment]
Hi @yshinkarev,
Thanks for the feedback.
We've logged an internal task in our system and will take a look into this.

**Comment by fazl** [comment]
Not sure I understood the issue referenced by @yshinkarev. 

But I was confused by a disparity in Section 4 ("Using a shared primary key") - the modeling in section 4.1 shows a column "user_id" in table address, which is never mentioned in the JPA code in section 4.2 (which explicitly refers to a column "id" in table address). 

My first thought was you could fix the annotation of the field Address.id in section 4.2 thus:
s/@Column(name = "id")/@Column(name = "user_id")/
to match the modeling diagram in the prior section, but it also seems wrong to mention user_id in the code for Address.

**Comment by lor6** [comment]
I've updated the article based on the feedback above: https://www.baeldung.com/jpa-one-to-one
