### ISSUE TITLE
Collaborative Filtering Tutorial Issue

### ISSUE THREAD

**Issue by NicBoi** [eugenp/tutorials#8400]
I believe there is an issue in this [tutorial](https://www.baeldung.com/java-collaborative-filtering-recommendations), more specifically in this [file](https://github.com/eugenp/tutorials/blob/master/algorithms-miscellaneous-2/src/main/java/com/baeldung/algorithms/slope_one/SlopeOne.java), lines 101-103.

The way it is at the moment, all missing ratings are set to "-1", regardless if the algorithm was able to predict a rating or not (it is overwriting the rating to "-1" in cases where it was able to make a prediction)

What I think solves the problem is to replace lines 101-103 with: 
```
else if (!clean.containsKey(j)) {
      	clean.put(j, -1.0);
}
```

Please let me know if this is an issue/bug and if my solution is correct or what would be the correct solution.

**Comment by kwoyke** [comment]
@NicBoi thanks for the feedback. We'll take a look into this and get back to you.

**Comment by kwoyke** [comment]
@NicBoi just wanted to let you know we have updated the code and the article. Thanks again for your feedback.
