### ISSUE TITLE
Unable to mvn clean install on java-websocket

### ISSUE THREAD

**Issue by ilikeflex** [eugenp/tutorials#8422]
Hi

I am trying to build project java-websocket project only and I am getting error

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.vackosar.gitflowincrementalbuilder:gitflow-incremental-builder:3.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.vackosar.gitflowincrementalbuilder:gitflow-incremental-builder:jar:3.8 @
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.vackosar.gitflowincrementalbuilder:gitflow-incremental-builder:3.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.vackosar.gitflowincrementalbuilder:gitflow-incremental-builder:jar:3.8 @

Any help is highly appreciated.

Regards

**Comment by kwoyke** [comment]
Hi @ilikeflex,

I've checked this module on our end a moment ago. Everything builds fine, i.e. gitflow-incremental-builder has been downloaded without any problem:
```
$ mvn clean install                                                                                                     
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/com/vackosar/gitflowincrementalbuilder/gitflow-incremental-builder/3.8/gitflow-incremental-builder-3.8.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/vackosar/gitflowincrementalbuilder/gitflow-incremental-builder/3.8/gitflow-incremental-builder-3.8.pom (20 kB at 36 kB/s)
(...)
```

Maybe you should verify your local maven setup?

**Comment by kwoyke** [comment]
The issue you're seeing is due to Maven not being able to download an artifact from the Central repository, even though the dependency is there.
 
This is common if you're behind a corporate proxy, or using a Repository Manager. You can find more information on these topics in the Maven documentation: http://maven.apache.org/guides/mini/guide-proxies.html https://maven.apache.org/repository-management.html

We advice you to double check your Maven setup.
