### ISSUE TITLE
Forgotten dependency in java-cassandra

### ISSUE THREAD

**Issue by TapiaX** [eugenp/tutorials#8457]
Failed to load class org.slf4j.impl.StaticLoggerBinder
You omitted the dependency of logback

**Comment by kwoyke** [comment]
Thanks for the feedback @TapiaX.
I've just build the module and has been able to successfully run all the tests.

Can you please provide more details on when you face the mentioned issue?

**Comment by kwoyke** [comment]
As there's no response here and we are not able to reproduce the issue, I'm closing this one.
