### ISSUE TITLE
I can't clone the project...

### ISSUE THREAD

**Issue by canliture** [eugenp/tutorials#8467]
The project is go large and I cloned the project so times.
How can I solve the problem...

**Comment by kwoyke** [comment]
Hi @canliture,
Can you please provide more details? Are you facing some issues when actually cloning the project from GitHub or importing it to the IDE?

**Comment by kwoyke** [comment]
@canliture I'm closing this issue as it's not clear what the real problem is and therefore we can't reproduce it.
