### ISSUE TITLE
durian-globals

### ISSUE THREAD

**Issue by nedtwigg** [eugenp/tutorials#8526]
Hello!  [Singletons in Java](https://www.baeldung.com/java-singleton) and [Double-Checked Locking with Singleton](https://www.baeldung.com/java-singleton-double-checked-locking) are both excellent!  But one missing piece is testing.

I made a library called [durian-globals](https://github.com/diffplug/durian-globals) which adheres to the lessons of your tutorials (e.g. [double-checked locking](https://github.com/diffplug/durian-globals/blob/cbc836cbfcd844f79cefe82387f529ebcc3cee44/durian-globals/src/main/java/com/diffplug/common/globals/Globals.java#L34-L46)), but adds the ability to test them.  We've used it internally for a long time so it has a lot of production-miles on it, but we just finally got around to open-sourcing it.

Would you be interested in a PR which shows an example?

**Comment by maibin** [comment]
Hi @nedtwigg yes - please write about it to team@baeldung.com -> we'll handle it from then.
Thanks!
