### ISSUE TITLE
/signup form is not available

### ISSUE THREAD

**Issue by dinesh-pathak100** [eugenp/tutorials#8528]
Hi, in spring-boot-crud tutorial, When I am adding a user then href will /signup but on that page only single string that is "add-user" is shown. How can I add user.

**Comment by kwoyke** [comment]
Hi @dinesh-pathak100, I've just run the application locally. You should get a following for when adding a new user:
![signup](https://user-images.githubusercontent.com/10830473/73133325-63c55380-4027-11ea-95b3-dec33fa10140.JPG)

Can you double check this on your end? If you're still facing an issue, can you describe how you start the app? Have you modified the code in any way before running the application?
