### ISSUE TITLE
spring-boot-admin-server member not working

### ISSUE THREAD

**Issue by crsgarcias** [eugenp/tutorials#8540]
I have a problem

I tried to add a new network, but I cant show

![image](https://user-images.githubusercontent.com/25749111/72479445-12f96380-37ba-11ea-8951-50f1d5968efa.png)

Do I need to modify another code?

Thanks!

**Comment by kwoyke** [comment]
Hi @crsgarcias,
Are there any entries regarding 172.20.54.15 address in the logs?

**Comment by crsgarcias** [comment]
Yes, it is, but I can´t react these address

**Comment by kwoyke** [comment]
So can you please share the relevant log entries here?

**Comment by kwoyke** [comment]
Hi @crsgarcias,
It's been a while. So is this issue still valid? Will you be able to provide the logs?
