### ISSUE TITLE
Spring cloud config server Java heap space issue.

### ISSUE THREAD

**Issue by anudeepmadrampalli** [eugenp/tutorials#8559]
Whenever I am trying to start the Spring cloud config server, I am facing the Java heap space issue. Is there a solution for this.

**Comment by kwoyke** [comment]
Hi @anudeepmadrampalli thanks for the feedback.
Can you please provide more details on how to reproduce this issue? I assume you're referring to the https://github.com/eugenp/tutorials/tree/master/spring-cloud/spring-cloud-config/server?
