### ISSUE TITLE
How do you exclude unwanted dependencies with import scope and using BOM?

### ISSUE THREAD

**Issue by kadimulam** [eugenp/tutorials#8720]

**Comment by kwoyke** [comment]
Hi @kadimulam,

I'm not sure the functionality you need is currently supported by the Maven.
Please take a look here - https://stackoverflow.com/questions/39276024/import-dependency-management-with-exclusion - and here - https://issues.apache.org/jira/browse/MNG-5600
As the above jira issue indicates, the fix should be delivered with Maven 3.7.

Anyway, this problem isn't directly related to our repository, so I'm closing this GitHub issue here.

Cheers.
