### ISSUE TITLE
ACL Spring security with ehcache 3

### ISSUE THREAD

**Issue by M-Thirumal** [eugenp/tutorials#8771]
Is there any option to create EhCacheBasedAclCache() with ehcache 3 instead of ehcache 2?

**Comment by kwoyke** [comment]
Hi @M-Thirumal,
If you take a look at the source code of the EhCacheBasedAclCache, you'll notice it still imports net.sf.ehcache.* classes. As far as I'm concerned, starting from version 3 ehcache moved to org.ehcache.
So, as for now, I don't think there's an easy way to use ehcache 3.
But anyway, I'll close this issue, as this doesn't address any problem with our codebase.
What I can advise though, is to turn directly to the spring-security project for help.
Cheers.
