### ISSUE TITLE
PACT file not generated 

### ISSUE THREAD

**Issue by salvag-ntt** [eugenp/tutorials#8923]
Hi,
I was following this (really good) tutorial https://www.baeldung.com/pact-junit-consumer-driven-contracts
In section - 4.1 Resulting Pact Artifact - the expectation is that the PACT file will be generated in a sub-directory of target. 
After a `mvn clan install` I don't seem to be able to find it. To be honest I am not even sure the tests ran.
Was using Java8 to compile

**Comment by kwoyke** [comment]
Hi @salvag-ntt,
Sorry to hear you're having trouble with this. I wasn't able to create the file either.
I'll log the internal ticket in our system and keep you updated.

**Comment by rcooper85** [comment]
Hi @salvag-ntt I was able to generate my pact json file by removing the `@Ignore` tag in the test. I then executed the `mvn test` command and it worked. It seems that the test has to execute for the file to be generated. I hope this helps. :)

**Comment by kwoyke** [comment]
Hi @salvag-ntt ,
We updated the code, fixed the test and unignored it. Currently the pact json file is generated properly.

**Comment by giuseppe-salvatore** [comment]
Of course... didn't see the test was ignored. I should have seen that coming with a test not running.
Thanks
