### ISSUE TITLE
Rectangle logic is wrong for default java coordinate scheme

### ISSUE THREAD

**Issue by ritcat14** [eugenp/tutorials#8966]
Rectangle intersects logic is wrong as follows:

First check of Y checks if rec1 top right y is less than rec2 bottom left y. In Java, because the coordinate system works from top-left (0,0), this doesn't work. A rectangle's top right can be above anothers bottom left and be intersecting.

Instead:
`if (topRight.getY() > oBottomLeft.getY() || bottomLeft.getY() < otherTopRight.getY()) return false;`

**Comment by kwoyke** [comment]
Hi @ritcat14,
I've verified the article and the code and to be honest it all looks correct.
Could you please add a new unit test that shows a case in which our code is wrong? You can simply add it to the RectangleUnitTest and issue a PR.

**Comment by ritcat14** [comment]
![rec example](https://user-images.githubusercontent.com/7569862/78806504-a6f25a00-79ba-11ea-9cb6-b919151cd14b.png)

Here is a basic diagram explaining. It is the simple logic that the top-right Y coordinate of rec2 can be less than the bottom left y coordinate of rec 1 and the rectangles can still be intersecting. Your code does not allow for this in Java with a coordinate system shown in the image above (the default java coordinate system)

**Comment by ritcat14** [comment]
You can find a working example here: https://github.com/ritcat14/CINDER-ENGINE/blob/master/src/main/java/core/objects/Rectangle.java

**Comment by kwoyke** [comment]
@ritcat14 Are you saying that in the above diagram the top-right Y coordinate of rec2 is **less** than the bottom left y coordinate of rec 1??

**Comment by ritcat14** [comment]
Yes if you pay attention to the fact this is based on the default java coordinate system (with the top left of the screen being 0,0), then it is obvious rec 2 top y is less than rec1 bottom left y

**Comment by kwoyke** [comment]
Let's then assume that the top-right Y coordinate of rec2 is (x=5, y=-1) and the bottom left y coordinate of rec 1 is (x=1, y=-6).
Does it mean -1 is less than -6?

**Comment by ritcat14** [comment]
Why would it be that at round? The top of the screen is y=0, with positive values of Y going down. E.g on a standard 1080p screen, the top left coordinate is (0,0), top right (1920,0), bottom left (0, 1080) and bottom right (1920,1080). If you wanted some example values, take the bottom left of rec1 as (x=1, y=6) and too right of rec2 as (x=6, y=1). In which case rec2y < rec1y as per the diagram and the default java coordinate system

**Comment by kwoyke** [comment]
I think we have a fundamental misunderstanding here. Our article, as well as the implementation, assume we use a "default math model" - Cartesian coordinate system.
So yeah, I agree, if you change the environment to anything other than that, the outcome might be unpredictable.
