### ISSUE TITLE
[hibernate-search] No transactional EntityManager available error

### ISSUE THREAD

**Issue by Med-All** [eugenp/tutorials#8973]
`No transactional EntityManager available` error when running example from

https://github.com/eugenp/tutorials/blob/master/persistence-modules/spring-hibernate-5/src/main/java/com/baeldung/hibernatesearch/ProductSearchDao.java

**Comment by andronix83** [comment]
Hi, which version of JDK are you using?
If it is 11 or higher, then the problem might be in missing JAXB API. In order to fix it, please add the following dependencies to your spring-hibernate-5 POM:

`        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.1</version>
            <scope>runtime</scope>
        </dependency>`

This should fix the problem

**Comment by Med-All** [comment]
I'm using JDK 1.8.0.151

**Comment by kwoyke** [comment]
Hi @Med-All,
Sorry to hear you're having issues with this.
Can you please clarify how to recreate the problem? Does it occur during the tests or only when the 'live' application is started?
Can you also say how do you deploy the app and provide the full log?
Thanks!

**Comment by kwoyke** [comment]
Hi @Med-All, just a quick ping. Would you be able to provide the additional information?

**Comment by Med-All** [comment]
@kwoyke I had the problem with the live application. Not sure because I have done it as SpringBoot2 but solved it by adding `@Transactional` annotation to the index builder code and search repository.
