### ISSUE TITLE
way to expand spring test properties from maven

### ISSUE THREAD

**Issue by clydzik** [eugenp/tutorials#9049]
I read and tried this one:
https://www.baeldung.com/spring-boot-auto-property-expansion

this obviously works but is there a way to expand application.properties
in
src/test/resources

As pointed here (no solution by one sentence):
https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/howto-properties-and-configuration.html

"
Only production configuration is filtered that way (in other words, no filtering is applied on src/test/resources).
"

how can i achieve that for test folder properties

**Comment by kwoyke** [comment]
Hi @clydzik,
As the official documentation says - it doesn't work out of the box for Spring Boot.
One idea would be to provide the configuration manually, something like:
        <testResources>
            <testResource>
                <directory>${basedir}/src/test/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/application*.yml</include>
                    <include>**/application*.yaml</include>
                    <include>**/application*.properties</include>
                </includes>
            </testResource>
        </testResources>
Plus the plugin configuration that we present in the article.
Note however, that above is **not** tested.

**Comment by clydzik** [comment]
yes. thx!. i was playing myself but in <resources> not <testResources> thus it was not working.
This one is a solution. can confirm
