### ISSUE TITLE
Lombok version mismatch in 'Implementing a Custom Lombok Annotation'

### ISSUE THREAD

**Issue by garkenbout-quintor** [eugenp/tutorials#9054]
In the Baeldung page of the tutorial it mentions using lombok version 1.18.4 as a dependency, but the backing repo has version 1.14.8, which is required to gain access to the JavacAnnotationHandler class since starting at version 1.16.0 has hidden the internal api from IDE's.

Solution:
Change the version in the Baeldung page to match the repo and specify why this version is used.

**Comment by kwoyke** [comment]
Hi @garkenbout-quintor,
Thanks for the heads up! We'll take a look into this.

**Comment by kwoyke** [comment]
@garkenbout-quintor, just wanted to let you know that we've added the appropriate note to the article. Again, thanks for the feedback!
