### ISSUE TITLE
DB Connection validity check

### ISSUE THREAD

**Issue by ammaralii** [eugenp/tutorials#9056]
In Core Java Persistence of Persistence Module, DB connection must be checked before giving it to resource to use it.

````
@Override
public Connection getConnection() throws SQLException {
        if (connectionPool.isEmpty()) {
            if (usedConnections.size() < MAX_POOL_SIZE) {
                connectionPool.add(createConnection(url, user, password));
            } else {
                throw new RuntimeException("Maximum pool size reached, no available connections!");
            }
        }
        Connection connection = connectionPool.remove(connectionPool.size() - 1);
        //Todo Check Connection Validity
        usedConnections.add(connection);
        return connection;
}
````

Todo in Code is added for more detail.

**Comment by ammaralii** [comment]
@eugenp assign this ticket to me.....

**Comment by kwoyke** [comment]
Hi @ammaralii,
Thanks for the feedback. We'll take a look into this.
I'll keep you updated!

**Comment by ammaralii** [comment]
Hi @kwoyke,
I already provide the fix and open the merge request. You can reproduce the issue locally by down the DB service then up again then it'll give exception communication link failure or sometimes null pointer exception on connection object we are using. But if we check the connection then whenever the connection is given from pool it first checks if its death then we will give another life.

**Comment by kwoyke** [comment]
Hi @ammaralii,
We've updated the article and codes. We couldn't merge your PR directly. You use hardcoded "SELECT 1" query - that would fail on Oracle or DB2 databases for example. Instead we used a generic Connection#isValid(int) that delegates to the JDBC driver.
Again, thanks for your feedback.
