### ISSUE TITLE
Global conversion doesn't work for me

### ISSUE THREAD

**Issue by rohadira** [eugenp/tutorials#9063]
Hi, the string to date conversion works for me at the controller level, but when I try to configure the conversion globally nothing happens and I get the same initial error: "Failed to convert value of type 'java.lang.String' to required type 'java.time.LocalDateTime ".

**Comment by kwoyke** [comment]
Hi @rohadira,
Can you please clarify what article does this refer to?
Also, can you shed some more light on how exactly you _configure the conversion globally_?
Thanks!

**Comment by rohadira** [comment]
the article I'm following is: https: //www.baeldung.com/spring-date-parameters

**Comment by rohadira** [comment]
controller level conversion works:
`@PostMapping("/save")
	public void date(
		@RequestParam("name") String name,
		@RequestParam("email") String email,
		@RequestParam("password") String password,
		@RequestParam("birthday")  @DateTimeFormat(pattern = "yyyy-MM-dd") Date birthday) {
		// ...
		User user = new User();
		user.setName( name );
		user.setEmail( email );
		user.setPassword( password );
		user.setBirthday( birthday );
		userServiceAPI.save(user);
	}`
-------------------------------------------------------

but the global conversion has no effect
`@Configuration
class DateTimeConfig {

    @Bean
    public FormattingConversionService conversionService() {
        DefaultFormattingConversionService conversionService = new DefaultFormattingConversionService(false);

        conversionService.addFormatterForFieldAnnotation(new NumberFormatAnnotationFormatterFactory());

        DateTimeFormatterRegistrar registrar = new DateTimeFormatterRegistrar();
        registrar.setDateFormatter(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        // registrar.setDateTimeFormatter(DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss"));
        registrar.registerFormatters(conversionService);

        return conversionService;
    }

}`
-----------------------------------------------------------
Error:
![image](https://user-images.githubusercontent.com/36553941/79073194-ce8f3e00-7caa-11ea-94ba-edc31df713b7.png)

**Comment by kwoyke** [comment]
@rohadira,
Thanks for the clarification!
We've registered an issue for that in our internal system and we'll take a look into this.

**Comment by lor6** [comment]
@rohadira The code and article are updated: https://www.baeldung.com/spring-date-parameters#convert-date-parameters-at-the-application-level You can see the code changes here: https://github.com/eugenp/tutorials/pull/10102/files
