### ISSUE TITLE
cas example missing pom.xml file

### ISSUE THREAD

**Issue by DPovilas** [eugenp/tutorials#9068]
Project **cas** contains empty pom.xml file.

**Comment by kwoyke** [comment]
Hi @DPovilas,
Thanks for the feedback.
Indeed, there are two empty pom.xml files in the cas and cas-server projects. But at first glance, it looks like they are not needed. 
There's a README in the cas-server that describes how to boot the server.
The cas-secured-app is a standard Spring Boot app and the pom.xml looks fine.
We'll clean up the cas module.
Please let me know if those empty poms cause any issues on your side. Thanks!

**Comment by DPovilas** [comment]
I think if you use CAS, you have to add dependency in your pom:
`<dependency>
       <groupId>org.springframework.security</groupId>
       <artifactId>spring-security-cas</artifactId>
</dependency>`

**Comment by kwoyke** [comment]
We'll clean up the cas module and remove the empty poms.
Also note that cas is gradle based project so you should use it instead of Maven.
