### ISSUE TITLE
Typo (should be node.right instead)

### ISSUE THREAD

**Issue by GMusliaj** [eugenp/tutorials#9092]
https://github.com/eugenp/tutorials/blob/1108b9738558b356b683fc92f3b96f0b0c085fd5/data-structures/src/main/java/com/baeldung/tree/BinaryTree.java#L145

**Comment by kwoyke** [comment]
Hi @GMusliaj,
Thanks for the feedback! We'll fix this.

**Comment by kwoyke** [comment]
Fixed.
