### ISSUE TITLE
Hi, When i was deploying this application in my Ec2 server i am getting EC2Exception error. Could you help for this..

### ISSUE THREAD

**Issue by vijaysavitri7** [eugenp/tutorials#9109]

**Comment by vijaysavitri7** [comment]
![aws_ec2_exception](https://user-images.githubusercontent.com/40000769/79449101-3d003300-8000-11ea-84c1-7051c16b32a4.PNG)

**Comment by lor6** [comment]
Hi @vijaysavitri7  The error suggests the credentials you've used don't have the right permissions in EC2 for the operation. 

Is this an issue you've reproduced in one of the modules from this repository?
