### ISSUE TITLE
serviceId related issue

### ISSUE THREAD

**Issue by amargJava** [eugenp/tutorials#9248]
https://github.com/eugenp/tutorials/blob/515095dbfbeb7c8597be0f5f8019b6b2e3c230c0/spring-cloud/spring-cloud-bootstrap/discovery/src/main/resources/bootstrap.properties#L2

When I have used spring.cloud.config.discovery.serviceId then the server did not find the Eureka server property value(eureka.client.serviceUrl.defaultZone) and tomcat became terminated.
So please help.

**Comment by kwoyke** [comment]
Hi @amargJava,
Can you please clarify if you make any other changes in the project? Does it work fine for you if you use  spring.cloud.config.uri?

**Comment by kwoyke** [comment]
Hi @amargJava,
Just a quick ping here :)

**Comment by amargJava** [comment]
Hi @kwoyke,
Thanks for ping me and yes if I use spring.cloud.config.uri, its working fine.
But when I I use spring.cloud.config.discovery.serviceId then the server became stopped.

So do you have any solution for the same?

**Comment by lor6** [comment]
@amargJava  Have you set the property: spring.cloud.config.discovery.enabled=true as well? You have to add these properties to a bootstrap.properties file if you want to use this approach, as described in the documentation: https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_client.html#discovery-first-bootstrap and exemplified in this section: https://www.baeldung.com/spring-cloud-bootstrapping#3-properties-2
