### ISSUE TITLE
Screen captures show "master" realm instead of "SpringBootKeycloak"

### ISSUE THREAD

**Issue by ProvenirJHansen** [eugenp/tutorials#9284]
Thank you for the excellent tutorial!

https://www.baeldung.com/spring-boot-keycloak

Problem description: The tutorial doesn't explicitly say which realm to create the client, role, and user in. Since the screenshots for each of these steps actually shows "master", this may mislead the user into creating these items in the master realm instead of the SpringBootKeycloak realm.

Suggestion:
1. Update the sections for creating the client, role, and user to indicate "In the SpringBootKeycloak realm, ...", or, alternately, insert a new Step 3.2 to explicitly make sure that realm is selected before continuing.
2. Update the screenshots

**Comment by kwoyke** [comment]
Hi @ProvenirJHansen,
Thanks for the feedback. I've taken the opportunity and registered the internal task to upgrade the article to the latest versions of Keycloak and Spring Boot. We'll update the screenshots as well.
I'll keep this GitHub issue open and keep you updated.

**Comment by lor6** [comment]
The post and screenshots have been updated.

**Comment by ProvenirJHansen** [comment]
Looks great! Much appreciated!
