### ISSUE TITLE
UUIDGenerator calculates uuidv3 and uuidv5 incorrectly.

### ISSUE THREAD

**Issue by JMcNamaraMediaMath** [eugenp/tutorials#9292]
I took a look at two UUID generators and compared to the output of the code provided.

Other generators:
https://github.com/cowtowncoder/java-uuid-generator/blob/master/src/main/java/com/fasterxml/uuid/impl/UUIDUtil.java#L233

https://www.uuidtools.com/generate/v3

For example, if I plug the letter "d" into the generators above with DNS namespace and UUIDv3 I get:
dbd41ecb-f466-33de-b309-1468addfc63b.

Executing the code in https://github.com/eugenp/tutorials/blob/cf2d93b4e70cc1ec70ab4bb078612d0c054c9f6a/core-java-modules/core-java/src/main/java/com/baeldung/uuid/UUIDGenerator.java#L45:
42a5f36a-cff5-3c1f-beb3-9b8b79c755d6

The issue appears to be the DNS namespace should be concatenated as a byte array instead of directly concatenated to the string.

**Comment by lor6** [comment]
Thanks @JMcNamaraMediaMath  I've logged an internal issue to look into this, and I'll provide an update once it's done.

**Comment by lor6** [comment]
The article https://www.baeldung.com/java-uuid and code are now updated.
