### ISSUE TITLE
HTTP Status 404 - /spring-security-mvc-socket/WEB-INF/jsp/index.jsp

### ISSUE THREAD

**Issue by rajivsatish** [eugenp/tutorials#9386]
Issue -1 : HTTP Status 404 - /spring-security-mvc-socket/WEB-INF/jsp/index.jsp
The requested resource is not available.

I have copied all code from the repository and set up in Eclipse Kepler IDE as they are present.

I ran the code with tomcat7 or tomcat8 but getting same response. I checked the logic also specially AppConfig.java...looks good to me. Also there is no error in the workspace and server console -

I am deploying the code to tomcat webserver from eclipse directly. please find log file.
[ServerConsole.txt](https://github.com/eugenp/tutorials/files/4696156/ServerConsole.txt)

Please help !!
[AppConfig.txt](https://github.com/eugenp/tutorials/files/4696009/AppConfig.txt)

**Comment by rajivsatish** [comment]
Above issue has been resolved. It had occured due to pom.xml not configured correctly.

But, Now none of the front end button as for example Send, ConnectSpecific, ConnectAll, SubscribeAll don't seem to work. Nothing happened upon clicking the button.

please advice!!!!

**Comment by lor6** [comment]
@rajivsatish I can't reproduce your issues in our code. The behavior should be as described in the supporting tutorial: https://www.baeldung.com/spring-websockets-send-message-to-user You should see the messages displayed in the browser Console. Note that this article is focused on sending a message to a user.

For a full chat example, have a look at: https://www.baeldung.com/websockets-spring
