### ISSUE TITLE
Missing From header

### ISSUE THREAD

**Issue by dacopan** [eugenp/tutorials#9429]
in Spring mail tutorial https://www.baeldung.com/spring-email you are missing put setFrom in mime message (SimpleMailMessage) without it many email server refused this email

**Comment by kwoyke** [comment]
Hi @dacopan,
Thanks for the feedback. Indeed, many SMTP servers reject such emails. We'll update the article.

**Comment by kwoyke** [comment]
@dacopan we've updated the article. Thanks!
