### ISSUE TITLE
UsernamePasswordAuthenticationToken cannot be casted to CustomAuthenticationToken

### ISSUE THREAD

**Issue by saipavan9** [eugenp/tutorials#9485]
I have used the same codebase in the tutorial but still, I am facing this issue. I have only changed the UserRepository to my custom repository. All the code is same.

The error message is
```
class org.springframework.security.authentication.UsernamePasswordAuthenticationToken cannot be cast to class mng.security.CustomAuthenticationToken (org.springframework.security.authentication.UsernamePasswordAuthenticationToken is in unnamed module of loader 'app'; mng.security.CustomAuthenticationToken is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @4a3b1ffb)
java.lang.ClassCastException: class org.springframework.security.authentication.UsernamePasswordAuthenticationToken cannot be cast to class mng.security.CustomAuthenticationToken (org.springframework.security.authentication.UsernamePasswordAuthenticationToken is in unnamed module of loader 'app'; mng.security.CustomAuthenticationToken is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @4a3b1ffb)
	at mng.security.CustomUserDetailsAuthenticationProvider.retrieveUser(CustomUserDetailsAuthenticationProvider.java:68)

```

**Comment by lor6** [comment]
Hi @saipavan9  Which tutorial are you referring to?

**Comment by saipavan9** [comment]
I am referring to spring-security-modules/spring-security-mvc-boot-2 code base.

**Comment by kwoyke** [comment]
Hi @saipavan9,
Can you please clarify which article you're referring to?

**Comment by lor6** [comment]
@saipavan9  I can't tell which tutorial you're referring to, as there's no CustomAuthenticationToken in the spring-security-web-boot-2 project (renamed from spring-security-mvc-boot-2). If this is referring to the "Multiple Authentication Providers" article: https://www.baeldung.com/spring-security-multiple-auth-providers - I checked the code and it's working as expected. 

Please clarify the steps to reproduce the issue in our repository, or provide a PR that reproduces it with your changes.

Thanks.
