### ISSUE TITLE
RandomStringUnitTest.kt bug indexing into charPool and other notes

### ISSUE THREAD

**Issue by markjfisher** [eugenp/tutorials#9504]
The example of using a SecureRandom, and then bitwise manipulation into the index of the charPool has some subtle issues.

Class: tutorials/core-kotlin-modules/core-kotlin-strings/src/test/kotlin/com/baeldung/randomstring/RandomStringUnitTest.kt

The code:

        var randomString = (0..bytes.size - 1).map { i ->
            charPool.get((bytes[i] and 0xFF.toByte() and (charPool.size-1).toByte()).toInt())
        }.joinToString("")

### Using "and" to index into the pool does not work

The final "and" is a bit-mask (size 62 = 26+26+10), less 1, which is binary 111101

This will mask off the 2nd bit every time, so if the random byte has it set (e.g. "2", "3", "6" ...) then it will be masked down to two less (i.e. 2 -> 0, 3 -> 1, 6 -> 4, 7 -> 5, ...) **leading to only choosing from a reduced pool by a half, missing letters "c", "d", "g", "h", ...**

Running a simple check over the values returned from the function yielded the following (running 50,000 samples):

    0 -> 1547
    1 -> 1533
    4 -> 1582
    5 -> 1658
    8 -> 1596
    9 -> 1622
    C -> 1582
    D -> 1567
    G -> 1494
    H -> 1547
    K -> 1484
    L -> 1599
    O -> 1536
    P -> 1536
    S -> 1592
    T -> 1515
    W -> 1532
    X -> 1547
    a -> 1571
    b -> 1574
    e -> 1565
    f -> 1569
    i -> 1558
    j -> 1493
    m -> 1544
    n -> 1552
    q -> 1531
    r -> 1536
    u -> 1619
    v -> 1620
    y -> 1555
    z -> 1645

(Showing the distribution is roughly even, but reduces the pool to a half its normal size.)

To illustrate this further, try changing the pool to just 17 characters (a..q). It will only choose from the 1st and last entries in the pool because all other values are masked out (the mask will be b10000 and only allow values 0 or 16 into the index, i.e. first and last char leading to strings of "a" and "q" only). The same is true of any pool of size 2^n + 1.

Instead, the operation should be **modulus pool size**, which will leave a remainder of 0..(pool size -1), which can be indexed into the whole pool.

        return bytes.indices
                .map { charPool[(bytes[it] and mask7f) % charPool.size] }
                .joinToString("")

If you are after a method that returns letters from the given pool at random, then this will do. If you want even distribution however, it will not. This is weighted to the lower end of the pool (a,b,c,d) because of the masking. If the pool size was a perfect power of 2 (e.g. by adding "-" and "+" to the pool) then it does distribute evenly.

However, in testing, I found I could run 5 million values in ~600ms with this, whereas using a simpler random.nextInt(charPool.size) only took ~1.3s, and was distributed evenly, so the gain is hardly worth the effort.

### Masking with 0xFF is pointless

The first "and" masking 0xFF is the full size of a byte, so does nothing to mask something that is already a byte. The code additionally "and" into something between 0...poolsize, so negative numbers (which I suspect this was trying to originally mask) were being dropped anyway.

In my semi-fixed example above, I mask with 0x7F before modulus into the pool size to strip the negative value. However, as discussed above the distribution isn't then uniform.

### Conclusion

In the end, I would favour

    charPool[random.nextInt(charPool.size)]

as it is much simpler, is distributed evenly across the whole pool size, doesn't fall into any common bit manipulation traps that the original did, and is performant enough for most scenarios.

**Comment by kwoyke** [comment]
Hi @markjfisher,
Thanks for the detailed feedback. We logged the internal ticket to take a deeper look into this.
I'll follow up here.

**Comment by lor6** [comment]
Thanks @markjfisher  This is indeed simpler. I've changed the example to use charPool[random.nextInt(charPool.size)]
