### ISSUE TITLE
eye icon for password field 

### ISSUE THREAD

**Issue by ShilpaVKulkarni** [eugenp/tutorials#9523]
Hi All,
I am using UAA war file in tomcat. I want to put eye icon for password field in reset_password.html  page, for this  I have added the java script code in the file to toggle the visibility of password. Eye icon is appearing  but the java script code is not working which is for toggle the visibility of password. I am not getting why the java script code is not working.. Can anyone please help me in resolving this issue?

**Comment by jlorenzoC** [comment]
Hi, did you correctly place your JavaScript? If you could try to do something else with the same placed script in the page, it would work?

**Comment by ShilpaVKulkarni** [comment]
@jlorenzoC thank you for the reply.. Yes I tried with some other  code but that java script code also did not work. I tried the same code in separate html file then the code is working properly.. But the code is not working in this project.

Following is my code.

```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org"
      xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
      layout:decorator="layouts/main">


<div class="island" layout:fragment="page-content">
    <h1>Enter New Password</h1>
    <div class="island-content">
        <div th:text="|Email: ${email}|" class="email-display">Email: user@example.com</div>
        <form th:action="@{/reset_password.do}" method="post" novalidate="novalidate">
            <input type="hidden" name="code" th:value="${code}"/>
            <input type="hidden" name="email" th:value="${email}"/>
            <div th:if="${message_code}" th:text="#{'reset_password.' + ${message_code}}" class="error-message"></div>
            <div th:if="${message}" th:text="${message}" class="error-message"></div>
            <input name="password" type="password" placeholder="New Password" autocomplete="off" class="form-control"/>
            <input name="password_confirmation" type="password" placeholder="Confirm New Password" autocomplete="off" class="form-control"/>

<p><input id="pass_log_id" type="password" name="password_confirmation" autocomplete="off" class="form-control"/>
<span toggle="#password-field" class="fa fa-fw fa-eye field_icon toggle-password"></span></p>
            <input type="submit" value="Reset Password" class="island-button"/>
        </form>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
<script>
$(document).on('click', '.toggle-password', function() {

    $(this).toggleClass("fa-eye fa-eye-slash");
    
    var input = $("#pass_log_id");
    input.attr('type') === 'password' ? input.attr('type','text') : input.attr('type','password')
});
 </script>
</html>
```

The same code is working fine in separate html file but the same code is not working with this project.. What might be the issue?

**Comment by kwoyke** [comment]
Hi @ShilpaVKulkarni, from what I see here you're having an issue with the code you've added to our example, right? Or am I missing something?
Here, on the GitHub issues workspace, we'd like to keep opened only the issues that actually relate to our code base.

**Comment by ShilpaVKulkarni** [comment]
yes @kwoyke you are correct. I am having an issue with code i have added..
I want to put eye icon for password feild to toggle the visibility of password.. How to achieve it?

**Comment by DeepakLalchandani** [comment]
Where is this article published in baeldung website

**Comment by DeepakLalchandani** [comment]
How did u resolve this issue ?

**Comment by kwoyke** [comment]
I'm closing this one as it's not directly related with any particular issue in our codebase.
