### ISSUE TITLE
Wrong e-mail regex

### ISSUE THREAD

**Issue by heannig** [eugenp/tutorials#9548]
https://github.com/eugenp/tutorials/blob/master/spring-boot-modules/spring-boot-mvc/src/main/java/com/baeldung/swagger2boot/model/User.java

`@Email(regexp=".@.\\..*", message = "Email should be valid")`
==> 
`@Email(regexp=".*@.*\\..*", message = "Email should be valid")`

**Comment by kwoyke** [comment]
Hi @heannig,
Thanks for the feedback! We'll update the code and the article.

**Comment by kwoyke** [comment]
Hey @heannig,
We've updated the article.
