### ISSUE TITLE
Passing the username in the mail content of reset password

### ISSUE THREAD

**Issue by ShilpaVKulkarni** [eugenp/tutorials#9578]
Hi All,
I am using UAA war file in tomcat. In the uaa tomcat in the templates\mail\reset_password.html file I have customized the content. But I want to pass username in the email content but not getting the username. Can anyone please help me in resolving the issue?

**Comment by kwoyke** [comment]
Hi @ShilpaVKulkarni,

Which article you're referring to?

**Comment by lor6** [comment]
Hi @ShilpaVKulkarni If you find an issue in this repository, please specify the module you're running, or open a PR that reproduces the issue. We can't help with your custom code.
