### ISSUE TITLE
MultipartFileUploadClient makes no attempt to set the content type for the uploaded files

### ISSUE THREAD

**Issue by sprior** [eugenp/tutorials#9583]
com.baeldung.web.upload.client.MultipartFileUploadClient seems so useful until I realized that it doesn't show how to set the content type for the files created by getTestFile().  It would seem that in any real world use case that you'd have to do this, but only isn't this done, but the example code doesn't give any clue how you would do it.

**Comment by lor6** [comment]
Hi @sprior Please see section 5 in the associated article: https://www.baeldung.com/spring-rest-template-multipart-upload#uploading-a-single-file:

> 
> We need to create HttpEntitywith header and body. Set the content-type header value to MediaType.MULTIPART_FORM_DATA. When this header is set, RestTemplate automatically marshals the file data along with some metadata.
> 
> Metadata includes file name, file size, and file content type (for example text/plain)".
> 

If you look at the controller endpoint where the file is uploaded, you'll see that the MultipartFile object contains information about the content type as well: https://github.com/eugenp/tutorials/blob/master/spring-resttemplate/src/main/java/com/baeldung/web/upload/controller/FileServerResource.java#L24

Please re-open this if you have any other concerns.
