### ISSUE TITLE
OIDC PKCE supported Java Client 

### ISSUE THREAD

**Issue by praveenbommalibits** [eugenp/tutorials#9635]
Hi, 
Java Client which supports OIDC PKCE flow. Here it should support both generic authorisation url.

**Comment by kwoyke** [comment]
Hi @praveenbommalibits ,
Can you clarify what article this refers to and what's the actual issue here?

**Comment by praveenbommalibits** [comment]
tutorials/spring-5-security-oauth/ , Actually I'm exploring to do  native application support where we have to  follow Authorization code flow + PKCE.  As I Verified the code, seems  like not supporting

**Comment by lor6** [comment]
The spring-5-security-oauth project doesn't currently include support for PKCE. We'll add this to our to-do list for a future article.
