### ISSUE TITLE
Spring boot version 2.4.0 - ResourceBundle not found for MessageSource: Can't find bundle for base name...

### ISSUE THREAD

**Issue by Lopner** [eugenp/tutorials#9699]
https://github.com/eugenp/tutorials/blob/301ec100f121cda3a5e2212d2c8cb62b7ac5c794/spring-mvc-basics-2/src/main/java/com/baeldung/spring/configuration/EmailConfiguration.java#L85

correct way - 
```
messageSource.setBasename("mailMessages");
```
instead
```        
messageSource.setBasename("/mailMessages");
```

**Comment by kwoyke** [comment]
Hi @Lopner,

I've just verified our codes and everything works as expected, i.e. the mailMessages properties are correctly retrieved.
Can you please clarify how to reproduce the issue? Does it occur when you use our samples with Spring Boot 2.4.x?

**Comment by lor6** [comment]
@Lopner  I've updated the code in this configuration.

Thanks.
