### ISSUE TITLE
open-liberty with JPA does not work

### ISSUE THREAD

**Issue by aktion-hip** [eugenp/tutorials#9730]
I have the impression that the _open-liberty_ tutorial with persistence does not work correctly.  
In the pom.xml, the _maven-dependency-plugin_ copies the derby.jar into the _shared/resources_ folder: `<outputDirectory>${project.build.directory}/liberty/wlp/usr/shared/resources/</outputDirectory>`.   
However, _mvn liberty:dev_ deletes this folder and, therefore, the liberty server can't find the resource needed for the persistency.  
Is there a way to configure the _liberty-maven-plugin_ so that it does not delete the shared resources folder?

**Comment by kwoyke** [comment]
Hi @aktion-hip,
Sorry to hear you're having troubles with this.
Can you please clarify which article you're referring to? Also, any tips on how to reproduce the issue and/or the error logs are welcome.

**Comment by aktion-hip** [comment]
Sorry for being not precise enough.
It's the "Introduction to Open Liberty" (https://www.baeldung.com/java-open-liberty).
On line _87_ of your _pom.xml_ (https://github.com/eugenp/tutorials/blob/master/open-liberty/pom.xml) you copy the downloaded derby-dependency to _/liberty/wlp/usr/shared/resources/_.   
However, when I started the liberty server, the directories under _/liberty/wlp/usr/_ are cleared and, thus, the derby-dependency is deleted.  
Do you observe a different behavior?

**Comment by kwoyke** [comment]
Thanks for clarifying this. We'll take a look into this and follow up here.

**Comment by aktion-hip** [comment]
@kwoyke 
As workaround I've copied the driver file in a directory at _/src/main/liberty/config/_. The _pom.xml_ looks like:
`<outputDirectory>${project.basedir}/src/main/liberty/config/jpa/</outputDirectory>`
The server.xml then has the following configuration:
`<library id="postgresqlLib">   
	<file name="${server.config.dir}/jpa/postgresql-42.2.6.jar" />   
</library>`

**Comment by kwoyke** [comment]
@aktion-hip we've updated the module and solved this issue with the copyDependencies feature recently introduced in the plugin. Hope this helps :)
