### ISSUE TITLE
The method authorizationRequestResolver(CustomAuthorizationRequestResolver) is undefined for   the type OAuth2LoginConfigurer<HttpSecurity>.AuthorizationEndpointConfig

### ISSUE THREAD

**Issue by PraveenBiradar** [eugenp/tutorials#9735]
source code path : https://github.com/eugenp/tutorials/blob/master/spring-5-security-oauth/src/main/java/com/baeldung/oauth2/CustomRequestSecurityConfig.java

line no : 47

oauth2 maven dependencies:
https://mvnrepository.com/artifact/org.springframework.security.oauth.boot/spring-security-oauth2-autoconfigure/2.3.1.RELEASE
https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-client/5.3.3.RELEASE
https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-core/5.3.3.RELEASE

error : The method authorizationRequestResolver(CustomAuthorizationRequestResolver) is undefined for   the type OAuth2LoginConfigurer<HttpSecurity>.AuthorizationEndpointConfig

**Comment by lor6** [comment]
Hi @PraveenBiradar I'm not able to reproduce the issue on our codebase. The method resolves correctly, as it's defined in the OAuth2LoginConfigurer.AuthorizationEndpointConfig class as shown here: https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.AuthorizationEndpointConfig.html#authorizationRequestResolver-org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestResolver-

This class is part of the spring-security-config dependency.
