### ISSUE TITLE
getErrorPath() method in org.springframework.boot.web.servlet.error.ErrorController interface has been depreciated in Spring Boot 2.3.1

### ISSUE THREAD

**Issue by UbaidurRehman1** [eugenp/tutorials#9761]
- Please Update this file ```spring-boot-modules/spring-boot-basic-customization/src/main/java/com/baeldung/errorhandling/controllers/MyErrorController.java``` as getErrorPath() has been deprecated in the favor of ```server.error.path``` in Spring Boot 2.3.1

**Comment by kwoyke** [comment]
Hi @UbaidurRehman1,
Thanks for the feedback.
As for now, the spring-boot-basic-customization is based on the Spring Boot 2.2.6 version. We'll update the article after we upgrade the Spring Boot version used.
