### ISSUE TITLE
code not work some website

### ISSUE THREAD

**Issue by TechComet** [eugenp/tutorials#9769]
I tested code for
https://hcaptcha.com/siteverify

but not work

Tutorial:
https://www.baeldung.com/httpurlconnection-post

**Comment by kwoyke** [comment]
Hi @TechComet,
Can you clarify what particular issue you're facing with this article?

**Comment by TechComet** [comment]
I try this
URL url = new URL ("https://reqres.in/api/users");
It's work
but
URL url = new URL ("https://hcaptcha.com/siteverify");
not show message error or verify complete

https://docs.hcaptcha.com

**Comment by kwoyke** [comment]
I'm not sure what's the issue you're facing. But I doubt it's a problem with our article, i.e. you say it works with the https://reqres.in/api/users address that we use in the article.
Anyway, you should rather try to find an answer on sites like StackOverflow.
