### ISSUE TITLE
Spring boot 2.0.0 with Mongo Java Driver 3.4.2

### ISSUE THREAD

**Issue by cpatil7** [eugenp/tutorials#9796]
Hello Team,
Need input how to auto create Index with spring boot application connecting with Azure Cosmos DB(Mongo API).
Application Details
1.	Below are dependencies defined
buildscript {
    ext {
        springBootVersion = '2.0.0.RELEASE'
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}
implementation 'org.springframework.boot:spring-boot-starter-undertow'
implementation 'org.springframework.boot:spring-boot-starter-web'
implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
implementation 'org.springframework.boot:spring-boot-starter-cloud-connectors'
implementation 'org.springframework.boot:spring-boot-starter-data-rest'
implementation 'org.springframework.cloud:spring-cloud-starter-config:2.0.0.RELEASE'
2.	Mongo DB driver
implementation ('org.mongodb:mongo-java-driver:3.4.2') {
force = true
}
In the pojo model, annotate @indexed on the property(for which, index to be created) and model is decorated with @document. No explicit code for mapping or creating the document.

public class MongoConfiguration extends AbstractCloudConfig { @Bean public MongoDbFactory mongoDbFactory() { return connectionFactory().mongoDbFactory(); } }

My understanding is that Auto creation of index is disabled by default. What changes are required to enable the index creation. Any suggestions would be great help.

**Comment by kwoyke** [comment]
Hi @cpatil7,
Are you facing any issue with one of our articles and/or its codebase?
