### ISSUE TITLE
Event listener with jrjc?

### ISSUE THREAD

**Issue by acyuta1** [eugenp/tutorials#9810]
Hello,
I wanted to ask, is there any way we can integrate an event listener with jrjc? So that when a new issue is created in jira, it's logged/printed in application? 

Please help. 
Thankyou!

**Comment by kwoyke** [comment]
Hi @acyuta1,
I'm not sure if you're referring to any of our article.
Anyway, these kinds of questions are better to be asked on sites like stackoverflow.com or community.atlassian.com.
Here, we want to keep only the issues related to our codebase.
