### ISSUE TITLE
Getting this exception when running tests

### ISSUE THREAD

**Issue by alonsoir** [eugenp/tutorials#9813]
[com.netflix.zuul.exception.ZuulException: 429](https://pastebin.com/gugfvQpQ)

I m not sure that if it is the normal behavior, because, mvn test phase ends successfully, but not sure at all.
install phase ends successfully too.

$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_242, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"

**Comment by kwoyke** [comment]
Hi @alonsoir,

This exception is thrown by GreetingControllerUnitTest#whenRequestExceedingCapacity_thenReturnTooManyRequestsResponse test case. It verifies that 429 error code is returned when the rate limit is exceeded (one request per 2 sec in our case).
So yeah the exception looks OK.
