### ISSUE TITLE
Errata of article `Introduction to Project Lombok`

### ISSUE THREAD

**Issue by snowman** [eugenp/tutorials#9817]
According to page https://www.baeldung.com/intro-to-project-lombok#lazygetter, the page **code** also needs to be modified according to what article say.

```java
// https://www.baeldung.com/intro-to-project-lombok#lazygetter
public class GetterLazy {
 
    @Getter(lazy = true)
    private final Map<String, Long> transactions = readTxnsFromFile();
 
    private Map<String, Long> getTransactions() {     // ERRATA: this function should be name readTxnsFromFile
 
        final Map<String, Long> cache = new HashMap<>();
        List<String> txnRows = readTxnListFromFile();
 
        txnRows.forEach(s -> {
            String[] txnIdValueTuple = s.split(DELIMETER);
            cache.put(txnIdValueTuple[0], Long.parseLong(txnIdValueTuple[1]));
        });
 
        return cache;
    }
}
```

https://github.com/eugenp/tutorials/blob/8b5a19ebec8979ae440e1284753e11255b32afe9/lombok/src/main/java/com/baeldung/lombok/intro/GetterLazy.java#L11-L36

Line 16 should be declared `private Map<String, Long> readTxnsFromFile() {`

Line 18 should be declared `private final Map<String, Long> transactions = readTxnsFromFile();`

Correct me if i am wrong

**Comment by kwoyke** [comment]
Hi @snowman,

Thanks for the feedback. We'll align the code with the article 👍

**Comment by kwoyke** [comment]
We updated the article.
