### ISSUE TITLE
HelloServiceImplBase : file does not exists in gRPC article

### ISSUE THREAD

**Issue by swayamraina** [eugenp/tutorials#9829]
> Irrespective of which method you use for code generation, following key files will be generated:
> - HelloRequest.java – contains the HelloRequest type definition
> - HelloResponse.java – this contains the HelleResponse type definition
> - HelloServiceImplBase.java – this contains the abstract class HelloServiceImplBase which provides an implementation of all the operations we defined in the service interface

The article mentions this but `HelloServiceImplBase` is not generated. It is also not present in the project. 

link: https://www.baeldung.com/grpc-introduction

**Comment by kwoyke** [comment]
Hi @swayamraina,

How do you try to generate the classes - with Protocol Buffer Compiler or using the Maven plugin?

**Comment by swayamraina** [comment]
@kwoyke I am using the protobuf compiler 

The article mentions,
> protoc -I=$SRC_DIR --java_out=$DST_DIR $SRC_DIR/HelloService.proto


While in [this SO](https://stackoverflow.com/questions/31029675/protoc-not-generating-service-stub-files/31031346#31031346) post I found out we also need to add `--plugin=protoc-gen-grpc-java=path/to/protoc-gen-grpc-java`

**Comment by kwoyke** [comment]
Yes @swayamraina, if you use protobuf compiler you need to use protoc-gen-grpc-java plugin as well. The maven configuration works fine though.
Anyway, soon we'll update the article!

**Comment by anush-bm** [comment]
Adding the below snippet to under build also works. 

Make sure you have the correct path mentioned. 


`<protoSourceRoot>
						${basedir}/src/main/resources/proto/
</protoSourceRoot>`

![image](https://user-images.githubusercontent.com/109654820/220332738-b8c456b2-8f99-4aa2-a2c2-63b237018744.png)
