### ISSUE TITLE
Deprecated función

### ISSUE THREAD

**Issue by WHK102** [eugenp/tutorials#9835]
In `src/main/java/com/baeldung/errorhandling/controllers/MyErrorController.java` have a deprecatd function:

```
warning: [deprecation] getErrorPath() in MyErrorController has been deprecated
    public String getErrorPath() {
                  ^
```

**Comment by kwoyke** [comment]
Hi @WHK102 ,
Yes since 2.3.x version of Spring Boot this method has been deprecated. Our article here https://www.baeldung.com/spring-boot-custom-error-page mentions this explicitly.
