### ISSUE TITLE
It's not fair. Just to download a Jenkins plugin I need to download everything. 

### ISSUE THREAD

**Issue by ahmadsayeed3** [eugenp/tutorials#9844]

**Comment by kwoyke** [comment]
Hi @ahmadsayeed3,
Well.. life's not fair ¯\_(ツ)_/¯
Now, seriously, do you want to raise any particular issue with any of our articles?

**Comment by ahmadsayeed3** [comment]
Thanks @kwoyke your Jenkins plugin example helped me a lot.

I belong to a village where internet is costly and slow. But yeah I downloaded everything and it worked. 😊

**Comment by ahmadsayeed3** [comment]
I don't have any qu

**Comment by ahmadsayeed3** [comment]
Closing the issue.
