### ISSUE TITLE
Correct spelling mistake

### ISSUE THREAD

**Issue by mailniranjan** [eugenp/tutorials#9848]
https://github.com/eugenp/tutorials/tree/master/spring-kafka

In KafkaApplication class, system out println uses misspelled received and message in some places. Yeah i know this is a very small issue. But when searching for messages, using keyword "received" or "message", people who are new to kafka like me will miss some stuff.

**Comment by kwoyke** [comment]
Hi @mailniranjan,
We've fixed the code and update the article.
Thanks for the heads-up!
