### ISSUE TITLE
Custom Scope Tutorial doesn't explain lifetime

### ISSUE THREAD

**Issue by charlesritchea** [eugenp/tutorials#9860]
In Dagger2, there is the concept of a Subcomponent that would be like if a Spring DI Application had an inner class application whose lifetime was only as long as the method it was created in.
From all descriptions, this sounds like what a custom`@Scope` would be used for, but your tutorial only shows how to create a Scope and use it for injection, but not how to limit the lifetime. How is your "tenant" Scope different from the default Singleton in terms of lifetime?

**Comment by kwoyke** [comment]
Duplicates #11142
