### ISSUE TITLE
Filter search with FileVisitor

### ISSUE THREAD

**Issue by UltraBurstXD** [eugenp/tutorials#9886]
Hi.
How can I search for a file with FileVisitor API, using filters? Like **start name** of a file and it's **end name** (or extension).

**Comment by kwoyke** [comment]
Hi @UltraBurstXD,
Can you please clarify which article you're referring to?

**Comment by UltraBurstXD** [comment]
core-java-nio: FileSearchExample.java
https://www.baeldung.com/java-nio2-file-visitor

**Comment by lor6** [comment]
Hi @UltraBurstXD The filter logic is added in the visitFile() method: https://www.baeldung.com/java-nio2-file-visitor#3-the-visitfile-api In our example this is checking if the file name matches a String; you can adapt this to any condition you want, like whether the file name starts with a String, or checking the attributes from the BasicFileAttributes object.
