### ISSUE TITLE
Example for Immutable objects

### ISSUE THREAD

**Issue by nimitsis** [eugenp/tutorials#9939]
Hi I recently read the examples created for immutability. In the tutorials/core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/immutableobjects/ the classes that are used to explain immutability are Currency and Money. However in the corresponding immutability tests tutorials/core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/immutableobjects/ there are examples for String class. Wouldn 't be more comprehend to have examples with Currency and Money objects?

**Comment by DeepakLalchandani** [comment]
Hi Eugenp/Tutorials,
   I had raised the same issue  very back earlier
But baeldung told it's not required ??

Regards,
Deepak

**Comment by DeepakLalchandani** [comment]
Any updates on this?

**Comment by nimitsis** [comment]
Hi,
Ok, thank you for the feedback.

**Comment by DeepakLalchandani** [comment]
Nimitsis , Can you upload the working Java code solution for Currency and Money

**Comment by DeepakLalchandani** [comment]
> Hi,
> Ok, thank you for the feedback.

Nimitsis , Can you upload the working Java code solution for Currency and Money
