### ISSUE TITLE
University Example ::  Java Source Code

### ISSUE THREAD

**Issue by DeepakLalchandani** [eugenp/tutorials#9962]
Hi,
    I am looking for a working  Java Source Code for the
University Example in the below link

https://www.baeldung.com/java-composition-aggregation-association

Please update the github link once completed and notify me.

Please help

**Comment by kwoyke** [comment]
Hi @DeepakLalchandani,
Is that what you're looking for - https://github.com/eugenp/tutorials/blob/master/core-java-modules/core-java-lang-oop-patterns/src/main/java/com/baeldung/relationships/university/University.java?

**Comment by DeepakLalchandani** [comment]
Where is the working Java code for it with public static void main method ??

**Comment by DeepakLalchandani** [comment]
Hi,
    I have updated the issue.
Check and revert back

Regards,
Deepak

**Comment by kwoyke** [comment]
The code is fine. Not every Java class needs a main method. Nothing to update here.

**Comment by DeepakLalchandani** [comment]
How will I execute the University class without main method ? 
This speaks no sense .

How will I see how the code works or not ? How will I even see how the code runs ?

I think you don't even know the basics of java.

It is illogical of you to reply like that ..
You can enroll in a basics course and then reply to me

You have just created dummy classes and arguing it is working ? Utter Nonsense..

**Comment by martian1431** [comment]
This is the first time I comment on github, I must say this human is rude. What's the point of learning programming if you can't test nor compile a simple class?

**Comment by DeepakLalchandani** [comment]
Hi,
    Think before calling me rude. I just raised this issue because the University class has no use cases.

1. How will University class be associated to professor,departments.? If you know java, you should know that it should cover the testing scenarios which I hardly see here. Hope this makes sense.

2. Since you have understood the complete problem  . Do update that tutorial with the working code covering all scenarios.( which you have admitted in above comment )?

**Comment by DeepakLalchandani** [comment]
Hi,

     My intention is not being rude

I just raised this issue because the University class has no use cases.

   1.

   How will University class be associated to professor,departments.? If
   you know java, you should know that it should cover the testing scenarios
   which I hardly see here. Hope this makes sense.
   2.

   Since you have understood the complete problem . Do update that tutorial
   with the working code covering all scenarios.( which you have admitted in
   above comment )?
